// Port of .archive/src/Export/Scripts/pantheons.lua.

package export

import "strings"

func init() {
	Scripts = append(Scripts, Script{Name: "pantheons", Outs: []string{"Data/Pantheons.lua"}, Run: scriptPantheons})
}

func scriptPantheons(x *Ctx) error {
	x.LoadStatFile("stat_descriptions.txt")

	out := x.Out("Data/Pantheons.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- The Pantheon data (c) Grinding Gear Games\n\n")
	out.W("return {\n")

	for _, p := range x.Dat("PantheonPanelLayout").GetRowList("IsDisabled", false) {
		out.W("\t[\"", luaStr(p.Get("Id")), "\"] = {\n")
		out.W("\t\tisMajorGod = ", luaStr(p.Get("IsMajorGod")), ",\n")
		out.W("\t\tsouls = {\n")

		type god struct {
			name     string
			statKeys []any
			values   []any
		}
		gods := []god{
			{luaStr(p.Get("GodName1")), p.Get("Effect1StatsKey").([]any), p.Get("Effect1Values").([]any)},
			{luaStr(p.Get("GodName2")), p.Get("Effect2StatsKey").([]any), p.Get("Effect2Values").([]any)},
			{luaStr(p.Get("GodName3")), p.Get("Effect3StatsKey").([]any), p.Get("Effect3Values").([]any)},
			{luaStr(p.Get("GodName4")), p.Get("Effect4StatsKey").([]any), p.Get("Effect4Values").([]any)},
		}
		for gi, g := range gods {
			if len(g.statKeys) > 0 {
				out.W("\t\t\t[", gi+1, "] = { ")
				out.W("name = \"", g.name, "\",\n")
				out.W("\t\t\t\tmods = {\n")
				for si, key := range g.statKeys {
					keyRow := key.(*Row)
					value := g.values[si].(int64)
					id := luaStr(keyRow.Get("Id"))
					stats := map[string]*statVal{
						id: {min: float64(value), max: float64(value)},
					}
					out.W("\t\t\t\t\t-- ", id, "\n")
					out.W("\t\t\t\t\t[", si+1, "] = { line = \"", strings.Join(x.DescribeStats(stats).Lines, " "), "\", ")
					out.W("value = { ", value, " }, ")
					out.W("},\n")
				}
				out.W("\t\t\t\t},\n")
				out.W("\t\t\t},\n")
			}
		}

		out.W("\t\t},\n")
		out.W("\t},\n")
	}

	out.W("}")
	return out.Close()
}
