// Port of .archive/src/Export/Scripts/cluster.lua.

package export

import (
	"fmt"
	"regexp"
	"strings"
)

func init() {
	Scripts = append(Scripts, Script{Name: "cluster", Outs: []string{"Data/ClusterJewels.lua"}, Run: scriptCluster})
}

var reDdsEnd = regexp.MustCompile(`dds$`)

func scriptCluster(x *Ctx) error {
	x.LoadStatFile("passive_skill_stat_descriptions.txt")

	out := x.Out("Data/ClusterJewels.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Jewel data (c) Grinding Gear Games\n\nreturn {\n")

	out.W("\tjewels = {\n")
	x.Dat("PassiveTreeExpansionJewels").Rows(func(jewel *Row) bool {
		size := jewel.Get("Size").(*Row)
		out.W("\t\t[\"", luaStr(jewel.Get("BaseItemType").(*Row).Get("Name")), "\"] = {\n")
		out.W("\t\t\tsize = \"", luaStr(size.Get("Id")), "\",\n")
		out.W("\t\t\tsizeIndex = ", size.Index-1, ",\n")
		out.W("\t\t\tminNodes = ", jewel.Get("MinNodes").(int64), ",\n")
		out.W("\t\t\tmaxNodes = ", jewel.Get("MaxNodes").(int64), ",\n")
		out.W("\t\t\tsmallIndicies = { ", concatInts(jewel.Get("SmallIndicies").([]any), ", "), " },\n")
		out.W("\t\t\tnotableIndicies = { ", concatInts(jewel.Get("NotableIndicies").([]any), ", "), " },\n")
		out.W("\t\t\tsocketIndicies = { ", concatInts(jewel.Get("SocketIndicies").([]any), ", "), " },\n")
		out.W("\t\t\ttotalIndicies = ", jewel.Get("TotalIndicies").(int64), ",\n")
		out.W("\t\t\tskills = {\n")
		for _, skill := range x.Dat("PassiveTreeExpansionSkills").GetRowList("JewelSize", size) {
			node := skill.Get("Node").(*Row)
			tagId := luaStr(skill.Get("Tag").(*Row).Get("Id"))
			out.W("\t\t\t\t[\"", luaStr(node.Get("Id")), "\"] = {\n")
			if strings.Contains(tagId, "old_do_not_use") {
				out.W("\t\t\t\t\tname = \"", luaStr(node.Get("Name")), " (Legacy)\",\n")
			} else {
				out.W("\t\t\t\t\tname = \"", luaStr(node.Get("Name")), "\",\n")
			}
			out.W("\t\t\t\t\ticon = \"", reDdsEnd.ReplaceAllString(luaStr(node.Get("Icon")), "png"), "\",\n")
			if mastery, ok := skill.Get("Mastery").(*Row); ok {
				out.W("\t\t\t\t\tmasteryIcon = \"", reDdsEnd.ReplaceAllString(luaStr(mastery.Get("Icon")), "png"), "\",\n")
			}
			out.W("\t\t\t\t\ttag = \"", tagId, "\",\n")
			stats := map[string]*statVal{}
			for i, stat := range node.Get("Stats").([]any) {
				v := float64(node.Get(fmt.Sprintf("Stat%d", i+1)).(int64))
				stats[luaStr(stat.(*Row).Get("Id"))] = &statVal{min: v, max: v}
			}
			desc := x.DescribeStats(stats)
			out.W("\t\t\t\t\tstats = { \"", strings.Join(desc.Lines, "\", \""), "\" },\n")
			out.W("\t\t\t\t\tenchant = {\n")
			for _, line := range desc.Lines {
				out.W("\t\t\t\t\t\t\"Added Small Passive Skills grant: ", line, "\",\n")
			}
			out.W("\t\t\t\t\t},\n")
			out.W("\t\t\t\t},\n")
		}
		out.W("\t\t\t},\n")
		out.W("\t\t},\n")
		return true
	})
	out.W("\t},\n")

	out.W("\tnotableSortOrder = {\n")
	x.Dat("PassiveTreeExpansionSpecialSkills").Rows(func(skill *Row) bool {
		node := skill.Get("Node").(*Row)
		if node.Get("Notable").(bool) {
			out.W("\t\t[\"", luaStr(node.Get("Name")), "\"] = ", skill.Get("Stat").(*Row).Index, ",\n")
		}
		return true
	})
	out.W("\t},\n")
	out.W("\tkeystones = {\n")
	x.Dat("PassiveTreeExpansionSpecialSkills").Rows(func(skill *Row) bool {
		node := skill.Get("Node").(*Row)
		if node.Get("Keystone").(bool) {
			out.W("\t\t\"", luaStr(node.Get("Name")), "\",\n")
		}
		return true
	})
	out.W("\t},\n")
	out.W("\torbitOffsets = {\n")
	x.Dat("PassiveJewelSlots").Rows(func(jewelSlot *Row) bool {
		if _, ok := jewelSlot.Get("ClusterSize").(*Row); ok {
			starts := jewelSlot.Get("StartIndices").([]any)
			out.W("\t\t[", jewelSlot.Get("Proxy").(*Row).Get("PassiveSkillNodeId").(int64), "] = {\n")
			out.W("\t\t\t[0] = ", starts[0].(int64), ",\n")
			if len(starts) > 1 {
				out.W("\t\t\t[1] = ", starts[1].(int64), ",\n")
			}
			if len(starts) > 2 {
				out.W("\t\t\t[2] = ", starts[2].(int64), ",\n")
			}
			out.W("\t\t},\n")
		}
		return true
	})
	out.W("\t},\n")

	out.W("}")
	return out.Close()
}
