// Port of .archive/src/Export/Scripts/miscdata.lua (and the pieces of
// Modules/Utils.lua it uses: stringify/saveTableToFile).

package export

import (
	"math"
	"sort"
	"strings"
)

func init() {
	Scripts = append(Scripts, Script{Name: "miscdata", Outs: []string{"Data/Misc.lua", "Data/CurrencyNames.lua"}, Run: scriptMiscdata})
}

// luaQ is Lua's string.format("%q") for the characters that survive
// stringify's newline conversion.
func luaQ(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\\n")
		case '\r':
			b.WriteString("\\13")
		case 0:
			b.WriteString("\\0")
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// otConstants parses an .ot file's wanted blocks the way miscdata.lua does.
func otConstants(x *Ctx, out *OutFile, file string, alsoPathfinding bool) {
	raw := x.GetFile(file)
	if raw == "" {
		return
	}
	text := convertUTF16to8([]byte(raw), 0)
	ws := strings.NewReplacer(" ", "", "\t", "", "\v", "", "\f", "")
	inWantedBlock := false
	for _, line := range reLine.FindAllString(text, -1) {
		if strings.HasPrefix(line, "Stats") || (alsoPathfinding && strings.HasPrefix(line, "Pathfinding")) {
			inWantedBlock = true
		} else if inWantedBlock && strings.HasPrefix(line, "}") {
			inWantedBlock = false
		} else if inWantedBlock && strings.Contains(line, "=") {
			stripped := ws.Replace(line)
			eq := strings.Index(stripped, "=")
			key, value := stripped[:eq], stripped[eq+1:]
			if value != "" {
				out.W("\t[\"", key, "\"] = ", value, ",\n")
			}
		}
	}
}

func scriptMiscdata(x *Ctx) error {
	out := x.Out("Data/Misc.lua")
	out.W("-- This file is automatically generated, do not edit!\n\n")
	out.W("local data = ...\n")

	var evasion, accuracy, life, altLife1, altLife2, allyLife, allyDamage, damage, armour, ailmentThreshold, monsterPhysConversionMulti strings.Builder
	x.Dat("DefaultMonsterStats").Rows(func(stats *Row) bool {
		evasion.WriteString(luaStr(stats.Get("Evasion")) + ", ")
		accuracy.WriteString(luaStr(stats.Get("Accuracy")) + ", ")
		life.WriteString(luaStr(stats.Get("MonsterLife")) + ", ")
		altLife1.WriteString(luaStr(stats.Get("AltLife1")) + ", ")
		altLife2.WriteString(luaStr(stats.Get("AltLife2")) + ", ")
		allyLife.WriteString(luaStr(stats.Get("MinionLife")) + ", ")
		damage.WriteString(luaStr(stats.Get("Damage")) + ", ")
		allyDamage.WriteString(luaStr(stats.Get("MinionDamage")) + ", ")
		ailmentThreshold.WriteString(luaStr(stats.Get("AilmentThreshold")) + ", ")
		monsterPhysConversionMulti.WriteString(luaStr(stats.Get("MonsterPhysConversionMulti")) + ", ")
		return true
	})
	mdri := x.Dat("GameConstants").GetRow("Id", "MonsterDamageReductionImprovement")
	mdriRatio := float64(mdri.Get("Value").(int64)) / float64(mdri.Get("Divisor").(int64))
	for i := 1; i <= 100; i++ {
		v := math.Floor((10 + 2*float64(i)) * math.Pow(1+mdriRatio/100, float64(i)))
		armour.WriteString(luaNum(v) + ", ")
	}
	out.W("-- From DefaultMonsterStats.dat\n")
	out.W("data.monsterEvasionTable = { " + evasion.String() + "}\n")
	out.W("data.monsterAccuracyTable = { " + accuracy.String() + "}\n")
	out.W("data.monsterLifeTable = { " + life.String() + "}\n")
	out.W("data.monsterLifeTable2 = { " + altLife1.String() + "}\n")
	out.W("data.monsterLifeTable3 = { " + altLife2.String() + "}\n")
	out.W("data.monsterAllyLifeTable = { " + allyLife.String() + "}\n")
	out.W("data.monsterDamageTable = { " + damage.String() + "}\n")
	out.W("data.monsterAllyDamageTable = { " + allyDamage.String() + "}\n")
	out.W("data.monsterArmourTable = { " + armour.String() + "}\n")
	out.W("data.monsterAilmentThresholdTable = { " + ailmentThreshold.String() + "}\n")
	out.W("data.monsterPhysConversionMultiTable = { " + monsterPhysConversionMulti.String() + "}\n")

	out.W("-- From GameConstants.dat\n")
	out.W("data.gameConstants = {\n")
	x.Dat("GameConstants").Rows(func(row *Row) bool {
		v := float64(row.Get("Value").(int64)) / float64(row.Get("Divisor").(int64))
		out.W("\t[\"", luaStr(row.Get("Id")), "\"] = ", luaNum(v), ",\n")
		return true
	})
	out.W("}\n")

	out.W("-- From Metadata/Characters/Character.ot\n")
	out.W("data.characterConstants = {\n")
	otConstants(x, out, "Metadata/Characters/Character.ot", true)
	out.W("}\n")

	out.W("-- From Metadata/Monsters/Monster.ot\n")
	out.W("data.monsterConstants = {\n")
	otConstants(x, out, "Metadata/Monsters/Monster.ot", false)
	out.W("}\n")

	var totemMult strings.Builder
	totemKeys := map[int64]bool{}
	x.Dat("SkillTotemVariations").Rows(func(vr *Row) bool {
		st := vr.Get("SkillTotem").(int64)
		if !totemKeys[st] {
			totemKeys[st] = true
			mult := float64(vr.Get("MonsterVariety").(*Row).Get("LifeMultiplier").(int64)) / 100
			totemMult.WriteString("[" + luaStr(st) + "] = " + luaNum(mult) + ", ")
		}
		return true
	})
	out.W("-- From MonsterVarieties.dat combined with SkillTotemVariations.dat\n")
	out.W("data.totemLifeMult = { " + totemMult.String() + "}\n")

	out.W("data.monsterVarietyLifeMult = {\n")
	cachedEntry := map[string]bool{}
	x.Dat("MonsterVarieties").Rows(func(row *Row) bool {
		for _, m := range row.Get("Mods").([]any) {
			mod := m.(*Row)
			name := luaStr(row.Get("Name"))
			if luaStr(mod.Get("Id")) == "MonsterNecromancerRaisable" && !cachedEntry[name] {
				out.W("\t[\"", name, "\"] = ", luaNum(float64(row.Get("LifeMultiplier").(int64))/100), ",\n")
				cachedEntry[name] = true
				break
			}
		}
		return true
	})
	out.W("}\n")

	out.W("-- From MonsterMapDifficulty.dat\n")
	out.W("data.mapLevelLifeMult = { ")
	x.Dat("MonsterMapDifficulty").Rows(func(row *Row) bool {
		out.W("[", row.Get("AreaLevel").(int64), "] = ", luaNum(1+float64(row.Get("LifePercentIncrease").(int64))/100), ", ")
		return true
	})
	out.W("}\n")

	var mapBossLifeMult, mapBossAilmentMult strings.Builder
	x.Dat("MonsterMapBossDifficulty").Rows(func(vr *Row) bool {
		lvl := luaStr(vr.Get("AreaLevel"))
		mapBossLifeMult.WriteString("[" + lvl + "] = " + luaNum(1+float64(vr.Get("BossLifePercentIncrease").(int64))/100) + ", ")
		mapBossAilmentMult.WriteString("[" + lvl + "] = " + luaNum((100+float64(vr.Get("BossAilmentPercentDecrease").(int64)))/100) + ", ")
		return true
	})
	out.W("-- From MonsterMapBossDifficulty.dat\n")
	out.W("data.mapLevelBossLifeMult = { " + mapBossLifeMult.String() + "}\n")
	out.W("data.mapLevelBossAilmentMult = { " + mapBossAilmentMult.String() + "}\n")

	out.W("-- From VillageBalancePerLevelShared.dat\n")
	out.W("data.goldRespecPrices = { ")
	x.Dat("VillageBalancePerLevelShared").Rows(func(row *Row) bool {
		out.W(row.Get("GoldRespec").(int64), ", ")
		return true
	})
	out.W("}\n")
	if err := out.Close(); err != nil {
		return err
	}

	currencies := map[string]string{}
	x.Dat("CurrencyExchange").Rows(func(row *Row) bool {
		base := row.Get("BaseItemType").(*Row)
		name := luaStr(base.Get("Name"))
		if luaStr(base.Get("ItemClass").(*Row).Get("Id")) == "StackableCurrency" &&
			name != "" && !strings.Contains(name, "DNT") {
			currencies[luaStr(base.Get("Id"))] = name
		}
		return true
	})
	cn := x.Out("Data/CurrencyNames.lua")
	cn.W("-- This file is automatically generated, do not edit!\n")
	cn.W("-- Game data (c) Grinding Gear Games\n\n")
	cn.W("-- This file contains mapping item names for every currency base item type ID.\n")
	cn.W("-- Used for working with the currency exchange which uses item type IDs.\n")
	cn.W("\n-- spell-checker: disable\nreturn {\n")
	ids := make([]string, 0, len(currencies))
	for id := range currencies {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		cn.W("\t[", luaQ(id), "] = ", luaQ(strings.NewReplacer("\r\n", " ", "\r", " ", "\n", " ").Replace(currencies[id])), ",\n")
	}
	cn.W("}\n")
	return cn.Close()
}
