// Port of .archive/src/Export/Scripts/crucible.lua.

package export

import "strings"

func init() {
	Scripts = append(Scripts, Script{Name: "crucible", Outs: []string{"Data/Crucible.lua"}, Run: scriptCrucible})
}

// concatInts is table.concat(list, sep) over a numeric list cell.
func concatInts(list []any, sep string) string {
	parts := make([]string, len(list))
	for i, v := range list {
		parts[i] = luaStr(v)
	}
	return strings.Join(parts, sep)
}

// concatNums is table.concat over describeStats orders.
func concatNums(nums []float64, sep string) string {
	parts := make([]string, len(nums))
	for i, v := range nums {
		parts[i] = luaNum(v)
	}
	return strings.Join(parts, sep)
}

func scriptCrucible(x *Ctx) error {
	x.LoadStatFile("stat_descriptions.txt")

	out := x.Out("Data/Crucible.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Item data (c) Grinding Gear Games\n\nreturn {\n")
	x.Dat("WeaponPassiveSkills").Rows(func(crucible *Row) bool {
		mod := crucible.Get("Mod").(*Row)
		modId := luaStr(mod.Get("Id"))
		if strings.HasSuffix(modId, "HardMode") {
			return true
		}
		stats := x.DescribeMod(mod)
		if len(stats.Orders) == 0 {
			// The Lua prints "Mod '...' has no stats".
			return true
		}
		out.W("\t[\"", modId, "\"] = { ")
		switch mod.Get("GenerationType").(int64) {
		case 31:
			out.W("type = \"Spawn\", ")
		case 32:
			out.W("type = \"MergeOnly\", ")
		}
		out.W("tier = ", crucible.Get("ModTier").(int64), ", ")
		out.W("\"", strings.Join(stats.Lines, "\", \""), "\", ")
		out.W("statOrder = { ", concatNums(stats.Orders, ", "), " }, ")
		out.W("level = ", mod.Get("Level").(int64), ", group = \"", luaStr(mod.Get("Type").(*Row).Get("Id")), "\", ")
		out.W("nodeType = \"", luaStr(crucible.Get("Type").(*Row).Get("Id")), "\", ")
		out.W("nodeLocation = { ", concatInts(crucible.Get("NodeSpawnLocation").([]any), ", "), " }, ")
		out.W("weightKey = { ")
		for _, tag := range mod.Get("SpawnTags").([]any) {
			out.W("\"", luaStr(tag.(*Row).Get("Id")), "\", ")
		}
		out.W("}, ")
		out.W("weightVal = { ", concatInts(mod.Get("SpawnWeights").([]any), ", "), " }, ")
		genTags := mod.Get("GenerationWeightTags").([]any)
		if len(genTags) > 0 {
			out.W("weightMultiplierKey = { ")
			for _, tag := range genTags {
				out.W("\"", luaStr(tag.(*Row).Get("Id")), "\", ")
			}
			out.W("}, ")
			out.W("weightMultiplierVal = { ", concatInts(mod.Get("GenerationWeightValues").([]any), ", "), " }, ")
			modTags := mod.Get("Tags").([]any)
			if len(modTags) > 0 {
				out.W("tags = { ")
				for _, tag := range modTags {
					out.W("\"", luaStr(tag.(*Row).Get("Id")), "\", ")
				}
				out.W("}, ")
			}
		}
		out.W("modTags = { ", stats.ModTags, " }, ")
		out.W("},\n")
		return true
	})
	out.W("}")
	return out.Close()
}
