// Port of .archive/src/Export/Scripts/costs.lua.

package export

func init() {
	Scripts = append(Scripts, Script{Name: "costs", Outs: []string{"Data/Costs.lua"}, Run: scriptCosts})
}

func scriptCosts(x *Ctx) error {
	out := x.Out("Data/Costs.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Skill costs data (c) Grinding Gear Games\n\n")
	out.W("return {\n")

	costSize := 0
	x.Dat("CostTypes").Rows(func(c *Row) bool {
		costSize++
		out.W("\t[", c.Index, "] = {\n")
		out.W("\t\tResource = \"", luaStr(c.Get("Resource")), "\",\n")
		if stat, ok := c.Get("Stat").(*Row); ok {
			out.W("\t\tStat = \"", luaStr(stat.Get("Id")), "\",\n")
		} else {
			out.W("\t\tStat = ", luaStr(c.Get("Stat")), ",\n")
		}
		out.W("\t\tResourceString = \"", luaStr(c.Get("ResourceString")), "\",\n")
		out.W("\t\tDivisor = ", c.Get("Divisor").(int64), ",\n")
		out.W("\t},\n")
		return true
	})

	// special case for soul cost
	out.W("\t[", costSize+1, "] = {\n")
	out.W("\t\tResource = \"", "Soul", "\",\n")
	out.W("\t\tStat = ", "\" \"", ",\n")
	out.W("\t\tResourceString = \"", "{0} Souls Per Use", "\",\n")
	out.W("\t\tDivisor = ", "1", ",\n")
	out.W("\t}\n")

	out.W("}\n")
	return out.Close()
}
