// Port of .archive/src/Export/Scripts/masters.lua.

package export

import "strings"

func init() {
	Scripts = append(Scripts, Script{Name: "masters", Outs: []string{"Data/ModMaster.lua"}, Run: scriptMasters})
}

func scriptMasters(x *Ctx) error {
	x.LoadStatFile("stat_descriptions.txt")

	itemClassMap := map[string]string{
		"LifeFlask":                "Flask",
		"ManaFlask":                "Flask",
		"HybridFlask":              "Flask",
		"Amulet":                   "Amulet",
		"Ring":                     "Ring",
		"Claw":                     "Claw",
		"Dagger":                   "Dagger",
		"Rune Dagger":              "Dagger",
		"Wand":                     "Wand",
		"One Hand Sword":           "One Handed Sword",
		"Thrusting One Hand Sword": "Thrusting One Handed Sword",
		"One Hand Axe":             "One Handed Axe",
		"One Hand Mace":            "One Handed Mace",
		"Bow":                      "Bow",
		"Fishing Rod":              "Fishing Rod",
		"Staff":                    "Staff",
		"Warstaff":                 "Staff",
		"Two Hand Sword":           "Two Handed Sword",
		"Two Hand Axe":             "Two Handed Axe",
		"Two Hand Mace":            "Two Handed Mace",
		"Quiver":                   "Quiver",
		"Belt":                     "Belt",
		"Gloves":                   "Gloves",
		"Boots":                    "Boots",
		"Body Armour":              "Body Armour",
		"Helmet":                   "Helmet",
		"Shield":                   "Shield",
		"Sceptre":                  "Sceptre",
		"UtilityFlask":             "Flask",
		"UtilityFlaskCritical":     "Flask",
		"Map":                      "Map",
		"Jewel":                    "Jewel",
	}

	out := x.Out("Data/ModMaster.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Item data (c) Grinding Gear Games\n\nreturn {\n")
	for _, craft := range x.Dat("CraftingBenchOptions").GetRowList("IsDisabled", false) {
		mod, ok := craft.Get("Mod").(*Row)
		if !ok {
			continue
		}
		out.W("\t{ ")
		switch mod.Get("GenerationType").(int64) {
		case 1:
			out.W("type = \"Prefix\", ")
		case 2:
			out.W("type = \"Suffix\", ")
		}
		out.W("affix = \"", luaStr(mod.Get("Name")), "\", ")
		stats := x.DescribeMod(mod)
		out.W("modTags = { ", stats.ModTags, " }, ")
		out.W("\"", strings.Join(stats.Lines, "\", \""), "\", ")
		out.W("statOrder = { ", concatNums(stats.Orders, ", "), " }, ")
		out.W("level = ", mod.Get("Level").(int64), ", group = \"", luaStr(mod.Get("Type").(*Row).Get("Id")), "\", ")
		out.W("types = { ")
		uniqueTypes := map[string]bool{}
		for _, category := range craft.Get("ItemCategories").([]any) {
			for _, itemClass := range category.(*Row).Get("ItemClasses").([]any) {
				mapped, found := itemClassMap[luaStr(itemClass.(*Row).Get("Id"))]
				if found && !uniqueTypes[mapped] {
					uniqueTypes[mapped] = true
					out.W("[\"", mapped, "\"] = true, ")
				}
			}
		}
		out.W("}, ")
		out.W("},\n")
	}
	out.W("}")
	return out.Close()
}
