// Port of .archive/src/Export/Scripts/essence.lua.

package export

import "sort"

func init() {
	Scripts = append(Scripts, Script{Name: "essence", Outs: []string{"Data/Essence.lua"}, Run: scriptEssence})
}

func scriptEssence(x *Ctx) error {
	colMap := map[string]string{
		"Amulet":                     "AmuletMod",
		"Ring":                       "RingMod",
		"Belt":                       "BeltMod",
		"Quiver":                     "QuiverMod",
		"Helmet":                     "HelmetMod",
		"Body Armour":                "BodyArmourMod",
		"Boots":                      "BootsMod",
		"Gloves":                     "GlovesMod",
		"Shield":                     "ShieldMod",
		"Bow":                        "BowMod",
		"Claw":                       "ClawMod",
		"Dagger":                     "DaggerMod",
		"Staff":                      "StaffMod",
		"Wand":                       "WandMod",
		"One Handed Axe":             "OneHandAxeMod",
		"One Handed Mace":            "OneHandMaceMod",
		"One Handed Sword":           "OneHandSwordMod",
		"Sceptre":                    "SceptreMod",
		"Thrusting One Handed Sword": "ThrustingOneHandSwordMod",
		"Two Handed Axe":             "TwoHandAxeMod",
		"Two Handed Mace":            "TwoHandMaceMod",
		"Two Handed Sword":           "TwoHandSwordMod",
	}
	sortedTypes := make([]string, 0, len(colMap))
	for k := range colMap {
		sortedTypes = append(sortedTypes, k)
	}
	sort.Strings(sortedTypes)

	out := x.Out("Data/Essence.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Item data (c) Grinding Gear Games\n\nreturn {\n")
	x.Dat("Essences").Rows(func(essence *Row) bool {
		if essence.Get("Tier").(int64) > 0 {
			base := essence.Get("BaseItemType").(*Row)
			out.W("\t[\"", luaStr(base.Get("Id")), "\"] = { name = \"", luaStr(base.Get("Name")), "\", ")
			out.W("type = ", essence.Get("Type").(*Row).Index-1, ", tier = ", essence.Get("Tier").(int64), ", ")
			out.W("mods = { ")
			for _, typ := range sortedTypes {
				out.W("[\"", typ, "\"] = \"", luaStr(essence.Get(colMap[typ]).(*Row).Get("Id")), "\", ")
			}
			out.W("}, },\n")
		}
		return true
	})
	out.W("}")
	return out.Close()
}
