// Port of .archive/src/Export/Scripts/modScalability.lua.

package export

import "sort"

func init() {
	Scripts = append(Scripts, Script{Name: "modScalability", Outs: []string{"Data/ModScalability.lua"}, Run: scriptModScalability})
}

func scriptModScalability(x *Ctx) error {
	x.LoadStatFile("stat_descriptions.txt")

	out := x.Out("Data/ModScalability.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Item data (c) Grinding Gear Games\n\nreturn {\n")
	scalabilityLines := x.DescribeScalability("stat_descriptions.txt")
	lines := make([]string, 0, len(scalabilityLines))
	for line := range scalabilityLines {
		lines = append(lines, line)
	}
	sort.Strings(lines)
	for _, line := range lines {
		sc := scalabilityLines[line]
		out.W("\t[\"", line, "\"] = { ")
		for i, scalable := range sc {
			out.W("{ isScalable = ", luaStr(scalable.isScalable))
			if scalable.formats != nil {
				out.W(", formats = { ")
				for j, format := range scalable.formats {
					out.W("\"", format, "\"")
					if j < len(scalable.formats)-1 {
						out.W(", ")
					}
				}
				out.W(" }")
			}
			out.W(" }")
			if i < len(sc)-1 {
				out.W(", ")
			}
		}
		out.W(" },\n")
	}
	out.W("}")
	return out.Close()
}
