// Port of .archive/src/Export/Scripts/mapUniqueToFoulborn.lua.

package export

import (
	"regexp"
	"sort"
	"strings"
)

func init() {
	Scripts = append(Scripts, Script{Name: "mapUniqueToFoulborn", Outs: []string{"Data/ModFoulbornMap.lua"}, Run: scriptMapUniqueToFoulborn})
}

var foulbornIdFixer = strings.NewReplacer(
	"Amluet", "Amulet",
	"Botts", "Boots",
	"HelmetDex2", "DexHelmet2",
	"HelmetInt2", "IntHelmet2",
)

func scriptMapUniqueToFoulborn(x *Ctx) error {
	if err := x.EnsureMods(); err != nil {
		return err
	}
	// The Lua dofiles Scripts/flavourText.lua unconditionally.
	if err := scriptFlavourText(x); err != nil {
		return err
	}

	foulbornIds := make([]string, 0, len(x.modFoulborn))
	for id := range x.modFoulborn {
		foulbornIds = append(foulbornIds, id)
	}
	sort.Strings(foulbornIds)

	finalUniqueMap := map[string][][]string{}
	for _, unique := range x.flavourEntries {
		re := regexp.MustCompile(regexp.QuoteMeta(unique.id) + "[A-Za-z]+")
		for _, modId := range foulbornIds {
			sanitized := foulbornIdFixer.Replace(modId)
			if re.MatchString(sanitized) {
				finalUniqueMap[unique.name] = append(finalUniqueMap[unique.name], x.modFoulborn[modId].lines)
			}
		}
	}

	out := x.Out("Data/ModFoulbornMap.lua")
	out.W("-- This file is automatically generated, do not edit!\n")
	out.W("-- Item data (c) Grinding Gear Games\n\nreturn {\n")
	names := make([]string, 0, len(finalUniqueMap))
	for name := range finalUniqueMap {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		out.W("\t[\"", name, "\"] = {\n")
		for _, mod := range finalUniqueMap[name] {
			out.W("\t\t\"", strings.Join(mod, " "), "\",\n")
		}
		out.W("\t},\n")
	}
	out.W("}\n")
	return out.Close()
}
