// Transformed one-time from .archive/src/Export/spec.lua (column schemas for
// the game's .dat64 tables); maintained here in Go from now on. Tables with no
// spec are omitted. UI-only column widths are dropped.

package export

// Col describes one column of a .dat64 table.
type Col struct {
	Name  string // column name; "" for unknown/unnamed columns
	Type  string // Bool, Int, UInt16, UInt, Interval, Float, String, Enum, ShortKey, Key
	List  bool   // 16-byte list cell (count + offset into variable data)
	RefTo string // referenced table for Enum/ShortKey/Key columns
}

var datSpecs = map[string][]Col{
	"achievementitems": {
		{Name: "Id", Type: "String", RefTo: "Achievements"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Name", Type: "String"},
		{Name: "CompletionsRequired", Type: "Int"},
		{Name: "AchievementsKey", Type: "Key", RefTo: "Achievements"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"actiontypes": {
		{Name: "Name", Type: "String"},
		{Name: "HASH16", Type: "UInt16"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"activeskills": {
		{Name: "Id", Type: "String"},
		{Name: "DisplayName", Type: "String"},
		{Name: "Description", Type: "String"},
		{Name: "ActionType", Type: "Key", RefTo: "ActionTypes"},
		{Name: "Icon", Type: "String"},
		{Name: "TargetTypes", Type: "Enum", List: true, RefTo: "ActiveSkillTargetTypes"},
		{Name: "SkillTypes", Type: "Key", List: true, RefTo: "ActiveSkillType"},
		{Name: "WeaponRestrictions", Type: "Key", List: true, RefTo: "ItemClasses"},
		{Name: "WebsiteDescription", Type: "String"},
		{Name: "WebsiteImage", Type: "String"},
		{Name: "HideOnWebsite", Type: "Bool"},
		{Name: "GrantedEffect", Type: "String"},
		{Type: "Bool"},
		{Name: "SkillTotem", Type: "Int"},
		{Name: "ManuallyCast", Type: "Bool"},
		{Name: "SkillSpecificStat", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "GenericStat", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "MinionSkillTypes", Type: "Key", List: true, RefTo: "ActiveSkillType"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "SecondarySkillSpecificStat", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "SkillMine", Type: "Int", RefTo: "SkillMines"},
		{Name: "TargetingBehaviours", Type: "Key", RefTo: "AlternateSkillTargetingBehaviours"},
		{Type: "Bool"},
		{Name: "TotemAI", Type: "String"},
		{Name: "StatContextFlags", Type: "Key", List: true, RefTo: "VirtualStatContextFlags"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "RegularVersion", Type: "ShortKey", RefTo: "ActiveSkills"},
		{Type: "String"},
	},
	"activeskilltype": {
		{Name: "Id", Type: "String"},
		{Name: "FlagStat", Type: "Key", RefTo: "Stats"},
	},
	"addbufftotargetvarieties": {
		{Name: "BuffDefinitions", Type: "Key", RefTo: "BuffDefinitions"},
		{Type: "Int", List: true},
		{Name: "StatsKeys", Type: "Key", List: true, RefTo: "Stats"},
		{Type: "Int"},
		{Type: "Int", List: true},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int", List: true},
	},
	"additionallifescaling": {
		{Type: "Int"},
		{Name: "DATFilename", Type: "String"},
		{Name: "DATFilepath", Type: "String"},
	},
	"aegisvariations": {
		{Name: "Id", Type: "String"},
		{Name: "MitigatesPhysicalDmg", Type: "Bool"},
		{Name: "MitigatesFireDmg", Type: "Bool"},
		{Name: "MitigatesColdDmg", Type: "Bool"},
		{Name: "MitigatesLightningDmg", Type: "Bool"},
		{Name: "MitigatesChaosDmg", Type: "Bool"},
		{Name: "ActiveBuff", Type: "Key", RefTo: "BuffDefinitions"},
		{Name: "DepletedBuff", Type: "Key", RefTo: "BuffDefinitions"},
		{Type: "Key", RefTo: "BuffDefinitions"},
		{Name: "AnimatedEffect", Type: "Key", RefTo: "MiscAnimated"},
		{Name: "MtxEffect", Type: "Key", List: true, RefTo: "MiscAnimated"},
	},
	"alternatepassiveadditions": {
		{Name: "Id", Type: "String"},
		{Name: "AlternateTreeVersionsKey", Type: "Key", RefTo: "AlternateTreeVersions"},
		{Name: "SpawnWeight", Type: "Int"},
		{Name: "StatsKeys", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: "Interval"},
		{Name: "Stat2", Type: "Interval"},
		{Name: "Stat3", Type: "Interval"},
		{Name: "PassiveType", Type: "Int", List: true},
		{Name: "SpawnWeight", Type: "Int"},
	},
	"alternatepassiveskills": {
		{Name: "Id", Type: "String"},
		{Name: "AlternateTreeVersionsKey", Type: "Key", RefTo: "AlternateTreeVersions"},
		{Name: "Name", Type: "String"},
		{Name: "PassiveType", Type: "Int", List: true},
		{Name: "StatsKeys", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: "Interval"},
		{Name: "Stat2", Type: "Interval"},
		{Name: "Stat3", Type: "Interval"},
		{Name: "Stat4", Type: "Interval"},
		{Name: "Stat5", Type: "Interval"},
		{Name: "Stat6", Type: "Interval"},
		{Name: "SpawnWeight", Type: "Int"},
		{Name: "ConquerorIndex", Type: "Int"},
		{Name: "Random", Type: "Interval"},
		{Name: "FlavourText", Type: "String"},
		{Name: "DDSIcon", Type: "String"},
		{Name: "AchievementItemsKeys", Type: "Key", List: true},
		{Name: "ConquerorVersion", Type: "Int"},
		{Name: "ConquerorSpawnWeight", Type: "Int"},
	},
	"alternatequalitytypes": {
		{Name: "Id", Type: "String"},
		{Name: "Description", Type: "String"},
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Type: "Key"},
		{Name: "MapStats", Type: "Key", List: true, RefTo: "Stats"},
		{Type: "Int"},
		{Name: "IsCatalyst", Type: "Bool"},
		{Name: "HASH16", Type: "UInt16"},
		{Name: "CatalystMod", Type: "Key", RefTo: "Mods"},
	},
	"alternateskilltargetingbehaviours": {
		{Name: "Id", Type: "String"},
		{Name: "Value", Type: "Int"},
		{Name: "ClientString", Type: "Key", RefTo: "ClientStrings"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int", List: true},
	},
	"alternatetreeart": {
		{Name: "TreeVersion", Type: "Key", RefTo: "AlternateTreeVersions"},
		{Name: "ConnectionArt", Type: "Key", RefTo: "PassiveSkillTreeConnectionArt"},
		{Name: "KeystoneFrameArt", Type: "Key", RefTo: "PassiveSkillTreeNodeFrameArt"},
		{Name: "RadiiArt", Type: "Key", RefTo: "PassiveJewelRadiiArt"},
		{Name: "NotableFrameArt", Type: "Key", RefTo: "PassiveSkillTreeNodeFrameArt"},
		{Name: "AscendancyFrameArt", Type: "Key", RefTo: "PassiveSkillTreeNodeFrameArt"},
	},
	"alternatetreeversions": {
		{Name: "Id", Type: "String"},
		{Name: "SmallAttributeReplaced", Type: "Bool"},
		{Name: "SmallNormalPassiveReplaced ", Type: "Bool"},
		{Name: "SmallAttributePassiveSkillAdditions", Type: "Interval"},
		{Name: "NotableAdditions", Type: "Interval"},
		{Name: "SmallNormalPassiveSkillAdditions", Type: "Interval"},
		{Name: "NotableReplacementSpawnWeight ", Type: "Int"},
	},
	"animateweaponuniques": {
		{Name: "Name", Type: "String"},
		{Name: "VisualIdentity", Type: "Key", RefTo: "ItemVisualIdentity"},
		{Name: "ItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "MinLevelReq", Type: "Int"},
	},
	"animation": {
		{Name: "Id", Type: "String"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "Mainhand", Type: "ShortKey", RefTo: "Animation"},
		{Name: "Offhand", Type: "ShortKey", RefTo: "Animation"},
		{Type: "Bool"},
		{Name: "VariationStat", Type: "Key", RefTo: "Stats"},
		{Name: "AnimationStart", Type: "ShortKey", RefTo: "Animation"},
		{Type: "Bool"},
		{Name: "AnimationEnd", Type: "ShortKey", RefTo: "Animation"},
		{Type: "Int", List: true},
	},
	"archetypes": {
		{Type: "String"},
	},
	"archnemesismetarewards": {
		{Type: "String"},
	},
	"archnemesismodcomboachievements": {
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
	},
	"archnemesismods": {
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
	},
	"archnemesismodvisuals": {
		{Type: "String"},
	},
	"archnemesisrecipes": {
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
	},
	"armourtypes": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "ArmourMin", Type: "Int"},
		{Name: "ArmourMax", Type: "Int"},
		{Name: "EvasionMin", Type: "Int"},
		{Name: "EvasionMax", Type: "Int"},
		{Name: "EnergyShieldMin", Type: "Int"},
		{Name: "EnergyShieldMax", Type: "Int"},
		{Name: "MovementPenalty", Type: "Int"},
		{Name: "WardMin", Type: "Int"},
		{Name: "WardMax", Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
	},
	"ascendancy": {
		{Name: "Id", Type: "String"},
		{Name: "Index", Type: "Int"},
		{Name: "Class", Type: "Key", RefTo: "Characters"},
		{Name: "FlavourRect", Type: "String"},
		{Name: "FlavourColour", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "Flavour", Type: "String"},
		{Name: "Audio", Type: "String"},
		{Name: "PassiveTreeImage", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "BackgroundImage", Type: "String"},
		{Name: "AlternateName", Type: "String"},
		{Name: "AlternateFlavourText", Type: "String"},
		{Name: "AlternateBackgroundImage", Type: "String"},
		{Name: "AlternatePassiveTreeImage", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "AlternateIcon", Type: "String"},
	},
	"atlasmods": {
		{Name: "Mod", Type: "Key", RefTo: "Mods"},
		{Name: "Tier", Type: "Int"},
	},
	"azmerifeaturerooms": {
		{Type: "Int"},
		{Type: "Enum"},
		{Type: "String"},
		{Type: "String"},
		{Name: "Achievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Type: "Bool"},
	},
	"azmerilifescalingperlevel": {
		{Type: "Int"},
		{Type: "Int"},
	},
	"azmeriwoodsdusttype": {
		{Name: "AzmeriLeader", Type: "String"},
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Name", Type: "String"},
		{Name: "UISymbol", Type: "String"},
		{Type: "Key"},
		{Type: "Key"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Name: "UiArt", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Key"},
		{Type: "String"},
	},
	"baseitemtypes": {
		{Name: "Id", Type: "String"},
		{Name: "ItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "Width", Type: "Int"},
		{Name: "Height", Type: "Int"},
		{Name: "Name", Type: "String"},
		{Name: "BaseType", Type: "String"},
		{Name: "DropLevel", Type: "Int"},
		{Name: "FlavourTextKey", Type: "Key", RefTo: "FlavourText"},
		{Name: "ImplicitMods", Type: "Key", List: true, RefTo: "Mods"},
		{Name: "SizeOnGround", Type: "Int"},
		{Name: "SoundEffect", Type: "Key", RefTo: "SoundEffects"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "ModDomain", Type: "Enum", RefTo: "ModDomains"},
		{Name: "ItemVisualIdentityKey", Type: "Key", RefTo: "ItemVisualIdentity"},
		{Name: "HASH32", Type: "UInt"},
		{Name: "VendorRecipeAchievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "Inflection", Type: "String"},
		{Name: "EquipAchievement", Type: "Key", RefTo: "AchievementItems"},
		{Name: "IsCorrupted", Type: "Bool"},
		{Name: "IdentifyAchievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "IdentifyMagicAchievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "FragmentBaseItemTypesKey", Type: "ShortKey", RefTo: "BaseItemTypes"},
		{Type: "Bool"},
		{Type: "Key"},
		{Type: "Key"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "Achievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "Achievement2", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "IgnoreQuantBonus", Type: "Bool"},
		{Type: "Bool"},
		{Name: "ShopTag", Type: "Key", RefTo: "ShopTag"},
		{Type: "Key", List: true},
		{Type: "Key", List: true},
		{Type: "Key", List: true},
		{Name: "EnchantMods", Type: "Key", List: true, RefTo: "Mods"},
	},
	"brequelgraftgrantedskilllevels": {
		{Name: "AreaLevel", Type: "Int"},
		{Name: "SkillLevel", Type: "Int"},
		{Name: "LevelReq", Type: "Int"},
	},
	"brequelgraftskillstats": {
		{Name: "GraftStat", Type: "Key", RefTo: "Stats"},
		{Name: "PlayerStat", Type: "Key", RefTo: "Stats"},
	},
	"brequelgrafttypes": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "LeftArmAnimatedObject", Type: "String"},
		{Name: "RightArmAnimatedObject", Type: "String"},
		{Name: "SkillGem", Type: "Key", RefTo: "SkillGems"},
		{Type: "Int"},
		{Name: "AIScript", Type: "String"},
		{Name: "Achievement", Type: "Key", RefTo: "AchievementItems"},
	},
	"buffdefinitions": {
		{Name: "Id", Type: "String"},
		{Name: "Description", Type: "String"},
		{Name: "Invisible", Type: "Bool"},
		{Name: "Removable", Type: "Bool"},
		{Name: "Name", Type: "String"},
		{Name: "Stats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "CancelOnDeath", Type: "Bool"},
		{Name: "MergeMode", Type: "Enum", RefTo: "BuffMergeModes"},
		{Name: "ShowCount", Type: "Bool"},
		{Name: "MaxStat", Type: "Key", RefTo: "Stats"},
		{Name: "CurrentStat", Type: "Key", RefTo: "Stats"},
		{Type: "Bool"},
		{Type: "Enum"},
		{Name: "Visual", Type: "Key", RefTo: "BuffVisuals"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Enum"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "Limit", Type: "Int"},
		{Type: "Bool"},
		{Name: "Implementation", Type: "String"},
		{Name: "isRecovery", Type: "Bool"},
		{Type: "Bool"},
		{Name: "MinStat", Type: "Key", RefTo: "Stats"},
		{Type: "Bool"},
		{Name: "UIStackMode", Type: "Int"},
		{Type: "Bool"},
		{Name: "IsSkillBuff", Type: "Bool"},
		{Type: "Int"},
		{Type: "Int", List: true},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "MultiPartAchievement", Type: "Key", List: true, RefTo: "MultiPartAchievements"},
		{Type: "Bool"},
		{Name: "Stats2", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "GrantedFlags", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "GrantedStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "ConditionStats", Type: "Key", List: true, RefTo: "Stats"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Key", RefTo: "Stats"},
		{Type: "Int", List: true},
		{Type: "String"},
		{Type: "Key", List: true, RefTo: "Stats"},
		{Type: "Bool"},
	},
	"bufftemplates": {
		{Name: "Id", Type: "String"},
		{Name: "BuffDefinition", Type: "Key", RefTo: "BuffDefinitions"},
		{Name: "StatValues", Type: "Int", List: true},
		{Name: "AuraRadius", Type: "Int"},
		{Type: "Int", List: true},
		{Type: "Int", List: true, RefTo: "Mods"},
		{Name: "Visual", Type: "Key", RefTo: "BuffVisuals"},
		{Type: "Float"},
		{Type: "Bool"},
		{Name: "Stats", Type: "Key", List: true, RefTo: "Stats"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Key", RefTo: "Stats"},
	},
	"buffvisualartvariations": {
		{Name: "Id", Type: "String"},
	},
	"buffvisualorbart": {
		{Name: "Id", Type: "String"},
		{Name: "MiscAnimated", Type: "Key", RefTo: "MiscAnimated"},
		{Type: "Int", List: true},
		{Type: "String", List: true},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "Int"},
		{Name: "MonsterExpiredSound", Type: "Key", RefTo: "SoundEffects"},
		{Name: "PlayerExpiredSound", Type: "Key", RefTo: "SoundEffects"},
		{Name: "PlayerAcquiredSound", Type: "Key", RefTo: "SoundEffects"},
		{Type: "Key", RefTo: "SoundEffects"},
		{Type: "Bool"},
		{Type: "Int"},
	},
	"buffvisualorbs": {
		{Name: "Id", Type: "String"},
		{Name: "OrbType", Type: "Key", RefTo: "BuffVisualOrbTypes"},
		{Name: "OrbArt", Type: "Key", List: true, RefTo: "BuffVisualOrbArt"},
		{Name: "OrbArtPlayer", Type: "Key", List: true, RefTo: "BuffVisualOrbArt"},
		{Name: "OrbArt2", Type: "Key", List: true, RefTo: "BuffVisualOrbArt"},
	},
	"buffvisualorbtypes": {
		{Name: "Id", Type: "String"},
		{Type: "Float"},
		{Type: "Float"},
		{Type: "Float"},
		{Type: "Float"},
		{Type: "Int"},
		{Type: "Bool"},
		{Name: "RadiusStat", Type: "Key", RefTo: "Stats"},
		{Name: "HeightStat", Type: "Key", RefTo: "Stats"},
		{Type: "Int"},
		{Type: "Float"},
		{Type: "Int"},
		{Type: "Float"},
		{Type: "Bool"},
		{Type: "Float"},
		{Type: "Int"},
	},
	"buffvisuals": {
		{Name: "Id", Type: "String"},
		{Name: "Icon", Type: "String"},
		{Type: "String", List: true},
		{Type: "String", List: true},
		{Name: "PreloadGroup", Type: "Key", List: true, RefTo: "PreloadGroups"},
		{Type: "Bool"},
		{Name: "Name", Type: "String"},
		{Name: "MiscAnimated", Type: "Key", RefTo: "MiscAnimated"},
		{Type: "Key", RefTo: "MiscAnimated"},
		{Name: "Description", Type: "String"},
		{Name: "EPKFile", Type: "String"},
		{Type: "Bool"},
		{Type: "String"},
		{Type: "Int", List: true},
		{Name: "EPKFiles", Type: "String", List: true},
		{Name: "Orbs", Type: "Key", List: true, RefTo: "BuffVisualOrbs"},
		{Name: "Animation", Type: "Key", RefTo: "MiscAnimated"},
		{Type: "Key"},
		{Type: "String"},
		{Type: "Float"},
		{Type: "Float"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "String", List: true},
	},
	"buffvisualsartvariations": {
		{Name: "Buff", Type: "String"},
		{Name: "Visuals", Type: "Key", List: true, RefTo: "BuffVisuals"},
		{Type: "Int"},
	},
	"buffvisualsetentries": {
		{Name: "Id", Type: "String"},
		{Type: "Int"},
		{Name: "Visual", Type: "Key", RefTo: "BuffVisuals"},
		{Type: "Int"},
	},
	"characters": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "AnimatedObject", Type: "String"},
		{Name: "ActorFile", Type: "String"},
		{Name: "BaseMaxLife", Type: "Int"},
		{Name: "BaseMaxMana", Type: "Int"},
		{Name: "WeaponSpeed", Type: "Int"},
		{Name: "MinDamage", Type: "Int"},
		{Name: "MaxDamage", Type: "Int"},
		{Name: "MaxAttackDistance", Type: "Int"},
		{Name: "Icon", Type: "String"},
		{Name: "IntegerId", Type: "Int"},
		{Name: "BaseStrength", Type: "Int"},
		{Name: "BaseDexterity", Type: "Int"},
		{Name: "BaseIntelligence", Type: "Int"},
		{Type: "String", List: true, RefTo: "Stats"},
		{Name: "Description", Type: "String"},
		{Name: "StartSkillGem", Type: "Key", RefTo: "SkillGems"},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "CharacterSize", Type: "Int"},
		{Name: "IntroSoundFile", Type: "String"},
		{Name: "StartWeapons", Type: "Key", List: true, RefTo: "BaseItemTypes"},
		{Name: "Gender", Type: "String"},
		{Name: "TraitDescription", Type: "String"},
		{Type: "Key", RefTo: "GrantedEffectStatSets"},
		{Type: "Key"},
		{Type: "Key"},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Key", List: true},
		{Name: "PassiveTreeImage", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "TencentVideo", Type: "String"},
		{Name: "AttrsAsId", Type: "String"},
		{Name: "LoginScreen", Type: "String"},
		{Name: "PlayerCritter", Type: "String"},
		{Name: "PlayerEffect", Type: "String"},
		{Name: "AfterImage", Type: "String"},
		{Name: "Mirage", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "CloneImmobile", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "ReplicateClone", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "LightningClone", Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Float"},
		{Type: "Float"},
		{Name: "SkillTreeBackground", Type: "String"},
		{Name: "Clone", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "Double", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "MirageWarrior", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "DoubleTwo", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "DarkExile", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "Attr", Type: "String"},
		{Name: "AttrLowercase", Type: "String"},
		{Name: "Script", Type: "String"},
		{Type: "Key"},
		{Type: "Int"},
		{Name: "RainOfArrowsClone", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "ElementalShotClone", Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Int"},
		{Type: "Float"},
		{Type: "Key"},
		{Type: "Key"},
	},
	"clientstrings": {
		{Name: "Id", Type: "String"},
		{Name: "Text", Type: "String"},
		{Name: "XBoxText", Type: "String"},
		{Name: "XBoxText2", Type: "String"},
		{Name: "HASH32", Type: "UInt"},
		{Name: "PlaystationText", Type: "String"},
		{Type: "String"},
	},
	"commands": {
		{Name: "Id", Type: "String"},
		{Name: "Command", Type: "String"},
		{Type: "Bool"},
		{Name: "EnglishCommand", Type: "String"},
		{Name: "Description", Type: "String"},
		{Type: "Bool"},
	},
	"componentarmour": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Armour", Type: "Int"},
		{Name: "Evasion", Type: "Int"},
		{Name: "EnergyShield", Type: "Int"},
		{Name: "MovementPenalty", Type: "Int"},
	},
	"componentattributerequirements": {
		{Name: "BaseItemType", Type: "String"},
		{Name: "Str", Type: "Int"},
		{Name: "Dex", Type: "Int"},
		{Name: "Int", Type: "Int"},
	},
	"componentcharges": {
		{Name: "BaseItemType", Type: "String"},
		{Name: "Max", Type: "Int"},
		{Name: "PerUse", Type: "Int"},
		{Name: "MaxRuthless", Type: "Int"},
		{Name: "PerUseRuthless", Type: "Int"},
	},
	"corpsetypetags": {
		{Name: "Tag", Type: "Key", RefTo: "Tags"},
		{Name: "Name", Type: "String"},
		{Name: "Buff", Type: "Key", RefTo: "BuffDefinitions"},
		{Name: "Icon", Type: "String"},
		{Type: "Int"},
		{Type: "Key"},
		{Type: "String"},
		{Type: "Key"},
	},
	"costtypes": {
		{Name: "Resource", Type: "String"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Name: "ResourceString", Type: "String"},
		{Name: "Divisor", Type: "Int"},
	},
	"craftingbenchoptions": {
		{Name: "HideoutNPC", Type: "Key", RefTo: "HideoutNPCs"},
		{Name: "Order", Type: "Int"},
		{Name: "Mod", Type: "Key", RefTo: "Mods"},
		{Name: "Cost_BaseItemTypes", Type: "Key", List: true, RefTo: "BaseItemTypes"},
		{Name: "CostValue", Type: "Int", List: true},
		{Name: "RequiredLevel", Type: "Int"},
		{Name: "Name", Type: "String"},
		{Type: "Int"},
		{Name: "ItemClasses", Type: "Key", List: true, RefTo: "ItemClasses"},
		{Name: "Links", Type: "Int"},
		{Name: "Colours", Type: "String"},
		{Name: "Sockets", Type: "Int"},
		{Name: "ItemQuantity", Type: "Int"},
		{Type: "Int", List: true},
		{Name: "Description", Type: "String"},
		{Name: "IsDisabled", Type: "Bool"},
		{Name: "IsAreaOption", Type: "Bool"},
		{Name: "RecipeIds", Type: "Int", List: true},
		{Name: "Tier", Type: "Int"},
		{Name: "ItemCategories", Type: "Key", List: true, RefTo: "CraftingItemClassCategories"},
		{Type: "Int"},
		{Type: "Key", List: true},
		{Name: "Achievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "AddEnchantment", Type: "Key", RefTo: "Mods"},
		{Name: "SortCategory", Type: "Key", RefTo: "CraftingBenchSortCategories"},
		{Name: "ModType", Type: "Key", RefTo: "ModType"},
		{Type: "Bool"},
		{Type: "Int"},
		{Name: "Stat1", Type: "Key", RefTo: "Stats"},
		{Name: "Stat2", Type: "Key", RefTo: "Stats"},
		{Name: "Stat3", Type: "Key", RefTo: "Stats"},
		{Type: "Bool"},
		{Name: "PassiveSkills", Type: "Key", List: true, RefTo: "PassiveSkills"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Type: "Int", List: true},
	},
	"craftingbenchsortcategories": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "Key", RefTo: "ClientStrings"},
		{Name: "IsVisible", Type: "Bool"},
		{Type: "Key"},
	},
	"craftingbenchspecificoptionid": {
		{Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
	},
	"craftingbenchunlockcategories": {
		{Name: "Id", Type: "String"},
	},
	"craftingitemclasscategories": {
		{Name: "Id", Type: "String"},
		{Name: "ItemClasses", Type: "Key", List: true, RefTo: "ItemClasses"},
		{Type: "String"},
		{Type: "String"},
		{Type: "Key", List: true},
	},
	"cruciblelifescalingperlevel": {
		{Name: "Level", Type: "Int"},
		{Name: "LifeMore", Type: "Int"},
	},
	"crucibletags": {
		{Name: "Tags", Type: "String"},
		{Type: "Bool"},
	},
	"currencyexchange": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Category", Type: "Key", RefTo: "CurrencyExchangeCategories"},
		{Name: "SubCategory", Type: "Key", RefTo: "CurrencyExchangeCategories"},
		{Type: "Bool"},
		{Name: "EnabledInLeague", Type: "Bool"},
		{Name: "GoldFee", Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"defaultmonsterstats": {
		{Name: "Level", Type: "String"},
		{Name: "Damage", Type: "Float"},
		{Name: "Evasion", Type: "Int"},
		{Name: "Accuracy", Type: "Int"},
		{Name: "MonsterLife", Type: "Int"},
		{Name: "XP", Type: "Int"},
		{Name: "MinionLife", Type: "Int"},
		{Name: "Armour", Type: "Int"},
		{Name: "ResistancePart", Type: "Int"},
		{Name: "MinionDamage", Type: "Float"},
		{Name: "AltLife1", Type: "Int"},
		{Name: "AltDamage1", Type: "Float"},
		{Name: "AltDamage2", Type: "Float"},
		{Name: "AltLife2", Type: "Int"},
		{Name: "EvasiveEvasion", Type: "Int"},
		{Name: "AilmentThreshold", Type: "Int"},
		{Name: "MonsterPhysConversionMulti", Type: "Int"},
	},
	"descendancy": {
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
	},
	"displayminionmonstertype": {
		{Name: "Id", Type: "Int"},
		{Name: "MonsterVarieties", Type: "Key", RefTo: "MonsterVarieties"},
	},
	"divinationbufftemplates": {
		{Name: "Buff", Type: "Key", RefTo: "BuffTemplates"},
		{Name: "DivCardArt", Type: "Key", RefTo: "DivinationCardArt"},
	},
	"effectivenesscostconstants": {
		{Name: "Id", Type: "String"},
		{Name: "Value", Type: "Float"},
	},
	"essences": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Unknown1", Type: "Key"},
		{Name: "Unknown2", Type: "Key"},
		{Name: "Unknown3", Type: "Key"},
		{Name: "Unknown4", Type: "Key"},
		{Name: "Unknown5", Type: "Key"},
		{Name: "Unknown6", Type: "Key"},
		{Name: "Unknown7", Type: "Key"},
		{Name: "Unknown8", Type: "Key"},
		{Name: "Unknown9", Type: "Key"},
		{Name: "Unknown10", Type: "Key"},
		{Name: "Unknown11", Type: "Key"},
		{Name: "WandsMod", Type: "Key", RefTo: "Mods"},
		{Name: "BowMods", Type: "Key", RefTo: "Mods"},
		{Name: "QuiverMod", Type: "Key", RefTo: "Mods"},
		{Name: "AmuletMods", Type: "Key", RefTo: "Mods"},
		{Name: "RingMods", Type: "Key", RefTo: "Mods"},
		{Name: "BeltMods", Type: "Key", RefTo: "Mods"},
		{Name: "GlovesMods", Type: "Key", RefTo: "Mods"},
		{Name: "BootsMods", Type: "Key", RefTo: "Mods"},
		{Name: "BodyArmourMods", Type: "Key", RefTo: "Mods"},
		{Name: "HelmetMods", Type: "Key", RefTo: "Mods"},
		{Name: "ShieldMods", Type: "Key", RefTo: "Mods"},
		{Name: "HASH32", Type: "UInt"},
		{Name: "DropLevel", Type: "Int", List: true},
		{Name: "MonsterMods", Type: "Key", List: true, RefTo: "Mods"},
		{Name: "Type", Type: "Key", RefTo: "EssenceType"},
		{Name: "Tier", Type: "Int"},
		{Type: "Int", List: true},
		{Name: "WeaponMod", Type: "Key", RefTo: "Mods"},
		{Name: "MeleeWeaponMod", Type: "Key", RefTo: "Mods"},
		{Name: "OneHandWeaponMod", Type: "Key", RefTo: "Mods"},
		{Name: "TwoHandWeaponMod", Type: "Key", RefTo: "Mods"},
		{Name: "TwoHandMeleeMod", Type: "Key", RefTo: "Mods"},
		{Name: "ArmourMod", Type: "Key", RefTo: "Mods"},
		{Name: "RangedWeaponMod", Type: "Key", RefTo: "Mods"},
		{Name: "HelmetMod", Type: "Key", RefTo: "Mods"},
		{Name: "BodyArmourMod", Type: "Key", RefTo: "Mods"},
		{Name: "BootsMod", Type: "Key", RefTo: "Mods"},
		{Name: "GlovesMod", Type: "Key", RefTo: "Mods"},
		{Name: "BowMod", Type: "Key", RefTo: "Mods"},
		{Name: "WandMod", Type: "Key", RefTo: "Mods"},
		{Name: "StaffMod", Type: "Key", RefTo: "Mods"},
		{Name: "TwoHandSwordMod", Type: "Key", RefTo: "Mods"},
		{Name: "TwoHandAxeMod", Type: "Key", RefTo: "Mods"},
		{Name: "TwoHandMaceMod", Type: "Key", RefTo: "Mods"},
		{Name: "ClawMod", Type: "Key", RefTo: "Mods"},
		{Name: "DaggerMod", Type: "Key", RefTo: "Mods"},
		{Name: "OneHandSwordMod", Type: "Key", RefTo: "Mods"},
		{Name: "ThrustingOneHandSwordMod", Type: "Key", RefTo: "Mods"},
		{Name: "OneHandAxeMod", Type: "Key", RefTo: "Mods"},
		{Name: "OneHandMaceMod", Type: "Key", RefTo: "Mods"},
		{Name: "SceptreMod", Type: "Key", RefTo: "Mods"},
		{Name: "MonsterMod", Type: "Key", RefTo: "Mods"},
		{Name: "ItemLevelRestriction", Type: "Int", RefTo: "Mods"},
		{Name: "BeltMod", Type: "Key", RefTo: "Mods"},
		{Name: "AmuletMod", Type: "Key", RefTo: "Mods"},
		{Name: "RingMod", Type: "Key", RefTo: "Mods"},
		{Name: "JewelleryMod", Type: "Key", RefTo: "Mods"},
		{Name: "ShieldMod", Type: "Key", RefTo: "Mods"},
		{Name: "OtherItemMod", Type: "Key", RefTo: "Mods"},
		{Name: "IsScreaming", Type: "Bool"},
		{Name: "MemoryLines", Type: "Key", List: true, RefTo: "Mods"},
		{Type: "Int", List: true},
		{Type: "Int", List: true},
	},
	"essencetype": {
		{Name: "Name", Type: "String"},
		{Name: "TypeTier", Type: "Int"},
		{Name: "CorruptOnly", Type: "Bool"},
		{Type: "Key", RefTo: "Words"},
		{Name: "PartyMods", Type: "Key", RefTo: "Stats"},
	},
	"experiencelevels": {
		{Type: "String"},
		{Type: "Int"},
		{Type: "UInt"},
	},
	"flasks": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Name", Type: "String"},
		{Type: "Enum", RefTo: "FlaskType"},
		{Name: "LifePerUse", Type: "Int"},
		{Name: "ManaPerUse", Type: "Int"},
		{Name: "RecoveryTime", Type: "Int"},
		{Name: "Buff", Type: "Key", RefTo: "BuffDefinitions"},
		{Name: "BuffMagnitudes", Type: "Int", List: true},
		{Name: "RecoveryTime2", Type: "Int"},
		{Name: "BuffMagnitude2", Type: "Int", List: true},
	},
	"flavourtext": {
		{Name: "Id", Type: "String"},
		{Type: "Int"},
		{Name: "Text", Type: "String"},
	},
	"gameconstants": {
		{Name: "Id", Type: "String"},
		{Name: "Value", Type: "Int"},
		{Name: "Divisor", Type: "Int"},
	},
	"gemeffects": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "GrantedEffect", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "GrantedEffectHardmode", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "GrantedEffect2", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "GrantedEffect2Hardmode", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "Description", Type: "String"},
		{Name: "SecondarySupportName", Type: "String"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "GemTags"},
		{Name: "HungryLoopMod", Type: "Key", RefTo: "Mods"},
		{Name: "Variant", Type: "Int"},
	},
	"gemtags": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "LocalLevelStat", Type: "Key", RefTo: "Stats"},
		{Name: "LocalQualityStat", Type: "Key", RefTo: "Stats"},
		{Name: "GlobalSpellLevelStat", Type: "Key", RefTo: "Stats"},
		{Name: "GlobalSkillLevelStat", Type: "Key", RefTo: "Stats"},
	},
	"genericbuffauras": {
		{Name: "Id", Type: "String"},
	},
	"grantedeffectqualitystats": {
		{Name: "GrantedEffect", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "GrantedStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "StatValues", Type: "Int", List: true},
		{Name: "AddTypes", Type: "Enum", List: true, RefTo: "ActiveSkillType"},
		{Name: "AddMinionTypes", Type: "Enum", List: true, RefTo: "ActiveSkillType"},
	},
	"grantedeffects": {
		{Name: "Id", Type: "String"},
		{Name: "IsSupport", Type: "Bool"},
		{Name: "SupportTypes", Type: "Key", List: true, RefTo: "ActiveSkillType"},
		{Name: "SupportGemLetter", Type: "String"},
		{Name: "Attribute", Type: "Int"},
		{Name: "AddTypes", Type: "Key", List: true, RefTo: "ActiveSkillType"},
		{Name: "ExcludeTypes", Type: "Key", List: true, RefTo: "ActiveSkillType"},
		{Name: "SupportGemsOnly", Type: "Bool"},
		{Name: "Hash32", Type: "UInt"},
		{Type: "Enum", List: true},
		{Name: "CannotBeSupported", Type: "Bool"},
		{Name: "LifeLeech?", Type: "Int"},
		{Name: "CastTime", Type: "Int"},
		{Name: "ActiveSkill", Type: "Key", RefTo: "ActiveSkills"},
		{Name: "IgnoreMinionTypes", Type: "Bool"},
		{Name: "CooldownNotRecoverDuringActive", Type: "Bool"},
		{Name: "AddMinionTypes", Type: "Key", List: true, RefTo: "ActiveSkillType"},
		{Name: "Animation", Type: "Key", RefTo: "Animation"},
		{Name: "MultiPartAchievement", Type: "Key", RefTo: "MultiPartAchievements"},
		{Type: "Bool"},
		{Name: "WeaponRestrictions", Type: "Key", List: true, RefTo: "ItemClasses"},
		{Name: "PlusVersionOf", Type: "ShortKey", RefTo: "GrantedEffects"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
		{Name: "GrantedEffectStatSets", Type: "Key", RefTo: "GrantedEffectStatSets"},
		{Name: "GrantedEffectStatSets2", Type: "Key", List: true, RefTo: "GrantedEffectStatSets"},
	},
	"grantedeffectsperlevel": {
		{Name: "GrantedEffect", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "Level", Type: "Int", RefTo: "nil"},
		{Name: "PlayerLevelReq", Type: "Float"},
		{Name: "CostMultiplier", Type: "Int"},
		{Name: "StoredUses", Type: "Int"},
		{Name: "Cooldown", Type: "Int"},
		{Name: "CooldownBypassType", Type: "Int", RefTo: "CooldownBypassTypes"},
		{Name: "VaalSouls", Type: "Int", RefTo: "Stats"},
		{Name: "VaalStoredUses", Type: "Int"},
		{Name: "CooldownGroup", Type: "Int"},
		{Name: "PvPDamageMultiplier", Type: "Int"},
		{Name: "SoulGainPreventionDuration", Type: "Int"},
		{Name: "AttackSpeedMultiplier", Type: "Int"},
		{Type: "Int"},
		{Name: "CostAmounts", Type: "Int", List: true},
		{Name: "CostTypes", Type: "Key", List: true, RefTo: "CostTypes"},
		{Name: "ManaReservationFlat", Type: "Int"},
		{Name: "ManaReservationPercent", Type: "Int"},
		{Name: "LifeReservationFlat", Type: "Int"},
		{Name: "LifeReservationPercent", Type: "Int"},
		{Name: "AttackTime", Type: "Int"},
	},
	"grantedeffectstatsets": {
		{Name: "Id", Type: "String"},
		{Name: "ImplicitStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "ConstantStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "ConstantStatsValues", Type: "Int", List: true},
		{Name: "BaseEffectiveness", Type: "Float"},
		{Type: "Int"},
		{Name: "IncrementalEffectiveness", Type: "Float"},
	},
	"grantedeffectstatsetsperlevel": {
		{Name: "GrantedEffectStatSets", Type: "Key", RefTo: "GrantedEffectStatSets"},
		{Name: "GemLevel", Type: "Int"},
		{Name: "PlayerLevelReq", Type: "Float"},
		{Name: "AttackCritChance", Type: "Int"},
		{Name: "OffhandCritChance", Type: "Int"},
		{Name: "BaseMultiplier", Type: "Int"},
		{Name: "DamageEffectiveness", Type: "Int"},
		{Name: "BaseResolvedValues", Type: "Int", List: true, RefTo: "Stats"},
		{Name: "AdditionalStatsValues", Type: "Int", List: true, RefTo: "Stats"},
		{Name: "GrantedEffect", Type: "Key", List: true, RefTo: "GrantedEffects"},
		{Name: "AdditionalBooleanStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "FloatStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "InterpolationBases", Type: "Key", List: true, RefTo: "EffectivenessCostConstants"},
		{Name: "AdditionalStats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "StatInterpolations", Type: "Int", List: true},
		{Name: "FloatStatsValues", Type: "Float", List: true},
	},
	"hideoutnpcs": {
		{Name: "NPC", Type: "Key", RefTo: "NPCs"},
	},
	"indexableskillgems": {
		{Name: "Id", Type: "Int"},
		{Name: "BaseItemType", Type: "Key", List: true, RefTo: "SkillGems"},
		{Name: "Skill", Type: "String"},
		{Name: "BaseItemTypeRuthless", Type: "Key", List: true, RefTo: "SkillGems"},
		{Name: "SkillRuthless", Type: "String"},
		{Name: "IdRuthless", Type: "Key", RefTo: "indexableskillgems"},
	},
	"indexablesupportgems": {
		{Name: "Id", Type: "Int"},
		{Name: "BaseItemType", Type: "Key", RefTo: "SkillGems"},
		{Name: "Skill", Type: "String"},
	},
	"influencetags": {
		{Name: "ItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "InfluenceType", Type: "Enum", RefTo: "influencetypes"},
		{Name: "tags", Type: "Key", RefTo: "Tags"},
	},
	"influencetypes": {
		{Name: "Id", Type: "String"},
	},
	"itemclasscategories": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Type: "Key"},
	},
	"itemclasses": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "ItemClassCategory", Type: "Key", RefTo: "ItemClassCategories"},
		{Name: "RemovedIfLeavesArea", Type: "Bool"},
		{Type: "Key", List: true},
		{Name: "Achievements", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "AllocateToMapOwner", Type: "Bool"},
		{Name: "AlwaysAllocate", Type: "Bool"},
		{Name: "CanHaveVeiledMods", Type: "Bool"},
		{Name: "PickedUpQuest", Type: "Key", RefTo: "QuestFlags"},
		{Type: "Int"},
		{Name: "AlwaysShow", Type: "Bool"},
		{Name: "CanBeCorrupted", Type: "Bool"},
		{Name: "CanHaveIncubators", Type: "Bool"},
		{Name: "CanHaveInfluence", Type: "Bool"},
		{Name: "CanBeDoubleCorrupted", Type: "Bool"},
		{Name: "CanHaveAspects", Type: "Bool"},
		{Name: "CanTransferSkin", Type: "Bool"},
		{Name: "ItemStance", Type: "Key", RefTo: "ItemStances"},
		{Name: "CanScourge", Type: "Bool"},
		{Name: "CanUpgradeRarity", Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "Flags", Type: "Int", List: true},
		{Name: "Unmodifiable", Type: "Bool"},
		{Name: "CanBeFractured", Type: "Bool"},
		{Name: "EquipAchievements", Type: "Key", RefTo: "AchievementItems"},
		{Name: "UsedInMapDevice", Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"itemexperienceperlevel": {
		{Name: "ItemExperienceType", Type: "Key", RefTo: "ItemExperienceTypes"},
		{Name: "Level", Type: "Int"},
		{Name: "Experience", Type: "Int"},
	},
	"itemexperiencetypes": {
		{Name: "Id", Type: "String"},
	},
	"itemisedcorpse": {
		{Name: "BaseItem", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Monster", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "MonsterAbilities", Type: "String"},
		{Name: "MonsterCategory", Type: "Key", RefTo: "CorpseTypeTags"},
	},
	"itemstances": {
		{Name: "Id", Type: "String"},
	},
	"itemsynthesiscorruptedmods": {
		{Name: "ItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "ImplicitMods", Type: "Key", List: true, RefTo: "Mods"},
	},
	"itemsynthesismods": {
		{Name: "Id", Type: "String"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Type: "Int"},
		{Name: "ItemClasses", Type: "Key", List: true, RefTo: "ItemClasses"},
		{Name: "ImplicitMod", Type: "Key", List: true, RefTo: "Mods"},
	},
	"itemvisualidentity": {
		{Name: "Id", Type: "String"},
		{Name: "DDSFile", Type: "String"},
		{Name: "AOFile", Type: "String"},
		{Name: "InventorySound", Type: "Key", RefTo: "SoundEffects"},
		{Name: "Hash", Type: "UInt16"},
		{Name: "AOFile2", Type: "String"},
		{Name: "MarauderSMFiles", Type: "String", List: true},
		{Name: "RangerSMFiles", Type: "String", List: true},
		{Name: "WitchSMFiles", Type: "String", List: true},
		{Name: "DuelistDexSMFiles", Type: "String", List: true},
		{Name: "TemplarSMFiles", Type: "String", List: true},
		{Name: "ShadowSMFiles", Type: "String", List: true},
		{Name: "ScionSMFiles", Type: "String", List: true},
		{Name: "MarauderShape", Type: "String"},
		{Name: "RangerShape", Type: "String"},
		{Name: "WitchShape", Type: "String"},
		{Name: "DuelistShape", Type: "String"},
		{Name: "TemplarShape", Type: "String"},
		{Name: "ShadowShape", Type: "String"},
		{Name: "ScionShape", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Pickup_AchievementItemsKeys", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "SMFiles", Type: "String", List: true},
		{Name: "Identify_AchievementItemsKeys", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "EPKFile", Type: "String"},
		{Name: "Corrupt_AchievementItemsKeys", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "IsAlternateArt", Type: "Bool"},
		{Type: "Bool"},
		{Name: "CreateCorruptedJewelAchievementItemsKey", Type: "Key", RefTo: "AchievementItems"},
		{Name: "AnimationLocation", Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Name: "IsAtlasOfWorldsMapIcon", Type: "Bool"},
		{Name: "IsTier16Icon", Type: "Bool"},
		{Name: "KalandaAchievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Type: "Bool"},
		{Name: "HeistAchievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Type: "String"},
		{Type: "Int"},
		{Type: "Key", RefTo: "Stats"},
		{Type: "Key", RefTo: "Stats"},
		{Type: "Key", RefTo: "Stats"},
		{Type: "Key", RefTo: "Stats"},
		{Type: "Key", List: true},
		{Type: "Key", List: true},
		{Type: "Bool"},
		{Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "Key", List: true},
	},
	"leaguenames": {
		{Type: "String"},
		{Name: "Name", Type: "String"},
		{Type: "String"},
	},
	"mavenjewelradiuskeystones": {
		{Name: "Keystone_Key", Type: "Key", RefTo: "PassiveSkills"},
	},
	"melee": {
		{Name: "ActiveSkill", Type: "Key", RefTo: "ActiveSkills"},
		{Type: "Int"},
		{Name: "MiscAnimated", Type: "Key", RefTo: "MiscAnimated"},
		{Name: "MeleeTrails1", Type: "Key", RefTo: "MeleeTrails"},
		{Name: "MeleeTrails2", Type: "Key", RefTo: "MeleeTrails"},
		{Name: "MeleeTrails3", Type: "Key", RefTo: "MeleeTrails"},
		{Name: "MeleeTrails4", Type: "Key", RefTo: "MeleeTrails"},
		{Name: "MeleeTrails5", Type: "Key", RefTo: "MeleeTrails"},
		{Name: "MeleeTrails6", Type: "Key", RefTo: "MeleeTrails"},
		{Name: "MeleeTrails7", Type: "Key", RefTo: "MeleeTrails"},
		{Type: "Bool"},
		{Name: "SurgeEPK", Type: "String"},
		{Type: "String"},
		{Type: "String"},
	},
	"mercenaryattributes": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "Tag", Type: "Key", List: true, RefTo: "Tags"},
	},
	"mercenarybuilds": {
		{Name: "Id", Type: "String"},
		{Name: "Class", Type: "Key", RefTo: "MercenaryClasses"},
		{Name: "Skill1", Type: "Key", List: true, RefTo: "MercenarySkills"},
		{Name: "Skill1CountMax", Type: "Int"},
		{Name: "Skill2", Type: "Key", List: true, RefTo: "MercenarySkills"},
		{Type: "Int"},
		{Type: "Key", List: true},
		{Name: "Skill2CountMax", Type: "Int"},
		{Name: "Skill3", Type: "Key", List: true, RefTo: "MercenarySkills"},
		{Type: "Key", List: true},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "AIFile", Type: "String"},
		{Name: "HASH16", Type: "UInt16"},
		{Name: "BuildName", Type: "String"},
		{Type: "Int"},
		{Name: "Infamous", Type: "Bool"},
		{Type: "Key"},
		{Type: "String"},
		{Type: "String", List: true},
		{Name: "Achievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "WeaponTypes", Type: "Key", List: true, RefTo: "MercenaryWieldableTypes"},
	},
	"mercenaryclasses": {
		{Name: "Id", Type: "String"},
		{Name: "MonsterVariety", Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Int"},
		{Name: "Terrain", Type: "Key", RefTo: "ExtraTerrainFeatures"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Icon", Type: "String"},
		{Name: "HouseIcon", Type: "String"},
		{Name: "Attribute", Type: "Key", RefTo: "MercenaryAttributes"},
		{Name: "BuffIcon", Type: "String"},
		{Name: "MonsterVarietyAllied", Type: "Key", RefTo: "MonsterVarieties"},
	},
	"mercenaryinventories": {
		{Name: "Inventory", Type: "Key", RefTo: "Inventories"},
		{Name: "Id", Type: "Int"},
		{Name: "XOffset", Type: "Int"},
		{Name: "YOffset", Type: "Int"},
		{Name: "InventoryType", Type: "Int"},
	},
	"mercenaryskillfamilies": {
		{Name: "Id", Type: "String"},
	},
	"mercenaryskills": {
		{Name: "Id", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "SupportCount", Type: "Key", RefTo: "MercenarySupportCounts"},
		{Name: "PossibleSupports", Type: "Key", List: true, RefTo: "MercenarySupports"},
		{Name: "SecondaryGrantedEffect", Type: "Key", RefTo: "GrantedEffects"},
		{Name: "Name", Type: "String"},
		{Name: "Description", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "SkillFamily", Type: "Key", RefTo: "MercenarySkillFamilies"},
		{Name: "HASH16", Type: "UInt16"},
		{Name: "HouseSkillIcon", Type: "String"},
	},
	"mercenarysupportcounts": {
		{Name: "Id", Type: "String"},
	},
	"mercenarysupportfamilies": {
		{Name: "Id", Type: "String"},
	},
	"mercenarysupports": {
		{Name: "Id", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Stat", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "StatValues", Type: "Int", List: true},
		{Name: "Name", Type: "String"},
		{Name: "SupportFamily", Type: "Key", RefTo: "MercenarySupportFamilies"},
		{Name: "HASH16", Type: "UInt16"},
		{Name: "GemIcon", Type: "String"},
		{Name: "Variant", Type: "Int"},
		{Type: "Key", List: true},
		{Type: "Key", List: true},
	},
	"mercenarywieldabletypes": {
		{Name: "ItemClasses", Type: "Key", RefTo: "ItemClasses"},
	},
	"miniondoublingstattypes": {
		{Name: "Id", Type: "Int"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Name: "MinionType", Type: "Key", RefTo: "MinionType"},
	},
	"miniontype": {
		{Name: "Id", Type: "String"},
		{Name: "LimitStat", Type: "Key", RefTo: "stats"},
		{Name: "ActiveCountStat", Type: "Key", RefTo: "stats"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"miscanimated": {
		{Name: "Id", Type: "String"},
		{Name: "AOFile", Type: "String"},
		{Name: "PreloadGroup", Type: "Key", List: true, RefTo: "PreloadGroups"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "HASH32", Type: "UInt"},
	},
	"miscanimatedartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "MiscAnimated", Type: "Key", List: true, RefTo: "MiscAnimated"},
		{Type: "Int"},
		{Name: "Variant", Type: "Int"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
	},
	"miscbeams": {
		{Name: "Id", Type: "String"},
		{Name: "MiscAnimated", Type: "Key", RefTo: "MiscAnimated"},
		{Type: "Float"},
		{Name: "PreloadGroup", Type: "Key", List: true, RefTo: "PreloadGroups"},
		{Type: "Int"},
	},
	"miscbeamsartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "MiscBeams", Type: "Key", List: true, RefTo: "MiscBeams"},
		{Type: "Int"},
		{Name: "Variant", Type: "Int"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
	},
	"misceffectpacksartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "MiscEffectPack", Type: "Key", List: true, RefTo: "MiscEffectPacks"},
		{Name: "Variant", Type: "Int"},
	},
	"miscobjectartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "MiscObject", Type: "Key", List: true, RefTo: "MiscObjects"},
		{Name: "Variant", Type: "Int"},
	},
	"modeffectstats": {
		{Name: "Stats", Type: "Key", RefTo: "Stats"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "ApplyToExplicit", Type: "Bool"},
		{Type: "Int"},
		{Name: "ApplyToImplicit", Type: "Bool"},
		{Name: "ApplyToPrefix", Type: "Bool"},
		{Name: "ApplyToSuffix", Type: "Bool"},
		{Name: "Multiplier", Type: "Int"},
	},
	"modequivalencies": {
		{Name: "Id", Type: "String"},
		{Name: "ModsKey0", Type: "Key", RefTo: "Mods"},
		{Name: "ModsKey1", Type: "Key", RefTo: "Mods"},
		{Name: "ModsKey2", Type: "Key", RefTo: "Mods"},
		{Type: "Bool"},
	},
	"modfamily": {
		{Name: "Id", Type: "String"},
	},
	"mods": {
		{Name: "Id", Type: "String"},
		{Name: "Hash", Type: "UInt16"},
		{Name: "Type", Type: "Key", RefTo: "ModType"},
		{Name: "Level", Type: "Int"},
		{Name: "Stat1", Type: "Key", RefTo: "Stats"},
		{Name: "Stat2", Type: "Key", RefTo: "Stats"},
		{Name: "Stat3", Type: "Key", RefTo: "Stats"},
		{Name: "Stat4", Type: "Key", RefTo: "Stats"},
		{Name: "Domain", Type: "Int", RefTo: "ModDomains"},
		{Name: "Name", Type: "String"},
		{Name: "GenerationType", Type: "Int", RefTo: "ModGenerationType"},
		{Name: "Family", Type: "Key", List: true, RefTo: "ModFamily"},
		{Name: "Stat1Value", Type: "Interval"},
		{Name: "Stat2Value", Type: "Interval"},
		{Name: "Stat3Value", Type: "Interval"},
		{Name: "Stat4Value", Type: "Interval"},
		{Name: "SpawnTags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "SpawnWeights", Type: "Int", List: true, RefTo: "Tags"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "GrantedEffect", Type: "Key", List: true, RefTo: "GrantedEffectsPerLevel"},
		{Name: "AuraFlags", Type: "Enum", List: true, RefTo: "ModAuraFlags"},
		{Name: "Daemon", Type: "String"},
		{Name: "MonsterKillAchievements", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "ArchnemesisType", Type: "Key", List: true, RefTo: "ModType"},
		{Name: "Stat5Value", Type: "Interval"},
		{Name: "Stat5", Type: "Key", RefTo: "Stats"},
		{Name: "FullClear", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "AchievementItemsKey", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "GenerationWeightTags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "GenerationWeightValues", Type: "Int", List: true, RefTo: "Tags"},
		{Name: "ModifyMapsAchievements", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "IsEssence", Type: "Bool"},
		{Name: "Stat6Value", Type: "Interval"},
		{Name: "Stat6", Type: "Key", RefTo: "Stats"},
		{Name: "MaxLevel", Type: "Int"},
		{Type: "Bool"},
		{Name: "CraftingClassRestrictions", Type: "Key", List: true, RefTo: "ItemClasses"},
		{Name: "MonsterOnDeath", Type: "String"},
		{Type: "Int"},
		{Name: "HeistAchievements", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "Heist_SubStatValue1", Type: "Int", RefTo: "Heist_SubStatValue1"},
		{Name: "Heist_SubStatValue2", Type: "Int", RefTo: "GrantedEffectsPerLevel"},
		{Name: "Heist_StatsKey0", Type: "Key", RefTo: "Stats"},
		{Name: "Heist_StatsKey1", Type: "Key", RefTo: "Stats"},
		{Name: "Heist_AddStatValue1", Type: "Int"},
		{Name: "Heist_AddStatValue2", Type: "Int"},
		{Name: "InfluenceTypes", Type: "Int"},
		{Name: "ImplicitTags", Type: "Key", List: true, RefTo: "Tags"},
		{Type: "Bool"},
		{Name: "UnknownStat1", Type: "Interval"},
		{Name: "UnknownStat2", Type: "Interval"},
		{Name: "UnknownStat3", Type: "Interval"},
		{Name: "UnknownStat4", Type: "Interval"},
		{Name: "UnknownStat5", Type: "Interval"},
		{Name: "UnknownStat6", Type: "Interval"},
		{Name: "UnknownStat7", Type: "Interval"},
		{Name: "UnknownStat8", Type: "Interval"},
		{Name: "BuffTemplate1", Type: "Key", RefTo: "BuffTemplates"},
		{Name: "ArchnemesisMinionMod", Type: "ShortKey", RefTo: "Mods"},
		{Name: "HASH32", Type: "UInt"},
		{Name: "BuffTemplate2", Type: "Key", List: true, RefTo: "BuffTemplates"},
		{Name: "GameMode", Type: "Int"},
		{Name: "RuthlessReplacement", Type: "Key", List: true, RefTo: "GrantedEffectsPerLevel"},
		{Type: "Bool"},
	},
	"modsellpricetypes": {
		{Name: "Id", Type: "String"},
	},
	"modtype": {
		{Name: "Id", Type: "String"},
		{Name: "Stat", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "ModSellPriceTypesKeys", Type: "Key", List: true, RefTo: "ModSellPriceTypes"},
		{Type: "Bool"},
	},
	"monsterbonuses": {
		{Type: "String"},
	},
	"monsterconditions": {
		{Name: "Id", Type: "String"},
		{Name: "Rarity", Type: "Key", RefTo: "Rarity"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Name: "NotRarity", Type: "Key", RefTo: "Rarity"},
		{Name: "NotStat", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "MapBoss", Type: "Bool"},
		{Name: "NotMapBoss", Type: "Bool"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "NotTags", Type: "Key", List: true, RefTo: "Tags"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "HASH32", Type: "UInt"},
	},
	"monstermapbossdifficulty": {
		{Name: "AreaLevel", Type: "Int"},
		{Name: "BossLifePercentIncrease", Type: "Int"},
		{Name: "BossDamagePercentIncrease", Type: "Int"},
		{Name: "Stat1", Type: "Key", RefTo: "Stats"},
		{Name: "Stat2", Type: "Key", RefTo: "Stats"},
		{Name: "Stat3", Type: "Key", RefTo: "Stats"},
		{Name: "BossIncItemQuantity", Type: "Int"},
		{Name: "Stat4", Type: "Key", RefTo: "Stats"},
		{Name: "BossIncItemRarity", Type: "Int"},
		{Name: "Stat5", Type: "Key", RefTo: "Stats"},
		{Name: "BossAilmentPercentDecrease", Type: "Int"},
	},
	"monstermapdifficulty": {
		{Name: "AreaLevel", Type: "Int"},
		{Name: "LifePercentIncrease", Type: "Int"},
		{Name: "DamagePercentIncrease", Type: "Int"},
		{Name: "Stat1", Type: "Key", RefTo: "Stats"},
		{Name: "Stat2", Type: "Key", RefTo: "Stats"},
		{Name: "Stat3", Type: "Key", RefTo: "Stats"},
		{Name: "Stat3Value", Type: "Int"},
		{Name: "Stat4", Type: "Key", RefTo: "Stats"},
		{Name: "Stat4Value", Type: "Int"},
	},
	"monsterresistances": {
		{Name: "Id", Type: "String"},
		{Name: "FireNormal", Type: "Int"},
		{Name: "ColdNormal", Type: "Int"},
		{Name: "LightningNormal", Type: "Int"},
		{Name: "ChaosNormal", Type: "Int"},
		{Name: "FireCruel", Type: "Int"},
		{Name: "ColdCruel", Type: "Int"},
		{Name: "LightningCruel", Type: "Int"},
		{Name: "ChaosCruel", Type: "Int"},
		{Name: "FireMerciless", Type: "Int"},
		{Name: "ColdMerciless", Type: "Int"},
		{Name: "LightningMerciless", Type: "Int"},
		{Name: "ChaosMerciless", Type: "Int"},
	},
	"monstertypes": {
		{Name: "Id", Type: "String"},
		{Name: "Accuracy", Type: "Int"},
		{Name: "IsPlayerMinion", Type: "Bool"},
		{Name: "Armour", Type: "Int"},
		{Name: "Evasion", Type: "Int"},
		{Name: "EnergyShield", Type: "Int"},
		{Name: "DamageSpread", Type: "Int"},
		{Name: "Resistances", Type: "Key", RefTo: "MonsterResistances"},
		{Name: "AltLife1", Type: "Bool"},
		{Name: "AltLife2", Type: "Bool"},
		{Name: "BaseDamageIgnoresAttackSpeed", Type: "Bool"},
	},
	"monstervarieties": {
		{Name: "Id", Type: "String"},
		{Name: "Type", Type: "Key", RefTo: "MonsterTypes"},
		{Name: "MovementSpeed", Type: "Int"},
		{Name: "ObjectSize", Type: "Enum"},
		{Name: "MinimumAttackRange", Type: "Int"},
		{Name: "MaximumAttackRange", Type: "Int"},
		{Name: "Actor", Type: "String", List: true},
		{Name: "AnimatedObject", Type: "String", List: true},
		{Name: "ObjectType", Type: "String"},
		{Name: "Mods", Type: "Key", List: true, RefTo: "Mods"},
		{Type: "Int"},
		{Type: "String"},
		{Type: "String"},
		{Name: "ModelSizeMultiplier", Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "ExperienceMultiplier", Type: "Int"},
		{Type: "Int", List: true},
		{Name: "MinAgroRange", Type: "Int"},
		{Name: "MaxAgroRange", Type: "Int"},
		{Name: "SpotlightColour1", Type: "Int"},
		{Name: "SpotlightColour2", Type: "Int"},
		{Name: "SpotlightColour3", Type: "Int"},
		{Name: "GrantedEffects", Type: "Key", List: true, RefTo: "GrantedEffects"},
		{Name: "AIScript", Type: "String"},
		{Name: "ModsKeys2", Type: "Key", List: true, RefTo: "Mods"},
		{Name: "Stance", Type: "String"},
		{Type: "Key"},
		{Name: "Name", Type: "String"},
		{Name: "DamageMultiplier", Type: "Int"},
		{Name: "LifeMultiplier", Type: "Int"},
		{Name: "AttackDuration", Type: "Int"},
		{Name: "MainHandItem", Type: "Key", List: true, RefTo: "ItemVisualIdentity"},
		{Name: "OffHandItem", Type: "Key", List: true, RefTo: "ItemVisualIdentity"},
		{Name: "BackItem", Type: "Key", RefTo: "ItemVisualIdentity"},
		{Name: "MainHandItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "OffHandItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "HelmetItem", Type: "Key", RefTo: "ItemVisualIdentity"},
		{Type: "Int"},
		{Name: "KillSpecificMonsterCount", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "SpecialMods", Type: "Key", List: true, RefTo: "Mods"},
		{Name: "KillRare", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Int", RefTo: "AchievementItems"},
		{Type: "Int", RefTo: "AchievementItems"},
		{Type: "Int", RefTo: "AchievementItems"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Hash", Type: "UInt16"},
		{Type: "Bool"},
		{Type: "String"},
		{Name: "AchievementFlashback", Type: "Key", RefTo: "AchievementItems"},
		{Name: "MonsterSegments", Type: "Key", RefTo: "MonsterSegments"},
		{Name: "MonsterArmours", Type: "Key", RefTo: "MonsterArmours"},
		{Name: "AchievementTalisman", Type: "Key", RefTo: "AchievementItems"},
		{Name: "ModsPart1", Type: "Key", List: true, RefTo: "Mods"},
		{Name: "ModsPart2", Type: "Key", List: true, RefTo: "Mods"},
		{Name: "ModsEndgame", Type: "Key", List: true, RefTo: "Mods"},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "MultiPartAchievements", Type: "Key", List: true, RefTo: "MultiPartAchievements"},
		{Type: "Int"},
		{Name: "SinkAnimation", Type: "String"},
		{Type: "Bool"},
		{Type: "Key", List: true, RefTo: "MultiPartAchievements"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Float"},
		{Name: "AilmentThreshold", Type: "Int"},
		{Name: "SinkEffect", Type: "String"},
		{Type: "Int"},
		{Name: "MonsterConditionalEffectPack", Type: "Key", RefTo: "MonsterConditionalEffectPacks"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "AddonMonsterTypeIndex", Type: "String", List: true},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
		{Name: "BossHealthBar", Type: "Bool"},
		{Type: "Bool"},
	},
	"monstervarietiesartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "Variant", Type: "Int"},
		{Name: "MonsterVariety", Type: "Key", List: true, RefTo: "MonsterVarieties"},
	},
	"multipartachievements": {
		{Name: "Id", Type: "String"},
		{Type: "Int"},
		{Name: "Achievement", Type: "Key", RefTo: "AchievementItems"},
		{Name: "Threshold", Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
	},
	"nearbymonsterconditions": {
		{Type: "String"},
	},
	"npcs": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "Metadata", Type: "String"},
		{Name: "QuestFlag", Type: "Key", RefTo: "QuestFlags"},
		{Name: "NPCMaster", Type: "Key", RefTo: "NPCMaster"},
		{Name: "ShortName", Type: "String"},
		{Type: "Int"},
		{Name: "NPCAudio1", Type: "Key", List: true, RefTo: "NPCAudio"},
		{Name: "NPCAudio2", Type: "Key", List: true, RefTo: "NPCAudio"},
		{Name: "HASH16", Type: "UInt16"},
		{Type: "ShortKey", RefTo: "NPCS"},
		{Name: "Portrait", Type: "Key", RefTo: "NPCPortraits"},
		{Name: "DialogueStyle", Type: "Key", RefTo: "NPCDialogueStyles"},
		{Type: "Bool"},
		{Type: "Key", RefTo: "NPCShopSets"},
		{Name: "Gender", Type: "String"},
		{Type: "Bool"},
		{Type: "Int"},
	},
	"pantheonpanellayout": {
		{Name: "Id", Type: "String"},
		{Name: "X", Type: "Int"},
		{Name: "Y", Type: "Int"},
		{Name: "IsMajorGod", Type: "Bool"},
		{Name: "CoverImage", Type: "String"},
		{Name: "GodName2", Type: "String"},
		{Name: "SelectionFrame", Type: "String"},
		{Name: "Effect1StatsKey", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "Effect1Values", Type: "Int", List: true},
		{Name: "Effect2StatsKey", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "GodName3", Type: "String"},
		{Name: "Effect3Values", Type: "Int", List: true},
		{Name: "Effect3StatsKey", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "GodName4", Type: "String"},
		{Name: "Effect4StatsKey", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "Effect4Values", Type: "Int", List: true},
		{Name: "GodName1", Type: "String"},
		{Name: "Effect2Values", Type: "Int", List: true},
		{Name: "QuestFlags", Type: "Key", RefTo: "QuestFlags"},
		{Name: "IsDisabled", Type: "Bool"},
		{Name: "AchievementItems", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "LeagueQuestFlag1", Type: "Int"},
		{Name: "LeagueQuestFlag2", Type: "Int"},
		{Name: "LeagueQuestFlag3", Type: "Int"},
		{Name: "DowngradeFlag1", Type: "Key", RefTo: "QuestFlags"},
		{Name: "DowngradeFlag2", Type: "Key", RefTo: "QuestFlags"},
		{Name: "DowngradeFlag3", Type: "Key", RefTo: "QuestFlags"},
	},
	"passivejewelradii": {
		{Name: "Id", Type: "String"},
		{Name: "RingOuter", Type: "Int"},
		{Name: "RingInner", Type: "Int"},
		{Name: "Radius", Type: "Int"},
		{Name: "Name", Type: "Key", RefTo: "ClientStrings"},
	},
	"passivejewelradiiart": {
		{Name: "Id", Type: "String"},
		{Name: "Circle1", Type: "String"},
		{Name: "Circle2", Type: "String"},
		{Name: "Glow", Type: "String"},
	},
	"passivejewelslots": {
		{Name: "Passive", Type: "Key", RefTo: "PassiveSkills"},
		{Name: "ClusterSize", Type: "Key", RefTo: "PassiveTreeExpansionJewelSizes"},
		{Name: "ClusterIndex", Type: "Int"},
		{Name: "Parent", Type: "ShortKey", RefTo: "PassiveJewelSlots"},
		{Name: "Proxy", Type: "Key", RefTo: "PassiveSkills"},
		{Name: "StartIndices", Type: "Int", List: true},
		{Type: "Bool"},
	},
	"passiveoverridelimits": {
		{Name: "Id", Type: "String"},
		{Name: "Description", Type: "String"},
		{Type: "Bool"},
	},
	"passiveskillbuffs": {
		{Name: "Id", Type: "String"},
		{Type: "Float", List: true},
		{Name: "Buff", Type: "Key", RefTo: "BuffDefinitions"},
		{Type: "Int"},
	},
	"passiveskillmasteryeffects": {
		{Name: "Id", Type: "String"},
		{Name: "Hash", Type: "UInt16"},
		{Name: "Stats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: "Int"},
		{Name: "Stat2", Type: "Int"},
		{Name: "Stat3", Type: "Int"},
		{Name: "AchievementItem", Type: "Key", RefTo: "AchievementItems"},
		{Type: "Key"},
	},
	"passiveskillmasterygroups": {
		{Name: "Id", Type: "String"},
		{Name: "MasteryEffects", Type: "Key", List: true, RefTo: "PassiveSkillMasteryEffects"},
		{Name: "IconInactive", Type: "String"},
		{Name: "IconActive", Type: "String"},
		{Name: "Background", Type: "String"},
		{Type: "Bool"},
		{Name: "SoundEffect", Type: "Key", RefTo: "SoundEffects"},
		{Name: "MasteryCount", Type: "Key", RefTo: "Stats"},
	},
	"passiveskilloverrides": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
		{Name: "Icon", Type: "String"},
		{Name: "StatsKeys", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "StatValues", Type: "Int", List: true},
		{Name: "Hash", Type: "Int"},
		{Name: "Background", Type: "String"},
		{Name: "GrantedEffect", Type: "Key", RefTo: "GrantedEffectsPerLevel"},
		{Name: "OverrideType", Type: "Key", RefTo: "passiveskilloverridetypes"},
		{Name: "Limit", Type: "Key", RefTo: "passiveoverridelimits"},
		{Name: "MinimumConnected", Type: "Int"},
		{Name: "MaximumConnected", Type: "Int"},
		{Name: "PassiveSkill", Type: "Key", RefTo: "PassiveSkills"},
		{Name: "BlockingPassive", Type: "Key", List: true, RefTo: "PassiveSkills"},
	},
	"passiveskilloverridetypes": {
		{Name: "Id", Type: "String"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"passiveskills": {
		{Name: "Id", Type: "String"},
		{Name: "Icon", Type: "String"},
		{Name: "Stats", Type: "Key", List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: "Int"},
		{Name: "Stat2", Type: "Int"},
		{Name: "Stat3", Type: "Int"},
		{Name: "Stat4", Type: "Int"},
		{Name: "PassiveSkillNodeId", Type: "UInt16"},
		{Name: "Name", Type: "String"},
		{Name: "ClassStart", Type: "Key", List: true, RefTo: "Characters"},
		{Name: "Keystone", Type: "Bool"},
		{Name: "Notable", Type: "Bool"},
		{Name: "FlavourText", Type: "String"},
		{Name: "Mastery", Type: "Bool"},
		{Name: "Achievement", Type: "Key", RefTo: "AchievementItems"},
		{Name: "JewelSocket", Type: "Bool"},
		{Name: "Ascendancy", Type: "Key", RefTo: "Ascendancy"},
		{Name: "AscendancyStart", Type: "Bool"},
		{Name: "ReminderTexts", Type: "Key", List: true, RefTo: "ReminderText"},
		{Name: "PassivePointsGranted", Type: "Int"},
		{Name: "MultipleChoice", Type: "Bool"},
		{Name: "MultipleChoiceOption", Type: "Bool"},
		{Name: "Stat5", Type: "Int"},
		{Name: "Buffs", Type: "Key", List: true, RefTo: "BuffTemplates"},
		{Name: "GrantedEffect", Type: "Key", RefTo: "GrantedEffectsPerLevel"},
		{Name: "AnnointOnly", Type: "Bool"},
		{Type: "Int"},
		{Name: "ClusterNode", Type: "Bool"},
		{Name: "Proxy", Type: "Bool"},
		{Name: "Type", Type: "Enum", RefTo: "PassiveSkillTypes"},
		{Name: "MasteryGroup", Type: "Key", RefTo: "PassiveSkillMasteryGroups"},
		{Name: "AtlasMastery_rid", Type: "Key", RefTo: "AtlasPassiveSkillTreeGroupType"},
		{Name: "SoundEffect", Type: "Key", RefTo: "SoundEffects"},
		{Name: "AtlasnodeGroup", Type: "String"},
		{Type: "Bool"},
		{Name: "StatValue1", Type: "Int"},
		{Name: "StatValue2", Type: "Int"},
		{Name: "StatValue3", Type: "Int"},
		{Name: "StatValue4", Type: "Int"},
		{Name: "StatValue5", Type: "Int"},
		{Name: "Stat", Type: "Key", List: true, RefTo: "Stats"},
		{Type: "Int"},
		{Name: "BuffTemplate", Type: "Key", List: true, RefTo: "BuffTemplates"},
		{Type: "Bool"},
		{Type: "Key"},
		{Name: "GrantedEffect", Type: "Key", RefTo: "GrantedEffectsPerLevel"},
		{Type: "Key"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
	},
	"passiveskillstatcategories": {
		{Name: "Id", Type: "String"},
		{Name: "Name", Type: "String"},
	},
	"passiveskilltattoos": {
		{Name: "BaseItem", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Override", Type: "Key", RefTo: "passiveskilloverrides"},
		{Name: "NodeTarget", Type: "Key", RefTo: "passiveskilltattootargetsets"},
		{Type: "Int"},
		{Type: "Key"},
	},
	"passiveskilltattootargetsets": {
		{Name: "Id", Type: "String"},
		{Type: "Int", List: true},
		{Name: "Type", Type: "String"},
		{Name: "Value", Type: "String"},
	},
	"passiveskilltreeconnectionart": {
		{Name: "Id", Type: "String"},
		{Name: "Normal", Type: "String"},
		{Name: "Intermediate2", Type: "String"},
		{Name: "Intermediate", Type: "String"},
		{Name: "Active", Type: "String"},
		{Name: "Mask", Type: "String"},
		{Name: "Ornament1", Type: "String"},
		{Name: "Ornament2", Type: "String"},
	},
	"passiveskilltreenodeframeart": {
		{Name: "Id", Type: "String"},
		{Name: "Normal", Type: "String"},
		{Name: "CanAllocate", Type: "String"},
		{Name: "Active", Type: "String"},
		{Name: "Mask", Type: "String"},
		{Name: "Header", Type: "String"},
	},
	"passiveskilltypes": {
		{Name: "Id", Type: "String"},
	},
	"passivetreeexpansionjewels": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Size", Type: "Key", RefTo: "PassiveTreeExpansionJewelSizes"},
		{Name: "MinNodes", Type: "Int"},
		{Name: "MaxNodes", Type: "Int"},
		{Name: "SmallIndicies", Type: "Int", List: true},
		{Name: "NotableIndicies", Type: "Int", List: true},
		{Name: "SocketIndicies", Type: "Int", List: true},
		{Name: "TotalIndicies", Type: "Int"},
	},
	"passivetreeexpansionjewelsizes": {
		{Name: "Id", Type: "String"},
	},
	"passivetreeexpansionskills": {
		{Name: "Node", Type: "Key", RefTo: "PassiveSkills"},
		{Name: "Mastery", Type: "Key", RefTo: "PassiveSkills"},
		{Name: "Tag", Type: "Key", RefTo: "Tags"},
		{Name: "JewelSize", Type: "Key", RefTo: "PassiveTreeExpansionJewelSizes"},
	},
	"passivetreeexpansionspecialskills": {
		{Name: "Node", Type: "Key", RefTo: "PassiveSkills"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
	},
	"preloadgroups": {
		{Name: "Id", Type: "String"},
	},
	"projectiles": {
		{Name: "Id", Type: "String"},
		{Name: "AOFiles", Type: "String", List: true},
		{Name: "LoopAnimationIds", Type: "String", List: true},
		{Name: "ImpactAnimationIds", Type: "String", List: true},
		{Name: "ProjectileSpeed", Type: "Int"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "InheritsFrom", Type: "String"},
		{Type: "Int"},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "Stuck_AOFile", Type: "String", List: true},
		{Name: "Bounce_AOFile", Type: "String"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "PrimaryAnimation", Type: "Key", RefTo: "MiscAnimated"},
		{Name: "SecondaryAnimation", Type: "Key", RefTo: "MiscAnimated"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "String", List: true},
		{Type: "Bool"},
		{Type: "Int", List: true},
		{Type: "String"},
	},
	"projectilesartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "Variant", Type: "Int"},
		{Name: "Projectile", Type: "Key", List: true, RefTo: "Projectiles"},
		{Type: "Int"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
	},
	"rarity": {
		{Name: "Id", Type: "String"},
		{Name: "MinMods", Type: "Int"},
		{Name: "MaxMods", Type: "Int"},
		{Type: "Int"},
		{Name: "MaxPrefix", Type: "Int"},
		{Type: "Int"},
		{Name: "MaxSuffix", Type: "Int"},
		{Name: "Colour", Type: "String"},
		{Type: "String"},
	},
	"remindertext": {
		{Name: "Id", Type: "String"},
		{Name: "Text", Type: "String"},
		{Name: "Text2", Type: "String"},
	},
	"shieldtypes": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Block", Type: "Int"},
	},
	"shrines": {
		{Name: "Id", Type: "String"},
		{Name: "Timeout", Type: "Int"},
		{Name: "Shared", Type: "Bool"},
		{Name: "PlayerBuff", Type: "Key", RefTo: "BuffTemplates"},
		{Name: "Weighting", Type: "Int"},
		{Name: "MinLevel", Type: "Int"},
		{Name: "MonsterBuff", Type: "Key", RefTo: "BuffTemplates"},
		{Name: "MonsterVarieties", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "MonsterVarietiesPlayer", Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Int"},
		{Name: "Duration", Type: "Int"},
		{Name: "ShrineSounds", Type: "Key", RefTo: "ShrineSounds"},
		{Type: "Bool"},
		{Name: "Achievement", Type: "Key", List: true, RefTo: "AchievementItems"},
		{Name: "PVPOnly", Type: "Bool"},
		{Type: "Bool"},
		{Name: "LesserShrine", Type: "Bool"},
		{Name: "Description", Type: "Key", RefTo: "ClientStrings"},
		{Name: "Name", Type: "Key", RefTo: "ClientStrings"},
		{Name: "Royale", Type: "Bool"},
		{Name: "TouchedMod", Type: "Key", RefTo: "Mods"},
		{Name: "MonsterPack", Type: "Key", List: true, RefTo: "MonsterPacks"},
	},
	"skillartvariations": {
		{Name: "Id", Type: "String"},
		{Name: "AnimatedArt", Type: "Key", List: true, RefTo: "MiscAnimatedArtVariations"},
		{Name: "BeamArt", Type: "Key", List: true, RefTo: "MiscBeamsArtVariations"},
		{Name: "EffectPacksArt", Type: "Key", List: true, RefTo: "MiscEffectPacksArtVariations"},
		{Name: "ObjectArt", Type: "Key", List: true, RefTo: "MiscObjectsArtVariations"},
		{Name: "Variants", Type: "String", List: true},
		{Name: "BuffVisuals", Type: "Key", List: true, RefTo: "BuffVisualsArtVariations"},
		{Name: "VariantID?", Type: "Int", List: true},
		{Name: "ProjectileArt", Type: "Key", List: true, RefTo: "ProjectilesArtVariations"},
		{Name: "Stat", Type: "Key", RefTo: "Stats"},
		{Name: "MonsterVarietiesArt", Type: "Key", List: true, RefTo: "MonsterVarietiesArtVariations"},
		{Name: "ActiveSkill", Type: "Key", List: true, RefTo: "ActiveSkills"},
		{Name: "GrantedEffect", Type: "Key", List: true, RefTo: "GrantedEffects"},
		{Type: "Key", List: true},
	},
	"skillgems": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "Str", Type: "Int"},
		{Name: "Dex", Type: "Int"},
		{Name: "Int", Type: "Int"},
		{Name: "VaalGem", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "IsVaalGem", Type: "Bool"},
		{Name: "MinionGlobalSkillLevelStat", Type: "Key", RefTo: "Stats"},
		{Name: "IsSupport", Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Name: "Awakened", Type: "ShortKey", RefTo: "SkillGems"},
		{Name: "Regular", Type: "ShortKey", RefTo: "SkillGems"},
		{Name: "GemColour", Type: "Int"},
		{Name: "GemLevelProgression", Type: "Key", RefTo: "ItemExperienceTypes"},
		{Name: "MtxSlotType", Type: "Key", List: true, RefTo: "MicrotransactionSkillGemEffectSlotTypes"},
		{Name: "GemVariants", Type: "Key", List: true, RefTo: "GemEffects"},
	},
	"skilltotemvariations": {
		{Name: "SkillTotem", Type: "Int"},
		{Name: "Variation", Type: "Int"},
		{Name: "MonsterVariety", Type: "Key", RefTo: "MonsterVarieties"},
	},
	"soundeffects": {
		{Name: "Id", Type: "String"},
		{Type: "String"},
		{Type: "String"},
		{Type: "Bool"},
		{Type: "String"},
	},
	"spectreoverrides": {
		{Name: "Monster", Type: "Key", RefTo: "MonsterVarieties"},
		{Name: "Spectre", Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Key", List: true},
	},
	"stats": {
		{Name: "Id", Type: "String"},
		{Name: "A", Type: "Bool"},
		{Name: "Local", Type: "Bool"},
		{Name: "WeaponLocal", Type: "Bool"},
		{Name: "Semantic", Type: "Enum", RefTo: "StatSemantics"},
		{Type: "Bool"},
		{Name: "Virtual", Type: "Bool"},
		{Name: "Main Hand Stat", Type: "ShortKey", RefTo: "Stats"},
		{Name: "Off Hand Stat", Type: "ShortKey", RefTo: "Stats"},
		{Type: "Bool"},
		{Name: "Hash", Type: "UInt"},
		{Name: "Skills", Type: "String", List: true},
		{Name: "PassiveCategory", Type: "Key", RefTo: "PassiveSkillStatCategories"},
		{Name: "CannotGrantToMinion", Type: "Bool"},
		{Type: "Bool"},
		{Name: "IsScalable", Type: "Bool"},
		{Name: "ContextFlags", Type: "Key", List: true, RefTo: "VirtualStatContextFlags"},
		{Name: "DotFlag", Type: "Key", List: true, RefTo: "VirtualStatContextFlags"},
	},
	"statsaffectinggeneration": {
		{Type: "Key", RefTo: "Stats"},
		{Type: "Int"},
	},
	"statsfromskillstats": {
		{Type: "Key"},
		{Type: "Key"},
	},
	"suicideexplosion": {
		{Name: "Id", Type: "Int"},
		{Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Key"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Bool"},
	},
	"summonedspecificmonsters": {
		{Name: "Id", Type: "Int"},
		{Name: "MonsterVarietiesKey", Type: "Key", RefTo: "MonsterVarieties"},
		{Type: "Int"},
		{Type: "Key"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Key"},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "String"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
	},
	"tablecharge": {
		{Type: "Int"},
		{Type: "Float"},
		{Type: "Float"},
		{Type: "Bool"},
		{Type: "Key"},
		{Type: "Bool"},
		{Type: "Key", List: true},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Key"},
		{Type: "Key"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Bool"},
		{Type: "Bool"},
		{Type: "Int"},
	},
	"tags": {
		{Name: "Id", Type: "String"},
		{Name: "Hash", Type: "UInt"},
		{Name: "DisplayText", Type: "String"},
		{Name: "Text", Type: "String"},
	},
	"tinctures": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "ManaBurn", Type: "Int"},
		{Name: "CoolDown", Type: "Int"},
	},
	"trademarketimplicitmoddisplay": {
		{Type: "Key"},
		{Type: "String"},
	},
	"trademarketindexitemas": {
		{Name: "Item", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "IndexAs", Type: "Key", RefTo: "BaseItemTypes"},
	},
	"uniquestashlayout": {
		{Name: "WordsKey", Type: "Key", RefTo: "Words"},
		{Name: "ItemVisualIdentity", Type: "Key", RefTo: "ItemVisualIdentity"},
		{Name: "UniqueStashTypes", Type: "Key", RefTo: "UniqueStashTypes"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "OverrideWidth", Type: "Int"},
		{Name: "OverrideHeight", Type: "Int"},
		{Name: "ShowIfEmptyChallengeLeague", Type: "Bool"},
		{Name: "ShowIfEmptyStandard", Type: "Bool"},
		{Name: "RenamedVersion", Type: "ShortKey", RefTo: "UniqueStashLayout"},
		{Name: "BaseVersion", Type: "ShortKey", RefTo: "UniqueStashLayout"},
		{Name: "IsAlternateArt", Type: "Bool"},
	},
	"uniquestashtypes": {
		{Name: "Id", Type: "String"},
		{Name: "Order", Type: "Int"},
		{Name: "Width", Type: "Int"},
		{Name: "Height", Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "Name", Type: "String"},
		{Name: "StandardCount", Type: "Int"},
		{Name: "Image", Type: "String"},
		{Name: "ChallengeLeagueCount", Type: "Int"},
		{Name: "Disabled", Type: "Bool"},
	},
	"villagebalanceperlevelshared": {
		{Name: "Level", Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Name: "GoldRespec", Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
		{Type: "Int"},
	},
	"villageuniquedisenchantvalues": {
		{Name: "Unique", Type: "Key", RefTo: "Words.Text"},
		{Type: "Float"},
	},
	"virtualstatcontextflags": {
		{Name: "Id", Type: "String"},
		{Type: "Int"},
	},
	"weaponclasses": {
		{Name: "ItemClass", Type: "Key", RefTo: "ItemClasses"},
		{Name: "MaxRange", Type: "Int"},
	},
	"weaponpassiveskills": {
		{Name: "Id", Type: "String"},
		{Name: "ModTier", Type: "Int"},
		{Name: "Mod", Type: "Key", RefTo: "Mods"},
		{Name: "NodeSpawnLocation", Type: "Int", List: true},
		{Name: "Tags", Type: "Key", List: true, RefTo: "CrucibleTags"},
		{Name: "ArtFilepath", Type: "String"},
		{Name: "Type", Type: "Key", RefTo: "WeaponPassiveSkillTypes"},
		{Name: "Achievements", Type: "Key", List: true, RefTo: "AchievementItems"},
	},
	"weaponpassiveskilltypes": {
		{Name: "Id", Type: "String"},
		{Type: "Int"},
	},
	"weaponpassivetreebalanceperitemlevel": {
		{Name: "ItemLevel", Type: "Int"},
		{Name: "XPNode1", Type: "Int"},
		{Name: "XPNode2", Type: "Int"},
		{Name: "XPNode3", Type: "Int"},
		{Name: "XPNode4", Type: "Int"},
		{Name: "XPNode5", Type: "Int"},
	},
	"weaponpassivetreeuniquebasetypes": {
		{Name: "UniqueBase", Type: "Key", RefTo: "BaseItemTypes"},
		{Type: "Int"},
	},
	"weapontypes": {
		{Name: "BaseItemType", Type: "Key", RefTo: "BaseItemTypes"},
		{Name: "CritChance", Type: "Int"},
		{Name: "Speed", Type: "Int"},
		{Name: "DamageMin", Type: "Int"},
		{Name: "DamageMax", Type: "Int"},
		{Name: "Range", Type: "Int"},
		{Type: "Int"},
	},
	"words": {
		{Name: "Wordlist", Type: "Int"},
		{Name: "Text", Type: "String"},
		{Name: "SpawnWeight_Tags", Type: "Key", List: true, RefTo: "Tags"},
		{Name: "SpawnWeight_Values", Type: "Int", List: true},
		{Name: "HASH32", Type: "Int"},
		{Name: "Text2", Type: "String"},
		{Name: "Gender", Type: "String"},
	},
	"worldareas": {
		{Type: "String"},
	},
}
