// Column schemas for the game's .dat64 tables. Transformed once from
// .archive/src/Export/spec.lua and Go-maintained since: not generated, not
// regenerated — edit this file on a schema change. Tables with no spec are
// omitted. UI-only column widths are dropped.

package export

// Col describes one column of a .dat64 table.
type Col struct {
	Name  string // column name; "" for unknown/unnamed columns
	Type  ColType
	List  bool   // 16-byte list cell (count + offset into variable data)
	RefTo string // referenced table for Enum/ShortKey/Key columns
}

var datSpecs = map[string][]Col{
	"achievementitems": {
		{Name: "Id", Type: ColString, RefTo: "Achievements"},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Name", Type: ColString},
		{Name: "CompletionsRequired", Type: ColInt},
		{Name: "AchievementsKey", Type: ColKey, RefTo: "Achievements"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
	},
	"actiontypes": {
		{Name: "Name", Type: ColString},
		{Name: "HASH16", Type: ColUInt16},
		{Type: ColBool},
		{Type: ColBool},
	},
	"activeskills": {
		{Name: "Id", Type: ColString},
		{Name: "DisplayName", Type: ColString},
		{Name: "Description", Type: ColString},
		{Name: "ActionType", Type: ColKey, RefTo: "ActionTypes"},
		{Name: "Icon", Type: ColString},
		{Name: "TargetTypes", Type: ColEnum, List: true, RefTo: "ActiveSkillTargetTypes"},
		{Name: "SkillTypes", Type: ColKey, List: true, RefTo: "ActiveSkillType"},
		{Name: "WeaponRestrictions", Type: ColKey, List: true, RefTo: "ItemClasses"},
		{Name: "WebsiteDescription", Type: ColString},
		{Name: "WebsiteImage", Type: ColString},
		{Name: "HideOnWebsite", Type: ColBool},
		{Name: "GrantedEffect", Type: ColString},
		{Type: ColBool},
		{Name: "SkillTotem", Type: ColInt},
		{Name: "ManuallyCast", Type: ColBool},
		{Name: "SkillSpecificStat", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "GenericStat", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "MinionSkillTypes", Type: ColKey, List: true, RefTo: "ActiveSkillType"},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "SecondarySkillSpecificStat", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "SkillMine", Type: ColInt, RefTo: "SkillMines"},
		{Name: "TargetingBehaviours", Type: ColKey, RefTo: "AlternateSkillTargetingBehaviours"},
		{Type: ColBool},
		{Name: "TotemAI", Type: ColString},
		{Name: "StatContextFlags", Type: ColKey, List: true, RefTo: "VirtualStatContextFlags"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "RegularVersion", Type: ColShortKey, RefTo: "ActiveSkills"},
		{Type: ColString},
	},
	"activeskilltype": {
		{Name: "Id", Type: ColString},
		{Name: "FlagStat", Type: ColKey, RefTo: "Stats"},
	},
	"addbufftotargetvarieties": {
		{Name: "BuffDefinitions", Type: ColKey, RefTo: "BuffDefinitions"},
		{Type: ColInt, List: true},
		{Name: "StatsKeys", Type: ColKey, List: true, RefTo: "Stats"},
		{Type: ColInt},
		{Type: ColInt, List: true},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt, List: true},
	},
	"additionallifescaling": {
		{Type: ColInt},
		{Name: "DATFilename", Type: ColString},
		{Name: "DATFilepath", Type: ColString},
	},
	"aegisvariations": {
		{Name: "Id", Type: ColString},
		{Name: "MitigatesPhysicalDmg", Type: ColBool},
		{Name: "MitigatesFireDmg", Type: ColBool},
		{Name: "MitigatesColdDmg", Type: ColBool},
		{Name: "MitigatesLightningDmg", Type: ColBool},
		{Name: "MitigatesChaosDmg", Type: ColBool},
		{Name: "ActiveBuff", Type: ColKey, RefTo: "BuffDefinitions"},
		{Name: "DepletedBuff", Type: ColKey, RefTo: "BuffDefinitions"},
		{Type: ColKey, RefTo: "BuffDefinitions"},
		{Name: "AnimatedEffect", Type: ColKey, RefTo: "MiscAnimated"},
		{Name: "MtxEffect", Type: ColKey, List: true, RefTo: "MiscAnimated"},
	},
	"alternatepassiveadditions": {
		{Name: "Id", Type: ColString},
		{Name: "AlternateTreeVersionsKey", Type: ColKey, RefTo: "AlternateTreeVersions"},
		{Name: "SpawnWeight", Type: ColInt},
		{Name: "StatsKeys", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: ColInterval},
		{Name: "Stat2", Type: ColInterval},
		{Name: "Stat3", Type: ColInterval},
		{Name: "PassiveType", Type: ColInt, List: true},
		{Name: "SpawnWeight2", Type: ColInt},
	},
	"alternatepassiveskills": {
		{Name: "Id", Type: ColString},
		{Name: "AlternateTreeVersionsKey", Type: ColKey, RefTo: "AlternateTreeVersions"},
		{Name: "Name", Type: ColString},
		{Name: "PassiveType", Type: ColInt, List: true},
		{Name: "StatsKeys", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: ColInterval},
		{Name: "Stat2", Type: ColInterval},
		{Name: "Stat3", Type: ColInterval},
		{Name: "Stat4", Type: ColInterval},
		{Name: "Stat5", Type: ColInterval},
		{Name: "Stat6", Type: ColInterval},
		{Name: "SpawnWeight", Type: ColInt},
		{Name: "ConquerorIndex", Type: ColInt},
		{Name: "Random", Type: ColInterval},
		{Name: "FlavourText", Type: ColString},
		{Name: "DDSIcon", Type: ColString},
		{Name: "AchievementItemsKeys", Type: ColKey, List: true},
		{Name: "ConquerorVersion", Type: ColInt},
		{Name: "ConquerorSpawnWeight", Type: ColInt},
	},
	"alternatequalitytypes": {
		{Name: "Id", Type: ColString},
		{Name: "Description", Type: ColString},
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Type: ColKey},
		{Name: "MapStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Type: ColInt},
		{Name: "IsCatalyst", Type: ColBool},
		{Name: "HASH16", Type: ColUInt16},
		{Name: "CatalystMod", Type: ColKey, RefTo: "Mods"},
	},
	"alternateskilltargetingbehaviours": {
		{Name: "Id", Type: ColString},
		{Name: "Value", Type: ColInt},
		{Name: "ClientString", Type: ColKey, RefTo: "ClientStrings"},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt, List: true},
	},
	"alternatetreeart": {
		{Name: "TreeVersion", Type: ColKey, RefTo: "AlternateTreeVersions"},
		{Name: "ConnectionArt", Type: ColKey, RefTo: "PassiveSkillTreeConnectionArt"},
		{Name: "KeystoneFrameArt", Type: ColKey, RefTo: "PassiveSkillTreeNodeFrameArt"},
		{Name: "RadiiArt", Type: ColKey, RefTo: "PassiveJewelRadiiArt"},
		{Name: "NotableFrameArt", Type: ColKey, RefTo: "PassiveSkillTreeNodeFrameArt"},
		{Name: "AscendancyFrameArt", Type: ColKey, RefTo: "PassiveSkillTreeNodeFrameArt"},
	},
	"alternatetreeversions": {
		{Name: "Id", Type: ColString},
		{Name: "SmallAttributeReplaced", Type: ColBool},
		{Name: "SmallNormalPassiveReplaced ", Type: ColBool},
		{Name: "SmallAttributePassiveSkillAdditions", Type: ColInterval},
		{Name: "NotableAdditions", Type: ColInterval},
		{Name: "SmallNormalPassiveSkillAdditions", Type: ColInterval},
		{Name: "NotableReplacementSpawnWeight ", Type: ColInt},
	},
	"animateweaponuniques": {
		{Name: "Name", Type: ColString},
		{Name: "VisualIdentity", Type: ColKey, RefTo: "ItemVisualIdentity"},
		{Name: "ItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "MinLevelReq", Type: ColInt},
	},
	"animation": {
		{Name: "Id", Type: ColString},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "Mainhand", Type: ColShortKey, RefTo: "Animation"},
		{Name: "Offhand", Type: ColShortKey, RefTo: "Animation"},
		{Type: ColBool},
		{Name: "VariationStat", Type: ColKey, RefTo: "Stats"},
		{Name: "AnimationStart", Type: ColShortKey, RefTo: "Animation"},
		{Type: ColBool},
		{Name: "AnimationEnd", Type: ColShortKey, RefTo: "Animation"},
		{Type: ColInt, List: true},
	},
	"archetypes": {
		{Type: ColString},
	},
	"archnemesismetarewards": {
		{Type: ColString},
	},
	"archnemesismodcomboachievements": {
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
	},
	"archnemesismods": {
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
	},
	"archnemesismodvisuals": {
		{Type: ColString},
	},
	"archnemesisrecipes": {
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
	},
	"armourtypes": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "ArmourMin", Type: ColInt},
		{Name: "ArmourMax", Type: ColInt},
		{Name: "EvasionMin", Type: ColInt},
		{Name: "EvasionMax", Type: ColInt},
		{Name: "EnergyShieldMin", Type: ColInt},
		{Name: "EnergyShieldMax", Type: ColInt},
		{Name: "MovementPenalty", Type: ColInt},
		{Name: "WardMin", Type: ColInt},
		{Name: "WardMax", Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
	},
	"ascendancy": {
		{Name: "Id", Type: ColString},
		{Name: "Index", Type: ColInt},
		{Name: "Class", Type: ColKey, RefTo: "Characters"},
		{Name: "FlavourRect", Type: ColString},
		{Name: "FlavourColour", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "Flavour", Type: ColString},
		{Name: "Audio", Type: ColString},
		{Name: "PassiveTreeImage", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "BackgroundImage", Type: ColString},
		{Name: "AlternateName", Type: ColString},
		{Name: "AlternateFlavourText", Type: ColString},
		{Name: "AlternateBackgroundImage", Type: ColString},
		{Name: "AlternatePassiveTreeImage", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "AlternateIcon", Type: ColString},
	},
	"atlasmods": {
		{Name: "Mod", Type: ColKey, RefTo: "Mods"},
		{Name: "Tier", Type: ColInt},
	},
	"azmerifeaturerooms": {
		{Type: ColInt},
		{Type: ColEnum},
		{Type: ColString},
		{Type: ColString},
		{Name: "Achievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Type: ColBool},
	},
	"azmerilifescalingperlevel": {
		{Type: ColInt},
		{Type: ColInt},
	},
	"azmeriwoodsdusttype": {
		{Name: "AzmeriLeader", Type: ColString},
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Name", Type: ColString},
		{Name: "UISymbol", Type: ColString},
		{Type: ColKey},
		{Type: ColKey},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Name: "UiArt", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColKey},
		{Type: ColString},
	},
	"baseitemtypes": {
		{Name: "Id", Type: ColString},
		{Name: "ItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "Width", Type: ColInt},
		{Name: "Height", Type: ColInt},
		{Name: "Name", Type: ColString},
		{Name: "BaseType", Type: ColString},
		{Name: "DropLevel", Type: ColInt},
		{Name: "FlavourTextKey", Type: ColKey, RefTo: "FlavourText"},
		{Name: "ImplicitMods", Type: ColKey, List: true, RefTo: "Mods"},
		{Name: "SizeOnGround", Type: ColInt},
		{Name: "SoundEffect", Type: ColKey, RefTo: "SoundEffects"},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "ModDomain", Type: ColEnum, RefTo: "ModDomains"},
		{Name: "ItemVisualIdentityKey", Type: ColKey, RefTo: "ItemVisualIdentity"},
		{Name: "HASH32", Type: ColUInt},
		{Name: "VendorRecipeAchievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "Inflection", Type: ColString},
		{Name: "EquipAchievement", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "IsCorrupted", Type: ColBool},
		{Name: "IdentifyAchievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "IdentifyMagicAchievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "FragmentBaseItemTypesKey", Type: ColShortKey, RefTo: "BaseItemTypes"},
		{Type: ColBool},
		{Type: ColKey},
		{Type: ColKey},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "Achievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "Achievement2", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "IgnoreQuantBonus", Type: ColBool},
		{Type: ColBool},
		{Name: "ShopTag", Type: ColKey, RefTo: "ShopTag"},
		{Type: ColKey, List: true},
		{Type: ColKey, List: true},
		{Type: ColKey, List: true},
		{Name: "EnchantMods", Type: ColKey, List: true, RefTo: "Mods"},
	},
	"brequelgraftgrantedskilllevels": {
		{Name: "AreaLevel", Type: ColInt},
		{Name: "SkillLevel", Type: ColInt},
		{Name: "LevelReq", Type: ColInt},
	},
	"brequelgraftskillstats": {
		{Name: "GraftStat", Type: ColKey, RefTo: "Stats"},
		{Name: "PlayerStat", Type: ColKey, RefTo: "Stats"},
	},
	"brequelgrafttypes": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "LeftArmAnimatedObject", Type: ColString},
		{Name: "RightArmAnimatedObject", Type: ColString},
		{Name: "SkillGem", Type: ColKey, RefTo: "SkillGems"},
		{Type: ColInt},
		{Name: "AIScript", Type: ColString},
		{Name: "Achievement", Type: ColKey, RefTo: "AchievementItems"},
	},
	"buffdefinitions": {
		{Name: "Id", Type: ColString},
		{Name: "Description", Type: ColString},
		{Name: "Invisible", Type: ColBool},
		{Name: "Removable", Type: ColBool},
		{Name: "Name", Type: ColString},
		{Name: "Stats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "CancelOnDeath", Type: ColBool},
		{Name: "MergeMode", Type: ColEnum, RefTo: "BuffMergeModes"},
		{Name: "ShowCount", Type: ColBool},
		{Name: "MaxStat", Type: ColKey, RefTo: "Stats"},
		{Name: "CurrentStat", Type: ColKey, RefTo: "Stats"},
		{Type: ColBool},
		{Type: ColEnum},
		{Name: "Visual", Type: ColKey, RefTo: "BuffVisuals"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColEnum},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "Limit", Type: ColInt},
		{Type: ColBool},
		{Name: "Implementation", Type: ColString},
		{Name: "isRecovery", Type: ColBool},
		{Type: ColBool},
		{Name: "MinStat", Type: ColKey, RefTo: "Stats"},
		{Type: ColBool},
		{Name: "UIStackMode", Type: ColInt},
		{Type: ColBool},
		{Name: "IsSkillBuff", Type: ColBool},
		{Type: ColInt},
		{Type: ColInt, List: true},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "MultiPartAchievement", Type: ColKey, List: true, RefTo: "MultiPartAchievements"},
		{Type: ColBool},
		{Name: "Stats2", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "GrantedFlags", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "GrantedStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "ConditionStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColKey, RefTo: "Stats"},
		{Type: ColInt, List: true},
		{Type: ColString},
		{Type: ColKey, List: true, RefTo: "Stats"},
		{Type: ColBool},
	},
	"bufftemplates": {
		{Name: "Id", Type: ColString},
		{Name: "BuffDefinition", Type: ColKey, RefTo: "BuffDefinitions"},
		{Name: "StatValues", Type: ColInt, List: true},
		{Name: "AuraRadius", Type: ColInt},
		{Type: ColInt, List: true},
		{Type: ColInt, List: true, RefTo: "Mods"},
		{Name: "Visual", Type: ColKey, RefTo: "BuffVisuals"},
		{Type: ColFloat},
		{Type: ColBool},
		{Name: "Stats", Type: ColKey, List: true, RefTo: "Stats"},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColKey, RefTo: "Stats"},
	},
	"buffvisualartvariations": {
		{Name: "Id", Type: ColString},
	},
	"buffvisualorbart": {
		{Name: "Id", Type: ColString},
		{Name: "MiscAnimated", Type: ColKey, RefTo: "MiscAnimated"},
		{Type: ColInt, List: true},
		{Type: ColString, List: true},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColInt},
		{Name: "MonsterExpiredSound", Type: ColKey, RefTo: "SoundEffects"},
		{Name: "PlayerExpiredSound", Type: ColKey, RefTo: "SoundEffects"},
		{Name: "PlayerAcquiredSound", Type: ColKey, RefTo: "SoundEffects"},
		{Type: ColKey, RefTo: "SoundEffects"},
		{Type: ColBool},
		{Type: ColInt},
	},
	"buffvisualorbs": {
		{Name: "Id", Type: ColString},
		{Name: "OrbType", Type: ColKey, RefTo: "BuffVisualOrbTypes"},
		{Name: "OrbArt", Type: ColKey, List: true, RefTo: "BuffVisualOrbArt"},
		{Name: "OrbArtPlayer", Type: ColKey, List: true, RefTo: "BuffVisualOrbArt"},
		{Name: "OrbArt2", Type: ColKey, List: true, RefTo: "BuffVisualOrbArt"},
	},
	"buffvisualorbtypes": {
		{Name: "Id", Type: ColString},
		{Type: ColFloat},
		{Type: ColFloat},
		{Type: ColFloat},
		{Type: ColFloat},
		{Type: ColInt},
		{Type: ColBool},
		{Name: "RadiusStat", Type: ColKey, RefTo: "Stats"},
		{Name: "HeightStat", Type: ColKey, RefTo: "Stats"},
		{Type: ColInt},
		{Type: ColFloat},
		{Type: ColInt},
		{Type: ColFloat},
		{Type: ColBool},
		{Type: ColFloat},
		{Type: ColInt},
	},
	"buffvisuals": {
		{Name: "Id", Type: ColString},
		{Name: "Icon", Type: ColString},
		{Type: ColString, List: true},
		{Type: ColString, List: true},
		{Name: "PreloadGroup", Type: ColKey, List: true, RefTo: "PreloadGroups"},
		{Type: ColBool},
		{Name: "Name", Type: ColString},
		{Name: "MiscAnimated", Type: ColKey, RefTo: "MiscAnimated"},
		{Type: ColKey, RefTo: "MiscAnimated"},
		{Name: "Description", Type: ColString},
		{Name: "EPKFile", Type: ColString},
		{Type: ColBool},
		{Type: ColString},
		{Type: ColInt, List: true},
		{Name: "EPKFiles", Type: ColString, List: true},
		{Name: "Orbs", Type: ColKey, List: true, RefTo: "BuffVisualOrbs"},
		{Name: "Animation", Type: ColKey, RefTo: "MiscAnimated"},
		{Type: ColKey},
		{Type: ColString},
		{Type: ColFloat},
		{Type: ColFloat},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColString, List: true},
	},
	"buffvisualsartvariations": {
		{Name: "Buff", Type: ColString},
		{Name: "Visuals", Type: ColKey, List: true, RefTo: "BuffVisuals"},
		{Type: ColInt},
	},
	"buffvisualsetentries": {
		{Name: "Id", Type: ColString},
		{Type: ColInt},
		{Name: "Visual", Type: ColKey, RefTo: "BuffVisuals"},
		{Type: ColInt},
	},
	"characters": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "AnimatedObject", Type: ColString},
		{Name: "ActorFile", Type: ColString},
		{Name: "BaseMaxLife", Type: ColInt},
		{Name: "BaseMaxMana", Type: ColInt},
		{Name: "WeaponSpeed", Type: ColInt},
		{Name: "MinDamage", Type: ColInt},
		{Name: "MaxDamage", Type: ColInt},
		{Name: "MaxAttackDistance", Type: ColInt},
		{Name: "Icon", Type: ColString},
		{Name: "IntegerId", Type: ColInt},
		{Name: "BaseStrength", Type: ColInt},
		{Name: "BaseDexterity", Type: ColInt},
		{Name: "BaseIntelligence", Type: ColInt},
		{Type: ColString, List: true, RefTo: "Stats"},
		{Name: "Description", Type: ColString},
		{Name: "StartSkillGem", Type: ColKey, RefTo: "SkillGems"},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "CharacterSize", Type: ColInt},
		{Name: "IntroSoundFile", Type: ColString},
		{Name: "StartWeapons", Type: ColKey, List: true, RefTo: "BaseItemTypes"},
		{Name: "Gender", Type: ColString},
		{Name: "TraitDescription", Type: ColString},
		{Type: ColKey, RefTo: "GrantedEffectStatSets"},
		{Type: ColKey},
		{Type: ColKey},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColKey, List: true},
		{Name: "PassiveTreeImage", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "TencentVideo", Type: ColString},
		{Name: "AttrsAsId", Type: ColString},
		{Name: "LoginScreen", Type: ColString},
		{Name: "PlayerCritter", Type: ColString},
		{Name: "PlayerEffect", Type: ColString},
		{Name: "AfterImage", Type: ColString},
		{Name: "Mirage", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "CloneImmobile", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "ReplicateClone", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "LightningClone", Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColFloat},
		{Type: ColFloat},
		{Name: "SkillTreeBackground", Type: ColString},
		{Name: "Clone", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "Double", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "MirageWarrior", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "DoubleTwo", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "DarkExile", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "Attr", Type: ColString},
		{Name: "AttrLowercase", Type: ColString},
		{Name: "Script", Type: ColString},
		{Type: ColKey},
		{Type: ColInt},
		{Name: "RainOfArrowsClone", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "ElementalShotClone", Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColInt},
		{Type: ColFloat},
		{Type: ColKey},
		{Type: ColKey},
	},
	"clientstrings": {
		{Name: "Id", Type: ColString},
		{Name: "Text", Type: ColString},
		{Name: "XBoxText", Type: ColString},
		{Name: "XBoxText2", Type: ColString},
		{Name: "HASH32", Type: ColUInt},
		{Name: "PlaystationText", Type: ColString},
		{Type: ColString},
	},
	"commands": {
		{Name: "Id", Type: ColString},
		{Name: "Command", Type: ColString},
		{Type: ColBool},
		{Name: "EnglishCommand", Type: ColString},
		{Name: "Description", Type: ColString},
		{Type: ColBool},
	},
	"componentarmour": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Armour", Type: ColInt},
		{Name: "Evasion", Type: ColInt},
		{Name: "EnergyShield", Type: ColInt},
		{Name: "MovementPenalty", Type: ColInt},
	},
	"componentattributerequirements": {
		{Name: "BaseItemType", Type: ColString},
		{Name: "Str", Type: ColInt},
		{Name: "Dex", Type: ColInt},
		{Name: "Int", Type: ColInt},
	},
	"componentcharges": {
		{Name: "BaseItemType", Type: ColString},
		{Name: "Max", Type: ColInt},
		{Name: "PerUse", Type: ColInt},
		{Name: "MaxRuthless", Type: ColInt},
		{Name: "PerUseRuthless", Type: ColInt},
	},
	"corpsetypetags": {
		{Name: "Tag", Type: ColKey, RefTo: "Tags"},
		{Name: "Name", Type: ColString},
		{Name: "Buff", Type: ColKey, RefTo: "BuffDefinitions"},
		{Name: "Icon", Type: ColString},
		{Type: ColInt},
		{Type: ColKey},
		{Type: ColString},
		{Type: ColKey},
	},
	"costtypes": {
		{Name: "Resource", Type: ColString},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Name: "ResourceString", Type: ColString},
		{Name: "Divisor", Type: ColInt},
	},
	"craftingbenchoptions": {
		{Name: "HideoutNPC", Type: ColKey, RefTo: "HideoutNPCs"},
		{Name: "Order", Type: ColInt},
		{Name: "Mod", Type: ColKey, RefTo: "Mods"},
		{Name: "Cost_BaseItemTypes", Type: ColKey, List: true, RefTo: "BaseItemTypes"},
		{Name: "CostValue", Type: ColInt, List: true},
		{Name: "RequiredLevel", Type: ColInt},
		{Name: "Name", Type: ColString},
		{Type: ColInt},
		{Name: "ItemClasses", Type: ColKey, List: true, RefTo: "ItemClasses"},
		{Name: "Links", Type: ColInt},
		{Name: "Colours", Type: ColString},
		{Name: "Sockets", Type: ColInt},
		{Name: "ItemQuantity", Type: ColInt},
		{Type: ColInt, List: true},
		{Name: "Description", Type: ColString},
		{Name: "IsDisabled", Type: ColBool},
		{Name: "IsAreaOption", Type: ColBool},
		{Name: "RecipeIds", Type: ColInt, List: true},
		{Name: "Tier", Type: ColInt},
		{Name: "ItemCategories", Type: ColKey, List: true, RefTo: "CraftingItemClassCategories"},
		{Type: ColInt},
		{Type: ColKey, List: true},
		{Name: "Achievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "AddEnchantment", Type: ColKey, RefTo: "Mods"},
		{Name: "SortCategory", Type: ColKey, RefTo: "CraftingBenchSortCategories"},
		{Name: "ModType", Type: ColKey, RefTo: "ModType"},
		{Type: ColBool},
		{Type: ColInt},
		{Name: "Stat1", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat2", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat3", Type: ColKey, RefTo: "Stats"},
		{Type: ColBool},
		{Name: "PassiveSkills", Type: ColKey, List: true, RefTo: "PassiveSkills"},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Type: ColInt, List: true},
	},
	"craftingbenchsortcategories": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColKey, RefTo: "ClientStrings"},
		{Name: "IsVisible", Type: ColBool},
		{Type: ColKey},
	},
	"craftingbenchspecificoptionid": {
		{Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
	},
	"craftingbenchunlockcategories": {
		{Name: "Id", Type: ColString},
	},
	"craftingitemclasscategories": {
		{Name: "Id", Type: ColString},
		{Name: "ItemClasses", Type: ColKey, List: true, RefTo: "ItemClasses"},
		{Type: ColString},
		{Type: ColString},
		{Type: ColKey, List: true},
	},
	"cruciblelifescalingperlevel": {
		{Name: "Level", Type: ColInt},
		{Name: "LifeMore", Type: ColInt},
	},
	"crucibletags": {
		{Name: "Tags", Type: ColString},
		{Type: ColBool},
	},
	"currencyexchange": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Category", Type: ColKey, RefTo: "CurrencyExchangeCategories"},
		{Name: "SubCategory", Type: ColKey, RefTo: "CurrencyExchangeCategories"},
		{Type: ColBool},
		{Name: "EnabledInLeague", Type: ColBool},
		{Name: "GoldFee", Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
	},
	"defaultmonsterstats": {
		{Name: "Level", Type: ColString},
		{Name: "Damage", Type: ColFloat},
		{Name: "Evasion", Type: ColInt},
		{Name: "Accuracy", Type: ColInt},
		{Name: "MonsterLife", Type: ColInt},
		{Name: "XP", Type: ColInt},
		{Name: "MinionLife", Type: ColInt},
		{Name: "Armour", Type: ColInt},
		{Name: "ResistancePart", Type: ColInt},
		{Name: "MinionDamage", Type: ColFloat},
		{Name: "AltLife1", Type: ColInt},
		{Name: "AltDamage1", Type: ColFloat},
		{Name: "AltDamage2", Type: ColFloat},
		{Name: "AltLife2", Type: ColInt},
		{Name: "EvasiveEvasion", Type: ColInt},
		{Name: "AilmentThreshold", Type: ColInt},
		{Name: "MonsterPhysConversionMulti", Type: ColInt},
	},
	"descendancy": {
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
	},
	"displayminionmonstertype": {
		{Name: "Id", Type: ColInt},
		{Name: "MonsterVarieties", Type: ColKey, RefTo: "MonsterVarieties"},
	},
	"divinationbufftemplates": {
		{Name: "Buff", Type: ColKey, RefTo: "BuffTemplates"},
		{Name: "DivCardArt", Type: ColKey, RefTo: "DivinationCardArt"},
	},
	"effectivenesscostconstants": {
		{Name: "Id", Type: ColString},
		{Name: "Value", Type: ColFloat},
	},
	"essences": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Unknown1", Type: ColKey},
		{Name: "Unknown2", Type: ColKey},
		{Name: "Unknown3", Type: ColKey},
		{Name: "Unknown4", Type: ColKey},
		{Name: "Unknown5", Type: ColKey},
		{Name: "Unknown6", Type: ColKey},
		{Name: "Unknown7", Type: ColKey},
		{Name: "Unknown8", Type: ColKey},
		{Name: "Unknown9", Type: ColKey},
		{Name: "Unknown10", Type: ColKey},
		{Name: "Unknown11", Type: ColKey},
		{Name: "WandsMod", Type: ColKey, RefTo: "Mods"},
		{Name: "BowMods", Type: ColKey, RefTo: "Mods"},
		{Name: "QuiverMod", Type: ColKey, RefTo: "Mods"},
		{Name: "AmuletMods", Type: ColKey, RefTo: "Mods"},
		{Name: "RingMods", Type: ColKey, RefTo: "Mods"},
		{Name: "BeltMods", Type: ColKey, RefTo: "Mods"},
		{Name: "GlovesMods", Type: ColKey, RefTo: "Mods"},
		{Name: "BootsMods", Type: ColKey, RefTo: "Mods"},
		{Name: "BodyArmourMods", Type: ColKey, RefTo: "Mods"},
		{Name: "HelmetMods", Type: ColKey, RefTo: "Mods"},
		{Name: "ShieldMods", Type: ColKey, RefTo: "Mods"},
		{Name: "HASH32", Type: ColUInt},
		{Name: "DropLevel", Type: ColInt, List: true},
		{Name: "MonsterMods", Type: ColKey, List: true, RefTo: "Mods"},
		{Name: "Type", Type: ColKey, RefTo: "EssenceType"},
		{Name: "Tier", Type: ColInt},
		{Type: ColInt, List: true},
		{Name: "WeaponMod", Type: ColKey, RefTo: "Mods"},
		{Name: "MeleeWeaponMod", Type: ColKey, RefTo: "Mods"},
		{Name: "OneHandWeaponMod", Type: ColKey, RefTo: "Mods"},
		{Name: "TwoHandWeaponMod", Type: ColKey, RefTo: "Mods"},
		{Name: "TwoHandMeleeMod", Type: ColKey, RefTo: "Mods"},
		{Name: "ArmourMod", Type: ColKey, RefTo: "Mods"},
		{Name: "RangedWeaponMod", Type: ColKey, RefTo: "Mods"},
		{Name: "HelmetMod", Type: ColKey, RefTo: "Mods"},
		{Name: "BodyArmourMod", Type: ColKey, RefTo: "Mods"},
		{Name: "BootsMod", Type: ColKey, RefTo: "Mods"},
		{Name: "GlovesMod", Type: ColKey, RefTo: "Mods"},
		{Name: "BowMod", Type: ColKey, RefTo: "Mods"},
		{Name: "WandMod", Type: ColKey, RefTo: "Mods"},
		{Name: "StaffMod", Type: ColKey, RefTo: "Mods"},
		{Name: "TwoHandSwordMod", Type: ColKey, RefTo: "Mods"},
		{Name: "TwoHandAxeMod", Type: ColKey, RefTo: "Mods"},
		{Name: "TwoHandMaceMod", Type: ColKey, RefTo: "Mods"},
		{Name: "ClawMod", Type: ColKey, RefTo: "Mods"},
		{Name: "DaggerMod", Type: ColKey, RefTo: "Mods"},
		{Name: "OneHandSwordMod", Type: ColKey, RefTo: "Mods"},
		{Name: "ThrustingOneHandSwordMod", Type: ColKey, RefTo: "Mods"},
		{Name: "OneHandAxeMod", Type: ColKey, RefTo: "Mods"},
		{Name: "OneHandMaceMod", Type: ColKey, RefTo: "Mods"},
		{Name: "SceptreMod", Type: ColKey, RefTo: "Mods"},
		{Name: "MonsterMod", Type: ColKey, RefTo: "Mods"},
		{Name: "ItemLevelRestriction", Type: ColInt, RefTo: "Mods"},
		{Name: "BeltMod", Type: ColKey, RefTo: "Mods"},
		{Name: "AmuletMod", Type: ColKey, RefTo: "Mods"},
		{Name: "RingMod", Type: ColKey, RefTo: "Mods"},
		{Name: "JewelleryMod", Type: ColKey, RefTo: "Mods"},
		{Name: "ShieldMod", Type: ColKey, RefTo: "Mods"},
		{Name: "OtherItemMod", Type: ColKey, RefTo: "Mods"},
		{Name: "IsScreaming", Type: ColBool},
		{Name: "MemoryLines", Type: ColKey, List: true, RefTo: "Mods"},
		{Type: ColInt, List: true},
		{Type: ColInt, List: true},
	},
	"essencetype": {
		{Name: "Name", Type: ColString},
		{Name: "TypeTier", Type: ColInt},
		{Name: "CorruptOnly", Type: ColBool},
		{Type: ColKey, RefTo: "Words"},
		{Name: "PartyMods", Type: ColKey, RefTo: "Stats"},
	},
	"experiencelevels": {
		{Type: ColString},
		{Type: ColInt},
		{Type: ColUInt},
	},
	"flasks": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Name", Type: ColString},
		{Type: ColEnum, RefTo: "FlaskType"},
		{Name: "LifePerUse", Type: ColInt},
		{Name: "ManaPerUse", Type: ColInt},
		{Name: "RecoveryTime", Type: ColInt},
		{Name: "Buff", Type: ColKey, RefTo: "BuffDefinitions"},
		{Name: "BuffMagnitudes", Type: ColInt, List: true},
		{Name: "RecoveryTime2", Type: ColInt},
		{Name: "BuffMagnitude2", Type: ColInt, List: true},
	},
	"flavourtext": {
		{Name: "Id", Type: ColString},
		{Type: ColInt},
		{Name: "Text", Type: ColString},
	},
	"gameconstants": {
		{Name: "Id", Type: ColString},
		{Name: "Value", Type: ColInt},
		{Name: "Divisor", Type: ColInt},
	},
	"gemeffects": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "GrantedEffect", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "GrantedEffectHardmode", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "GrantedEffect2", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "GrantedEffect2Hardmode", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "Description", Type: ColString},
		{Name: "SecondarySupportName", Type: ColString},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "GemTags"},
		{Name: "HungryLoopMod", Type: ColKey, RefTo: "Mods"},
		{Name: "Variant", Type: ColInt},
	},
	"gemtags": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "LocalLevelStat", Type: ColKey, RefTo: "Stats"},
		{Name: "LocalQualityStat", Type: ColKey, RefTo: "Stats"},
		{Name: "GlobalSpellLevelStat", Type: ColKey, RefTo: "Stats"},
		{Name: "GlobalSkillLevelStat", Type: ColKey, RefTo: "Stats"},
	},
	"genericbuffauras": {
		{Name: "Id", Type: ColString},
	},
	"grantedeffectqualitystats": {
		{Name: "GrantedEffect", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "GrantedStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "StatValues", Type: ColInt, List: true},
		{Name: "AddTypes", Type: ColEnum, List: true, RefTo: "ActiveSkillType"},
		{Name: "AddMinionTypes", Type: ColEnum, List: true, RefTo: "ActiveSkillType"},
	},
	"grantedeffects": {
		{Name: "Id", Type: ColString},
		{Name: "IsSupport", Type: ColBool},
		{Name: "SupportTypes", Type: ColKey, List: true, RefTo: "ActiveSkillType"},
		{Name: "SupportGemLetter", Type: ColString},
		{Name: "Attribute", Type: ColInt},
		{Name: "AddTypes", Type: ColKey, List: true, RefTo: "ActiveSkillType"},
		{Name: "ExcludeTypes", Type: ColKey, List: true, RefTo: "ActiveSkillType"},
		{Name: "SupportGemsOnly", Type: ColBool},
		{Name: "Hash32", Type: ColUInt},
		{Type: ColEnum, List: true},
		{Name: "CannotBeSupported", Type: ColBool},
		{Name: "LifeLeech?", Type: ColInt},
		{Name: "CastTime", Type: ColInt},
		{Name: "ActiveSkill", Type: ColKey, RefTo: "ActiveSkills"},
		{Name: "IgnoreMinionTypes", Type: ColBool},
		{Name: "CooldownNotRecoverDuringActive", Type: ColBool},
		{Name: "AddMinionTypes", Type: ColKey, List: true, RefTo: "ActiveSkillType"},
		{Name: "Animation", Type: ColKey, RefTo: "Animation"},
		{Name: "MultiPartAchievement", Type: ColKey, RefTo: "MultiPartAchievements"},
		{Type: ColBool},
		{Name: "WeaponRestrictions", Type: ColKey, List: true, RefTo: "ItemClasses"},
		{Name: "PlusVersionOf", Type: ColShortKey, RefTo: "GrantedEffects"},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
		{Name: "GrantedEffectStatSets", Type: ColKey, RefTo: "GrantedEffectStatSets"},
		{Name: "GrantedEffectStatSets2", Type: ColKey, List: true, RefTo: "GrantedEffectStatSets"},
	},
	"grantedeffectsperlevel": {
		{Name: "GrantedEffect", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "Level", Type: ColInt, RefTo: "nil"},
		{Name: "PlayerLevelReq", Type: ColFloat},
		{Name: "CostMultiplier", Type: ColInt},
		{Name: "StoredUses", Type: ColInt},
		{Name: "Cooldown", Type: ColInt},
		{Name: "CooldownBypassType", Type: ColInt, RefTo: "CooldownBypassTypes"},
		{Name: "VaalSouls", Type: ColInt, RefTo: "Stats"},
		{Name: "VaalStoredUses", Type: ColInt},
		{Name: "CooldownGroup", Type: ColInt},
		{Name: "PvPDamageMultiplier", Type: ColInt},
		{Name: "SoulGainPreventionDuration", Type: ColInt},
		{Name: "AttackSpeedMultiplier", Type: ColInt},
		{Type: ColInt},
		{Name: "CostAmounts", Type: ColInt, List: true},
		{Name: "CostTypes", Type: ColKey, List: true, RefTo: "CostTypes"},
		{Name: "ManaReservationFlat", Type: ColInt},
		{Name: "ManaReservationPercent", Type: ColInt},
		{Name: "LifeReservationFlat", Type: ColInt},
		{Name: "LifeReservationPercent", Type: ColInt},
		{Name: "AttackTime", Type: ColInt},
	},
	"grantedeffectstatsets": {
		{Name: "Id", Type: ColString},
		{Name: "ImplicitStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "ConstantStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "ConstantStatsValues", Type: ColInt, List: true},
		{Name: "BaseEffectiveness", Type: ColFloat},
		{Type: ColInt},
		{Name: "IncrementalEffectiveness", Type: ColFloat},
	},
	"grantedeffectstatsetsperlevel": {
		{Name: "GrantedEffectStatSets", Type: ColKey, RefTo: "GrantedEffectStatSets"},
		{Name: "GemLevel", Type: ColInt},
		{Name: "PlayerLevelReq", Type: ColFloat},
		{Name: "AttackCritChance", Type: ColInt},
		{Name: "OffhandCritChance", Type: ColInt},
		{Name: "BaseMultiplier", Type: ColInt},
		{Name: "DamageEffectiveness", Type: ColInt},
		{Name: "BaseResolvedValues", Type: ColInt, List: true, RefTo: "Stats"},
		{Name: "AdditionalStatsValues", Type: ColInt, List: true, RefTo: "Stats"},
		{Name: "GrantedEffect", Type: ColKey, List: true, RefTo: "GrantedEffects"},
		{Name: "AdditionalBooleanStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "FloatStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "InterpolationBases", Type: ColKey, List: true, RefTo: "EffectivenessCostConstants"},
		{Name: "AdditionalStats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "StatInterpolations", Type: ColInt, List: true},
		{Name: "FloatStatsValues", Type: ColFloat, List: true},
	},
	"hideoutnpcs": {
		{Name: "NPC", Type: ColKey, RefTo: "NPCs"},
	},
	"indexableskillgems": {
		{Name: "Id", Type: ColInt},
		{Name: "BaseItemType", Type: ColKey, List: true, RefTo: "SkillGems"},
		{Name: "Skill", Type: ColString},
		{Name: "BaseItemTypeRuthless", Type: ColKey, List: true, RefTo: "SkillGems"},
		{Name: "SkillRuthless", Type: ColString},
		{Name: "IdRuthless", Type: ColKey, RefTo: "indexableskillgems"},
	},
	"indexablesupportgems": {
		{Name: "Id", Type: ColInt},
		{Name: "BaseItemType", Type: ColKey, RefTo: "SkillGems"},
		{Name: "Skill", Type: ColString},
	},
	"influencetags": {
		{Name: "ItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "InfluenceType", Type: ColEnum, RefTo: "influencetypes"},
		{Name: "tags", Type: ColKey, RefTo: "Tags"},
	},
	"influencetypes": {
		{Name: "Id", Type: ColString},
	},
	"itemclasscategories": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Type: ColKey},
	},
	"itemclasses": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "ItemClassCategory", Type: ColKey, RefTo: "ItemClassCategories"},
		{Name: "RemovedIfLeavesArea", Type: ColBool},
		{Type: ColKey, List: true},
		{Name: "Achievements", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "AllocateToMapOwner", Type: ColBool},
		{Name: "AlwaysAllocate", Type: ColBool},
		{Name: "CanHaveVeiledMods", Type: ColBool},
		{Name: "PickedUpQuest", Type: ColKey, RefTo: "QuestFlags"},
		{Type: ColInt},
		{Name: "AlwaysShow", Type: ColBool},
		{Name: "CanBeCorrupted", Type: ColBool},
		{Name: "CanHaveIncubators", Type: ColBool},
		{Name: "CanHaveInfluence", Type: ColBool},
		{Name: "CanBeDoubleCorrupted", Type: ColBool},
		{Name: "CanHaveAspects", Type: ColBool},
		{Name: "CanTransferSkin", Type: ColBool},
		{Name: "ItemStance", Type: ColKey, RefTo: "ItemStances"},
		{Name: "CanScourge", Type: ColBool},
		{Name: "CanUpgradeRarity", Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "Flags", Type: ColInt, List: true},
		{Name: "Unmodifiable", Type: ColBool},
		{Name: "CanBeFractured", Type: ColBool},
		{Name: "EquipAchievements", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "UsedInMapDevice", Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
	},
	"itemexperienceperlevel": {
		{Name: "ItemExperienceType", Type: ColKey, RefTo: "ItemExperienceTypes"},
		{Name: "Level", Type: ColInt},
		{Name: "Experience", Type: ColInt},
	},
	"itemexperiencetypes": {
		{Name: "Id", Type: ColString},
	},
	"itemisedcorpse": {
		{Name: "BaseItem", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Monster", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "MonsterAbilities", Type: ColString},
		{Name: "MonsterCategory", Type: ColKey, RefTo: "CorpseTypeTags"},
	},
	"itemstances": {
		{Name: "Id", Type: ColString},
	},
	"itemsynthesiscorruptedmods": {
		{Name: "ItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "ImplicitMods", Type: ColKey, List: true, RefTo: "Mods"},
	},
	"itemsynthesismods": {
		{Name: "Id", Type: ColString},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Type: ColInt},
		{Name: "ItemClasses", Type: ColKey, List: true, RefTo: "ItemClasses"},
		{Name: "ImplicitMod", Type: ColKey, List: true, RefTo: "Mods"},
	},
	"itemvisualidentity": {
		{Name: "Id", Type: ColString},
		{Name: "DDSFile", Type: ColString},
		{Name: "AOFile", Type: ColString},
		{Name: "InventorySound", Type: ColKey, RefTo: "SoundEffects"},
		{Name: "Hash", Type: ColUInt16},
		{Name: "AOFile2", Type: ColString},
		{Name: "MarauderSMFiles", Type: ColString, List: true},
		{Name: "RangerSMFiles", Type: ColString, List: true},
		{Name: "WitchSMFiles", Type: ColString, List: true},
		{Name: "DuelistDexSMFiles", Type: ColString, List: true},
		{Name: "TemplarSMFiles", Type: ColString, List: true},
		{Name: "ShadowSMFiles", Type: ColString, List: true},
		{Name: "ScionSMFiles", Type: ColString, List: true},
		{Name: "MarauderShape", Type: ColString},
		{Name: "RangerShape", Type: ColString},
		{Name: "WitchShape", Type: ColString},
		{Name: "DuelistShape", Type: ColString},
		{Name: "TemplarShape", Type: ColString},
		{Name: "ShadowShape", Type: ColString},
		{Name: "ScionShape", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Pickup_AchievementItemsKeys", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "SMFiles", Type: ColString, List: true},
		{Name: "Identify_AchievementItemsKeys", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "EPKFile", Type: ColString},
		{Name: "Corrupt_AchievementItemsKeys", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "IsAlternateArt", Type: ColBool},
		{Type: ColBool},
		{Name: "CreateCorruptedJewelAchievementItemsKey", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "AnimationLocation", Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Name: "IsAtlasOfWorldsMapIcon", Type: ColBool},
		{Name: "IsTier16Icon", Type: ColBool},
		{Name: "KalandaAchievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Type: ColBool},
		{Name: "HeistAchievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Type: ColString},
		{Type: ColInt},
		{Type: ColKey, RefTo: "Stats"},
		{Type: ColKey, RefTo: "Stats"},
		{Type: ColKey, RefTo: "Stats"},
		{Type: ColKey, RefTo: "Stats"},
		{Type: ColKey, List: true},
		{Type: ColKey, List: true},
		{Type: ColBool},
		{Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColKey, List: true},
	},
	"leaguenames": {
		{Type: ColString},
		{Name: "Name", Type: ColString},
		{Type: ColString},
	},
	"mavenjewelradiuskeystones": {
		{Name: "Keystone_Key", Type: ColKey, RefTo: "PassiveSkills"},
	},
	"melee": {
		{Name: "ActiveSkill", Type: ColKey, RefTo: "ActiveSkills"},
		{Type: ColInt},
		{Name: "MiscAnimated", Type: ColKey, RefTo: "MiscAnimated"},
		{Name: "MeleeTrails1", Type: ColKey, RefTo: "MeleeTrails"},
		{Name: "MeleeTrails2", Type: ColKey, RefTo: "MeleeTrails"},
		{Name: "MeleeTrails3", Type: ColKey, RefTo: "MeleeTrails"},
		{Name: "MeleeTrails4", Type: ColKey, RefTo: "MeleeTrails"},
		{Name: "MeleeTrails5", Type: ColKey, RefTo: "MeleeTrails"},
		{Name: "MeleeTrails6", Type: ColKey, RefTo: "MeleeTrails"},
		{Name: "MeleeTrails7", Type: ColKey, RefTo: "MeleeTrails"},
		{Type: ColBool},
		{Name: "SurgeEPK", Type: ColString},
		{Type: ColString},
		{Type: ColString},
	},
	"mercenaryattributes": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "Tag", Type: ColKey, List: true, RefTo: "Tags"},
	},
	"mercenarybuilds": {
		{Name: "Id", Type: ColString},
		{Name: "Class", Type: ColKey, RefTo: "MercenaryClasses"},
		{Name: "Skill1", Type: ColKey, List: true, RefTo: "MercenarySkills"},
		{Name: "Skill1CountMax", Type: ColInt},
		{Name: "Skill2", Type: ColKey, List: true, RefTo: "MercenarySkills"},
		{Type: ColInt},
		{Type: ColKey, List: true},
		{Name: "Skill2CountMax", Type: ColInt},
		{Name: "Skill3", Type: ColKey, List: true, RefTo: "MercenarySkills"},
		{Type: ColKey, List: true},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "AIFile", Type: ColString},
		{Name: "HASH16", Type: ColUInt16},
		{Name: "BuildName", Type: ColString},
		{Type: ColInt},
		{Name: "Infamous", Type: ColBool},
		{Type: ColKey},
		{Type: ColString},
		{Type: ColString, List: true},
		{Name: "Achievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "WeaponTypes", Type: ColKey, List: true, RefTo: "MercenaryWieldableTypes"},
	},
	"mercenaryclasses": {
		{Name: "Id", Type: ColString},
		{Name: "MonsterVariety", Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColInt},
		{Name: "Terrain", Type: ColKey, RefTo: "ExtraTerrainFeatures"},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Icon", Type: ColString},
		{Name: "HouseIcon", Type: ColString},
		{Name: "Attribute", Type: ColKey, RefTo: "MercenaryAttributes"},
		{Name: "BuffIcon", Type: ColString},
		{Name: "MonsterVarietyAllied", Type: ColKey, RefTo: "MonsterVarieties"},
	},
	"mercenaryinventories": {
		{Name: "Inventory", Type: ColKey, RefTo: "Inventories"},
		{Name: "Id", Type: ColInt},
		{Name: "XOffset", Type: ColInt},
		{Name: "YOffset", Type: ColInt},
		{Name: "InventoryType", Type: ColInt},
	},
	"mercenaryskillfamilies": {
		{Name: "Id", Type: ColString},
	},
	"mercenaryskills": {
		{Name: "Id", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "SupportCount", Type: ColKey, RefTo: "MercenarySupportCounts"},
		{Name: "PossibleSupports", Type: ColKey, List: true, RefTo: "MercenarySupports"},
		{Name: "SecondaryGrantedEffect", Type: ColKey, RefTo: "GrantedEffects"},
		{Name: "Name", Type: ColString},
		{Name: "Description", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "SkillFamily", Type: ColKey, RefTo: "MercenarySkillFamilies"},
		{Name: "HASH16", Type: ColUInt16},
		{Name: "HouseSkillIcon", Type: ColString},
	},
	"mercenarysupportcounts": {
		{Name: "Id", Type: ColString},
	},
	"mercenarysupportfamilies": {
		{Name: "Id", Type: ColString},
	},
	"mercenarysupports": {
		{Name: "Id", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Stat", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "StatValues", Type: ColInt, List: true},
		{Name: "Name", Type: ColString},
		{Name: "SupportFamily", Type: ColKey, RefTo: "MercenarySupportFamilies"},
		{Name: "HASH16", Type: ColUInt16},
		{Name: "GemIcon", Type: ColString},
		{Name: "Variant", Type: ColInt},
		{Type: ColKey, List: true},
		{Type: ColKey, List: true},
	},
	"mercenarywieldabletypes": {
		{Name: "ItemClasses", Type: ColKey, RefTo: "ItemClasses"},
	},
	"miniondoublingstattypes": {
		{Name: "Id", Type: ColInt},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Name: "MinionType", Type: ColKey, RefTo: "MinionType"},
	},
	"miniontype": {
		{Name: "Id", Type: ColString},
		{Name: "LimitStat", Type: ColKey, RefTo: "stats"},
		{Name: "ActiveCountStat", Type: ColKey, RefTo: "stats"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
	},
	"miscanimated": {
		{Name: "Id", Type: ColString},
		{Name: "AOFile", Type: ColString},
		{Name: "PreloadGroup", Type: ColKey, List: true, RefTo: "PreloadGroups"},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "HASH32", Type: ColUInt},
	},
	"miscanimatedartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "MiscAnimated", Type: ColKey, List: true, RefTo: "MiscAnimated"},
		{Type: ColInt},
		{Name: "Variant", Type: ColInt},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
	},
	"miscbeams": {
		{Name: "Id", Type: ColString},
		{Name: "MiscAnimated", Type: ColKey, RefTo: "MiscAnimated"},
		{Type: ColFloat},
		{Name: "PreloadGroup", Type: ColKey, List: true, RefTo: "PreloadGroups"},
		{Type: ColInt},
	},
	"miscbeamsartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "MiscBeams", Type: ColKey, List: true, RefTo: "MiscBeams"},
		{Type: ColInt},
		{Name: "Variant", Type: ColInt},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
	},
	"misceffectpacksartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "MiscEffectPack", Type: ColKey, List: true, RefTo: "MiscEffectPacks"},
		{Name: "Variant", Type: ColInt},
	},
	"miscobjectartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "MiscObject", Type: ColKey, List: true, RefTo: "MiscObjects"},
		{Name: "Variant", Type: ColInt},
	},
	"modeffectstats": {
		{Name: "Stats", Type: ColKey, RefTo: "Stats"},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "ApplyToExplicit", Type: ColBool},
		{Type: ColInt},
		{Name: "ApplyToImplicit", Type: ColBool},
		{Name: "ApplyToPrefix", Type: ColBool},
		{Name: "ApplyToSuffix", Type: ColBool},
		{Name: "Multiplier", Type: ColInt},
	},
	"modequivalencies": {
		{Name: "Id", Type: ColString},
		{Name: "ModsKey0", Type: ColKey, RefTo: "Mods"},
		{Name: "ModsKey1", Type: ColKey, RefTo: "Mods"},
		{Name: "ModsKey2", Type: ColKey, RefTo: "Mods"},
		{Type: ColBool},
	},
	"modfamily": {
		{Name: "Id", Type: ColString},
	},
	"mods": {
		{Name: "Id", Type: ColString},
		{Name: "Hash", Type: ColUInt16},
		{Name: "Type", Type: ColKey, RefTo: "ModType"},
		{Name: "Level", Type: ColInt},
		{Name: "Stat1", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat2", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat3", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat4", Type: ColKey, RefTo: "Stats"},
		{Name: "Domain", Type: ColInt, RefTo: "ModDomains"},
		{Name: "Name", Type: ColString},
		{Name: "GenerationType", Type: ColInt, RefTo: "ModGenerationType"},
		{Name: "Family", Type: ColKey, List: true, RefTo: "ModFamily"},
		{Name: "Stat1Value", Type: ColInterval},
		{Name: "Stat2Value", Type: ColInterval},
		{Name: "Stat3Value", Type: ColInterval},
		{Name: "Stat4Value", Type: ColInterval},
		{Name: "SpawnTags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "SpawnWeights", Type: ColInt, List: true, RefTo: "Tags"},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "GrantedEffect", Type: ColKey, List: true, RefTo: "GrantedEffectsPerLevel"},
		{Name: "AuraFlags", Type: ColEnum, List: true, RefTo: "ModAuraFlags"},
		{Name: "Daemon", Type: ColString},
		{Name: "MonsterKillAchievements", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "ArchnemesisType", Type: ColKey, List: true, RefTo: "ModType"},
		{Name: "Stat5Value", Type: ColInterval},
		{Name: "Stat5", Type: ColKey, RefTo: "Stats"},
		{Name: "FullClear", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "AchievementItemsKey", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "GenerationWeightTags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "GenerationWeightValues", Type: ColInt, List: true, RefTo: "Tags"},
		{Name: "ModifyMapsAchievements", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "IsEssence", Type: ColBool},
		{Name: "Stat6Value", Type: ColInterval},
		{Name: "Stat6", Type: ColKey, RefTo: "Stats"},
		{Name: "MaxLevel", Type: ColInt},
		{Type: ColBool},
		{Name: "CraftingClassRestrictions", Type: ColKey, List: true, RefTo: "ItemClasses"},
		{Name: "MonsterOnDeath", Type: ColString},
		{Type: ColInt},
		{Name: "HeistAchievements", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "Heist_SubStatValue1", Type: ColInt, RefTo: "Heist_SubStatValue1"},
		{Name: "Heist_SubStatValue2", Type: ColInt, RefTo: "GrantedEffectsPerLevel"},
		{Name: "Heist_StatsKey0", Type: ColKey, RefTo: "Stats"},
		{Name: "Heist_StatsKey1", Type: ColKey, RefTo: "Stats"},
		{Name: "Heist_AddStatValue1", Type: ColInt},
		{Name: "Heist_AddStatValue2", Type: ColInt},
		{Name: "InfluenceTypes", Type: ColInt},
		{Name: "ImplicitTags", Type: ColKey, List: true, RefTo: "Tags"},
		{Type: ColBool},
		{Name: "UnknownStat1", Type: ColInterval},
		{Name: "UnknownStat2", Type: ColInterval},
		{Name: "UnknownStat3", Type: ColInterval},
		{Name: "UnknownStat4", Type: ColInterval},
		{Name: "UnknownStat5", Type: ColInterval},
		{Name: "UnknownStat6", Type: ColInterval},
		{Name: "UnknownStat7", Type: ColInterval},
		{Name: "UnknownStat8", Type: ColInterval},
		{Name: "BuffTemplate1", Type: ColKey, RefTo: "BuffTemplates"},
		{Name: "ArchnemesisMinionMod", Type: ColShortKey, RefTo: "Mods"},
		{Name: "HASH32", Type: ColUInt},
		{Name: "BuffTemplate2", Type: ColKey, List: true, RefTo: "BuffTemplates"},
		{Name: "GameMode", Type: ColInt},
		{Name: "RuthlessReplacement", Type: ColKey, List: true, RefTo: "GrantedEffectsPerLevel"},
		{Type: ColBool},
	},
	"modsellpricetypes": {
		{Name: "Id", Type: ColString},
	},
	"modtype": {
		{Name: "Id", Type: ColString},
		{Name: "Stat", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "ModSellPriceTypesKeys", Type: ColKey, List: true, RefTo: "ModSellPriceTypes"},
		{Type: ColBool},
	},
	"monsterbonuses": {
		{Type: ColString},
	},
	"monsterconditions": {
		{Name: "Id", Type: ColString},
		{Name: "Rarity", Type: ColKey, RefTo: "Rarity"},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Name: "NotRarity", Type: ColKey, RefTo: "Rarity"},
		{Name: "NotStat", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "MapBoss", Type: ColBool},
		{Name: "NotMapBoss", Type: ColBool},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "NotTags", Type: ColKey, List: true, RefTo: "Tags"},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "HASH32", Type: ColUInt},
	},
	"monstermapbossdifficulty": {
		{Name: "AreaLevel", Type: ColInt},
		{Name: "BossLifePercentIncrease", Type: ColInt},
		{Name: "BossDamagePercentIncrease", Type: ColInt},
		{Name: "Stat1", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat2", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat3", Type: ColKey, RefTo: "Stats"},
		{Name: "BossIncItemQuantity", Type: ColInt},
		{Name: "Stat4", Type: ColKey, RefTo: "Stats"},
		{Name: "BossIncItemRarity", Type: ColInt},
		{Name: "Stat5", Type: ColKey, RefTo: "Stats"},
		{Name: "BossAilmentPercentDecrease", Type: ColInt},
	},
	"monstermapdifficulty": {
		{Name: "AreaLevel", Type: ColInt},
		{Name: "LifePercentIncrease", Type: ColInt},
		{Name: "DamagePercentIncrease", Type: ColInt},
		{Name: "Stat1", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat2", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat3", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat3Value", Type: ColInt},
		{Name: "Stat4", Type: ColKey, RefTo: "Stats"},
		{Name: "Stat4Value", Type: ColInt},
	},
	"monsterresistances": {
		{Name: "Id", Type: ColString},
		{Name: "FireNormal", Type: ColInt},
		{Name: "ColdNormal", Type: ColInt},
		{Name: "LightningNormal", Type: ColInt},
		{Name: "ChaosNormal", Type: ColInt},
		{Name: "FireCruel", Type: ColInt},
		{Name: "ColdCruel", Type: ColInt},
		{Name: "LightningCruel", Type: ColInt},
		{Name: "ChaosCruel", Type: ColInt},
		{Name: "FireMerciless", Type: ColInt},
		{Name: "ColdMerciless", Type: ColInt},
		{Name: "LightningMerciless", Type: ColInt},
		{Name: "ChaosMerciless", Type: ColInt},
	},
	"monstertypes": {
		{Name: "Id", Type: ColString},
		{Name: "Accuracy", Type: ColInt},
		{Name: "IsPlayerMinion", Type: ColBool},
		{Name: "Armour", Type: ColInt},
		{Name: "Evasion", Type: ColInt},
		{Name: "EnergyShield", Type: ColInt},
		{Name: "DamageSpread", Type: ColInt},
		{Name: "Resistances", Type: ColKey, RefTo: "MonsterResistances"},
		{Name: "AltLife1", Type: ColBool},
		{Name: "AltLife2", Type: ColBool},
		{Name: "BaseDamageIgnoresAttackSpeed", Type: ColBool},
	},
	"monstervarieties": {
		{Name: "Id", Type: ColString},
		{Name: "Type", Type: ColKey, RefTo: "MonsterTypes"},
		{Name: "MovementSpeed", Type: ColInt},
		{Name: "ObjectSize", Type: ColEnum},
		{Name: "MinimumAttackRange", Type: ColInt},
		{Name: "MaximumAttackRange", Type: ColInt},
		{Name: "Actor", Type: ColString, List: true},
		{Name: "AnimatedObject", Type: ColString, List: true},
		{Name: "ObjectType", Type: ColString},
		{Name: "Mods", Type: ColKey, List: true, RefTo: "Mods"},
		{Type: ColInt},
		{Type: ColString},
		{Type: ColString},
		{Name: "ModelSizeMultiplier", Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "ExperienceMultiplier", Type: ColInt},
		{Type: ColInt, List: true},
		{Name: "MinAgroRange", Type: ColInt},
		{Name: "MaxAgroRange", Type: ColInt},
		{Name: "SpotlightColour1", Type: ColInt},
		{Name: "SpotlightColour2", Type: ColInt},
		{Name: "SpotlightColour3", Type: ColInt},
		{Name: "GrantedEffects", Type: ColKey, List: true, RefTo: "GrantedEffects"},
		{Name: "AIScript", Type: ColString},
		{Name: "ModsKeys2", Type: ColKey, List: true, RefTo: "Mods"},
		{Name: "Stance", Type: ColString},
		{Type: ColKey},
		{Name: "Name", Type: ColString},
		{Name: "DamageMultiplier", Type: ColInt},
		{Name: "LifeMultiplier", Type: ColInt},
		{Name: "AttackDuration", Type: ColInt},
		{Name: "MainHandItem", Type: ColKey, List: true, RefTo: "ItemVisualIdentity"},
		{Name: "OffHandItem", Type: ColKey, List: true, RefTo: "ItemVisualIdentity"},
		{Name: "BackItem", Type: ColKey, RefTo: "ItemVisualIdentity"},
		{Name: "MainHandItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "OffHandItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "HelmetItem", Type: ColKey, RefTo: "ItemVisualIdentity"},
		{Type: ColInt},
		{Name: "KillSpecificMonsterCount", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "SpecialMods", Type: ColKey, List: true, RefTo: "Mods"},
		{Name: "KillRare", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColInt, RefTo: "AchievementItems"},
		{Type: ColInt, RefTo: "AchievementItems"},
		{Type: ColInt, RefTo: "AchievementItems"},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Hash", Type: ColUInt16},
		{Type: ColBool},
		{Type: ColString},
		{Name: "AchievementFlashback", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "MonsterSegments", Type: ColKey, RefTo: "MonsterSegments"},
		{Name: "MonsterArmours", Type: ColKey, RefTo: "MonsterArmours"},
		{Name: "AchievementTalisman", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "ModsPart1", Type: ColKey, List: true, RefTo: "Mods"},
		{Name: "ModsPart2", Type: ColKey, List: true, RefTo: "Mods"},
		{Name: "ModsEndgame", Type: ColKey, List: true, RefTo: "Mods"},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "MultiPartAchievements", Type: ColKey, List: true, RefTo: "MultiPartAchievements"},
		{Type: ColInt},
		{Name: "SinkAnimation", Type: ColString},
		{Type: ColBool},
		{Type: ColKey, List: true, RefTo: "MultiPartAchievements"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColFloat},
		{Name: "AilmentThreshold", Type: ColInt},
		{Name: "SinkEffect", Type: ColString},
		{Type: ColInt},
		{Name: "MonsterConditionalEffectPack", Type: ColKey, RefTo: "MonsterConditionalEffectPacks"},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "AddonMonsterTypeIndex", Type: ColString, List: true},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
		{Name: "BossHealthBar", Type: ColBool},
		{Type: ColBool},
	},
	"monstervarietiesartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "Variant", Type: ColInt},
		{Name: "MonsterVariety", Type: ColKey, List: true, RefTo: "MonsterVarieties"},
	},
	"multipartachievements": {
		{Name: "Id", Type: ColString},
		{Type: ColInt},
		{Name: "Achievement", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "Threshold", Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
	},
	"nearbymonsterconditions": {
		{Type: ColString},
	},
	"npcs": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "Metadata", Type: ColString},
		{Name: "QuestFlag", Type: ColKey, RefTo: "QuestFlags"},
		{Name: "NPCMaster", Type: ColKey, RefTo: "NPCMaster"},
		{Name: "ShortName", Type: ColString},
		{Type: ColInt},
		{Name: "NPCAudio1", Type: ColKey, List: true, RefTo: "NPCAudio"},
		{Name: "NPCAudio2", Type: ColKey, List: true, RefTo: "NPCAudio"},
		{Name: "HASH16", Type: ColUInt16},
		{Type: ColShortKey, RefTo: "NPCS"},
		{Name: "Portrait", Type: ColKey, RefTo: "NPCPortraits"},
		{Name: "DialogueStyle", Type: ColKey, RefTo: "NPCDialogueStyles"},
		{Type: ColBool},
		{Type: ColKey, RefTo: "NPCShopSets"},
		{Name: "Gender", Type: ColString},
		{Type: ColBool},
		{Type: ColInt},
	},
	"pantheonpanellayout": {
		{Name: "Id", Type: ColString},
		{Name: "X", Type: ColInt},
		{Name: "Y", Type: ColInt},
		{Name: "IsMajorGod", Type: ColBool},
		{Name: "CoverImage", Type: ColString},
		{Name: "GodName2", Type: ColString},
		{Name: "SelectionFrame", Type: ColString},
		{Name: "Effect1StatsKey", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "Effect1Values", Type: ColInt, List: true},
		{Name: "Effect2StatsKey", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "GodName3", Type: ColString},
		{Name: "Effect3Values", Type: ColInt, List: true},
		{Name: "Effect3StatsKey", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "GodName4", Type: ColString},
		{Name: "Effect4StatsKey", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "Effect4Values", Type: ColInt, List: true},
		{Name: "GodName1", Type: ColString},
		{Name: "Effect2Values", Type: ColInt, List: true},
		{Name: "QuestFlags", Type: ColKey, RefTo: "QuestFlags"},
		{Name: "IsDisabled", Type: ColBool},
		{Name: "AchievementItems", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "LeagueQuestFlag1", Type: ColInt},
		{Name: "LeagueQuestFlag2", Type: ColInt},
		{Name: "LeagueQuestFlag3", Type: ColInt},
		{Name: "DowngradeFlag1", Type: ColKey, RefTo: "QuestFlags"},
		{Name: "DowngradeFlag2", Type: ColKey, RefTo: "QuestFlags"},
		{Name: "DowngradeFlag3", Type: ColKey, RefTo: "QuestFlags"},
	},
	"passivejewelradii": {
		{Name: "Id", Type: ColString},
		{Name: "RingOuter", Type: ColInt},
		{Name: "RingInner", Type: ColInt},
		{Name: "Radius", Type: ColInt},
		{Name: "Name", Type: ColKey, RefTo: "ClientStrings"},
	},
	"passivejewelradiiart": {
		{Name: "Id", Type: ColString},
		{Name: "Circle1", Type: ColString},
		{Name: "Circle2", Type: ColString},
		{Name: "Glow", Type: ColString},
	},
	"passivejewelslots": {
		{Name: "Passive", Type: ColKey, RefTo: "PassiveSkills"},
		{Name: "ClusterSize", Type: ColKey, RefTo: "PassiveTreeExpansionJewelSizes"},
		{Name: "ClusterIndex", Type: ColInt},
		{Name: "Parent", Type: ColShortKey, RefTo: "PassiveJewelSlots"},
		{Name: "Proxy", Type: ColKey, RefTo: "PassiveSkills"},
		{Name: "StartIndices", Type: ColInt, List: true},
		{Type: ColBool},
	},
	"passiveoverridelimits": {
		{Name: "Id", Type: ColString},
		{Name: "Description", Type: ColString},
		{Type: ColBool},
	},
	"passiveskillbuffs": {
		{Name: "Id", Type: ColString},
		{Type: ColFloat, List: true},
		{Name: "Buff", Type: ColKey, RefTo: "BuffDefinitions"},
		{Type: ColInt},
	},
	"passiveskillmasteryeffects": {
		{Name: "Id", Type: ColString},
		{Name: "Hash", Type: ColUInt16},
		{Name: "Stats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: ColInt},
		{Name: "Stat2", Type: ColInt},
		{Name: "Stat3", Type: ColInt},
		{Name: "AchievementItem", Type: ColKey, RefTo: "AchievementItems"},
		{Type: ColKey},
	},
	"passiveskillmasterygroups": {
		{Name: "Id", Type: ColString},
		{Name: "MasteryEffects", Type: ColKey, List: true, RefTo: "PassiveSkillMasteryEffects"},
		{Name: "IconInactive", Type: ColString},
		{Name: "IconActive", Type: ColString},
		{Name: "Background", Type: ColString},
		{Type: ColBool},
		{Name: "SoundEffect", Type: ColKey, RefTo: "SoundEffects"},
		{Name: "MasteryCount", Type: ColKey, RefTo: "Stats"},
	},
	"passiveskilloverrides": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
		{Name: "Icon", Type: ColString},
		{Name: "StatsKeys", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "StatValues", Type: ColInt, List: true},
		{Name: "Hash", Type: ColInt},
		{Name: "Background", Type: ColString},
		{Name: "GrantedEffect", Type: ColKey, RefTo: "GrantedEffectsPerLevel"},
		{Name: "OverrideType", Type: ColKey, RefTo: "passiveskilloverridetypes"},
		{Name: "Limit", Type: ColKey, RefTo: "passiveoverridelimits"},
		{Name: "MinimumConnected", Type: ColInt},
		{Name: "MaximumConnected", Type: ColInt},
		{Name: "PassiveSkill", Type: ColKey, RefTo: "PassiveSkills"},
		{Name: "BlockingPassive", Type: ColKey, List: true, RefTo: "PassiveSkills"},
	},
	"passiveskilloverridetypes": {
		{Name: "Id", Type: ColString},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Type: ColBool},
		{Type: ColBool},
	},
	"passiveskills": {
		{Name: "Id", Type: ColString},
		{Name: "Icon", Type: ColString},
		{Name: "Stats", Type: ColKey, List: true, RefTo: "Stats"},
		{Name: "Stat1", Type: ColInt},
		{Name: "Stat2", Type: ColInt},
		{Name: "Stat3", Type: ColInt},
		{Name: "Stat4", Type: ColInt},
		{Name: "PassiveSkillNodeId", Type: ColUInt16},
		{Name: "Name", Type: ColString},
		{Name: "ClassStart", Type: ColKey, List: true, RefTo: "Characters"},
		{Name: "Keystone", Type: ColBool},
		{Name: "Notable", Type: ColBool},
		{Name: "FlavourText", Type: ColString},
		{Name: "Mastery", Type: ColBool},
		{Name: "Achievement", Type: ColKey, RefTo: "AchievementItems"},
		{Name: "JewelSocket", Type: ColBool},
		{Name: "Ascendancy", Type: ColKey, RefTo: "Ascendancy"},
		{Name: "AscendancyStart", Type: ColBool},
		{Name: "ReminderTexts", Type: ColKey, List: true, RefTo: "ReminderText"},
		{Name: "PassivePointsGranted", Type: ColInt},
		{Name: "MultipleChoice", Type: ColBool},
		{Name: "MultipleChoiceOption", Type: ColBool},
		{Name: "Stat5", Type: ColInt},
		{Name: "Buffs", Type: ColKey, List: true, RefTo: "BuffTemplates"},
		{Name: "GrantedEffect", Type: ColKey, RefTo: "GrantedEffectsPerLevel"},
		{Name: "AnnointOnly", Type: ColBool},
		{Type: ColInt},
		{Name: "ClusterNode", Type: ColBool},
		{Name: "Proxy", Type: ColBool},
		{Name: "Type", Type: ColEnum, RefTo: "PassiveSkillTypes"},
		{Name: "MasteryGroup", Type: ColKey, RefTo: "PassiveSkillMasteryGroups"},
		{Name: "AtlasMastery_rid", Type: ColKey, RefTo: "AtlasPassiveSkillTreeGroupType"},
		{Name: "SoundEffect", Type: ColKey, RefTo: "SoundEffects"},
		{Name: "AtlasnodeGroup", Type: ColString},
		{Type: ColBool},
		{Name: "StatValue1", Type: ColInt},
		{Name: "StatValue2", Type: ColInt},
		{Name: "StatValue3", Type: ColInt},
		{Name: "StatValue4", Type: ColInt},
		{Name: "StatValue5", Type: ColInt},
		{Name: "Stat", Type: ColKey, List: true, RefTo: "Stats"},
		{Type: ColInt},
		{Name: "BuffTemplate", Type: ColKey, List: true, RefTo: "BuffTemplates"},
		{Type: ColBool},
		{Type: ColKey},
		{Name: "GrantedEffect", Type: ColKey, RefTo: "GrantedEffectsPerLevel"},
		{Type: ColKey},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
	},
	"passiveskillstatcategories": {
		{Name: "Id", Type: ColString},
		{Name: "Name", Type: ColString},
	},
	"passiveskilltattoos": {
		{Name: "BaseItem", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Override", Type: ColKey, RefTo: "passiveskilloverrides"},
		{Name: "NodeTarget", Type: ColKey, RefTo: "passiveskilltattootargetsets"},
		{Type: ColInt},
		{Type: ColKey},
	},
	"passiveskilltattootargetsets": {
		{Name: "Id", Type: ColString},
		{Type: ColInt, List: true},
		{Name: "Type", Type: ColString},
		{Name: "Value", Type: ColString},
	},
	"passiveskilltreeconnectionart": {
		{Name: "Id", Type: ColString},
		{Name: "Normal", Type: ColString},
		{Name: "Intermediate2", Type: ColString},
		{Name: "Intermediate", Type: ColString},
		{Name: "Active", Type: ColString},
		{Name: "Mask", Type: ColString},
		{Name: "Ornament1", Type: ColString},
		{Name: "Ornament2", Type: ColString},
	},
	"passiveskilltreenodeframeart": {
		{Name: "Id", Type: ColString},
		{Name: "Normal", Type: ColString},
		{Name: "CanAllocate", Type: ColString},
		{Name: "Active", Type: ColString},
		{Name: "Mask", Type: ColString},
		{Name: "Header", Type: ColString},
	},
	"passiveskilltypes": {
		{Name: "Id", Type: ColString},
	},
	"passivetreeexpansionjewels": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Size", Type: ColKey, RefTo: "PassiveTreeExpansionJewelSizes"},
		{Name: "MinNodes", Type: ColInt},
		{Name: "MaxNodes", Type: ColInt},
		{Name: "SmallIndicies", Type: ColInt, List: true},
		{Name: "NotableIndicies", Type: ColInt, List: true},
		{Name: "SocketIndicies", Type: ColInt, List: true},
		{Name: "TotalIndicies", Type: ColInt},
	},
	"passivetreeexpansionjewelsizes": {
		{Name: "Id", Type: ColString},
	},
	"passivetreeexpansionskills": {
		{Name: "Node", Type: ColKey, RefTo: "PassiveSkills"},
		{Name: "Mastery", Type: ColKey, RefTo: "PassiveSkills"},
		{Name: "Tag", Type: ColKey, RefTo: "Tags"},
		{Name: "JewelSize", Type: ColKey, RefTo: "PassiveTreeExpansionJewelSizes"},
	},
	"passivetreeexpansionspecialskills": {
		{Name: "Node", Type: ColKey, RefTo: "PassiveSkills"},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
	},
	"preloadgroups": {
		{Name: "Id", Type: ColString},
	},
	"projectiles": {
		{Name: "Id", Type: ColString},
		{Name: "AOFiles", Type: ColString, List: true},
		{Name: "LoopAnimationIds", Type: ColString, List: true},
		{Name: "ImpactAnimationIds", Type: ColString, List: true},
		{Name: "ProjectileSpeed", Type: ColInt},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "InheritsFrom", Type: ColString},
		{Type: ColInt},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "Stuck_AOFile", Type: ColString, List: true},
		{Name: "Bounce_AOFile", Type: ColString},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "PrimaryAnimation", Type: ColKey, RefTo: "MiscAnimated"},
		{Name: "SecondaryAnimation", Type: ColKey, RefTo: "MiscAnimated"},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColString, List: true},
		{Type: ColBool},
		{Type: ColInt, List: true},
		{Type: ColString},
	},
	"projectilesartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "Variant", Type: ColInt},
		{Name: "Projectile", Type: ColKey, List: true, RefTo: "Projectiles"},
		{Type: ColInt},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
	},
	"rarity": {
		{Name: "Id", Type: ColString},
		{Name: "MinMods", Type: ColInt},
		{Name: "MaxMods", Type: ColInt},
		{Type: ColInt},
		{Name: "MaxPrefix", Type: ColInt},
		{Type: ColInt},
		{Name: "MaxSuffix", Type: ColInt},
		{Name: "Colour", Type: ColString},
		{Type: ColString},
	},
	"remindertext": {
		{Name: "Id", Type: ColString},
		{Name: "Text", Type: ColString},
		{Name: "Text2", Type: ColString},
	},
	"shieldtypes": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Block", Type: ColInt},
	},
	"shrines": {
		{Name: "Id", Type: ColString},
		{Name: "Timeout", Type: ColInt},
		{Name: "Shared", Type: ColBool},
		{Name: "PlayerBuff", Type: ColKey, RefTo: "BuffTemplates"},
		{Name: "Weighting", Type: ColInt},
		{Name: "MinLevel", Type: ColInt},
		{Name: "MonsterBuff", Type: ColKey, RefTo: "BuffTemplates"},
		{Name: "MonsterVarieties", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "MonsterVarietiesPlayer", Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColInt},
		{Name: "Duration", Type: ColInt},
		{Name: "ShrineSounds", Type: ColKey, RefTo: "ShrineSounds"},
		{Type: ColBool},
		{Name: "Achievement", Type: ColKey, List: true, RefTo: "AchievementItems"},
		{Name: "PVPOnly", Type: ColBool},
		{Type: ColBool},
		{Name: "LesserShrine", Type: ColBool},
		{Name: "Description", Type: ColKey, RefTo: "ClientStrings"},
		{Name: "Name", Type: ColKey, RefTo: "ClientStrings"},
		{Name: "Royale", Type: ColBool},
		{Name: "TouchedMod", Type: ColKey, RefTo: "Mods"},
		{Name: "MonsterPack", Type: ColKey, List: true, RefTo: "MonsterPacks"},
	},
	"skillartvariations": {
		{Name: "Id", Type: ColString},
		{Name: "AnimatedArt", Type: ColKey, List: true, RefTo: "MiscAnimatedArtVariations"},
		{Name: "BeamArt", Type: ColKey, List: true, RefTo: "MiscBeamsArtVariations"},
		{Name: "EffectPacksArt", Type: ColKey, List: true, RefTo: "MiscEffectPacksArtVariations"},
		{Name: "ObjectArt", Type: ColKey, List: true, RefTo: "MiscObjectsArtVariations"},
		{Name: "Variants", Type: ColString, List: true},
		{Name: "BuffVisuals", Type: ColKey, List: true, RefTo: "BuffVisualsArtVariations"},
		{Name: "VariantID?", Type: ColInt, List: true},
		{Name: "ProjectileArt", Type: ColKey, List: true, RefTo: "ProjectilesArtVariations"},
		{Name: "Stat", Type: ColKey, RefTo: "Stats"},
		{Name: "MonsterVarietiesArt", Type: ColKey, List: true, RefTo: "MonsterVarietiesArtVariations"},
		{Name: "ActiveSkill", Type: ColKey, List: true, RefTo: "ActiveSkills"},
		{Name: "GrantedEffect", Type: ColKey, List: true, RefTo: "GrantedEffects"},
		{Type: ColKey, List: true},
	},
	"skillgems": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "Str", Type: ColInt},
		{Name: "Dex", Type: ColInt},
		{Name: "Int", Type: ColInt},
		{Name: "VaalGem", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "IsVaalGem", Type: ColBool},
		{Name: "MinionGlobalSkillLevelStat", Type: ColKey, RefTo: "Stats"},
		{Name: "IsSupport", Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Name: "Awakened", Type: ColShortKey, RefTo: "SkillGems"},
		{Name: "Regular", Type: ColShortKey, RefTo: "SkillGems"},
		{Name: "GemColour", Type: ColInt},
		{Name: "GemLevelProgression", Type: ColKey, RefTo: "ItemExperienceTypes"},
		{Name: "MtxSlotType", Type: ColKey, List: true, RefTo: "MicrotransactionSkillGemEffectSlotTypes"},
		{Name: "GemVariants", Type: ColKey, List: true, RefTo: "GemEffects"},
	},
	"skilltotemvariations": {
		{Name: "SkillTotem", Type: ColInt},
		{Name: "Variation", Type: ColInt},
		{Name: "MonsterVariety", Type: ColKey, RefTo: "MonsterVarieties"},
	},
	"soundeffects": {
		{Name: "Id", Type: ColString},
		{Type: ColString},
		{Type: ColString},
		{Type: ColBool},
		{Type: ColString},
	},
	"spectreoverrides": {
		{Name: "Monster", Type: ColKey, RefTo: "MonsterVarieties"},
		{Name: "Spectre", Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColKey, List: true},
	},
	"stats": {
		{Name: "Id", Type: ColString},
		{Name: "A", Type: ColBool},
		{Name: "Local", Type: ColBool},
		{Name: "WeaponLocal", Type: ColBool},
		{Name: "Semantic", Type: ColEnum, RefTo: "StatSemantics"},
		{Type: ColBool},
		{Name: "Virtual", Type: ColBool},
		{Name: "Main Hand Stat", Type: ColShortKey, RefTo: "Stats"},
		{Name: "Off Hand Stat", Type: ColShortKey, RefTo: "Stats"},
		{Type: ColBool},
		{Name: "Hash", Type: ColUInt},
		{Name: "Skills", Type: ColString, List: true},
		{Name: "PassiveCategory", Type: ColKey, RefTo: "PassiveSkillStatCategories"},
		{Name: "CannotGrantToMinion", Type: ColBool},
		{Type: ColBool},
		{Name: "IsScalable", Type: ColBool},
		{Name: "ContextFlags", Type: ColKey, List: true, RefTo: "VirtualStatContextFlags"},
		{Name: "DotFlag", Type: ColKey, List: true, RefTo: "VirtualStatContextFlags"},
	},
	"statsaffectinggeneration": {
		{Type: ColKey, RefTo: "Stats"},
		{Type: ColInt},
	},
	"statsfromskillstats": {
		{Type: ColKey},
		{Type: ColKey},
	},
	"suicideexplosion": {
		{Name: "Id", Type: ColInt},
		{Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColKey},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColBool},
	},
	"summonedspecificmonsters": {
		{Name: "Id", Type: ColInt},
		{Name: "MonsterVarietiesKey", Type: ColKey, RefTo: "MonsterVarieties"},
		{Type: ColInt},
		{Type: ColKey},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColKey},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColString},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
	},
	"tablecharge": {
		{Type: ColInt},
		{Type: ColFloat},
		{Type: ColFloat},
		{Type: ColBool},
		{Type: ColKey},
		{Type: ColBool},
		{Type: ColKey, List: true},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColKey},
		{Type: ColKey},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColBool},
		{Type: ColBool},
		{Type: ColInt},
	},
	"tags": {
		{Name: "Id", Type: ColString},
		{Name: "Hash", Type: ColUInt},
		{Name: "DisplayText", Type: ColString},
		{Name: "Text", Type: ColString},
	},
	"tinctures": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "ManaBurn", Type: ColInt},
		{Name: "CoolDown", Type: ColInt},
	},
	"trademarketimplicitmoddisplay": {
		{Type: ColKey},
		{Type: ColString},
	},
	"trademarketindexitemas": {
		{Name: "Item", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "IndexAs", Type: ColKey, RefTo: "BaseItemTypes"},
	},
	"uniquestashlayout": {
		{Name: "WordsKey", Type: ColKey, RefTo: "Words"},
		{Name: "ItemVisualIdentity", Type: ColKey, RefTo: "ItemVisualIdentity"},
		{Name: "UniqueStashTypes", Type: ColKey, RefTo: "UniqueStashTypes"},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "OverrideWidth", Type: ColInt},
		{Name: "OverrideHeight", Type: ColInt},
		{Name: "ShowIfEmptyChallengeLeague", Type: ColBool},
		{Name: "ShowIfEmptyStandard", Type: ColBool},
		{Name: "RenamedVersion", Type: ColShortKey, RefTo: "UniqueStashLayout"},
		{Name: "BaseVersion", Type: ColShortKey, RefTo: "UniqueStashLayout"},
		{Name: "IsAlternateArt", Type: ColBool},
	},
	"uniquestashtypes": {
		{Name: "Id", Type: ColString},
		{Name: "Order", Type: ColInt},
		{Name: "Width", Type: ColInt},
		{Name: "Height", Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "Name", Type: ColString},
		{Name: "StandardCount", Type: ColInt},
		{Name: "Image", Type: ColString},
		{Name: "ChallengeLeagueCount", Type: ColInt},
		{Name: "Disabled", Type: ColBool},
	},
	"villagebalanceperlevelshared": {
		{Name: "Level", Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Name: "GoldRespec", Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
		{Type: ColInt},
	},
	"villageuniquedisenchantvalues": {
		{Name: "Unique", Type: ColKey, RefTo: "Words.Text"},
		{Type: ColFloat},
	},
	"virtualstatcontextflags": {
		{Name: "Id", Type: ColString},
		{Type: ColInt},
	},
	"weaponclasses": {
		{Name: "ItemClass", Type: ColKey, RefTo: "ItemClasses"},
		{Name: "MaxRange", Type: ColInt},
	},
	"weaponpassiveskills": {
		{Name: "Id", Type: ColString},
		{Name: "ModTier", Type: ColInt},
		{Name: "Mod", Type: ColKey, RefTo: "Mods"},
		{Name: "NodeSpawnLocation", Type: ColInt, List: true},
		{Name: "Tags", Type: ColKey, List: true, RefTo: "CrucibleTags"},
		{Name: "ArtFilepath", Type: ColString},
		{Name: "Type", Type: ColKey, RefTo: "WeaponPassiveSkillTypes"},
		{Name: "Achievements", Type: ColKey, List: true, RefTo: "AchievementItems"},
	},
	"weaponpassiveskilltypes": {
		{Name: "Id", Type: ColString},
		{Type: ColInt},
	},
	"weaponpassivetreebalanceperitemlevel": {
		{Name: "ItemLevel", Type: ColInt},
		{Name: "XPNode1", Type: ColInt},
		{Name: "XPNode2", Type: ColInt},
		{Name: "XPNode3", Type: ColInt},
		{Name: "XPNode4", Type: ColInt},
		{Name: "XPNode5", Type: ColInt},
	},
	"weaponpassivetreeuniquebasetypes": {
		{Name: "UniqueBase", Type: ColKey, RefTo: "BaseItemTypes"},
		{Type: ColInt},
	},
	"weapontypes": {
		{Name: "BaseItemType", Type: ColKey, RefTo: "BaseItemTypes"},
		{Name: "CritChance", Type: ColInt},
		{Name: "Speed", Type: ColInt},
		{Name: "DamageMin", Type: ColInt},
		{Name: "DamageMax", Type: ColInt},
		{Name: "Range", Type: ColInt},
		{Type: ColInt},
	},
	"words": {
		{Name: "Wordlist", Type: ColInt},
		{Name: "Text", Type: ColString},
		{Name: "SpawnWeight_Tags", Type: ColKey, List: true, RefTo: "Tags"},
		{Name: "SpawnWeight_Values", Type: ColInt, List: true},
		{Name: "HASH32", Type: ColInt},
		{Name: "Text2", Type: ColString},
		{Name: "Gender", Type: ColString},
	},
	"worldareas": {
		{Type: ColString},
	},
}
