package test

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"sync"
	"testing"

	"github.com/MissingL-tter/missingPassives/data"
	"github.com/MissingL-tter/missingPassives/modparser"
)

// readStatMapCopies parses the skills.statMapKeys fixture record from
// the game-data dump (the canon string is itself JSON with arrays as
// {"1": ..} objects). Panics on malformed fixtures (runs under sync.Once).
func readStatMapCopies(dumpPath string) map[string][]string {
	f, err := os.Open(dumpPath)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<28)
	for sc.Scan() {
		var rec struct {
			K string `json:"k"`
			C string `json:"c"`
		}
		if err := json.Unmarshal(sc.Bytes(), &rec); err != nil {
			panic(err)
		}
		if rec.K != "skills.statMapKeys" {
			continue
		}
		var raw map[string]map[string]string
		if err := json.Unmarshal([]byte(rec.C), &raw); err != nil {
			panic("statMapKeys fixture: " + err.Error())
		}
		out := map[string][]string{}
		for id, keys := range raw {
			list := make([]string, len(keys))
			for idx, key := range keys {
				n, err := strconv.Atoi(idx)
				if err != nil || n < 1 || n > len(keys) {
					panic("statMapKeys fixture: bad index " + idx)
				}
				list[n-1] = key
			}
			out[id] = list
		}
		return out
	}
	return map[string][]string{}
}

var (
	gameDataOnce sync.Once
	gameDataDone bool
	gameDataSkip string
	gameDataFail string
)

// loadData populates the package-level data set once per test binary,
// from the embedded raw documents (data/raw, regenerated by pobexport).
// Skips only when the game-data archive dump (source of the statMap replay
// fixture) is missing.
func loadData(t *testing.T) {
	t.Helper()
	gameDataOnce.Do(func() {
		dumpPath := filepath.Join("testdata", "gamedata_archive.jsonl")
		if _, err := os.Stat(dumpPath); err != nil {
			gameDataSkip = "archive dump not present: " + err.Error()
			return
		}
		src := data.RawSources()
		src.StatMapCopies = readStatMapCopies(dumpPath)
		data.Load(src)
		gameDataDone = true
	})
	// A parser-level differential may have switched the parser to fresh
	// mode (SetModCache(nil), mirroring its dump's wipeTable); re-arm the
	// shipped cache for data-driven tests.
	modparser.SetModCache(data.LoadedModCache)
	if gameDataSkip != "" {
		t.Skip(gameDataSkip)
	}
	if gameDataFail != "" {
		t.Fatal(gameDataFail)
	}
}
