package test

// Verifies luaPairsIntKeys against the shipped luajit's actual pairs()
// order over the domain the GV additions merge uses (keys 0..37, up to 4
// distinct keys): every sequence of length 1-3 plus 200k pseudo-random
// length-4 sequences, generated by tools/gen_pairs_orders.lua.

import (
	"bufio"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestLuaPairsAgainstLuaJIT(t *testing.T) {
	f, err := os.Open(filepath.Join("testdata", "pairs_orders.txt"))
	if err != nil {
		t.Skipf("pairs_orders.txt not present (run tools/gen_pairs_orders.lua): %v", err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	checked, bad := 0, 0
	for sc.Scan() {
		parts := strings.SplitN(sc.Text(), "|", 2)
		var seq []int
		for _, s := range strings.Fields(parts[0]) {
			n, _ := strconv.Atoi(s)
			seq = append(seq, n)
		}
		want := strings.Split(parts[1], ",")
		got := luaPairsIntKeys(seq)
		ok := len(got) == len(want)
		if ok {
			for i := range got {
				if strconv.Itoa(got[i]) != want[i] {
					ok = false
					break
				}
			}
		}
		if !ok {
			bad++
			if bad <= 10 {
				t.Errorf("seq %v: got %v want %v", seq, got, want)
			}
		}
		checked++
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if checked < 250000 {
		t.Fatalf("fixture looks truncated: %d sequences", checked)
	}
	t.Logf("pairs order: %d sequences identical to luajit (%d mismatched)", checked, bad)
	if bad > 0 {
		t.Fail()
	}
}
