-- Regenerates data/gems.md AND data/gems.db from one collection pass.
-- Run from src/ (sqlite3 must be on PATH):
--   luajit ../.claude/skills/cook/tools/dump-gems.lua
--
-- Obtainability source of truth: grantedEffect.legacy, the flag GemTooltip.lua renders as
-- "Gem only exists in Standard League". It lives in Data/Skills/sup_*.lua; the tags live
-- in Data/Gems.lua. Legacy gems reach neither output - every db row is obtainable.
-- Numeric stats are snapshotted at the gem's natural max level.
local pob = dofile("../.claude/skills/cook/tools/pob.lua")
local data = pob.data()
local OUT = "../.claude/skills/cook/data/"
local q, qn, num = pob.q, pob.qn, pob.num

local function isLegacy(gd)
	local ge, ge2 = gd.grantedEffect, gd.secondaryGrantedEffect
	return ((ge and ge.legacy) or (ge2 and ge2.legacy)) and true or false
end

-- Highest defined level at or below the natural max.
local function atMaxLevel(gd)
	local ge = gd.grantedEffect
	if not ge or not ge.levels then return {} end
	for i = gd.naturalMaxLevel or 20, 1, -1 do
		if ge.levels[i] then return ge.levels[i] end
	end
	return {}
end

------------------------------------------------------------------ collect
local all, byGrantedId, nLegacy = {}, {}, 0
local keys = {}
for k in pairs(data.gems) do keys[#keys + 1] = k end
table.sort(keys)
for _, k in ipairs(keys) do
	local gd = data.gems[k]
	if gd.name then
		if gd.grantedEffect and gd.grantedEffect.id then byGrantedId[gd.grantedEffect.id] = gd end
		if isLegacy(gd) then nLegacy = nLegacy + 1 else all[#all + 1] = gd end
	end
end
table.sort(all, function(a, b)
	if a.name ~= b.name then return a.name < b.name end
	return (a.variantId or "") < (b.variantId or "")
end)

-- plusVersionOf: upgraded support tiers, both directions, obtainable-only (all[] is filtered)
local upgradeOf, upgradedVersion, nUpgrades = {}, {}, 0
for _, gd in ipairs(all) do
	local ge = gd.grantedEffect
	if ge and ge.plusVersionOf then
		local base = byGrantedId[ge.plusVersionOf]
		if base and not isLegacy(base) then
			upgradeOf[gd] = base.name
			upgradedVersion[base.name] = gd.name
			nUpgrades = nUpgrades + 1
		end
	end
end

local treeVersion = tostring(_G.build.spec.treeVersion):gsub("_", ".")

------------------------------------------------------------------ gems.md
local f = assert(io.open(OUT .. "gems.md", "w+"))
local function w(fmt, ...)
	f:write(select("#", ...) > 0 and string.format(fmt, ...) or fmt, "\n")
end

w("<!-- GENERATED by .claude/skills/cook/tools/dump-gems.lua - do not hand-edit -->")
w("# Gems\n")
w("_Generated from PoB tree data `%s`. Regenerate after any data update - this script",
	treeVersion)
w("rebuilds `gems.db` too._\n")
w("A gem may be used IF AND ONLY IF it has a row in `data/gems.db` - the %d legacy gems",
	nLegacy)
w("are excluded at generation. Memory-sourced names are hypotheses - one query settles")
w("existence and legality together; zero rows, for any reason, means no. Nothing in")
w("PoB's UI or file format stops you picking an unobtainable gem - check while choosing;")
w("`validate.lua` catches it after the fact, when it costs a rebuild.\n")

w("## Querying gems.db\n")
w("Run `sqlite3` with paths from the repo root (from `src/`, prefix `../`). Names use")
w("PoB's convention: supports carry no \"Support\" suffix (`Melee Physical Damage`). For")
w("a gem's full behaviour beyond the columns, grep its entry in")
w("`src/Data/Skills/act_*.lua` / `sup_*.lua`.\n")
w("- `gems(id, name, variant_id, kind, vaal, color, max_level, req_level, cast_time,")
w("  crit_chance, dmg_effectiveness, cost, cost_multiplier, tag_string, description,")
w("  upgrade_of, upgraded_version)` - kind `active|support`; color `R|G|B|W`;")
w("  `variant_id` is the skillId build XMLs reference. Numeric stats are snapshots at")
w("  `max_level`: `req_level` = character level needed there, `cost` like `Mana=25` /")
w("  `Soul=30`, `cost_multiplier` is the support's total % (130 = 30% more, NULL = no")
w("  multiplier - reservation-style supports). NULL `crit_chance`/`dmg_effectiveness`")
w("  on actives = field does not apply (attacks use weapon crit; DoTs have no")
w("  effectiveness).")
w("- `gem_tags(gem_id, tag)` - lowercase game tags, one per row; AND tags by joining")
w("  `gem_tags` once per required tag.")
w("- `meta(key, value)` - `tree_version`, `generated_at`.\n")
w("Canonical queries:\n")
w("```sh")
w("DB=.claude/skills/cook/data/gems.db")
w("# existence - zero rows means DO NOT USE, whatever the reason")
w("sqlite3 $DB \"SELECT id, kind, max_level FROM gems WHERE name='Frostmage';\"")
w("# mana-tight builds: supports at low cost multiplier")
w("sqlite3 $DB \"SELECT name, cost_multiplier FROM gems WHERE kind='support'")
w("  AND cost_multiplier <= 110;\"")
w("# tag AND: triggerable spells")
w("sqlite3 $DB \"SELECT g.name FROM gems g")
w("  JOIN gem_tags t1 ON t1.gem_id=g.id AND t1.tag='spell'")
w("  JOIN gem_tags t2 ON t2.gem_id=g.id AND t2.tag='trigger' WHERE g.kind='active';\"")
w("```\n")

w("## Upgraded support tiers\n")
w("`grantedEffect.plusVersionOf` links a support to its upgraded version - in the db,")
w("`upgraded_version` (and `upgrade_of` as the reverse link). %d supports have an",
	nUpgrades)
w("obtainable upgrade; NULL `upgraded_version` means none exists, so do not go looking")
w("for one. Most upgrades are a renamed gem rather than an `Awakened *` one - that")
w("line is gone bar Empower, Enhance and Enlighten. An upgrade beats its base at every")
w("level, so prefer it whenever it exists.\n")
w("```sh")
w("sqlite3 $DB \"SELECT name, upgraded_version FROM gems WHERE upgraded_version IS NOT NULL;\"")
w("```\n")

w("## Level caps\n")
w("Every gem can be corrupted to one level above its natural max, with no exceptions.")
w("Cap is always `naturalMaxLevel + 1`; per-gem natural maxes are the `max_level` column.")
f:close()

------------------------------------------------------------------ gems.db
local nActive, nSupport = 0, 0
pob.buildDb(OUT .. "gems.db", function(w)
	w([[
PRAGMA journal_mode=OFF;
BEGIN;
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE gems (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	variant_id TEXT,
	kind TEXT NOT NULL,
	vaal INTEGER NOT NULL,
	color TEXT NOT NULL,
	max_level INTEGER NOT NULL,
	req_level INTEGER,
	cast_time REAL,
	crit_chance REAL,
	dmg_effectiveness REAL,
	cost TEXT,
	cost_multiplier INTEGER,
	tag_string TEXT,
	description TEXT,
	upgrade_of TEXT,
	upgraded_version TEXT
);
CREATE TABLE gem_tags (
	gem_id INTEGER NOT NULL REFERENCES gems(id),
	tag TEXT NOT NULL,
	PRIMARY KEY (gem_id, tag)
);]])

	local colors = { [1] = "R", [2] = "G", [3] = "B" }
	for id, gd in ipairs(all) do
		local ge = gd.grantedEffect or {}
		local lvl = atMaxLevel(gd)
		local support = ge.support and true or false
		if support then nSupport = nSupport + 1 else nActive = nActive + 1 end

		local cost
		if not support and type(lvl.cost) == "table" then
			local parts, ck = {}, {}
			for k in pairs(lvl.cost) do ck[#ck + 1] = k end
			table.sort(ck)
			for _, k in ipairs(ck) do parts[#parts + 1] = k .. "=" .. tostring(lvl.cost[k]) end
			if #parts > 0 then cost = table.concat(parts, ", ") end
		end

		w(("INSERT INTO gems VALUES (%d, %s, %s, %s, %d, %s, %d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"):format(
			id, q(gd.name), qn(gd.variantId), q(support and "support" or "active"),
			gd.vaalGem and 1 or 0, q(colors[ge.color] or "W"),
			gd.naturalMaxLevel or 20, num(lvl.levelRequirement),
			support and "NULL" or num(ge.castTime),
			support and "NULL" or num(lvl.critChance),
			support and "NULL" or num(lvl.damageEffectiveness),
			qn(cost),
			support and num(lvl.manaMultiplier and (100 + lvl.manaMultiplier)) or "NULL",
			qn(gd.tagString and gd.tagString:gsub("|", "/")),
			qn(ge.description and ge.description:gsub("\n", " ")),
			qn(upgradeOf[gd]), qn(upgradedVersion[gd.name])))

		local tags = {}
		for tag, on in pairs(gd.tags or {}) do if on then tags[#tags + 1] = tag end end
		table.sort(tags)
		for _, tag in ipairs(tags) do
			w(("INSERT INTO gem_tags VALUES (%d, %s);"):format(id, q(tag)))
		end
	end

	w(("INSERT INTO meta VALUES ('tree_version', %s);"):format(q(treeVersion)))
	w(("INSERT INTO meta VALUES ('generated_at', %s);"):format(q(os.date("!%Y-%m-%d"))))
	w("INSERT INTO meta VALUES ('generator', 'dump-gems.lua');")
	w([[
CREATE INDEX idx_gems_name ON gems(name);
CREATE INDEX idx_gems_kind ON gems(kind);
CREATE INDEX idx_gem_tags_tag ON gem_tags(tag);
COMMIT;]])
end)

print(string.format("wrote gems.md + gems.db: %d gems (%d active, %d support, %d legacy excluded), %d upgraded tiers, tree %s",
	#all, nActive, nSupport, nLegacy, nUpgrades, treeVersion))
