-- Regenerates data/jewels.md: every jewel that MODIFIES the passive tree - cluster jewels
-- (sizes, skills, notables, authoring), historic/timeless jewels (seeds, conquests), and
-- radius/rule-changing jewels. Plain stat jewels are ordinary affix items - affixes.lua.
-- Run from src/:
--   luajit ../.claude/skills/cook/tools/dump-jewels.lua
--
-- Sources: data.clusterJewels + Data/ModJewelCluster + tree.clusterNodeMap (cluster section);
-- data.uniques.jewel raw text (historic + radius sections); data.timelessJewelSeedMin/Max;
-- PassiveSpec.lua:1098+ conquest semantics, verified headless (see prose).
local pob = dofile("../.claude/skills/cook/tools/pob.lua")
local data = pob.data()
local tree = _G.build.spec.tree
local clusterMods = LoadModule("Data/ModJewelCluster")

local out = assert(io.open("../.claude/skills/cook/data/jewels.md", "w+"))
local emit = print
local function print(line) out:write(tostring(line), "\n") end

print("<!-- GENERATED by .claude/skills/cook/tools/dump-jewels.lua - do not hand-edit -->")
print("# Jewels that modify the tree\n")
print(string.format("_Generated from PoB tree data `%s`. Regenerate after any data update._\n",
	tostring(tree.treeVersion):gsub("_", ".")))
print([[
Three families rewrite the passive tree itself: cluster jewels grow new nodes, historic
jewels transform existing ones by seed, and a handful of radius/rule jewels transform,
re-grant or re-wire what is already there. Plain stat jewels are ordinary affix items -
`affixes.lua "Cobalt Jewel"` etc.
]])

------------------------------------------------------------------ cluster jewels
print([[
# Cluster jewels

Cluster jewels socket into the tree's outer rim and grow new passive nodes. The
subgraph PoB builds always matches the in-game structure.

## Mechanics, verified headless

- Only rim sockets take a Large jewel: `node.expansionJewel.size == 2`
  (`PassiveSpec.lua:1764`). Every rim socket costs ~2 travel + the socket itself.
- Subgraph nodes are real allocated nodes: they count toward the 122+extras passive
  budget (`CountAllocNodes`), and `validate.lua`'s tree check covers them.
- The jewel's skill, node count AND socket count come from its ENCHANT lines, parsed by
  exact text (`ModParser.lua:6544`, `:5199`). The `Cluster Jewel Skill:`/`Node Count:`
  properties are only crafting-UI state - without the enchant lines the subgraph never
  builds, and without the socket enchant line no socket nodes grow.
- Notables come from the generated "1 Added Passive Skill is X" lines, so an uncrafted
  jewel builds a subgraph of only small passives. Run `craft.lua`, as with every
  authored item.
- Notable legality = spawn weight with the jewel's skill tag passed as an include tag
  (`ItemsTab.lua:2150`); `affixes.lua --skill=<tag>` and `validate.lua` both do this.

## Nested sockets

Every Large carries "2 Added Passive Skills are Jewel Sockets", every Medium
"1 Added Passive Skill is a Jewel Socket", Smalls none - author these enchant lines,
they are part of the node count (smalls = count - sockets - notables). A nested socket
takes a smaller cluster jewel (Large holds Medium/Small, Medium holds Small) OR any
regular jewel, abyss jewels included - the one place a plain abyss jewel fits a tree
socket. Abyss HISTORICS are the reverse: their conquest data is keyed to base tree
sockets only, so nested placement does nothing (verified: zero conquered nodes).

This is the quiet half of cluster value: a nested socket is a 1-point jewel socket
where tree sockets cost 2-3. Nested socket nodes get STABLE tree ids (proxy nodes, not
generated ids) - craft, load, read the ids off the subgraph, then reference them in
`Spec/Sockets` like any socket. Verified round-trip: save and reload reproduce the
same ids, figures identical; `validate.lua` checks jewels in nested sockets like any
other slot.

## Authoring recipe (proven)

```
Rarity: RARE
Some Name
Large Cluster Jewel
Crafted: true
Item Level: 84
Cluster Jewel Skill: affliction_fire_damage
Cluster Jewel Node Count: 8
Prefix: {range:0.85}AfflictionNotablePrismaticHeart__
Prefix: {range:0.85}AfflictionNotableSmokingRemains
Implicits: 3
{enchant}Adds 8 Passive Skills
{enchant}2 Added Passive Skills are Jewel Sockets
{enchant}Added Small Passive Skills grant: 12% increased Fire Damage
```

The last enchant line must be the skill's exact enchant text from the tables below.
Socket via `<Socket nodeId="..." itemId="..."/>` on a rim socket, allocate the socket
node, then the subgraph nodes (generated ids land in the saved `nodes` list and reload
cleanly). Craft first, then allocate - notables only exist after crafting.

## Stat-stick clusters

Notables are not the only design. The `AfflictionJewelSmallPassivesGrant*` prefixes add
a stat to EVERY small ("Added Small Passive Skills also grant: ..."), and
`AfflictionJewelSmallPassivesHaveIncreasedEffect2` multiplies all of it by 35%. A
12-passive Large with no notables and three "also grant" mods is 12 custom-designed
small passives - e.g. life + attributes + armour on every node. `affixes.lua
"<size> Cluster Jewel" --skill=<tag>` lists these alongside the notables.

## Point economics

A jewel is worth `socket path (~3) + smalls walked + notables taken` points. Compare
against the tree wheel it replaces: smalls only pay if the enchant stat is live (a
15%-crit small is dead at 100% crit), so count notables per point, not nodes per point,
and count nested sockets as saved points against the 2-3 a tree socket costs.

Measured on the 3.29 CoC Blazing Salvo build (7.03m baseline):

- Medium crit (Pressure Points + Eye of the Storm): 7 points, +351k = 50k/pt -
  crit capped, so all four 15%-crit smalls were dead.
- Large fire (Prismatic Heart + Smoking Remains), no sockets: 8 points, +831k =
  104k/pt - 12%-fire smalls live, on par with the tree's last picks (~120-290k/pt).
- Same Large with its 2 sockets holding a Medium crit cluster and an ES/fire abyss
  jewel: 13 points, +1.88m and +136 ES = 145k/pt - the nested sockets beat everything.
]])

------------------------------------------------------------------ cluster sizes
print("## Sizes\n")
print("| size | nodes | sockets | socket enchant line |")
print("|---|---|---|---|")
local sizeOrder = { "Large Cluster Jewel", "Medium Cluster Jewel", "Small Cluster Jewel" }
local sizeSockets = {
	["Large Cluster Jewel"] = { 2, "2 Added Passive Skills are Jewel Sockets" },
	["Medium Cluster Jewel"] = { 1, "1 Added Passive Skill is a Jewel Socket" },
	["Small Cluster Jewel"] = { 0, "-" },
}
for _, name in ipairs(sizeOrder) do
	local j = data.clusterJewels.jewels[name]
	if j then
		print(string.format("| %s | %d-%d | %d | %s |", name, j.minNodes, j.maxNodes,
			sizeSockets[name][1], sizeSockets[name][2]))
	end
end
print("")

for _, name in ipairs(sizeOrder) do
	local j = data.clusterJewels.jewels[name]
	if j then
		print(string.format("## %s skills\n", name))
		print("| skill tag | small passive grants | enchant line for authoring |")
		print("|---|---|---|")
		local ids = {}
		for id in pairs(j.skills) do ids[#ids + 1] = id end
		table.sort(ids)
		for _, id in ipairs(ids) do
			local sk = j.skills[id]
			print(string.format("| %s | %s | %s |", id,
				table.concat(sk.stats or {}, " / "), table.concat(sk.enchant or {}, " / ")))
		end
		print("")
	end
end

print("## Not obtainable\n")
print("Removed from the game over the years; PoB keeps them at spawn weight 0, so")
print("`affixes.lua` never lists them and `validate.lua` rejects them by weight.")
print("Listed so their names do not tempt from old guides.\n")
local removed = {}
for id, mod in pairs(clusterMods) do
	local notable = (mod[1] or ""):match("^1 Added Passive Skill is (.+)$")
	if notable then
		local anyWeight = false
		for i, v in ipairs(mod.weightVal or {}) do
			if (mod.weightKey[i] or "") ~= "default" and v > 0 then anyWeight = true break end
		end
		if not anyWeight then removed[#removed + 1] = notable end
	end
end
table.sort(removed)
for _, name in ipairs(removed) do print("- " .. name) end
print("")

print("## Notables\n")
print("Grouped by the skill tags that can roll them; grep by tag or by stat. Weights")
print("are relative within the tag's pool. Stats come from the tree's own nodes.\n")
local byTag = {}
for id, mod in pairs(clusterMods) do
	if id:match("^AfflictionNotable") and mod.weightKey then
		local notable = (mod[1] or ""):match("^1 Added Passive Skill is (.+)$")
		if notable then
			for i, key in ipairs(mod.weightKey) do
				if key ~= "default" and (mod.weightVal[i] or 0) > 0 then
					byTag[key] = byTag[key] or {}
					table.insert(byTag[key], { id = id, name = notable, w = mod.weightVal[i] })
				end
			end
		end
	end
end
local tags = {}
for t in pairs(byTag) do tags[#tags + 1] = t end
table.sort(tags)
local nNotables = 0
for _, t in ipairs(tags) do
	print(string.format("### %s\n", t))
	print("| notable | weight | id | stats |")
	print("|---|---|---|---|")
	table.sort(byTag[t], function(a, b) return a.name < b.name end)
	for _, e in ipairs(byTag[t]) do
		local node = tree.clusterNodeMap[e.name]
		local stats = node and table.concat(node.sd or {}, " / "):gsub("|", "/") or "?"
		print(string.format("| %s | %d | %s | %s |", e.name, e.w, e.id, stats))
		nNotables = nNotables + 1
	end
	print("")
end

------------------------------------------------------------------ parse unique jewels
local knownProps = {
	["League"] = true, ["Source"] = true, ["Radius"] = true, ["Limited to"] = true,
	["Requires Level"] = true, ["Selected Variant"] = true, ["Selected Alt Variant"] = true,
	["Selected Alt Variant Two"] = true, ["Has Alt Variant"] = true, ["Has Alt Variant Two"] = true,
	["Item Level"] = true, ["LevelReq"] = true, ["Upgrade"] = true, ["Implicits"] = true,
}
local function parseUnique(raw)
	local u = { props = {}, variants = {}, mods = {} }
	local first = true
	for line in raw:gmatch("[^\r\n]+") do
		if first then u.name = line; first = false
		elseif not u.base and not line:match(":") then u.base = line
		else
			local variant = line:match("^Variant: (.+)$")
			local prop, val = line:match("^([%a][%w%s]-): (.+)$")
			if variant then table.insert(u.variants, variant)
			elseif prop and knownProps[prop] then u.props[prop] = val
			else table.insert(u.mods, line) end
		end
	end
	u.text = table.concat(u.mods, "\n")
	return u
end
local jewels = {}
for _, raw in ipairs(data.uniques.jewel or {}) do
	table.insert(jewels, parseUnique(raw))
end

------------------------------------------------------------------ historics
print([[
# Historic jewels

Seed-based node transformation. **The whole character gets ONE historic** - all eleven
carry `Limited to: 1 Historic`. PoB enforces it silently: the first-socketed jewel wins,
every later one gets `item.jewelData.limitDisabled = true` and contributes nothing.
Check that flag when a historic seems dead.

## The six radius timeless jewels

Socket in any tree socket; every node in Large radius is conquered. What happens then
(PassiveSpec.lua:1191+, verified headless):

- **Keystones** become the conqueror's keystone - fixed by VARIANT, the seed never
  matters. The keystone is the parenthesised name in the tables below.
- **Notables** roll on the seed: replaced by a legion notable or given legion additions.
  Sweep seeds by measuring; there is no shortcut reasoning.
- **Small passives** are deterministic per legion:

| legion | small passives | attribute smalls |
|---|---|---|
| Karui (Lethal Pride) | keep stats, +4 Strength | +2 Strength |
| Maraketh (Brutal Restraint) | keep stats, +4 Dexterity | +2 Dexterity |
| Kalguur (Heroic Tragedy) | keep stats, +2% increased Ward | +1% Ward |
| Templar (Militant Faith) | keep stats, +5 Devotion | replaced by +10 Devotion node |
| Eternal (Elegant Hubris) | REPLACED BY BLANK - stats wiped | blanked too |
| Vaal (Glorious Vanity) | rerolled from seed - anything | rerolled |
]])

local timeless = {}
local abyssHist = {}
for _, u in ipairs(jewels) do
	if u.props["Limited to"] == "1 Historic" then
		if u.base == "Timeless Jewel" then table.insert(timeless, u)
		else table.insert(abyssHist, u) end
	end
end
table.sort(timeless, function(a, b) return a.name < b.name end)
table.sort(abyssHist, function(a, b) return a.name < b.name end)

print("| jewel | legion | seed (item text) | conquerors -> keystone granted |")
print("|---|---|---|---|")
for _, u in ipairs(timeless) do
	local legion = (u.text:match("Conquered by the ([%a ]+)") or "?"):gsub("%s+$", "")
	local seed = u.text:match("%((%d+%-%d+)%)")
	local cq = {}
	for _, v in ipairs(u.variants) do
		local who, keystone = v:match("^([%a]+) %((.+)%)$")
		if who then
			if v:match("Pre %d") then
				table.insert(cq, who .. " -> " .. keystone:gsub("%) %(Pre.*", "") .. " LEGACY, not obtainable")
			else
				table.insert(cq, who .. " -> " .. keystone)
			end
		end
	end
	print(string.format("| %s | %s | %s | %s |", u.name, legion or "?", seed or "?",
		table.concat(cq, "; ")))
end
print([[

Elegant Hubris item-text seeds run 2000-160000 in steps of 20; internally PoB divides by
20 (seed ranges validated against `data.timelessJewelSeedMin/Max`). Selecting a LEGACY
conqueror variant fails `validate.lua`'s unique check.

Militant Faith additionally has two selectable devotion mods (`Has Alt Variant` /
`Has Alt Variant Two` + `Selected Alt Variant:`/`Selected Alt Variant Two:`), chosen from:
]])
for _, u in ipairs(timeless) do
	if u.name == "Militant Faith" then
		local seen = {}
		for _, m in ipairs(u.mods) do
			local devo = m:match("^{variant:%d+}(.*per 10 Devotion.*)$")
			if devo and not seen[devo] then seen[devo] = true; print("- " .. devo) end
		end
	end
end

print([[

## The five abyss historics

Abyss jewel bases; their conquest data is keyed to **base tree sockets only** - in a
cluster jewel's nested socket they conquer nothing (verified), and they have no other
stats, so nested placement is fully dead. The conquered set is baked per (seed, socket)
in the LUT: nodes near the socket are wholesale REPLACED with new abyss identities
(smalls and notables both; verified 58 nodes from one socket). Zorath's jewel instead
conquers the nodes along your CURRENT shortest allocated path from its socket to the
class start - reallocate the tree and the conquest moves with it (verified, 6 nodes).
]])
print("| jewel | base | lord | seed |")
print("|---|---|---|---|")
for _, u in ipairs(abyssHist) do
	local lord = u.text:match("thrall of ([%a]+)") or u.text:match("sustain ([%a]+)")
	local seed = u.text:match("%((%d+%-%d+)%)")
	print(string.format("| %s | %s | %s | %s |", u.name, u.base or "?", lord or "?", seed or "?"))
end

print([[

## Authoring and measuring historics headless

```
Rarity: UNIQUE
Lethal Pride
Timeless Jewel
Limited to: 1 Historic
Radius: Large
Implicits: 0
Commanded leadership over 12000 warriors under Kaom
Passives in radius are Conquered by the Karui
Historic
```

Write the seed line CONCRETE (validate checks it in range against the current variants).
Socket, refresh, then read `node.conqueredBy` / `node.sd` off the spec - conquests are
recomputed inside `BuildAllDependsAndPaths`, so they are always current. Seed hunting is
a sweep: loop seeds, edit the one number in the raw, re-parse, refresh, measure - or
call `data.readLUT(seed, nodeId, jewelType)` directly for a single node's outcomes
(types 1-6 in `data.timelessJewelTypes` order).

The LUTs ship as zlib streams (`src/Data/TimelessJewelData/*.zip*`, multi-part files
concatenated). HeadlessWrapper stubs `Inflate`/`Deflate` to return `""`; the kitchen's
`pob.lua` rebinds both through `runtime/zlib1.dll`, without which every notable reports
`Missing LUT` and abyss jewels CRASH the calc on socketing. First legion-jewel load also
rewrites the `.bin` caches the GUI uses; abyss data (~28 MB compressed each) is inflated
once per process and cached in memory only.
]])

------------------------------------------------------------------ radius / rule jewels
print([[
# Radius and rule-changing jewels

Obtainable uniques that transform, re-grant or re-wire existing nodes (plain "per X in
Radius" counters just READ the tree and are excluded). Multi-variant lines are shown as
the variant list.
]])

local groups = {
	{ key = "alsoGrant", title = "Radius auras - every allocated passive in radius also grants the stat",
	  match = function(t) return t:match("in Radius also grant") end },
	{ key = "transform", title = "Transformers - modifiers in radius become other modifiers",
	  match = function(t) return t:match("Transformed") end },
	{ key = "regrant", title = "Effect rewriters - nodes in radius grant more, less or nothing",
	  match = function(t) return (t:match("increased Effect of") and t:match("Radius"))
		or t:match("grant nothing") or t:match("Unallocated Small Passive") end },
	{ key = "rewire", title = "Allocation re-wiring - allocate without connection",
	  match = function(t) return t:match("can be Allocated without being connected")
		or t:match("Passives in Radius of") end },
	{ key = "position", title = "Socket-position jewels - scale on where the socket sits",
	  match = function(t) return t:match("connects to a class' starting location")
		or t:match("your Class' starting location") end },
}
local used = {}
for _, g in ipairs(groups) do
	local rows = {}
	for _, u in ipairs(jewels) do
		if not used[u.name] and not (u.props["Source"] or ""):match("No longer obtainable")
		   and u.props["Limited to"] ~= "1 Historic" and g.match(u.text) then
			used[u.name] = true
			table.insert(rows, u)
		end
	end
	if #rows > 0 then
		table.sort(rows, function(a, b) return a.name < b.name end)
		print("## " .. g.title .. "\n")
		for _, u in ipairs(rows) do
			local bits = {}
			if u.props["Radius"] then table.insert(bits, "radius " .. u.props["Radius"]) end
			if u.props["Limited to"] then table.insert(bits, "limit " .. u.props["Limited to"]) end
			print(string.format("**%s** (%s%s)", u.name, u.base,
				#bits > 0 and ", " .. table.concat(bits, ", ") or ""))
			local variantLines, plain = {}, {}
			for _, m in ipairs(u.mods) do
				local v = m:gsub("^{variant:[%d,]+}", "")
				if v ~= "Corrupted" and v ~= "Passage" and v ~= "Historic" then
					if v ~= m then table.insert(variantLines, v)
					elseif not m:match("^{") then table.insert(plain, v) end
				end
			end
			for _, m in ipairs(plain) do print("- " .. m) end
			if #variantLines > 0 then
				print("- one of: " .. table.concat(variantLines, " / "))
			end
			print("")
		end
	end
end

out:close()
emit(string.format("wrote jewels.md (%d cluster tags, %d notables, %d timeless, %d abyss historics)",
	#tags, nNotables, #timeless, #abyssHist))
