-- Regenerates data/ascendancies.md - every ascendancy node, primary and secondary.
-- Run from src/:
--   luajit ../.claude/skills/cook/tools/dump-ascendancies.lua
--
-- Writes the file itself rather than to stdout: PoB's loader prints its startup banner
-- to stdout, so a shell redirect lands that in the middle of the data.
--
-- Primary and secondary are in one file because they draw on the same 8 points: a
-- Bloodline node is only ever evaluable against the class node it displaces.
--
-- Everything is listed. Do not filter on isNotable - major nodes such as Assassin's
-- "Knife in the Back" are not flagged notable and would be silently dropped.
local pob = dofile("../.claude/skills/cook/tools/pob.lua")
pob.data()
local tree = _G.build.spec.tree

local out = assert(io.open("../.claude/skills/cook/data/ascendancies.md", "w+"))
local emit = print                     -- keep the real one for the closing summary
local function print(line) out:write(tostring(line), "\n") end

local function affinity(c)
	local attrs = { { "Str", c.base_str or 0 }, { "Dex", c.base_dex or 0 }, { "Int", c.base_int or 0 } }
	local best = 0
	for _, a in ipairs(attrs) do best = math.max(best, a[2]) end
	local names = {}
	for _, a in ipairs(attrs) do if a[2] == best then names[#names + 1] = a[1] end end
	return table.concat(names, "/")
end

-- node.ascendancyName -> its nodes
local nodesByAsc = {}
for _, node in pairs(tree.nodes) do
	local a = node.ascendancyName
	if a and node.dn and not node.isProxy and node.type ~= "AscendClassStart" then
		nodesByAsc[a] = nodesByAsc[a] or {}
		table.insert(nodesByAsc[a], node)
	end
end
local function emitNodes(ascName)
	local list = nodesByAsc[ascName] or {}
	table.sort(list, function(x, y) return (x.dn or "") < (y.dn or "") end)
	for _, node in ipairs(list) do
		-- CountAllocNodes skips isMultipleChoiceOption, so those are free
		local free = node.isMultipleChoiceOption and " _(no point cost)_" or ""
		print(string.format("- **%s** [%s]%s", node.dn, tostring(node.id), free))
		for _, s in ipairs(node.sd or {}) do print(string.format("  - %s", s)) end
	end
	if #list == 0 then print("_No nodes found._") end
	print("")
end

print("<!-- GENERATED by .claude/skills/cook/tools/dump-ascendancies.lua - do not hand-edit -->")
print("# Ascendancies\n")
print(string.format("_Generated from PoB tree data `%s`. Regenerate after any data update._\n",
	tostring(tree.treeVersion or _G.build.spec.treeVersion):gsub("_", ".")))

------------------------------------------------------------------ points
print("## Points\n")
print("Primary and secondary ascendancies share **one pool of 8 points**. A point spent on")
print("a Bloodline is a point not spent on the class, which is why both are in this file.\n")
print("`CountAllocNodes` (`PassiveSpec.lua:822`) returns `used, ascUsed, secondaryAscUsed`.")
print("`ascUsed` counts **every** node with an `ascendancyName`, Bloodline nodes included;")
print("`secondaryAscUsed` re-counts the Bloodline subset. `Build.lua:908` warns when")
print("`ascUsed > 8`, and separately when `secondaryAscUsed > 8`, so the total binds.")
print("Trust the warning and check `ascUsed` on every build.\n")
print("Nodes marked _(no point cost)_ are `isMultipleChoiceOption`, which `CountAllocNodes`")
print("skips - they are a choice attached to another node rather than a purchase.\n")

------------------------------------------------------------------ primary
print("## Primary\n")
print("Select with `build.spec:SelectClass(classId)` then")
print("`build.spec:SelectAscendClass(ascendId)`. Attribute affinity is the class's own")
print("starting attributes - it is a property of the class, not of the ascendancy.\n")
print("| class | classId | affinity | base str/dex/int | ascendancies |")
print("|---|---|---|---|---|")
local classIds = {}
for id in pairs(tree.classes or {}) do classIds[#classIds + 1] = id end
table.sort(classIds)
for _, id in ipairs(classIds) do
	local c = tree.classes[id]
	local names = {}
	for ascId, a in pairs(c.ascendancies or {}) do
		if a.name and a.name ~= "None" then names[#names + 1] = string.format("%d:%s", ascId, a.name) end
	end
	table.sort(names)
	print(string.format("| %s | %s | %s | %d/%d/%d | %s |", c.name, tostring(id), affinity(c),
		c.base_str or 0, c.base_dex or 0, c.base_int or 0, table.concat(names, ", ")))
end
print("")

for _, id in ipairs(classIds) do
	local c = tree.classes[id]
	print(string.format("### %s - classId %s, %s (%d str / %d dex / %d int)\n",
		c.name, tostring(id), affinity(c), c.base_str or 0, c.base_dex or 0, c.base_int or 0))
	local ascIds = {}
	for ascId, a in pairs(c.ascendancies or {}) do
		if a.name and a.name ~= "None" then ascIds[#ascIds + 1] = ascId end
	end
	table.sort(ascIds)
	for _, ascId in ipairs(ascIds) do
		print(string.format("#### %s - ascendId %d\n", c.ascendancies[ascId].name, ascId))
		emitNodes(c.ascendancies[ascId].name)
	end
end

------------------------------------------------------------------ secondary
print("## Secondary (Bloodlines)\n")
print("Select with `build.spec:SelectSecondaryAscendClass(ascId)`. The call takes only an")
print("ascId and does no class check, so any class may take any Bloodline. Bloodlines have")
print("no attribute affinity - their start node sits in a detached group of its own.\n")
local alt = {}
for ascId, a in pairs(tree.alternate_ascendancies or {}) do
	alt[#alt + 1] = { ascId = ascId, id = a.id, name = a.name }
end
table.sort(alt, function(x, y) return x.name < y.name end)
print("| ascId | id | name |")
print("|---|---|---|")
for _, a in ipairs(alt) do
	print(string.format("| %s | %s | %s |", tostring(a.ascId), a.id, a.name))
end
print("")
for _, a in ipairs(alt) do
	print(string.format("### %s - `%s`, ascId %s\n", a.name, a.id, tostring(a.ascId)))
	emitNodes(a.id)
end

out:close()
emit(string.format("wrote ascendancies.md (%d classes, %d bloodlines)", #classIds, #alt))
