-- Regenerates data/ascendancies.md AND data/ascendancies.db from one collection pass.
-- Run from src/ (sqlite3 must be on PATH):
--   luajit ../.claude/skills/cook/tools/dump-ascendancies.lua
--
-- Primary and secondary share one dataset because they draw on the same 8 points: a
-- Bloodline node is only ever evaluable against the class node it displaces.
--
-- Every node is included. Do not filter on isNotable - major nodes such as Assassin's
-- "Knife in the Back" are not flagged notable and would be silently dropped.
local pob = dofile("../.claude/skills/cook/tools/pob.lua")
pob.data()
local tree = _G.build.spec.tree
local OUT = "../.claude/skills/cook/data/"
local q = pob.q

local function affinity(c)
	local attrs = { { "Str", c.base_str or 0 }, { "Dex", c.base_dex or 0 }, { "Int", c.base_int or 0 } }
	local best = 0
	for _, a in ipairs(attrs) do best = math.max(best, a[2]) end
	local names = {}
	for _, a in ipairs(attrs) do if a[2] == best then names[#names + 1] = a[1] end end
	return table.concat(names, "/")
end

------------------------------------------------------------------ collect
-- node.ascendancyName -> its nodes (class ascendancies key by name, bloodlines by id)
local nodesByKey = {}
for _, node in pairs(tree.nodes) do
	local a = node.ascendancyName
	if a and node.dn and not node.isProxy and node.type ~= "AscendClassStart" then
		nodesByKey[a] = nodesByKey[a] or {}
		table.insert(nodesByKey[a], node)
	end
end
for _, list in pairs(nodesByKey) do
	table.sort(list, function(x, y) return (x.dn or "") < (y.dn or "") end)
end

local classIds = {}
for id in pairs(tree.classes or {}) do classIds[#classIds + 1] = id end
table.sort(classIds)

-- ascendancy rows: { name, kind, classId (nil for bloodlines), ascId, treeKey }
local ascRows = {}
for _, id in ipairs(classIds) do
	local c = tree.classes[id]
	local ascIds = {}
	for ascId, a in pairs(c.ascendancies or {}) do
		if a.name and a.name ~= "None" then ascIds[#ascIds + 1] = ascId end
	end
	table.sort(ascIds)
	for _, ascId in ipairs(ascIds) do
		ascRows[#ascRows + 1] = { name = c.ascendancies[ascId].name, kind = "class",
			classId = id, ascId = ascId, treeKey = c.ascendancies[ascId].name }
	end
end
local nBloodlines = 0
do
	local alt = {}
	for ascId, a in pairs(tree.alternate_ascendancies or {}) do
		alt[#alt + 1] = { ascId = ascId, id = a.id, name = a.name }
	end
	table.sort(alt, function(x, y) return x.name < y.name end)
	for _, a in ipairs(alt) do
		ascRows[#ascRows + 1] = { name = a.name, kind = "bloodline",
			classId = nil, ascId = a.ascId, treeKey = a.id }
		nBloodlines = nBloodlines + 1
	end
end

local treeVersion = tostring(tree.treeVersion or _G.build.spec.treeVersion):gsub("_", ".")

------------------------------------------------------------------ ascendancies.md
local f = assert(io.open(OUT .. "ascendancies.md", "w+"))
local function w(fmt, ...)
	f:write(select("#", ...) > 0 and string.format(fmt, ...) or fmt, "\n")
end

w("<!-- GENERATED by .claude/skills/cook/tools/dump-ascendancies.lua - do not hand-edit -->")
w("# Ascendancies\n")
w("_Generated from PoB tree data `%s`. Regenerate after any data update - this script",
	treeVersion)
w("rebuilds `ascendancies.db` too._\n")
w("Every class, ascendancy, Bloodline and node lives in `data/ascendancies.db`; this file")
w("holds the rules. A node name from memory is a hypothesis - query it; zero rows means")
w("it does not exist.\n")

w("## Points\n")
w("Primary and secondary ascendancies share **one pool of 8 points**. A point spent on")
w("a Bloodline is a point not spent on the class, which is why both are in one dataset.\n")
w("`CountAllocNodes` (`PassiveSpec.lua:822`) returns `used, ascUsed, secondaryAscUsed`.")
w("`ascUsed` counts **every** node with an `ascendancyName`, Bloodline nodes included;")
w("`secondaryAscUsed` re-counts the Bloodline subset. `Build.lua:908` warns when")
w("`ascUsed > 8`, and separately when `secondaryAscUsed > 8`, so the total binds.")
w("Trust the warning and check `ascUsed` on every build.\n")
w("Nodes with `free=1` are `isMultipleChoiceOption`, which `CountAllocNodes` skips -")
w("they are a choice attached to another node rather than a purchase.\n")

w("## Selection\n")
w("Primary: `build.spec:SelectClass(class_id)` then `build.spec:SelectAscendClass(asc_id)`.")
w("Secondary: `build.spec:SelectSecondaryAscendClass(asc_id)` with a `kind='bloodline'`")
w("`asc_id` - the call does no class check, so any class may take any Bloodline.\n")
w("Attribute affinity is the class's own starting attributes - a property of the class,")
w("not of the ascendancy. Bloodlines have no affinity; their start node sits in a")
w("detached group of its own.\n")

w("## Querying ascendancies.db\n")
w("Run `sqlite3` with paths from the repo root (from `src/`, prefix `../`).\n")
w("- `classes(id, name, base_str, base_dex, base_int, affinity)` - `id` is the")
w("  `SelectClass` argument.")
w("- `ascendancies(id, name, kind, class_id, asc_id, tree_key)` - kind `class|bloodline`;")
w("  `asc_id` is the `SelectAscendClass` / `SelectSecondaryAscendClass` argument")
w("  (per-class for kind=class, global for bloodlines); `class_id` NULL for bloodlines;")
w("  `tree_key` is the `ascendancyName` raw tree nodes carry.")
w("- `nodes(id, ascendancy_id, name, free)` - `id` is the tree node id; `free=1` = no")
w("  point cost (see Points).")
w("- `node_stats(node_id, ord, line, template)` - a node's stat lines in order;")
w("  `template` has every number as `#` - LIKE-match on it, not on `line`.")
w("- `meta(key, value)` - `tree_version`, `generated_at`.\n")
w("Canonical queries:\n")
w("```sh")
w("DB=.claude/skills/cook/data/ascendancies.db")
w("# classes with their ascendancies and selection ids")
w("sqlite3 $DB \"SELECT c.name, c.id, a.asc_id, a.name FROM ascendancies a")
w("  JOIN classes c ON c.id=a.class_id ORDER BY c.id, a.asc_id;\"")
w("# every node of one ascendancy, stats inline")
w("sqlite3 $DB \"SELECT n.name, n.free, s.line FROM nodes n")
w("  JOIN ascendancies a ON a.id=n.ascendancy_id")
w("  LEFT JOIN node_stats s ON s.node_id=n.id")
w("  WHERE a.name='Slayer' ORDER BY n.name, s.ord;\"")
w("# who grants a mechanic - search templates across all ascendancies")
w("sqlite3 $DB \"SELECT a.name, n.name, s.line FROM node_stats s")
w("  JOIN nodes n ON n.id=s.node_id JOIN ascendancies a ON a.id=n.ascendancy_id")
w("  WHERE s.template LIKE '%Culling Strike%';\"")
w("```")
f:close()

------------------------------------------------------------------ ascendancies.db
local nNodes, nStats = 0, 0
pob.buildDb(OUT .. "ascendancies.db", function(w)
	w([[
PRAGMA journal_mode=OFF;
BEGIN;
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE classes (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	base_str INTEGER NOT NULL, base_dex INTEGER NOT NULL, base_int INTEGER NOT NULL,
	affinity TEXT NOT NULL
);
CREATE TABLE ascendancies (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	kind TEXT NOT NULL,
	class_id INTEGER REFERENCES classes(id),
	asc_id INTEGER NOT NULL,
	tree_key TEXT NOT NULL
);
CREATE TABLE nodes (
	id INTEGER PRIMARY KEY,
	ascendancy_id INTEGER NOT NULL REFERENCES ascendancies(id),
	name TEXT NOT NULL,
	free INTEGER NOT NULL
);
CREATE TABLE node_stats (
	node_id INTEGER NOT NULL REFERENCES nodes(id),
	ord INTEGER NOT NULL,
	line TEXT NOT NULL,
	template TEXT NOT NULL,
	PRIMARY KEY (node_id, ord)
);]])

	for _, id in ipairs(classIds) do
		local c = tree.classes[id]
		w(("INSERT INTO classes VALUES (%d, %s, %d, %d, %d, %s);"):format(
			id, q(c.name), c.base_str or 0, c.base_dex or 0, c.base_int or 0, q(affinity(c))))
	end

	for aid, row in ipairs(ascRows) do
		w(("INSERT INTO ascendancies VALUES (%d, %s, %s, %s, %d, %s);"):format(
			aid, q(row.name), q(row.kind),
			row.classId and tostring(row.classId) or "NULL", row.ascId, q(row.treeKey)))
		for _, node in ipairs(nodesByKey[row.treeKey] or {}) do
			nNodes = nNodes + 1
			w(("INSERT INTO nodes VALUES (%d, %d, %s, %d);"):format(
				node.id, aid, q(node.dn), node.isMultipleChoiceOption and 1 or 0))
			for ord, s in ipairs(node.sd or {}) do
				nStats = nStats + 1
				local line = tostring(s):gsub("\n", " ")
				w(("INSERT INTO node_stats VALUES (%d, %d, %s, %s);"):format(
					node.id, ord, q(line), q((pob.templateLine(line)))))
			end
		end
	end

	w(("INSERT INTO meta VALUES ('tree_version', %s);"):format(q(treeVersion)))
	w(("INSERT INTO meta VALUES ('generated_at', %s);"):format(q(os.date("!%Y-%m-%d"))))
	w("INSERT INTO meta VALUES ('generator', 'dump-ascendancies.lua');")
	w([[
CREATE INDEX idx_asc_name ON ascendancies(name);
CREATE INDEX idx_nodes_asc ON nodes(ascendancy_id);
CREATE INDEX idx_node_stats_node ON node_stats(node_id);
COMMIT;]])
end)

print(string.format("wrote ascendancies.md + ascendancies.db: %d classes, %d ascendancies (%d bloodlines), %d nodes, %d stat lines, tree %s",
	#classIds, #ascRows, nBloodlines, nNodes, nStats, treeVersion))
