-- Regenerates data/gems.md, data/skills.md and data/supports.md from PoB's gem database.
-- Run from src/:  luajit ../.claude/skills/cook/tools/dump-gems.lua
--
-- Split mirrors the game's own: gems.md = rules cutting across both categories,
-- skills.md = active gems, supports.md = supports.
--
-- Obtainability source of truth: grantedEffect.legacy, the flag GemTooltip.lua renders as
-- "Gem only exists in Standard League". It lives in Data/Skills/sup_*.lua; the tags live in
-- Data/Gems.lua - "obtainable supports with tag X" is a join across four files, hence the
-- precompute.
local data = dofile("../.claude/skills/cook/tools/pob.lua").data()
local OUT = "../.claude/skills/cook/data/"

local function isLegacy(gd)
	local ge, ge2 = gd.grantedEffect, gd.secondaryGrantedEffect
	return ((ge and ge.legacy) or (ge2 and ge2.legacy)) and true or false
end
local function tags(gd) return (gd.tagString or ""):gsub("|", "/") end

local all, byGrantedId = {}, {}
for _, gd in pairs(data.gems) do
	if gd.name then
		all[#all + 1] = gd
		if gd.grantedEffect and gd.grantedEffect.id then byGrantedId[gd.grantedEffect.id] = gd end
	end
end
table.sort(all, function(a, b) return a.name < b.name end)

local legacy, supports, skills, plus = {}, {}, {}, {}
for _, gd in ipairs(all) do
	local ge = gd.grantedEffect
	if isLegacy(gd) then legacy[#legacy + 1] = gd end
	if ge and ge.support then
		supports[#supports + 1] = gd
		if ge.plusVersionOf then
			local base = byGrantedId[ge.plusVersionOf]
			plus[#plus + 1] = { base = base and base.name or ge.plusVersionOf, up = gd }
		end
	else
		skills[#skills + 1] = gd
	end
end
table.sort(plus, function(a, b) return a.base < b.base end)

local function writer(path)
	local f = assert(io.open(OUT .. path, "w+"))
	return function(fmt, ...)
		f:write(select("#", ...) > 0 and string.format(fmt, ...) or fmt, "\n")
	end, function() f:close() end
end
local GEN = "<!-- GENERATED by .claude/skills/cook/tools/dump-gems.lua - do not hand-edit -->"
local STAMP = "_Generated from PoB tree data `" ..
	tostring(_G.build.spec.treeVersion):gsub("_", ".") .. "`. Regenerate after any data update._"

------------------------------------------------------------------ gems.md
do
	local w, close = writer("gems.md")
	w(GEN)
	w("# Gems\n")
	w(STAMP .. "\n")
	w("Rules covering both categories. Active gems are in `skills.md`, supports in")
	w("`supports.md` - both list only obtainable gems.\n")
	w("Nothing in PoB's UI or file format stops you picking an unobtainable gem. Check here")
	w("while choosing; `validate.lua` catches it after the fact, when it costs a rebuild.\n")

	w("## Not obtainable\n")
	w("Unobtainable in a fresh league - do not put these in a build. Grouped by category;")
	w("a category is omitted when nothing in it is unobtainable.\n")
	local byCat = { { label = "Supports", list = {} }, { label = "Active skills", list = {} } }
	for _, gd in ipairs(legacy) do
		local ge = gd.grantedEffect
		local bucket = (ge and ge.support) and byCat[1].list or byCat[2].list
		bucket[#bucket + 1] = gd
	end
	for _, cat in ipairs(byCat) do
		if #cat.list > 0 then
			w("### %s (%d)\n", cat.label, #cat.list)
			for _, gd in ipairs(cat.list) do w("- %s", gd.name) end
			w("")
		end
	end

	local upgrades = {}
	for _, p in ipairs(plus) do if not isLegacy(p.up) then upgrades[#upgrades + 1] = p end end

	w("\n## Upgraded support tiers\n")
	w("`grantedEffect.plusVersionOf` links a support to its upgraded version. %d supports",
		#upgrades)
	w("have an obtainable upgrade; a support absent from this table has none, so do not go")
	w("looking for one. Most upgrades are a renamed gem rather than an `Awakened *` one -")
	w("that line is gone bar Empower, Enhance and Enlighten. An upgrade beats its base at")
	w("every level, so prefer it whenever it exists.\n")
	w("| base support | upgraded version |")
	w("|---|---|")
	for _, p in ipairs(upgrades) do
		w("| %s | %s |", p.base, p.up.name)
	end

	w("\n## Level caps\n")
	w("Every gem can be corrupted to one level above its natural max, with no exceptions.")
	w("Cap is always `naturalMaxLevel + 1`; per-gem natural maxes are in `skills.md` and")
	w("`supports.md`.")
	close()
end

------------------------------------------------------------------ supports.md
do
	local w, close = writer("supports.md")
	local nOk = 0
	for _, gd in ipairs(supports) do if not isLegacy(gd) then nOk = nOk + 1 end end
	w(GEN)
	w("# Support gems\n")
	w(STAMP .. "\n")
	w("The %d obtainable supports of %d total; the %d unobtainable ones are listed in",
		nOk, #supports, #legacy)
	w("`gems.md` and excluded here. Tags decide what a support can attach to.\n")
	w("Many support names say nothing about what they do, so the description is included.")
	w("Grep this file by tag or by keyword.\n")
	w("| support | max lvl | tags | description |")
	w("|---|---|---|---|")
	for _, gd in ipairs(supports) do
		if not isLegacy(gd) then
			local desc = ((gd.grantedEffect or {}).description or ""):gsub("\n", " "):gsub("|", "/")
			w("| %s | %d | %s | %s |", gd.name, gd.naturalMaxLevel or 20, tags(gd), desc)
		end
	end
	close()
end

------------------------------------------------------------------ skills.md
do
	local w, close = writer("skills.md")
	local nOk = 0
	for _, gd in ipairs(skills) do if not isLegacy(gd) then nOk = nOk + 1 end end
	w(GEN)
	w("# Active skill gems\n")
	w(STAMP .. "\n")
	w("The %d obtainable actives of %d total; any unobtainable ones are listed in `gems.md`",
		nOk, #skills)
	w("and excluded here. Tags are the fast filter; for a gem's full behaviour grep its")
	w("entry in `src/Data/Skills/act_*.lua`.\n")
	w("| skill | max lvl | tags |")
	w("|---|---|---|")
	for _, gd in ipairs(skills) do
		if not isLegacy(gd) then
			w("| %s | %d | %s |", gd.name, gd.naturalMaxLevel or 20, tags(gd))
		end
	end
	close()
end

print("wrote gems.md, supports.md, skills.md")
