-- Regenerates data/uniques.md. Run from src/:
--   luajit ../.claude/skills/cook/tools/dump-uniques.lua
--
-- Obtainability is PoB's own flag, not a heuristic. ItemDBControl.lua:114 computes it as
--   not (source == "No longer obtainable" or item.league == "Race Events")
-- from the item's `Source:` / `League:` lines (Item.lua:807 / :767). Items are built as real
-- Item objects here so the parse matches PoB's exactly.
local pob = dofile("../.claude/skills/cook/tools/pob.lua")
local data = pob.data()
local OUT = "../.claude/skills/cook/data/"

-- A variant name is legacy if it names the patch the item was changed in.
local function looksLegacy(name)
	return (name:match("[Pp]re %d") or name:match("[Ll]egacy")) ~= nil
end

local unobtainable, variants, seen, total = {}, {}, {}, 0
for _, list in pairs(data.uniques) do
	if type(list) == "table" then
		for _, raw in ipairs(list) do
			if type(raw) == "string" then
				local ok, item = pcall(function() return new("Item", raw) end)
				local title = ok and item and item.title
				if title and not seen[title] then
					seen[title] = true
					total = total + 1

					local source = item.source or ""
					local gone = nil
					if source == "No longer obtainable" then
						gone = "No longer obtainable"
					elseif item.league == "Race Events" then
						gone = "Race Events"
					end
					if gone then unobtainable[#unobtainable + 1] = { title = title, why = gone } end

					-- variants of an item that cannot drop are moot; only track obtainable ones
					local vlist, nLegacy = item.variantList or {}, 0
					for _, v in ipairs(vlist) do if looksLegacy(v) then nLegacy = nLegacy + 1 end end
					if nLegacy > 0 and not gone then
						variants[#variants + 1] = { title = title, n = #vlist, nLegacy = nLegacy }
					end
				end
			end
		end
	end
end
table.sort(unobtainable, function(a, b) return a.title < b.title end)
table.sort(variants, function(a, b) return a.title < b.title end)

local byWhy = { ["No longer obtainable"] = {}, ["Race Events"] = {} }
for _, it in ipairs(unobtainable) do table.insert(byWhy[it.why], it.title) end

local perMod = {}
for _, it in ipairs(variants) do
	if it.n >= 8 then perMod[#perMod + 1] = it end
end

local f = assert(io.open(OUT .. "uniques.md", "w+"))
local function w(fmt, ...)
	f:write(select("#", ...) > 0 and string.format(fmt, ...) or fmt, "\n")
end

w("<!-- GENERATED by .claude/skills/cook/tools/dump-uniques.lua - do not hand-edit -->")
w("# Uniques\n")
w("_Generated from PoB tree data `%s`. Regenerate after any data update._\n",
	tostring(_G.build.spec.treeVersion):gsub("_", "."))
w("Two separate hazards: an item that cannot drop at all, and an obtainable item whose")
w("older variant is the one you wrote down.\n")

------------------------------------------------------------------ obtainability
w("## Not obtainable\n")
w("%d of %d uniques. Check here before putting any unique in a spec.\n", #unobtainable, total)
for _, why in ipairs({ "No longer obtainable", "Race Events" }) do
	local list = byWhy[why]
	if #list > 0 then
		w("### %s (%d)\n", why, #list)
		for _, t in ipairs(list) do w("- %s", t) end
		w("")
	end
end

------------------------------------------------------------------ variants
w("\n## Variants\n")
w("%d obtainable uniques carry at least one legacy variant - a roll that existed before", #variants)
w("some patch and cannot be obtained now.\n")
w("`Item.lua:1496` defaults an item to its **last** variant:")
w("`self.variant = m_min(#self.variantList, self.variant or #self.variantList)`. Raw item")
w("text can pin any variant with a `Selected Variant:` line, and PoB keeps a legacy pick")
w("without complaint - so always read back the variant you actually got.\n")

w("### Per-mod variant items\n")
w("These encode one variant per possible mod **roll** rather than one per item version -")
w("Watcher's Eye has 106, one per aura mod - and several can be selected at once through")
w("`variantAlt1..5`. \"Use the last variant\" is meaningless here: it just picks the last")
w("aura in the list. A legacy roll sits directly beside its replacement under a name that")
w("says so - `Clarity: Mana Added As ES (Pre 3.12.0)` at `Gain (12-18)%` next to the")
w("current `Clarity: Mana Added As ES` at `Gain (6-10)%`. Same wording, nerfed numbers, so")
w("the name is what identifies the roll. Every variant's lines live in the item text at")
w("once, selected or not, which is the trap: read them through")
w("`Item:CheckModLineVariant` or you will judge a mod the item does not have.")
w("`validate.lua` does both.\n")
w("| item | variants | legacy |")
w("|---|---|---|")
for _, it in ipairs(perMod) do
	w("| %s | %d | %d |", it.title, it.n, it.nLegacy)
end

------------------------------------------------------------------ foulborn
-- data.foulbornMap[unique] maps originalModId -> foulbornModId: the Foulborn version REPLACES
-- a normal mod rather than adding one. Text: itemMods.ItemExclusive (original),
-- itemMods.Foulborn (replacement).
local exclusive, foulPool = data.itemMods.ItemExclusive, data.itemMods.Foulborn
local foul, nPairs = {}, 0
for title, map in pairs(data.foulbornMap or {}) do
	local rows = {}
	for origId, foulId in pairs(map) do
		local o, n = exclusive[origId], foulPool[foulId]
		if o and n then
			rows[#rows + 1] = { from = table.concat(o, " "), to = table.concat(n, " ") }
			nPairs = nPairs + 1
		end
	end
	if #rows > 0 then
		table.sort(rows, function(a, b) return a.from < b.from end)
		foul[#foul + 1] = { title = title, rows = rows }
	end
end
table.sort(foul, function(a, b) return a.title < b.title end)

w("\n## Foulborn\n")
w("Not a league mechanic - permanent, and roughly a year older than 3.29.\n")
w("A Foulborn unique **replaces** one of its normal mods with a mutated counterpart. It")
w("is not an extra mod, and you pick which one is replaced: %d uniques offer %d possible",
	#foul, nPairs)
w("swaps between them.\n")
w("To put one in a build spec, tag the replacement line `{mutated}` in the item's raw")
w("text. The `Foulborn ` name prefix is derived from that tag (`Item.lua:1564`), so")
w("writing it yourself does nothing.\n")
w("`Might of the Meek` is excluded: its transformation changes a radius rather than a")
w("mod line, which PoB cannot represent (`Item.lua:999`).\n")
w("| unique | replaces | with |")
w("|---|---|---|")
for _, it in ipairs(foul) do
	for i, r in ipairs(it.rows) do
		w("| %s | %s | %s |", i == 1 and it.title or "", r.from, r.to)
	end
end

f:close()
print(string.format("wrote uniques.md (%d uniques, %d unobtainable, %d with legacy variants)",
	total, #unobtainable, #variants))
