-- Regenerates data/cluster-jewels.md: sizes, skills per size, notables with stats
-- and weights, and the authoring recipe proven by test. Run from src/:
--   luajit ../.claude/skills/cook/tools/dump-cluster-jewels.lua
--
-- Sources: data.clusterJewels (sizes, skills, enchant text); Data/ModJewelCluster (notable
-- affixes: weightKey = skill tags, weightMultiplierKey = sizes); tree.clusterNodeMap (each
-- notable's actual stats).
local pob = dofile("../.claude/skills/cook/tools/pob.lua")
local data = pob.data()
local tree = _G.build.spec.tree
local clusterMods = LoadModule("Data/ModJewelCluster")

local out = assert(io.open("../.claude/skills/cook/data/cluster-jewels.md", "w+"))
local emit = print
local function print(line) out:write(tostring(line), "\n") end

print("<!-- GENERATED by .claude/skills/cook/tools/dump-cluster-jewels.lua - do not hand-edit -->")
print("# Cluster jewels\n")
print(string.format("_Generated from PoB tree data `%s`. Regenerate after any data update._\n",
	tostring(tree.treeVersion):gsub("_", ".")))

------------------------------------------------------------------ mechanics
print([[
Cluster jewels socket into the tree's outer rim and grow new passive nodes. The
subgraph PoB builds always matches the in-game structure.

## Mechanics, verified headless

- Only rim sockets take a Large jewel: `node.expansionJewel.size == 2`
  (`PassiveSpec.lua:1764`). Every rim socket costs ~2 travel + the socket itself.
- Subgraph nodes are real allocated nodes: they count toward the 122+extras passive
  budget (`CountAllocNodes`), and `validate.lua`'s tree check covers them.
- The jewel's skill, node count AND socket count come from its ENCHANT lines, parsed by
  exact text (`ModParser.lua:6544`, `:5199`). The `Cluster Jewel Skill:`/`Node Count:`
  properties are only crafting-UI state - without the enchant lines the subgraph never
  builds, and without the socket enchant line no socket nodes grow.
- Notables come from the generated "1 Added Passive Skill is X" lines, so an uncrafted
  jewel builds a subgraph of only small passives. Run `craft.lua`, as with every
  authored item.
- Notable legality = spawn weight with the jewel's skill tag passed as an include tag
  (`ItemsTab.lua:2150`); `affixes.lua --skill=<tag>` and `validate.lua` both do this.

## Nested sockets

Every Large carries "2 Added Passive Skills are Jewel Sockets", every Medium
"1 Added Passive Skill is a Jewel Socket", Smalls none - author these enchant lines,
they are part of the node count (smalls = count - sockets - notables). A nested socket
takes a smaller cluster jewel (Large holds Medium/Small, Medium holds Small) OR any
regular jewel, abyss jewels included - the one place an abyss jewel fits a tree socket.

This is the quiet half of cluster value: a nested socket is a 1-point jewel socket
where tree sockets cost 2-3. Nested socket nodes get STABLE tree ids (proxy nodes, not
generated ids) - craft, load, read the ids off the subgraph, then reference them in
`Spec/Sockets` like any socket. Verified round-trip: save and reload reproduce the
same ids, figures identical; `validate.lua` checks jewels in nested sockets like any
other slot.

## Authoring recipe (proven)

```
Rarity: RARE
Some Name
Large Cluster Jewel
Crafted: true
Item Level: 84
Cluster Jewel Skill: affliction_fire_damage
Cluster Jewel Node Count: 8
Prefix: {range:0.85}AfflictionNotablePrismaticHeart__
Prefix: {range:0.85}AfflictionNotableSmokingRemains
Implicits: 3
{enchant}Adds 8 Passive Skills
{enchant}2 Added Passive Skills are Jewel Sockets
{enchant}Added Small Passive Skills grant: 12% increased Fire Damage
```

The last enchant line must be the skill's exact enchant text from the tables below.
Socket via `<Socket nodeId="..." itemId="..."/>` on a rim socket, allocate the socket
node, then the subgraph nodes (generated ids land in the saved `nodes` list and reload
cleanly). Craft first, then allocate - notables only exist after crafting.

## Stat-stick clusters

Notables are not the only design. The `AfflictionJewelSmallPassivesGrant*` prefixes add
a stat to EVERY small ("Added Small Passive Skills also grant: ..."), and
`AfflictionJewelSmallPassivesHaveIncreasedEffect2` multiplies all of it by 35%. A
12-passive Large with no notables and three "also grant" mods is 12 custom-designed
small passives - e.g. life + attributes + armour on every node. `affixes.lua
"<size> Cluster Jewel" --skill=<tag>` lists these alongside the notables.

## Point economics

A jewel is worth `socket path (~3) + smalls walked + notables taken` points. Compare
against the tree wheel it replaces: smalls only pay if the enchant stat is live (a
15%-crit small is dead at 100% crit), so count notables per point, not nodes per point,
and count nested sockets as saved points against the 2-3 a tree socket costs.

Measured on the 3.29 CoC Blazing Salvo build (7.03m baseline):

- Medium crit (Pressure Points + Eye of the Storm): 7 points, +351k = 50k/pt -
  crit capped, so all four 15%-crit smalls were dead.
- Large fire (Prismatic Heart + Smoking Remains), no sockets: 8 points, +831k =
  104k/pt - 12%-fire smalls live, on par with the tree's last picks (~120-290k/pt).
- Same Large with its 2 sockets holding a Medium crit cluster and an ES/fire abyss
  jewel: 13 points, +1.88m and +136 ES = 145k/pt - the nested sockets beat everything.
]])

------------------------------------------------------------------ sizes
print("## Sizes\n")
print("| size | nodes | sockets | socket enchant line |")
print("|---|---|---|---|")
-- Socket counts are the game's fixed rule per size; socketIndicies is layout capacity, not
-- what rolls, so it is wrong for this table.
local sizeOrder = { "Large Cluster Jewel", "Medium Cluster Jewel", "Small Cluster Jewel" }
local sizeSockets = {
	["Large Cluster Jewel"] = { 2, "2 Added Passive Skills are Jewel Sockets" },
	["Medium Cluster Jewel"] = { 1, "1 Added Passive Skill is a Jewel Socket" },
	["Small Cluster Jewel"] = { 0, "-" },
}
for _, name in ipairs(sizeOrder) do
	local j = data.clusterJewels.jewels[name]
	if j then
		print(string.format("| %s | %d-%d | %d | %s |", name, j.minNodes, j.maxNodes,
			sizeSockets[name][1], sizeSockets[name][2]))
	end
end
print("")

------------------------------------------------------------------ skills per size
for _, name in ipairs(sizeOrder) do
	local j = data.clusterJewels.jewels[name]
	if j then
		print(string.format("## %s skills\n", name))
		print("| skill tag | small passive grants | enchant line for authoring |")
		print("|---|---|---|")
		local ids = {}
		for id in pairs(j.skills) do ids[#ids + 1] = id end
		table.sort(ids)
		for _, id in ipairs(ids) do
			local sk = j.skills[id]
			print(string.format("| %s | %s | %s |", id,
				table.concat(sk.stats or {}, " / "), table.concat(sk.enchant or {}, " / ")))
		end
		print("")
	end
end

------------------------------------------------------------------ notables
print("## Not obtainable\n")
print("Removed from the game over the years; PoB keeps them at spawn weight 0, so")
print("`affixes.lua` never lists them and `validate.lua` rejects them by weight.")
print("Listed so their names do not tempt from old guides.\n")
local removed = {}
for id, mod in pairs(clusterMods) do
	local notable = (mod[1] or ""):match("^1 Added Passive Skill is (.+)$")
	if notable then
		local anyWeight = false
		for i, v in ipairs(mod.weightVal or {}) do
			if (mod.weightKey[i] or "") ~= "default" and v > 0 then anyWeight = true break end
		end
		if not anyWeight then removed[#removed + 1] = notable end
	end
end
table.sort(removed)
for _, name in ipairs(removed) do print("- " .. name) end
print("")

print("## Notables\n")
print("Grouped by the skill tags that can roll them; grep by tag or by stat. Weights")
print("are relative within the tag's pool. Stats come from the tree's own nodes.\n")

local byTag = {}
for id, mod in pairs(clusterMods) do
	if id:match("^AfflictionNotable") and mod.weightKey then
		local notable = (mod[1] or ""):match("^1 Added Passive Skill is (.+)$")
		if notable then
			for i, key in ipairs(mod.weightKey) do
				if key ~= "default" and (mod.weightVal[i] or 0) > 0 then
					byTag[key] = byTag[key] or {}
					table.insert(byTag[key], { id = id, name = notable, w = mod.weightVal[i] })
				end
			end
		end
	end
end
local tags = {}
for t in pairs(byTag) do tags[#tags + 1] = t end
table.sort(tags)
local nNotables = 0
for _, t in ipairs(tags) do
	print(string.format("### %s\n", t))
	print("| notable | weight | id | stats |")
	print("|---|---|---|---|")
	table.sort(byTag[t], function(a, b) return a.name < b.name end)
	for _, e in ipairs(byTag[t]) do
		local node = tree.clusterNodeMap[e.name]
		local stats = node and table.concat(node.sd or {}, " / "):gsub("|", "/") or "?"
		print(string.format("| %s | %d | %s | %s |", e.name, e.w, e.id, stats))
		nNotables = nNotables + 1
	end
	print("")
end

out:close()
emit(string.format("wrote cluster-jewels.md (%d tags, %d notable entries)", #tags, nNotables))
