// Renders schema.Costs as Data/Costs.lua (Scripts/costs.lua's output).

package luarender

import "github.com/MissingL-tter/missingPassives/data/schema"

func init() { register("costs", renderCosts) }

func renderCosts(costs schema.Costs, _ Templates) (map[string]string, error) {
	var b B
	b.W("-- This file is automatically generated, do not edit!\n")
	b.W("-- Skill costs data (c) Grinding Gear Games\n\n")
	b.W("return {\n")
	for i, c := range costs {
		b.W("\t[", i+1, "] = {\n")
		b.W("\t\tResource = \"", c.Resource, "\",\n")
		if c.Stat != nil {
			b.W("\t\tStat = \"", *c.Stat, "\",\n")
		} else {
			b.W("\t\tStat = nil,\n")
		}
		b.W("\t\tResourceString = \"", c.ResourceString, "\",\n")
		b.W("\t\tDivisor = ", c.Divisor, ",\n")
		if i == len(costs)-1 {
			b.W("\t}\n")
		} else {
			b.W("\t},\n")
		}
	}
	b.W("}\n")
	return map[string]string{"Data/Costs.lua": b.String()}, nil
}
