// Renders the essence, modScalability, masters and crucible documents
// (Scripts/{essence,modScalability,masters,crucible}.lua outputs).

package luarender

import (
	"sort"
	"strings"

	"github.com/MissingL-tter/missingPassives/data/schema"
)

func init() {
	register("essence", renderEssence)
	register("modScalability", renderModScalability)
	register("masters", renderMasters)
	register("crucible", renderCrucible)
}

// itemHeader is the shared "-- Item data" preamble.
func (b *B) itemHeader() {
	b.W("-- This file is automatically generated, do not edit!\n")
	b.W("-- Item data (c) Grinding Gear Games\n\nreturn {\n")
}

// nums joins float64s with sep, %.14g each (table.concat).
func nums(vals []float64, sep string) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = luaNum(v)
	}
	return strings.Join(parts, sep)
}

// ints joins int64s with sep (table.concat).
func ints(vals []int64, sep string) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = luaStr(v)
	}
	return strings.Join(parts, sep)
}

func renderEssence(es schema.Essences, _ Templates) (map[string]string, error) {
	var b B
	b.itemHeader()
	for _, e := range es {
		types := make([]string, 0, len(e.Mods))
		for t := range e.Mods {
			types = append(types, t)
		}
		sort.Strings(types)
		b.W("\t[\"", e.BaseId, "\"] = { name = \"", e.Name, "\", ")
		b.W("type = ", e.Type, ", tier = ", e.Tier, ", ")
		b.W("mods = { ")
		for _, t := range types {
			b.W("[\"", t, "\"] = \"", e.Mods[t], "\", ")
		}
		b.W("}, },\n")
	}
	b.W("}")
	return map[string]string{"Data/Essence.lua": b.String()}, nil
}

func renderModScalability(sc schema.ModScalability, _ Templates) (map[string]string, error) {
	var b B
	b.itemHeader()
	// The reference sorted the escaped spellings.
	lines := make([]string, 0, len(sc))
	byEscaped := make(map[string]string, len(sc))
	for line := range sc {
		esc := luaEsc(line)
		lines = append(lines, esc)
		byEscaped[esc] = line
	}
	sort.Strings(lines)
	for _, esc := range lines {
		line := byEscaped[esc]
		b.W("\t[\"", esc, "\"] = { ")
		for i, s := range sc[line] {
			b.W("{ isScalable = ", luaStr(s.IsScalable))
			if s.Formats != nil {
				b.W(", formats = { ")
				for j, format := range s.Formats {
					b.W("\"", format, "\"")
					if j < len(s.Formats)-1 {
						b.W(", ")
					}
				}
				b.W(" }")
			}
			b.W(" }")
			if i < len(sc[line])-1 {
				b.W(", ")
			}
		}
		b.W(" },\n")
	}
	b.W("}")
	return map[string]string{"Data/ModScalability.lua": b.String()}, nil
}

func renderMasters(mc schema.MasterCrafts, _ Templates) (map[string]string, error) {
	var b B
	b.itemHeader()
	for _, c := range mc {
		b.W("\t{ ")
		if c.Type != "" {
			b.W("type = \"", c.Type, "\", ")
		}
		b.W("affix = \"", c.Affix, "\", ")
		b.W("modTags = { ", c.ModTags, " }, ")
		b.W("\"", strings.Join(c.Lines, "\", \""), "\", ")
		b.W("statOrder = { ", nums(c.StatOrders, ", "), " }, ")
		b.W("level = ", c.Level, ", group = \"", c.Group, "\", ")
		b.W("types = { ")
		for _, t := range c.Types {
			b.W("[\"", t, "\"] = true, ")
		}
		b.W("}, ")
		b.W("},\n")
	}
	b.W("}")
	return map[string]string{"Data/ModMaster.lua": b.String()}, nil
}

func renderCrucible(cn schema.CrucibleNodes, _ Templates) (map[string]string, error) {
	var b B
	b.itemHeader()
	for _, n := range cn {
		b.W("\t[\"", n.ModId, "\"] = { ")
		if n.Type != "" {
			b.W("type = \"", n.Type, "\", ")
		}
		b.W("tier = ", n.Tier, ", ")
		b.W("\"", strings.Join(n.Lines, "\", \""), "\", ")
		b.W("statOrder = { ", nums(n.StatOrders, ", "), " }, ")
		b.W("level = ", n.Level, ", group = \"", n.Group, "\", ")
		b.W("nodeType = \"", n.NodeType, "\", ")
		b.W("nodeLocation = { ", ints(n.NodeLocation, ", "), " }, ")
		b.W("weightKey = { ")
		for _, tag := range n.WeightKey {
			b.W("\"", tag, "\", ")
		}
		b.W("}, ")
		b.W("weightVal = { ", ints(n.WeightVal, ", "), " }, ")
		if len(n.WeightMultiplierKey) > 0 {
			b.W("weightMultiplierKey = { ")
			for _, tag := range n.WeightMultiplierKey {
				b.W("\"", tag, "\", ")
			}
			b.W("}, ")
			b.W("weightMultiplierVal = { ", ints(n.WeightMultiplierVal, ", "), " }, ")
			if len(n.Tags) > 0 {
				b.W("tags = { ")
				for _, tag := range n.Tags {
					b.W("\"", tag, "\", ")
				}
				b.W("}, ")
			}
		}
		b.W("modTags = { ", n.ModTags, " }, ")
		b.W("},\n")
	}
	b.W("}")
	return map[string]string{"Data/Crucible.lua": b.String()}, nil
}
