// Renders the miscdata, flavourText, mapUniqueToFoulborn and skillGemList
// documents.

package luarender

import (
	"sort"
	"strings"

	"github.com/MissingL-tter/missingPassives/data/schema"
)

func init() {
	register("miscdata", renderMiscdata)
	register("flavourText", renderFlavourText)
	register("mapUniqueToFoulborn", renderFoulbornMap)
	register("skillGemList", renderSkillGemList)
}

// luaQ is Lua's string.format("%q") for the characters that survive
// stringify's newline conversion.
func luaQ(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\\n")
		case '\r':
			b.WriteString("\\13")
		case 0:
			b.WriteString("\\0")
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// luaEsc spells a decoded text as the body of a Lua double-quoted literal
// the way the reference exporter wrote it: quotes, backslashes, newlines
// and carriage returns escaped, tabs raw.
func luaEsc(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}

// numList renders "{ v1, v2, ... }" with the trailing separator miscdata
// leaves behind every element.
func (b *B) numList(label string, vals []float64) {
	b.W("data.", label, " = { ")
	for _, v := range vals {
		b.W(v, ", ")
	}
	b.W("}\n")
}

func renderMiscdata(d schema.MiscData, _ Templates) (map[string]string, error) {
	var b B
	m := d.Misc
	b.W("-- This file is automatically generated, do not edit!\n\n")
	b.W("local data = ...\n")
	b.W("-- From DefaultMonsterStats.dat\n")
	b.numList("monsterEvasionTable", m.MonsterEvasion)
	b.numList("monsterAccuracyTable", m.MonsterAccuracy)
	b.numList("monsterLifeTable", m.MonsterLife)
	b.numList("monsterLifeTable2", m.MonsterLife2)
	b.numList("monsterLifeTable3", m.MonsterLife3)
	b.numList("monsterAllyLifeTable", m.MonsterAllyLife)
	b.numList("monsterDamageTable", m.MonsterDamage)
	b.numList("monsterAllyDamageTable", m.MonsterAllyDamage)
	b.numList("monsterArmourTable", m.MonsterArmour)
	b.numList("monsterAilmentThresholdTable", m.MonsterAilmentThreshold)
	b.numList("monsterPhysConversionMultiTable", m.MonsterPhysConversionMulti)

	b.W("-- From GameConstants.dat\n")
	b.W("data.gameConstants = {\n")
	for _, c := range m.GameConstants {
		b.W("\t[\"", c.Id, "\"] = ", c.Value, ",\n")
	}
	b.W("}\n")

	b.W("-- From Metadata/Characters/Character.ot\n")
	b.W("data.characterConstants = {\n")
	for _, kv := range m.CharacterConstants {
		b.W("\t[\"", kv.Key, "\"] = ", kv.Value, ",\n")
	}
	b.W("}\n")

	b.W("-- From Metadata/Monsters/Monster.ot\n")
	b.W("data.monsterConstants = {\n")
	for _, kv := range m.MonsterConstants {
		b.W("\t[\"", kv.Key, "\"] = ", kv.Value, ",\n")
	}
	b.W("}\n")

	b.W("-- From MonsterVarieties.dat combined with SkillTotemVariations.dat\n")
	b.W("data.totemLifeMult = { ")
	for _, t := range m.TotemLifeMult {
		b.W("[", t.Id, "] = ", t.Mult, ", ")
	}
	b.W("}\n")

	b.W("data.monsterVarietyLifeMult = {\n")
	for _, v := range m.MonsterVarietyLifeMult {
		b.W("\t[\"", v.Name, "\"] = ", v.Mult, ",\n")
	}
	b.W("}\n")

	b.W("-- From MonsterMapDifficulty.dat\n")
	b.W("data.mapLevelLifeMult = { ")
	for _, v := range m.MapLevelLifeMult {
		b.W("[", v.Level, "] = ", v.Mult, ", ")
	}
	b.W("}\n")

	b.W("-- From MonsterMapBossDifficulty.dat\n")
	b.W("data.mapLevelBossLifeMult = { ")
	for _, v := range m.MapLevelBossLifeMult {
		b.W("[", v.Level, "] = ", v.Mult, ", ")
	}
	b.W("}\n")
	b.W("data.mapLevelBossAilmentMult = { ")
	for _, v := range m.MapLevelBossAilmentMult {
		b.W("[", v.Level, "] = ", v.Mult, ", ")
	}
	b.W("}\n")

	b.W("-- From VillageBalancePerLevelShared.dat\n")
	b.W("data.goldRespecPrices = { ")
	for _, v := range m.GoldRespecPrices {
		b.W(v, ", ")
	}
	b.W("}\n")

	var cn B
	cn.W("-- This file is automatically generated, do not edit!\n")
	cn.W("-- Game data (c) Grinding Gear Games\n\n")
	cn.W("-- This file contains mapping item names for every currency base item type ID.\n")
	cn.W("-- Used for working with the currency exchange which uses item type IDs.\n")
	cn.W("\n-- spell-checker: disable\nreturn {\n")
	ids := make([]string, 0, len(d.CurrencyNames))
	for id := range d.CurrencyNames {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		cn.W("\t[", luaQ(id), "] = ", luaQ(d.CurrencyNames[id]), ",\n")
	}
	cn.W("}\n")

	return map[string]string{
		"Data/Misc.lua":          b.String(),
		"Data/CurrencyNames.lua": cn.String(),
	}, nil
}

func renderFlavourText(fts schema.FlavourTexts, _ Templates) (map[string]string, error) {
	var b B
	b.W("-- This file is automatically generated, do not edit!\n")
	b.W("-- Flavour text data (c) Grinding Gear Games\n\n")
	b.W("return {\n")
	for i, ft := range fts {
		b.W("\t[", i+1, "] = {\n")
		b.W("\t\tid = \"", ft.Id, "\",\n")
		b.W("\t\tname = \"", ft.Name, "\",\n")
		b.W("\t\ttext = {\n")
		for _, line := range ft.Text {
			b.W("\t\t\t\"", luaEsc(line), "\",\n")
		}
		b.W("\t\t},\n")
		b.W("\t},\n")
	}
	b.W("}\n")
	return map[string]string{"Data/FlavourText.lua": b.String()}, nil
}

func renderFoulbornMap(fm schema.FoulbornMap, _ Templates) (map[string]string, error) {
	var b B
	b.itemHeader()
	names := make([]string, 0, len(fm))
	for name := range fm {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		b.W("\t[\"", name, "\"] = {\n")
		for _, mod := range fm[name] {
			b.W("\t\t\"", mod, "\",\n")
		}
		b.W("\t},\n")
	}
	b.W("}\n")
	return map[string]string{"Data/ModFoulbornMap.lua": b.String()}, nil
}

func renderSkillGemList(d schema.SkillGemList, _ Templates) (map[string]string, error) {
	var b B
	b.W("-- This file is automatically generated, do not edit!\n")
	b.W("-- Gem data (c) Grinding Gear Games\n\n")

	pad45 := func(s string) string {
		n := 45 - len(s)
		if n < 0 {
			n = 0
		}
		return s + strings.Repeat(" ", n)
	}
	format := func(entries []schema.SkillGemEntry) []string {
		lines := make([]string, len(entries))
		for i, e := range entries {
			lines[i] = pad45(e.Name) + "\t\t----\t\t" + strings.Join(e.Effects, "\t")
		}
		sort.Strings(lines)
		return lines
	}

	for _, g := range d.Groups {
		b.W("\t\t\t\t\t\t--------- Active " + g.Type + " ---------\n")
		b.W(strings.Join(format(g.Active), "\n"))
		b.W("\n\n")
		b.W("\t\t\t\t\t\t--------- Support " + g.Type + " ---------\n")
		b.W(strings.Join(format(g.Support), "\n"))
		b.W("\n\n")
	}
	return map[string]string{"Export/Skills/SkillGems.txt": b.String()}, nil
}
