// Renders gamedata.ClusterJewels as Data/ClusterJewels.lua
// (Scripts/cluster.lua's output).

package luarender

import (
	"strings"

	"github.com/MissingL-tter/missingPassives/gamedata"
)

func init() { register("cluster", renderCluster) }

func renderCluster(cj gamedata.ClusterJewels, _ Templates) (map[string]string, error) {
	var b B
	b.W("-- This file is automatically generated, do not edit!\n")
	b.W("-- Jewel data (c) Grinding Gear Games\n\nreturn {\n")

	b.W("\tjewels = {\n")
	for _, j := range cj.Jewels {
		b.W("\t\t[\"", j.Name, "\"] = {\n")
		b.W("\t\t\tsize = \"", j.Size, "\",\n")
		b.W("\t\t\tsizeIndex = ", j.SizeIndex, ",\n")
		b.W("\t\t\tminNodes = ", j.MinNodes, ",\n")
		b.W("\t\t\tmaxNodes = ", j.MaxNodes, ",\n")
		b.W("\t\t\tsmallIndicies = { ", ints(j.SmallIndicies, ", "), " },\n")
		b.W("\t\t\tnotableIndicies = { ", ints(j.NotableIndicies, ", "), " },\n")
		b.W("\t\t\tsocketIndicies = { ", ints(j.SocketIndicies, ", "), " },\n")
		b.W("\t\t\ttotalIndicies = ", j.TotalIndicies, ",\n")
		b.W("\t\t\tskills = {\n")
		for _, s := range j.Skills {
			b.W("\t\t\t\t[\"", s.Id, "\"] = {\n")
			b.W("\t\t\t\t\tname = \"", s.Name, "\",\n")
			b.W("\t\t\t\t\ticon = \"", s.Icon, "\",\n")
			if s.MasteryIcon != nil {
				b.W("\t\t\t\t\tmasteryIcon = \"", *s.MasteryIcon, "\",\n")
			}
			b.W("\t\t\t\t\ttag = \"", s.Tag, "\",\n")
			b.W("\t\t\t\t\tstats = { \"", strings.Join(s.Stats, "\", \""), "\" },\n")
			b.W("\t\t\t\t\tenchant = {\n")
			for _, line := range s.Stats {
				b.W("\t\t\t\t\t\t\"Added Small Passive Skills grant: ", line, "\",\n")
			}
			b.W("\t\t\t\t\t},\n")
			b.W("\t\t\t\t},\n")
		}
		b.W("\t\t\t},\n")
		b.W("\t\t},\n")
	}
	b.W("\t},\n")

	b.W("\tnotableSortOrder = {\n")
	for _, n := range cj.NotableSortOrder {
		b.W("\t\t[\"", n.Name, "\"] = ", n.Order, ",\n")
	}
	b.W("\t},\n")
	b.W("\tkeystones = {\n")
	for _, k := range cj.Keystones {
		b.W("\t\t\"", k, "\",\n")
	}
	b.W("\t},\n")
	b.W("\torbitOffsets = {\n")
	for _, o := range cj.OrbitOffsets {
		b.W("\t\t[", o.NodeId, "] = {\n")
		for i, start := range o.Starts {
			if i > 2 {
				break
			}
			b.W("\t\t\t[", i, "] = ", start, ",\n")
		}
		b.W("\t\t},\n")
	}
	b.W("\t},\n")

	b.W("}")
	return map[string]string{"Data/ClusterJewels.lua": b.String()}, nil
}
