// Renders gamedata.Pantheons as Data/Pantheons.lua (Scripts/pantheons.lua's
// output).

package luarender

import "github.com/MissingL-tter/missingPassives/gamedata"

func init() { register("pantheons", renderPantheons) }

func renderPantheons(ps gamedata.Pantheons, _ Templates) (map[string]string, error) {
	var b B
	b.W("-- This file is automatically generated, do not edit!\n")
	b.W("-- The Pantheon data (c) Grinding Gear Games\n\n")
	b.W("return {\n")
	for _, p := range ps {
		b.W("\t[\"", p.Id, "\"] = {\n")
		b.W("\t\tisMajorGod = ", luaStr(p.IsMajorGod), ",\n")
		b.W("\t\tsouls = {\n")
		for _, g := range p.Gods {
			b.W("\t\t\t[", g.Index, "] = { ")
			b.W("name = \"", g.Name, "\",\n")
			b.W("\t\t\t\tmods = {\n")
			for mi, m := range g.Mods {
				b.W("\t\t\t\t\t-- ", m.StatId, "\n")
				b.W("\t\t\t\t\t[", mi+1, "] = { line = \"", m.Line, "\", ")
				b.W("value = { ", m.Value, " }, ")
				b.W("},\n")
			}
			b.W("\t\t\t\t},\n")
			b.W("\t\t\t},\n")
		}
		b.W("\t\t},\n")
		b.W("\t},\n")
	}
	b.W("}")
	return map[string]string{"Data/Pantheons.lua": b.String()}, nil
}
