// Renders the tattooPassives and legionPassives documents by rebuilding the
// Lua-shaped tree the scripts serialized and reproducing their private
// stringify().

package luarender

import (
	"sort"
	"strings"

	"github.com/MissingL-tter/missingPassives/data/schema"
)

func init() {
	register("tattooPassives", renderTattooPassives)
	register("legionPassives", renderLegionPassives)
}

// lt is a Lua table under construction: int/float and string keys.
type lt map[any]any

func ltKeyNum(k any) float64 {
	switch n := k.(type) {
	case int:
		return float64(n)
	case int64:
		return float64(n)
	case float64:
		return n
	}
	return 0
}

// stringifyLua reproduces the scripts' stringify(): sorted keys, "\n\t"-led
// entries, trailing ", " after every value, nested tables re-indented by one
// tab, no string escaping.
func stringifyLua(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case bool:
		return luaStr(t)
	case float64:
		return luaNum(t)
	case lt:
		var b strings.Builder
		b.WriteString("{")
		keys := make([]any, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(a, b int) bool {
			if ka, ok := keys[a].(string); ok {
				return ka < keys[b].(string)
			}
			return ltKeyNum(keys[a]) < ltKeyNum(keys[b])
		})
		for _, k := range keys {
			b.WriteString("\n\t")
			if ks, ok := k.(string); ok {
				b.WriteString("[\"" + ks + "\"] = ")
			} else {
				b.WriteString("[" + luaNum(ltKeyNum(k)) + "] = ")
			}
			val := t[k]
			if s, ok := val.(string); ok {
				b.WriteString("\"" + s + "\", ")
			} else if sub, ok := val.(lt); ok {
				b.WriteString(strings.ReplaceAll(stringifyLua(sub)+", ", "\n", "\n\t"))
			} else {
				b.WriteString(stringifyLua(val) + ", ")
			}
		}
		b.WriteString("\n}")
		return b.String()
	}
	panic("stringifyLua: unsupported type")
}

// strTable is a 1-based array table of strings.
func strTable(lines []string) lt {
	t := lt{}
	for i, l := range lines {
		t[i+1] = l
	}
	return t
}

// statsTable rebuilds the per-stat table keyed by stat id.
func statsTable(stats []schema.PassiveStat) lt {
	t := lt{}
	for _, s := range stats {
		e := lt{"min": s.Min, "max": s.Max}
		if s.Fmt != "" {
			e["fmt"] = s.Fmt
		}
		if s.MinZ {
			e["minZ"] = true
		}
		if s.MaxZ {
			e["maxZ"] = true
		}
		if s.Index != nil {
			e["index"] = float64(*s.Index)
		}
		if s.StatOrder != nil {
			e["statOrder"] = *s.StatOrder
		}
		t[s.Id] = e
	}
	return t
}

// passivesGroup is the fixed off-screen group both scripts emit.
func passivesGroup(n lt) lt {
	return lt{
		float64(1e9): lt{
			"x":  float64(-6500),
			"y":  float64(-6500),
			"oo": lt{},
			"n":  n,
		},
	}
}

func passivesFile(data lt) string {
	return "-- This file is automatically generated, do not edit!\n-- Item data (c) Grinding Gear Games\n\n" +
		"return " + stringifyLua(data)
}

func renderTattooPassives(d schema.TattooPassives, _ Templates) (map[string]string, error) {
	nodes := lt{}
	for _, n := range d.Nodes {
		t := lt{
			"id":                n.Id,
			"stats":             statsTable(n.Stats),
			"isTattoo":          true,
			"overrideType":      n.OverrideType,
			"ks":                n.Ks,
			"not":               n.Not,
			"m":                 n.M,
			"targetType":        n.TargetType,
			"targetValue":       n.TargetValue,
			"MinimumConnected":  float64(n.MinimumConnected),
			"MaximumConnected":  float64(n.MaximumConnected),
			"activeEffectImage": n.ActiveEffectImage,
			"dn":                n.Name,
			"icon":              n.Icon,
			"sd":                strTable(n.Sd),
		}
		if n.ReminderText != nil {
			t["reminderText"] = lt{1: *n.ReminderText}
		}
		if n.OverrideType == "AlternateMastery" {
			t["name"] = "Runegraft Mastery"
		}
		if n.Legacy != nil {
			t["legacy"] = *n.Legacy
		}
		nodes[n.Name] = t
	}
	data := lt{
		"nodes":  nodes,
		"groups": passivesGroup(lt{}),
	}
	return map[string]string{"Data/TattooPassives.lua": passivesFile(data)}, nil
}

func renderLegionPassives(d schema.LegionPassives, _ Templates) (map[string]string, error) {
	nodes := lt{}
	for i, n := range d.Nodes {
		o := 3.0
		if n.Ks {
			o = 4.0
		}
		nodes[i+1] = lt{
			"id":                     n.Id,
			"icon":                   n.Icon,
			"ks":                     n.Ks,
			"not":                    n.Not,
			"dn":                     n.Dn,
			"m":                      false,
			"isJewelSocket":          false,
			"isMultipleChoice":       false,
			"isMultipleChoiceOption": false,
			"passivePointsGranted":   0.0,
			"spc":                    lt{},
			"sd":                     strTable(n.Sd),
			"stats":                  statsTable(n.Stats),
			"sortedStats":            strTable(n.SortedStats),
			"g":                      float64(1e9),
			"o":                      o,
			"oidx":                   n.Oidx,
			"sa":                     0.0,
			"da":                     0.0,
			"ia":                     0.0,
			"out":                    lt{},
			"in":                     lt{},
		}
	}
	groupN := lt{}
	for i := range d.Nodes {
		groupN[i+1] = float64(i + 1)
	}
	additions := lt{}
	for i, a := range d.Additions {
		additions[i+1] = lt{
			"id":          a.Id,
			"dn":          a.Dn,
			"sd":          strTable(a.Sd),
			"stats":       statsTable(a.Stats),
			"sortedStats": strTable(a.SortedStats),
		}
	}
	data := lt{
		"nodes":     nodes,
		"groups":    passivesGroup(groupN),
		"additions": additions,
	}
	return map[string]string{"Data/TimelessJewelData/LegionPassives.lua": passivesFile(data)}, nil
}
