// Renders schema.StatDescs as Data/StatDescriptions/<name>.lua
// (Scripts/statdesc.lua's outputs) by rebuilding the Lua table tree and
// reproducing Common.lua's writeLuaTable/qFmt.

package luarender

import (
	"sort"
	"strings"

	"github.com/MissingL-tter/missingPassives/data/schema"
)

func init() { register("statdesc", renderStatdesc) }

func qFmt(s string) string {
	return "\"" + strings.ReplaceAll(strings.ReplaceAll(s, "\n", "\\n"), "\"", "\\\"") + "\""
}

// bareKey is ^%a[%a%d]*$ — letters and digits only, starting with a letter
// ("hexproof" excluded, as in the reference).
func bareKey(s string) bool {
	if s == "" || s == "hexproof" {
		return false
	}
	for i, c := range s {
		isAlpha := (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
		isDigit := c >= '0' && c <= '9'
		if i == 0 && !isAlpha {
			return false
		}
		if !isAlpha && !isDigit {
			return false
		}
	}
	return true
}

func ltTypeRank(k any) int {
	switch k.(type) {
	case bool:
		return 0 // "boolean"
	case int, int64, float64:
		return 1 // "number"
	case string:
		return 2 // "string"
	}
	return 3
}

// writeLuaTable ports Common.lua's writeLuaTable.
func writeLuaTable(b *B, t lt, indent int) {
	b.W("{\n")
	keys := make([]any, 0, len(t))
	for k := range t {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(a, c int) bool {
		ra, rc := ltTypeRank(keys[a]), ltTypeRank(keys[c])
		if ra != rc {
			return ra < rc
		}
		if ra == 1 {
			return ltKeyNum(keys[a]) < ltKeyNum(keys[c])
		}
		if ra == 2 {
			return keys[a].(string) < keys[c].(string)
		}
		return false
	})
	for i, k := range keys {
		v := t[k]
		b.W(strings.Repeat("\t", indent))
		if ks, ok := k.(string); ok && bareKey(ks) {
			b.W(ks, "=")
		} else if ltTypeRank(k) == 1 {
			b.W("[", luaNum(ltKeyNum(k)), "]=")
		} else {
			b.W("[", qFmt(k.(string)), "]=")
		}
		switch vv := v.(type) {
		case lt:
			writeLuaTable(b, vv, indent+1)
		case string:
			b.W(qFmt(vv))
		case bool:
			b.W(luaStr(vv))
		case float64:
			b.W(luaNum(vv))
		default:
			panic("writeLuaTable: unsupported value")
		}
		if i < len(keys)-1 {
			b.W(",")
		}
		b.W("\n")
	}
	b.W(strings.Repeat("\t", indent-1))
	b.W("}")
}

func numOrStrVal(v *schema.NumOrStr) any {
	if v.Num != nil {
		return *v.Num
	}
	return *v.Str
}

func renderStatdesc(docs schema.StatDescs, _ Templates) (map[string]string, error) {
	files := map[string]string{}
	for name, f := range docs {
		root := lt{}
		for i, d := range f.Descriptors {
			t := lt{}
			if d.NoDesc {
				t["stats"] = lt{1: d.Stats[0]}
			} else {
				lang := lt{}
				for j, dl := range d.Lang {
					desc := lt{"text": dl.Text}
					limits := lt{}
					for li, lim := range dl.Limits {
						e := lt{}
						if lim.Min != nil {
							e[1] = numOrStrVal(lim.Min)
						}
						if lim.Max != nil {
							e[2] = numOrStrVal(lim.Max)
						}
						limits[li+1] = e
					}
					desc["limit"] = limits
					for si, sp := range dl.Specials {
						e := lt{"k": sp.K}
						switch {
						case sp.VBool != nil:
							e["v"] = *sp.VBool
						case sp.VNum != nil:
							e["v"] = *sp.VNum
						default:
							e["v"] = *sp.VStr
						}
						desc[si+1] = e
					}
					if dl.Quality != "" {
						desc[dl.Quality] = true
					}
					lang[j+1] = desc
				}
				t[1] = lang
				if d.Name != "" {
					t["name"] = d.Name
				}
				if d.Stats != nil {
					st := lt{}
					for j, s := range d.Stats {
						st[j+1] = s
					}
					t["stats"] = st
				}
			}
			root[i+1] = t
			for _, s := range d.Stats {
				root[s] = float64(i + 1)
			}
		}
		if f.Parent != "" {
			root["parent"] = f.Parent
		}

		var b B
		b.W("-- This file is automatically generated, do not edit!\n")
		b.W("-- Item data (c) Grinding Gear Games\n\nreturn ")
		writeLuaTable(&b, root, 1)
		files["Data/StatDescriptions/"+name+".lua"] = b.String()
	}
	return files, nil
}
