// processTemplate reproduces Main.lua's processTemplateFile for the render
// side: template text copied through, #directive lines dispatched.

package luarender

import (
	"regexp"
	"strings"
)

var reDirective = regexp.MustCompile(`#([A-Za-z]+) ?(.*)`)

func processTemplate(tpl Templates, name, inDir string, b *B, directives map[string]func(args string, b *B)) error {
	raw, err := tpl.Read("Export/" + inDir + name + ".txt")
	if err != nil {
		return err
	}
	b.W("-- This file is automatically generated, do not edit!\n")
	lines := strings.Split(strings.ReplaceAll(raw, "\r\n", "\n"), "\n")
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	for _, line := range lines {
		if m := reDirective.FindStringSubmatch(line); m != nil {
			if fn := directives[m[1]]; fn != nil {
				fn(m[2], b)
			}
			// unknown directives just print a warning in the Lua
		} else {
			b.W(line, "\n")
		}
	}
	return nil
}
