package config

// Options is ConfigOptions.lua's varList: every configuration variable the
// application knows, in the reference's order. The order is load-bearing -
// BuildModList applies the options in it, and a few read state an earlier
// one wrote. Labels, tooltips and the visibility predicates (ifCond,
// ifFlag, ifSkillData and their kin) are view and are not carried.
//
// Converted once from the booted reference; Go-maintained since.
var Options = []Option{
	{Var: "resistancePenalty", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Num(-30)}, {Val: Num(-60)}}, DefaultIndex: 3},
	{Var: "bandit", Kind: KindList, List: []ListEntry{{Val: Str("None")}, {Val: Str("Oak")}, {Val: Str("Kraityn")}, {Val: Str("Alira")}}, DefaultIndex: 1},
	{Var: "pantheonMajorGod", Kind: KindList, List: []ListEntry{{Val: Str("None")}, {Val: Str("TheBrineKing")}, {Val: Str("Lunaris")}, {Val: Str("Solaris")}, {Val: Str("Arakaali")}}, DefaultIndex: 1},
	{Var: "pantheonMinorGod", Kind: KindList, List: []ListEntry{{Val: Str("None")}, {Val: Str("Gruthkul")}, {Val: Str("Yugul")}, {Val: Str("Abberath")}, {Val: Str("Tukohama")}, {Val: Str("Garukhan")}, {Val: Str("Ralakesh")}, {Val: Str("Ryslatha")}, {Val: Str("Shakari")}}, DefaultIndex: 1},
	{Var: "detonateDeadCorpseLife", Kind: KindCount},
	{Var: "conditionStationary", Kind: KindCount},
	{Var: "conditionMoving", Kind: KindCheck},
	{Var: "conditionFullLife", Kind: KindCheck},
	{Var: "conditionLowLife", Kind: KindCheck},
	{Var: "conditionFullMana", Kind: KindCheck},
	{Var: "conditionLowMana", Kind: KindCheck},
	{Var: "conditionFullEnergyShield", Kind: KindCheck},
	{Var: "conditionLowEnergyShield", Kind: KindCheck},
	{Var: "conditionHaveEnergyShield", Kind: KindCheck},
	{Var: "conditionUnbrokenWard", Kind: KindCheck},
	{Var: "minionsConditionFullLife", Kind: KindCheck},
	{Var: "minionsConditionLowLife", Kind: KindCheck},
	{Var: "minionsConditionFullEnergyShield", Kind: KindCheck},
	{Var: "minionsConditionCreatedRecently", Kind: KindCheck},
	{Var: "ailmentMode", Kind: KindList, List: []ListEntry{{Val: Str("AVERAGE")}, {Val: Str("CRIT")}}},
	{Var: "physMode", Kind: KindList, List: []ListEntry{{Val: Str("AVERAGE")}, {Val: Str("FIRE")}, {Val: Str("COLD")}, {Val: Str("LIGHTNING")}}},
	{Var: "lifeRegenMode", Kind: KindList, List: []ListEntry{{Val: Str("MIN")}, {Val: Str("AVERAGE")}, {Val: Str("FULL")}}},
	{Var: "resourceGainMode", Kind: KindList, List: []ListEntry{{Val: Str("MIN")}, {Val: Str("AVERAGE")}, {Val: Str("MAX")}}, DefaultIndex: 2},
	{Var: "EHPUnluckyWorstOf", Kind: KindList, List: []ListEntry{{Val: Num(1)}, {Val: Num(2)}, {Val: Num(4)}}},
	{Var: "DisableEHPGainOnBlock", Kind: KindCheck},
	{Var: "armourCalculationMode", Kind: KindList, List: []ListEntry{{Val: Str("MIN")}, {Val: Str("AVERAGE")}, {Val: Str("MAX")}}},
	{Var: "warcryMode", Kind: KindList, List: []ListEntry{{Val: Str("AVERAGE")}, {Val: Str("MAX")}}},
	{Var: "pactMode", Kind: KindList, List: []ListEntry{{Val: Str("AVERAGE")}, {Val: Str("MAX")}}},
	{Var: "EVBypass", Kind: KindCheck},
	{Var: "ignoreItemDisablers", Kind: KindCheck},
	{Var: "ignoreJewelLimits", Kind: KindCheck},
	{Var: "excludeCullingDPS", Kind: KindCheck},
	{Var: "overrideEmptyRedSockets", Kind: KindCount},
	{Var: "overrideEmptyGreenSockets", Kind: KindCount},
	{Var: "overrideEmptyBlueSockets", Kind: KindCount},
	{Var: "overrideEmptyWhiteSockets", Kind: KindCount},
	{Var: "arcaneCloakUsedRecentlyCheck", Kind: KindCheck},
	{Var: "aspectOfTheAvianAviansMight", Kind: KindCheck},
	{Var: "aspectOfTheAvianAviansFlight", Kind: KindCheck},
	{Var: "aspectOfTheCatCatsStealth", Kind: KindCheck},
	{Var: "aspectOfTheCatCatsAgility", Kind: KindCheck},
	{Var: "overrideCrabBarriers", Kind: KindCountAllowZero},
	{Var: "aspectOfTheSpiderWebStacks", Kind: KindCountAllowZero},
	{Var: "bannerPlanted", Kind: KindCheck},
	{Var: "bannerValour", Kind: KindCount},
	{Var: "barkskinStacks", Kind: KindCount},
	{Var: "Unbound", Kind: KindCheck},
	{Var: "bladestormInBloodstorm", Kind: KindCheck},
	{Var: "bladestormInSandstorm", Kind: KindCheck},
	{Var: "bloodsoakedBannerStages", Kind: KindCount, Default: Num(1)},
	{Var: "bloodSacramentReservationEHP", Kind: KindCheck},
	{Var: "ActiveBrands", Kind: KindCount},
	{Var: "BrandsAttachedToEnemy", Kind: KindCount},
	{Var: "targetBrandedEnemy", Kind: KindCheck, Default: Bool(true)},
	{Var: "BrandsInLastQuarter", Kind: KindCheck},
	{Var: "BrandsInLastHalf", Kind: KindCheck},
	{Var: "carrionGolemNearbyMinion", Kind: KindCount},
	{Var: "carrionGolemEqualsChaosGolem", Kind: KindCheck},
	{Var: "chaosGolemEqualsStoneGolem", Kind: KindCheck},
	{Var: "cinderflameStacks", Kind: KindCount},
	{Var: "stoneGolemEqualsCarrionGolem", Kind: KindCheck},
	{Var: "closeCombatCombatRush", Kind: KindCheck},
	{Var: "ColdSnapBypassCD", Kind: KindCheck},
	{Var: "ConcPathBypassCD", Kind: KindCheck, Default: Bool(true)},
	{Var: "conditionCorruptingCryStages", Kind: KindCount, Default: Num(1)},
	{Var: "overrideCruelty", Kind: KindCount},
	{Var: "channellingCycloneCheck", Kind: KindCheck},
	{Var: "darkPactSkeletonLife", Kind: KindCount},
	{Var: "divineSentinelPhysAsFire", Kind: KindCheck},
	{Var: "divineSentinelPhysAsLightning", Kind: KindCheck},
	{Var: "divineSentinelRegenLife", Kind: KindCheck},
	{Var: "divineSentinelRegenMana", Kind: KindCheck},
	{Var: "divineSentinelChaosResistance", Kind: KindCheck},
	{Var: "divineSentinelSelfCurseEffect", Kind: KindCheck},
	{Var: "doomBlastSource", Kind: KindList, List: []ListEntry{{Val: Str("expiration")}, {Val: Str("replacement")}, {Val: Str("vixen")}, {Val: Str("hexblast")}}, DefaultIndex: 3},
	{Var: "curseOverlaps", Kind: KindCount},
	{Var: "elementalArmyExposureType", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Str("Fire")}, {Val: Str("Cold")}, {Val: Str("Lightning")}}},
	{Var: "embraceMadnessActive", Kind: KindCheck},
	{Var: "touchedDebuffsCount", Kind: KindCountAllowZero, Default: Num(10)},
	{Var: "feedingFrenzyFeedingFrenzyActive", Kind: KindCheck},
	{Var: "flameWallAddedDamage", Kind: KindCheck},
	{Var: "FlickerStrikeBypassCD", Kind: KindCheck, Default: Bool(true)},
	{Var: "freshMeatBuffs", Kind: KindCheck},
	{Var: "frostShieldStages", Kind: KindCount},
	{Var: "Disgorged", Kind: KindCheck},
	{Var: "greaterHarbingerOfTimeSlipstream", Kind: KindCheck},
	{Var: "harbingerOfTimeSlipstream", Kind: KindCheck},
	{Var: "multiplierHexDoom", Kind: KindCount},
	{Var: "heraldOfAgonyVirulenceStack", Kind: KindCount},
	{Var: "hoaOverkill", Kind: KindCount},
	{Var: "heraldOfTheHivePressure", Kind: KindCount},
	{Var: "inventionMineTrapPlacedDuration", Kind: KindCount},
	{Var: "iceNovaCastOnFrostbolt", Kind: KindCheck},
	{Var: "infusedChannellingInfusion", Kind: KindCheck},
	{Var: "innervateInnervation", Kind: KindCheck},
	{Var: "intensifyIntensity", Kind: KindCount},
	{Var: "OverloadedIntensity", Kind: KindCount},
	{Var: "multiplierLinkedTargets", Kind: KindCount},
	{Var: "linkedToMinion", Kind: KindCheck},
	{Var: "linkedSourceRate", Kind: KindFloat},
	{Var: "manabondMissingUnreservedManaPercentage", Kind: KindCount},
	{Var: "minionPactLife", Kind: KindCount},
	{Var: "conditionEnemyMalignantMadness", Kind: KindCheck},
	{Var: "meatShieldEnemyNearYou", Kind: KindCheck},
	{Var: "enemyHitMistyReflection", Kind: KindCheck},
	{Var: "MomentumStacks", Kind: KindCount},
	{Var: "MomentumSwiftnessStacks", Kind: KindCount},
	{Var: "plagueBearerState", Kind: KindList, List: []ListEntry{{Val: Str("INC")}, {Val: Str("INF")}}, DefaultIndex: 1},
	{Var: "perforateSpikeOverlap", Kind: KindCount},
	{Var: "physicalAegisDepleted", Kind: KindCheck},
	{Var: "deathmarkDeathmarkActive", Kind: KindCheck},
	{Var: "prideEffect", Kind: KindList, List: []ListEntry{{Val: Str("MIN")}, {Val: Str("MAX")}}},
	{Var: "sacrificedRageCount", Kind: KindCount},
	{Var: "raiseSpectreEnableBuffs", Kind: KindCheck, Default: Bool(true)},
	{Var: "raiseSpectreEnableCurses", Kind: KindCheck, Default: Bool(true)},
	{Var: "conditionSummonedSpectreInPast8Sec", Kind: KindCheck},
	{Var: "raiseSpectreBladeVortexBladeCount", Kind: KindCount},
	{Var: "raiseSpectreKaomFireBeamTotemStage", Kind: KindCount},
	{Var: "raiseSpectreEnableSummonedUrsaRallyingCry", Kind: KindCheck},
	{Var: "raiseSpectreEnableSlashingHorrorEnrage", Kind: KindCheck},
	{Var: "raiseSpectreEnableSanguimancerDemonLowLife", Kind: KindCheck},
	{Var: "raiseSpidersSpiderCount", Kind: KindCount},
	{Var: "conditionSummonedZombieInPast8Sec", Kind: KindCheck},
	{Var: "animateWeaponLingeringBlade", Kind: KindCheck},
	{Var: "returningProjectileHits", Kind: KindCount},
	{Var: "ShrapnelBallistaProjectileOverlap", Kind: KindCount},
	{Var: "sigilOfPowerStages", Kind: KindCountAllowZero, DefaultPlaceholder: Num(1)},
	{Var: "siphoningTrapAffectedEnemies", Kind: KindCount},
	{Var: "configSnipeStages", Kind: KindCount},
	{Var: "configSpectralTigerCount", Kind: KindCount, DefaultPlaceholder: Num(5)},
	{Var: "configSpectralWolfCount", Kind: KindCount},
	{Var: "bloodSandStance", Kind: KindList, List: []ListEntry{{Val: Str("BLOOD")}, {Val: Str("SAND")}}},
	{Var: "changedStance", Kind: KindCheck},
	{Var: "shardsConsumed", Kind: KindCount},
	{Var: "steelWards", Kind: KindCount},
	{Var: "stormRainBeamOverlap", Kind: KindCount},
	{Var: "stormRainActiveArrows", Kind: KindCount},
	{Var: "summonElementalRelicEnableAngerAura", Kind: KindCheck, Default: Bool(true)},
	{Var: "summonElementalRelicEnableHatredAura", Kind: KindCheck, Default: Bool(true)},
	{Var: "summonElementalRelicEnableWrathAura", Kind: KindCheck, Default: Bool(true)},
	{Var: "summonHolyRelicEnableHolyRelicBoon", Kind: KindCheck},
	{Var: "summonLightningGolemEnableWrath", Kind: KindCheck},
	{Var: "summonReaperConsumeRecently", Kind: KindCheck},
	{Var: "weepingBlackStacks", Kind: KindCount},
	{Var: "nearbyBleedingEnemies", Kind: KindCount},
	{Var: "tornadoShotSecondaryHitChance", Kind: KindCount},
	{Var: "toxicRainPodOverlap", Kind: KindCount},
	{Var: "traumaStacks", Kind: KindCount},
	{Var: "configResonanceCount", Kind: KindCount},
	{Var: "configUnholyResonanceCount", Kind: KindCount},
	{Var: "conditionInsane", Kind: KindCheck},
	{Var: "VigilantStrikeBypassCD", Kind: KindCheck, Default: Bool(true)},
	{Var: "voltaxicBurstSpellsQueued", Kind: KindCount},
	{Var: "vortexCastOnFrostbolt", Kind: KindCheck},
	{Var: "multiplierWarcryPower", Kind: KindCount},
	{Var: "waveOfConvictionExposureType", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Str("Fire")}, {Val: Str("Cold")}, {Val: Str("Lightning")}}},
	{Var: "multiplierWoCExpiredDuration", Kind: KindCount},
	{Var: "absolutionSkillDamageCountedOnce", Kind: KindCheck},
	{Var: "dominatingBlowSkillDamageCountedOnce", Kind: KindCheck},
	{Var: "holyStrikeSkillDamageCountedOnce", Kind: KindCheck},
	{Var: "MoltenShellDamageMitigated", Kind: KindCount},
	{Var: "VaalMoltenShellDamageMitigated", Kind: KindCount},
	{Var: "enemySizePreset", Kind: KindList, List: []ListEntry{{Val: Str("Small")}, {Val: Str("Medium")}, {Val: Str("Large")}, {Val: Str("Huge")}}, DefaultIndex: 2},
	{Var: "enemyRadius", Kind: KindInteger},
	{Var: "TotalMinionLife", Kind: KindInteger},
	{Var: "TotalSpectreLife", Kind: KindInteger},
	{Var: "TotalTotemLife", Kind: KindInteger},
	{Var: "TotalRadianceSentinelLife", Kind: KindInteger},
	{Var: "TotalVoidSpawnLife", Kind: KindInteger},
	{Var: "TotalStoneGolemLife", Kind: KindInteger},
	{Var: "TotalVaalRejuvenationTotemLife", Kind: KindInteger},
	{Var: "balanceOfTerrorSelfCastConductivity", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastDespair", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastElementalWeakness", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastEnfeeble", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastFlammability", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastFrostbite", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastPunishment", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastTemporalChains", Kind: KindCheck},
	{Var: "balanceOfTerrorSelfCastVulnerability", Kind: KindCheck},
	{Var: "multiplierSextant", Kind: KindCount},
	{Var: "multiplierMapModEffect", Kind: KindCount},
	{Var: "multiplierMapModTier", Kind: KindList, List: []ListEntry{{Val: Str("HIGH")}, {Val: Str("MED")}, {Val: Str("LOW")}}},
	{Var: "MapPrefix1", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("Armoured")}, {Val: Str("Hexproof")}, {Val: Str("Hexwarded")}, {Val: Str("Resistant")}, {Val: Str("Unstoppable")}, {Val: Str("Impervious")}, {Val: Str("Savage")}, {Val: Str("Burning")}, {Val: Str("Freezing")}, {Val: Str("Shocking")}, {Val: Str("Profane")}, {Val: Str("Fleet")}, {Val: Str("Impaling")}, {Val: Str("Conflagrating")}, {Val: Str("Empowered")}, {Val: Str("Overlord's")}}},
	{Var: "MapPrefix2", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("Armoured")}, {Val: Str("Hexproof")}, {Val: Str("Hexwarded")}, {Val: Str("Resistant")}, {Val: Str("Unstoppable")}, {Val: Str("Impervious")}, {Val: Str("Savage")}, {Val: Str("Burning")}, {Val: Str("Freezing")}, {Val: Str("Shocking")}, {Val: Str("Profane")}, {Val: Str("Fleet")}, {Val: Str("Impaling")}, {Val: Str("Conflagrating")}, {Val: Str("Empowered")}, {Val: Str("Overlord's")}}},
	{Var: "MapPrefix3", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("Armoured")}, {Val: Str("Hexproof")}, {Val: Str("Hexwarded")}, {Val: Str("Resistant")}, {Val: Str("Unstoppable")}, {Val: Str("Impervious")}, {Val: Str("Savage")}, {Val: Str("Burning")}, {Val: Str("Freezing")}, {Val: Str("Shocking")}, {Val: Str("Profane")}, {Val: Str("Fleet")}, {Val: Str("Impaling")}, {Val: Str("Conflagrating")}, {Val: Str("Empowered")}, {Val: Str("Overlord's")}}},
	{Var: "MapPrefix4", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("Armoured")}, {Val: Str("Hexproof")}, {Val: Str("Hexwarded")}, {Val: Str("Resistant")}, {Val: Str("Unstoppable")}, {Val: Str("Impervious")}, {Val: Str("Savage")}, {Val: Str("Burning")}, {Val: Str("Freezing")}, {Val: Str("Shocking")}, {Val: Str("Profane")}, {Val: Str("Fleet")}, {Val: Str("Impaling")}, {Val: Str("Conflagrating")}, {Val: Str("Empowered")}, {Val: Str("Overlord's")}}},
	{Var: "MapSuffix1", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("of Congealment")}, {Val: Str("of Drought")}, {Val: Str("of Exposure")}, {Val: Str("of Impotence")}, {Val: Str("of Insulation")}, {Val: Str("of Miring")}, {Val: Str("of Rust")}, {Val: Str("of Smothering")}, {Val: Str("of Stasis")}, {Val: Str("of Toughness")}, {Val: Str("of Fatigue")}, {Val: Str("of Doubt")}, {Val: Str("of Imprecision")}, {Val: Str("of Venom")}, {Val: Str("of Deadliness")}}},
	{Var: "MapSuffix2", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("of Congealment")}, {Val: Str("of Drought")}, {Val: Str("of Exposure")}, {Val: Str("of Impotence")}, {Val: Str("of Insulation")}, {Val: Str("of Miring")}, {Val: Str("of Rust")}, {Val: Str("of Smothering")}, {Val: Str("of Stasis")}, {Val: Str("of Toughness")}, {Val: Str("of Fatigue")}, {Val: Str("of Doubt")}, {Val: Str("of Imprecision")}, {Val: Str("of Venom")}, {Val: Str("of Deadliness")}}},
	{Var: "MapSuffix3", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("of Congealment")}, {Val: Str("of Drought")}, {Val: Str("of Exposure")}, {Val: Str("of Impotence")}, {Val: Str("of Insulation")}, {Val: Str("of Miring")}, {Val: Str("of Rust")}, {Val: Str("of Smothering")}, {Val: Str("of Stasis")}, {Val: Str("of Toughness")}, {Val: Str("of Fatigue")}, {Val: Str("of Doubt")}, {Val: Str("of Imprecision")}, {Val: Str("of Venom")}, {Val: Str("of Deadliness")}}},
	{Var: "MapSuffix4", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("of Congealment")}, {Val: Str("of Drought")}, {Val: Str("of Exposure")}, {Val: Str("of Impotence")}, {Val: Str("of Insulation")}, {Val: Str("of Miring")}, {Val: Str("of Rust")}, {Val: Str("of Smothering")}, {Val: Str("of Stasis")}, {Val: Str("of Toughness")}, {Val: Str("of Fatigue")}, {Val: Str("of Doubt")}, {Val: Str("of Imprecision")}, {Val: Str("of Venom")}, {Val: Str("of Deadliness")}}},
	{Var: "PvpScaling", Kind: KindCheck},
	{Var: "playerCursedWithAssassinsMark", Kind: KindCount},
	{Var: "playerCursedWithConductivity", Kind: KindCount},
	{Var: "playerCursedWithDespair", Kind: KindCount},
	{Var: "playerCursedWithElementalWeakness", Kind: KindCount},
	{Var: "playerCursedWithEnfeeble", Kind: KindCount},
	{Var: "playerCursedWithFlammability", Kind: KindCount},
	{Var: "playerCursedWithFrostbite", Kind: KindCount},
	{Var: "playerCursedWithPoachersMark", Kind: KindCount},
	{Var: "playerCursedWithProjectileWeakness", Kind: KindCount},
	{Var: "playerCursedWithPunishment", Kind: KindCount},
	{Var: "playerCursedWithTemporalChains", Kind: KindCount},
	{Var: "playerCursedWithVulnerability", Kind: KindCount},
	{Var: "playerCursedWithWarlordsMark", Kind: KindCount},
	{Var: "usePowerCharges", Kind: KindCheck},
	{Var: "overridePowerCharges", Kind: KindCount},
	{Var: "useFrenzyCharges", Kind: KindCheck},
	{Var: "overrideFrenzyCharges", Kind: KindCount},
	{Var: "useEnduranceCharges", Kind: KindCheck},
	{Var: "overrideEnduranceCharges", Kind: KindCount},
	{Var: "useSiphoningCharges", Kind: KindCheck},
	{Var: "overrideSiphoningCharges", Kind: KindCount},
	{Var: "useChallengerCharges", Kind: KindCheck},
	{Var: "overrideChallengerCharges", Kind: KindCount},
	{Var: "useBlitzCharges", Kind: KindCheck},
	{Var: "overrideBlitzCharges", Kind: KindCount},
	{Var: "multiplierGaleForce", Kind: KindCount},
	{Var: "overrideInspirationCharges", Kind: KindCountAllowZero},
	{Var: "useGhostShrouds", Kind: KindCheck},
	{Var: "overrideGhostShrouds", Kind: KindCount},
	{Var: "waitForMaxSeals", Kind: KindCheck},
	{Var: "repeatMode", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("AVERAGE")}, {Val: Str("FINAL")}, {Val: Str("FINAL_DPS")}}, DefaultIndex: 2},
	{Var: "ruthlessSupportMode", Kind: KindList, List: []ListEntry{{Val: Str("AVERAGE")}, {Val: Str("MAX")}}},
	{Var: "ChanceToIgnoreEnemyPhysicalDamageReductionMode", Kind: KindList, List: []ListEntry{{Val: Str("MIN")}, {Val: Str("AVERAGE")}, {Val: Str("MAX")}}, DefaultIndex: 2},
	{Var: "overrideBloodCharges", Kind: KindCountAllowZero},
	{Var: "overrideSpiritCharges", Kind: KindCountAllowZero},
	{Var: "overrideSpiritInfusion", Kind: KindCountAllowZero},
	{Var: "minionsUsePowerCharges", Kind: KindCheck},
	{Var: "minionsUseFrenzyCharges", Kind: KindCheck},
	{Var: "minionsUseEnduranceCharges", Kind: KindCheck},
	{Var: "minionsOverridePowerCharges", Kind: KindCount},
	{Var: "minionsOverrideFrenzyCharges", Kind: KindCount},
	{Var: "minionsOverrideEnduranceCharges", Kind: KindCount},
	{Var: "multiplierRampage", Kind: KindCount},
	{Var: "multiplierSoulEater", Kind: KindCount},
	{Var: "multiplierMinionSoulEater", Kind: KindCount},
	{Var: "conditionFocused", Kind: KindCheck},
	{Var: "buffLifetap", Kind: KindCheck},
	{Var: "buffOnslaught", Kind: KindCheck},
	{Var: "buffArcaneSurge", Kind: KindCheck},
	{Var: "minionBuffOnslaught", Kind: KindCheck},
	{Var: "buffUnholyMight", Kind: KindCheck},
	{Var: "minionbuffUnholyMight", Kind: KindCheck},
	{Var: "buffChaoticMight", Kind: KindCheck},
	{Var: "buffSacrificialZeal", Kind: KindCheck},
	{Var: "minionbuffChaoticMight", Kind: KindCheck},
	{Var: "buffPhasing", Kind: KindCheck},
	{Var: "buffFortification", Kind: KindCheck},
	{Var: "overrideFortification", Kind: KindCount},
	{Var: "buffTailwind", Kind: KindCheck},
	{Var: "buffAdrenaline", Kind: KindCheck},
	{Var: "conditionChangedStanceLastSecond", Kind: KindCheck},
	{Var: "buffAlchemistsGenius", Kind: KindCheck},
	{Var: "buffVaalArcLuckyHits", Kind: KindCheck},
	{Var: "buffElusive", Kind: KindCheck},
	{Var: "overrideBuffElusive", Kind: KindCount},
	{Var: "buffDivinity", Kind: KindCheck},
	{Var: "multiplierDefiance", Kind: KindCount},
	{Var: "multiplierRage", Kind: KindCount},
	{Var: "buffWildSavagery", Kind: KindCheck},
	{Var: "conditionLeeching", Kind: KindCheck},
	{Var: "conditionLeechingLife", Kind: KindCheck},
	{Var: "conditionLeechingEnergyShield", Kind: KindCheck},
	{Var: "conditionLeechingMana", Kind: KindCheck},
	{Var: "minionsConditionLeechingEnergyShield", Kind: KindCheck},
	{Var: "conditionUsingFlask", Kind: KindCheck},
	{Var: "conditionUsedAmethystFlaskRecently", Kind: KindCheck},
	{Var: "conditionUsedRubyFlaskRecently", Kind: KindCheck},
	{Var: "conditionUsedSapphireFlaskRecently", Kind: KindCheck},
	{Var: "conditionUsedTopazFlaskRecently", Kind: KindCheck},
	{Var: "conditionUsingTincture", Kind: KindCheck},
	{Var: "multiplierManaBurnStacks", Kind: KindCount},
	{Var: "conditionHaveTotem", Kind: KindCheck},
	{Var: "conditionSummonedTotemRecently", Kind: KindCheck},
	{Var: "TotemsSummoned", Kind: KindCount},
	{Var: "conditionSummonedGolemInPast8Sec", Kind: KindCheck},
	{Var: "conditionSummonedGolemInPast10Sec", Kind: KindCheck},
	{Var: "multiplierNearbyAlly", Kind: KindCount},
	{Var: "multiplierNearbyCorpse", Kind: KindCount},
	{Var: "multiplierSummonedMinion", Kind: KindCount},
	{Var: "multiplierNonVaalSummonedMinion", Kind: KindCount},
	{Var: "multiplierPermanentMinion", Kind: KindCount},
	{Var: "conditionOnConsecratedGround", Kind: KindCheck},
	{Var: "conditionOnProfaneGround", Kind: KindCheck},
	{Var: "minionConditionOnProfaneGround", Kind: KindCheck},
	{Var: "conditionOnBrineGround", Kind: KindCheck},
	{Var: "minionConditionOnBrineGround", Kind: KindCheck},
	{Var: "conditionOnCausticGround", Kind: KindCheck},
	{Var: "conditionOnFungalGround", Kind: KindCheck},
	{Var: "conditionOnBurningGround", Kind: KindCheck},
	{Var: "conditionOnChilledGround", Kind: KindCheck},
	{Var: "conditionOnShockedGround", Kind: KindCheck},
	{Var: "conditionBlinded", Kind: KindCheck},
	{Var: "conditionBurning", Kind: KindCheck},
	{Var: "conditionIgnited", Kind: KindCheck},
	{Var: "conditionScorched", Kind: KindCheck},
	{Var: "conditionChilled", Kind: KindCheck},
	{Var: "conditionChilledEffect", Kind: KindCount},
	{Var: "conditionFrozen", Kind: KindCheck},
	{Var: "conditionBrittle", Kind: KindCheck},
	{Var: "conditionShocked", Kind: KindCheck},
	{Var: "conditionPlayerShockEffect", Kind: KindCount},
	{Var: "conditionSapped", Kind: KindCheck},
	{Var: "conditionBleeding", Kind: KindCheck},
	{Var: "conditionPoisoned", Kind: KindCheck},
	{Var: "conditionCanBeCurseImmune", Kind: KindCheck},
	{Var: "multiplierPoisonOnSelf", Kind: KindCount},
	{Var: "multiplierWitheredStackCountSelf", Kind: KindCountAllowZero, DefaultPlaceholder: Num(15)},
	{Var: "multiplierNearbyEnemies", Kind: KindCount},
	{Var: "multiplierNearbyRareOrUniqueEnemies", Kind: KindCountAllowZero},
	{Var: "conditionHitRecently", Kind: KindCheck},
	{Var: "conditionHitSpellRecently", Kind: KindCheck},
	{Var: "conditionCritRecently", Kind: KindCheck},
	{Var: "conditionSkillCritRecently", Kind: KindCheck},
	{Var: "conditionCritWithHeraldSkillRecently", Kind: KindCheck},
	{Var: "multiplierCritRecently", Kind: KindCount},
	{Var: "LostNonVaalBuffRecently", Kind: KindCheck},
	{Var: "conditionNonCritRecently", Kind: KindCheck},
	{Var: "conditionChannelling", Kind: KindCheck},
	{Var: "multiplierChannelling", Kind: KindCount},
	{Var: "conditionHitRecentlyWithWeapon", Kind: KindCheck},
	{Var: "conditionKilledRecently", Kind: KindCheck},
	{Var: "multiplierKilledRecently", Kind: KindCount},
	{Var: "conditionKilledLast3Seconds", Kind: KindCheck},
	{Var: "conditionKilledPoisonedLast2Seconds", Kind: KindCheck},
	{Var: "conditionKilledTauntedEnemyRecently", Kind: KindCheck},
	{Var: "conditionTotemsNotSummonedInPastTwoSeconds", Kind: KindCheck},
	{Var: "conditionTotemsKilledRecently", Kind: KindCheck},
	{Var: "conditionTotemsHitRecently", Kind: KindCheck},
	{Var: "conditionTotemsHitSpellRecently", Kind: KindCheck},
	{Var: "conditionUsedBrandRecently", Kind: KindCheck},
	{Var: "multiplierTotemsKilledRecently", Kind: KindCount},
	{Var: "conditionMinionsKilledRecently", Kind: KindCheck},
	{Var: "conditionMinionsDiedRecently", Kind: KindCheck},
	{Var: "multiplierMinionsKilledRecently", Kind: KindCount},
	{Var: "conditionKilledAffectedByDoT", Kind: KindCheck},
	{Var: "multiplierShockedEnemyKilledRecently", Kind: KindCount},
	{Var: "multiplierShockedNonShockedEnemyRecently", Kind: KindCount},
	{Var: "conditionFrozenEnemyRecently", Kind: KindCheck},
	{Var: "conditionChilledEnemyRecently", Kind: KindCheck},
	{Var: "conditionShatteredEnemyRecently", Kind: KindCheck},
	{Var: "conditionIgnitedEnemyRecently", Kind: KindCheck},
	{Var: "multiplierIgniteAppliedRecently", Kind: KindCount},
	{Var: "conditionShockedEnemyRecently", Kind: KindCheck},
	{Var: "conditionStunnedEnemyRecently", Kind: KindCheck},
	{Var: "conditionStunnedRecently", Kind: KindCheck},
	{Var: "conditionPoisonedEnemyRecently", Kind: KindCheck},
	{Var: "multiplierPoisonAppliedRecently", Kind: KindCount},
	{Var: "multiplierLifeSpentRecently", Kind: KindCount},
	{Var: "multiplierManaSpentRecently", Kind: KindCount},
	{Var: "conditionWardBrokenPast2Seconds", Kind: KindCheck},
	{Var: "conditionBeenHitRecently", Kind: KindCheck},
	{Var: "multiplierBeenHitRecently", Kind: KindCount},
	{Var: "conditionBeenHitByAttackRecently", Kind: KindCheck},
	{Var: "conditionBeenCritRecently", Kind: KindCheck},
	{Var: "conditionConsumed12SteelShardsRecently", Kind: KindCheck},
	{Var: "conditionGainedPowerChargeRecently", Kind: KindCheck},
	{Var: "conditionGainedFrenzyChargeRecently", Kind: KindCheck},
	{Var: "conditionBeenSavageHitRecently", Kind: KindCheck},
	{Var: "conditionHitByFireDamageRecently", Kind: KindCheck},
	{Var: "conditionHitByColdDamageRecently", Kind: KindCheck},
	{Var: "conditionHitByLightningDamageRecently", Kind: KindCheck},
	{Var: "conditionHitBySpellDamageRecently", Kind: KindCheck},
	{Var: "conditionTakenFireDamageFromEnemyHitRecently", Kind: KindCheck},
	{Var: "conditionBlockedRecently", Kind: KindCheck},
	{Var: "conditionBlockedAttackRecently", Kind: KindCheck},
	{Var: "conditionBlockedSpellRecently", Kind: KindCheck},
	{Var: "conditionEnergyShieldRechargeRecently", Kind: KindCheck},
	{Var: "conditionEnergyShieldRechargePastTwoSec", Kind: KindCheck},
	{Var: "conditionStoppedTakingDamageOverTimeRecently", Kind: KindCheck},
	{Var: "conditionConvergence", Kind: KindCheck},
	{Var: "buffPendulum", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Str("AREA")}, {Val: Str("DAMAGE")}}},
	{Var: "buffConflux", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Str("CHILLING")}, {Val: Str("SHOCKING")}, {Val: Str("IGNITING")}, {Val: Str("ALL")}}},
	{Var: "highestDamageType", Kind: KindList, List: []ListEntry{{Val: Str("NONE")}, {Val: Str("Physical")}, {Val: Str("Lightning")}, {Val: Str("Cold")}, {Val: Str("Fire")}, {Val: Str("Chaos")}}},
	{Var: "buffHeartstopper", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Str("AVERAGE")}, {Val: Str("HIT")}, {Val: Str("DOT")}}},
	{Var: "buffBastionOfHope", Kind: KindCheck},
	{Var: "buffNgamahuFlamesAdvance", Kind: KindCheck},
	{Var: "buffHerEmbrace", Kind: KindCheck},
	{Var: "conditionChampionIntimidate", Kind: KindCheck, Default: Bool(true)},
	{Var: "conditionUsedSkillRecently", Kind: KindCheck},
	{Var: "multiplierSkillUsedRecently", Kind: KindCount},
	{Var: "conditionAttackedRecently", Kind: KindCheck},
	{Var: "conditionCastSpellRecently", Kind: KindCheck},
	{Var: "multiplierNonInstantSpellCastRecently", Kind: KindCount},
	{Var: "multiplierAppliedAilmentsRecently", Kind: KindCount},
	{Var: "conditionLinkedRecently", Kind: KindCheck},
	{Var: "conditionStunnedWhileCastingRecently", Kind: KindCheck},
	{Var: "conditionCastLast1Seconds", Kind: KindCheck},
	{Var: "multiplierCastLast8Seconds", Kind: KindCount},
	{Var: "conditionSuppressedRecently", Kind: KindCheck},
	{Var: "multiplierHitsSuppressedRecently", Kind: KindCount},
	{Var: "conditionUsedFireSkillRecently", Kind: KindCheck},
	{Var: "conditionUsedColdSkillRecently", Kind: KindCheck},
	{Var: "conditionUsedMinionSkillRecently", Kind: KindCheck},
	{Var: "conditionUsedTravelSkillRecently", Kind: KindCheck},
	{Var: "conditionUsedDashRecently", Kind: KindCheck},
	{Var: "conditionUsedMovementSkillRecently", Kind: KindCheck},
	{Var: "conditionUsedVaalSkillRecently", Kind: KindCheck},
	{Var: "multiplierUsedVaalSkillInPast8Seconds", Kind: KindCount},
	{Var: "conditionSoulGainPrevention", Kind: KindCheck},
	{Var: "conditionSacrificeMinion", Kind: KindCheck, Default: Bool(true)},
	{Var: "conditionUsedWarcryRecently", Kind: KindCheck},
	{Var: "conditionUsedWarcryInPast8Seconds", Kind: KindCheck},
	{Var: "multiplierAffectedByWarcryBuffDuration", Kind: KindCount},
	{Var: "DetonatedMinesRecently", Kind: KindCheck},
	{Var: "multiplierMineDetonatedRecently", Kind: KindCount},
	{Var: "minesPerThrow", Kind: KindCount},
	{Var: "TriggeredTrapsRecently", Kind: KindCheck},
	{Var: "multiplierTrapTriggeredRecently", Kind: KindCount},
	{Var: "conditionThrownTrapOrMineRecently", Kind: KindCheck},
	{Var: "trapsPerThrow", Kind: KindCount},
	{Var: "conditionCursedEnemyRecently", Kind: KindCheck},
	{Var: "conditionCastMarkRecently", Kind: KindCheck},
	{Var: "conditionSpawnedCorpseRecently", Kind: KindCheck},
	{Var: "conditionConsumedCorpseRecently", Kind: KindCheck},
	{Var: "conditionConsumedCorpseInPast2Sec", Kind: KindCheck},
	{Var: "multiplierCorpseConsumedRecently", Kind: KindCount},
	{Var: "conditionRavenousCorpseConsumed", Kind: KindCheck},
	{Var: "multiplierWarcryUsedRecently", Kind: KindCount},
	{Var: "conditionTauntedEnemyRecently", Kind: KindCheck},
	{Var: "conditionLostEnduranceChargeInPast8Sec", Kind: KindCheck},
	{Var: "multiplierEnduranceChargesLostRecently", Kind: KindCount},
	{Var: "conditionBlockedHitFromUniqueEnemyInPast10Sec", Kind: KindCheck},
	{Var: "conditionKilledUniqueEnemy", Kind: KindCheck},
	{Var: "BlockedPast10Sec", Kind: KindCount},
	{Var: "conditionImpaledRecently", Kind: KindCheck},
	{Var: "multiplierImpalesOnEnemy", Kind: KindCountAllowZero},
	{Var: "conditionCausedBleedingRecently", Kind: KindCheck},
	{Var: "multiplierBleedsOnEnemy", Kind: KindCount},
	{Var: "multiplierFragileRegrowth", Kind: KindCount},
	{Var: "conditionHaveArborix", Kind: KindCheck},
	{Var: "conditionHaveAugyre", Kind: KindList, List: []ListEntry{{Val: Str("EleOverload")}, {Val: Str("ResTechnique")}}},
	{Var: "conditionHaveVulconus", Kind: KindCheck},
	{Var: "conditionHaveManaStorm", Kind: KindCheck},
	{Var: "GamblesprintMovementSpeed", Kind: KindList, List: []ListEntry{{Val: Num(-40)}, {Val: Num(-20)}, {Val: Num(0)}, {Val: Num(20)}, {Val: Num(30)}, {Val: Num(40)}, {Val: Num(60)}, {Val: Num(80)}, {Val: Num(100)}}, DefaultIndex: 5},
	{Var: "EverlastingSacrifice", Kind: KindCheck},
	{Var: "buffFanaticism", Kind: KindCheck},
	{Var: "conditionHitsAlwaysStun", Kind: KindCheck},
	{Var: "multiplierPvpTvalueOverride", Kind: KindCount},
	{Var: "multiplierPvpDamage", Kind: KindCount},
	{Var: "buffAccelerationShrine", Kind: KindCheck},
	{Var: "buffBrutalShrine", Kind: KindCheck},
	{Var: "buffDiamondShrine", Kind: KindCheck},
	{Var: "buffDivineShrine", Kind: KindCheck},
	{Var: "buffEchoingShrine", Kind: KindCheck},
	{Var: "buffGloomShrine", Kind: KindCheck},
	{Var: "buffGreaterFreezingShrine", Kind: KindCheck},
	{Var: "buffGreaterShockingShrine", Kind: KindCheck},
	{Var: "buffGreaterSkeletalShrine", Kind: KindCheck},
	{Var: "buffImpenetrableShrine", Kind: KindCheck},
	{Var: "buffMassiveShrine", Kind: KindCheck},
	{Var: "buffReplenishingShrine", Kind: KindCheck},
	{Var: "buffResistanceShrine", Kind: KindCheck},
	{Var: "buffResonatingShrine", Kind: KindCheck},
	{Var: "buffLesserAccelerationShrine", Kind: KindCheck},
	{Var: "buffLesserBrutalShrine", Kind: KindCheck},
	{Var: "buffLesserImpenetrableShrine", Kind: KindCheck},
	{Var: "buffLesserMassiveShrine", Kind: KindCheck},
	{Var: "buffLesserReplenishingShrine", Kind: KindCheck},
	{Var: "buffLesserResistanceShrine", Kind: KindCheck},
	{Var: "skillForkCount", Kind: KindCount},
	{Var: "skillChainCount", Kind: KindCount},
	{Var: "skillPierceCount", Kind: KindCount},
	{Var: "meleeDistance", Kind: KindCount, DefaultPlaceholder: Num(15)},
	{Var: "projectileDistance", Kind: KindCount, DefaultPlaceholder: Num(40)},
	{Var: "conditionAtCloseRange", Kind: KindCheck},
	{Var: "enemyMultiplierEnemyPresenceSeconds", Kind: KindCount},
	{Var: "conditionEnemyMoving", Kind: KindCheck},
	{Var: "conditionEnemyFullLife", Kind: KindCheck},
	{Var: "conditionEnemyLowLife", Kind: KindCheck},
	{Var: "conditionEnemyCursed", Kind: KindCheck},
	{Var: "conditionEnemyStunned", Kind: KindCheck},
	{Var: "conditionEnemyBleeding", Kind: KindCheck},
	{Var: "overrideBleedStackPotential", Kind: KindCount},
	{Var: "conditionSingleBleed", Kind: KindCheck},
	{Var: "multiplierRuptureStacks", Kind: KindCount},
	{Var: "conditionEnemyPoisoned", Kind: KindCheck},
	{Var: "multiplierPoisonOnEnemy", Kind: KindCount},
	{Var: "conditionNonPoisonedOnly", Kind: KindCheck},
	{Var: "multiplierCurseExpiredOnEnemy", Kind: KindCount},
	{Var: "multiplierCurseDurationExpiredOnEnemy", Kind: KindCount},
	{Var: "multiplierWitheredStackCount", Kind: KindCount},
	{Var: "multiplierCorrosionStackCount", Kind: KindCount},
	{Var: "multiplierEnsnaredStackCount", Kind: KindCount},
	{Var: "conditionEnemyMaimed", Kind: KindCheck},
	{Var: "conditionEnemyHindered", Kind: KindCheck},
	{Var: "conditionEnemyExcommunicated", Kind: KindCheck},
	{Var: "conditionEnemyBlinded", Kind: KindCheck},
	{Var: "overrideBuffBlinded", Kind: KindCount},
	{Var: "conditionEnemyTaunted", Kind: KindCheck},
	{Var: "conditionEnemyDebilitated", Kind: KindCheck},
	{Var: "conditionEnemyPacified", Kind: KindCheck},
	{Var: "conditionEnemyBurning", Kind: KindCheck},
	{Var: "conditionEnemyIgnited", Kind: KindCheck},
	{Var: "overrideIgniteStackPotential", Kind: KindCount},
	{Var: "conditionEnemyScorched", Kind: KindCheck},
	{Var: "conditionScorchedEffect", Kind: KindCount},
	{Var: "ScorchStacks", Kind: KindInteger, DefaultPlaceholder: Num(1)},
	{Var: "conditionEnemyOnScorchedGround", Kind: KindCheck},
	{Var: "conditionEnemyChilled", Kind: KindCheck},
	{Var: "multiplierChilledByYouSeconds", Kind: KindCount},
	{Var: "conditionEnemyChilledEffect", Kind: KindCount},
	{Var: "conditionEnemyChilledByYourHits", Kind: KindCheck},
	{Var: "HoarfrostStacks", Kind: KindCount},
	{Var: "multiplierBarnacleStacks", Kind: KindCount},
	{Var: "conditionEnemyFrozen", Kind: KindCheck},
	{Var: "multiplierFrozenByYouSeconds", Kind: KindCount},
	{Var: "conditionEnemyBrittle", Kind: KindCheck},
	{Var: "conditionBrittleEffect", Kind: KindCount},
	{Var: "conditionEnemyOnBrittleGround", Kind: KindCheck},
	{Var: "conditionEnemyShocked", Kind: KindCheck},
	{Var: "conditionShockEffect", Kind: KindCount},
	{Var: "ShockStacks", Kind: KindCount, DefaultPlaceholder: Num(1)},
	{Var: "conditionEnemyOnShockedGround", Kind: KindCheck},
	{Var: "conditionEnemySapped", Kind: KindCheck},
	{Var: "conditionSapEffect", Kind: KindCount},
	{Var: "conditionEnemyOnSappedGround", Kind: KindCheck},
	{Var: "multiplierFreezeShockIgniteOnEnemy", Kind: KindCount},
	{Var: "conditionEnemyFireExposure", Kind: KindCheck},
	{Var: "conditionEnemyColdExposure", Kind: KindCheck},
	{Var: "conditionEnemyLightningExposure", Kind: KindCheck},
	{Var: "conditionEnemyIntimidated", Kind: KindCheck},
	{Var: "conditionEnemyCrushed", Kind: KindCheck},
	{Var: "conditionEnemyHallowingFlame", Kind: KindCheck},
	{Var: "multiplierEnemyHallowingFlame", Kind: KindCount, DefaultPlaceholder: Num(1)},
	{Var: "multiplierHallowingFlameStacksRemovedByAlly", Kind: KindCountAllowZero, DefaultPlaceholder: Num(1)},
	{Var: "conditionHallowingFlameMagnitude", Kind: KindCountAllowZero},
	{Var: "conditionNearLinkedTarget", Kind: KindCheck},
	{Var: "conditionEnemyUnnerved", Kind: KindCheck},
	{Var: "conditionEnemyCoveredInAsh", Kind: KindCheck},
	{Var: "conditionEnemyCoveredInFrost", Kind: KindCheck},
	{Var: "conditionEnemyOnConsecratedGround", Kind: KindCheck},
	{Var: "conditionEnemyHaveEnergyShield", Kind: KindCheck},
	{Var: "conditionEnemyOnProfaneGround", Kind: KindCheck},
	{Var: "multiplierEnemyAffectedByGraspingVines", Kind: KindCount},
	{Var: "conditionEnemyOnFungalGround", Kind: KindCheck},
	{Var: "conditionEnemyOnBrineGround", Kind: KindCheck},
	{Var: "conditionEnemyInChillingArea", Kind: KindCheck},
	{Var: "conditionEnemyInFrostGlobe", Kind: KindCheck},
	{Var: "conditionEnemyLifeHigherThanPlayer", Kind: KindCheck},
	{Var: "enemyConditionHitByFireDamage", Kind: KindCheck},
	{Var: "enemyConditionHitByColdDamage", Kind: KindCheck},
	{Var: "enemyConditionHitByLightningDamage", Kind: KindCheck},
	{Var: "enemyInRFOrScorchingRay", Kind: KindCheck},
	{Var: "EEIgnoreHitDamage", Kind: KindCheck},
	{Var: "conditionBetweenYouAndLinkedTarget", Kind: KindCheck},
	{Var: "conditionEnemyFireResZero", Kind: KindCheck},
	{Var: "conditionEnemyColdResZero", Kind: KindCheck},
	{Var: "conditionEnemyLightningResZero", Kind: KindCheck},
	{Var: "maniaDebuffsCount", Kind: KindCountAllowZero, Default: Num(15)},
	{Var: "enemyLevel", Kind: KindCount},
	{Var: "conditionEnemyRareOrUnique", Kind: KindCheck},
	{Var: "enemyIsBoss", Kind: KindList, List: []ListEntry{{Val: Str("None")}, {Val: Str("Boss")}, {Val: Str("Pinnacle")}, {Val: Str("Uber")}}, DefaultIndex: 3},
	{Var: "deliriousPercentage", Kind: KindList, List: []ListEntry{{Val: Num(0)}, {Val: Str("20Percent")}, {Val: Str("40Percent")}, {Val: Str("60Percent")}, {Val: Str("80Percent")}, {Val: Str("100Percent")}}},
	{Var: "enemyPhysicalReduction", Kind: KindInteger},
	{Var: "enemyLightningResist", Kind: KindCountAllowZero},
	{Var: "enemyColdResist", Kind: KindCountAllowZero},
	{Var: "enemyFireResist", Kind: KindCountAllowZero},
	{Var: "enemyChaosResist", Kind: KindCountAllowZero},
	{Var: "enemyMaxResist", Kind: KindCheck},
	{Var: "enemyBlockChance", Kind: KindCountAllowZero},
	{Var: "enemyEvasion", Kind: KindCountAllowZero},
	{Var: "enemyArmour", Kind: KindCountAllowZero},
	{Var: "presetBossSkills", Kind: KindList, List: []ListEntry{{Val: Str("None")}, {Val: Str("Atziri Flameblast")}, {Val: Str("Shaper Ball")}, {Val: Str("Shaper Slam")}, {Val: Str("Shaper Beam")}, {Val: Str("Sirus Meteor")}, {Val: Str("Cortex Ground Degen")}, {Val: Str("Exarch Ball")}, {Val: Str("Eater Beam")}, {Val: Str("Maven Fireball")}, {Val: Str("Maven Memory Game")}}, DefaultIndex: 1},
	{Var: "enemyDamageRollRange", Kind: KindInteger, DefaultPlaceholder: Num(70)},
	{Var: "enemyDamageType", Kind: KindList, List: []ListEntry{{Val: Str("Average")}, {Val: Str("Untyped")}, {Val: Str("DamageOverTime")}, {Val: Str("Melee")}, {Val: Str("Projectile")}, {Val: Str("Spell")}, {Val: Str("SpellProjectile")}}},
	{Var: "enemySpeed", Kind: KindCountAllowZero, DefaultPlaceholder: Num(700)},
	{Var: "enemyMultiplierPvpDamage", Kind: KindCount},
	{Var: "enemyCritChance", Kind: KindCountAllowZero, DefaultPlaceholder: Num(5)},
	{Var: "enemyCritDamage", Kind: KindCountAllowZero, DefaultPlaceholder: Num(30)},
	{Var: "enemyPhysicalDamage", Kind: KindCountAllowZero, DefaultPlaceholder: Num(7)},
	{Var: "enemyPhysicalOverwhelm", Kind: KindCountAllowZero},
	{Var: "enemyLightningDamage", Kind: KindCountAllowZero},
	{Var: "enemyLightningPen", Kind: KindCountAllowZero},
	{Var: "enemyColdDamage", Kind: KindCountAllowZero},
	{Var: "enemyColdPen", Kind: KindCountAllowZero},
	{Var: "enemyFireDamage", Kind: KindCountAllowZero},
	{Var: "enemyFirePen", Kind: KindCountAllowZero},
	{Var: "enemyChaosDamage", Kind: KindCountAllowZero},
}

// byVar indexes Options by name, for the apply functions that reach for
// another option's current selection.
var byVar = func() map[Var]*Option {
	m := make(map[Var]*Option, len(Options))
	for i := range Options {
		m[Options[i].Var] = &Options[i]
	}
	return m
}()
