package modparser

// List of modifier forms — ModParser.lua:72.
var formList = map[string]any{
	`^([0-9]+)% increased`:                                               "INC",
	`^([0-9]+)% faster`:                                                  "INC",
	`^([0-9]+)% reduced`:                                                 "RED",
	`^([0-9]+)% slower`:                                                  "RED",
	`^([0-9]+)% more`:                                                    "MORE",
	`^([0-9]+)% less`:                                                    "LESS",
	`^([+\-][0-9.]+)%?`:                                                  "BASE",
	`^([+\-][0-9.]+)%? to`:                                               "BASE",
	`^([+\-]?[0-9.]+)%? of`:                                              "BASE",
	`^([+\-][0-9.]+)%? base`:                                             "BASE",
	`^([+\-]?[0-9.]+)%? additional`:                                      "BASE",
	`([0-9]+) additional hits?`:                                          "BASE",
	`([0-9]+) additional times?`:                                         "BASE",
	`^throw up to ([0-9]+)`:                                              "BASE",
	`^you gain ([0-9.]+)`:                                                "GAIN",
	`^gains? ([0-9.]+)% of`:                                              "GAIN",
	`^gain ([0-9.]+)`:                                                    "GAIN",
	`^gain \+([0-9]+)% to`:                                               "GAIN",
	`^you lose ([0-9.]+)`:                                                "LOSE",
	`^loses? ([0-9.]+)% of`:                                              "LOSE",
	`^lose ([0-9.]+)`:                                                    "LOSE",
	`^lose \+([0-9]+)% to`:                                               "LOSE",
	`^grants ([0-9.]+)`:                                                  "GRANTS",  // local
	`^removes? ([0-9.]+) ?o?f? ?y?o?u?r?`:                                "REMOVES", // local
	`^([0-9]+)`:                                                          "BASE",
	`^([+\-]?[0-9]+)% chance`:                                            "CHANCE",
	`^([+\-]?[0-9]+)% chance to gain `:                                   "FLAG",
	`^([+\-]?[0-9]+)% additional chance`:                                 "CHANCE",
	`costs? ([+\-]?[0-9]+)`:                                              "TOTALCOST",
	`skills cost ([+\-]?[0-9]+)`:                                         "BASECOST",
	`penetrates? ([0-9]+)%`:                                              "PEN",
	`penetrates ([0-9]+)% of`:                                            "PEN",
	`penetrates ([0-9]+)% of enemy`:                                      "PEN",
	`^([0-9.]+) (.+) regenerated per second`:                             "REGENFLAT",
	`^([0-9.]+)% (.+) regenerated per second`:                            "REGENPERCENT",
	`^([0-9.]+)% of (.+) regenerated per second`:                         "REGENPERCENT",
	`^regenerate ([0-9.]+) (.*?) per second`:                             "REGENFLAT",
	`^regenerate ([0-9.]+)% (.*?) per second`:                            "REGENPERCENT",
	`^regenerate ([0-9.]+)% of (.*?) per second`:                         "REGENPERCENT",
	`^regenerate ([0-9.]+)% of your (.*?) per second`:                    "REGENPERCENT",
	`^you regenerate ([0-9.]+)% of (.*?) per second`:                     "REGENPERCENT",
	`^([0-9.]+) (.+) lost per second`:                                    "DEGENFLAT",
	`^([0-9.]+)% (.+) lost per second`:                                   "DEGENPERCENT",
	`^([0-9.]+)% of (.+) lost per second`:                                "DEGENPERCENT",
	`^lose ([0-9.]+) (.*?) per second`:                                   "DEGENFLAT",
	`^lose ([0-9.]+)% (.*?) per second`:                                  "DEGENPERCENT",
	`^lose ([0-9.]+)% of (.*?) per second`:                               "DEGENPERCENT",
	`^lose ([0-9.]+)% of your (.*?) per second`:                          "DEGENPERCENT",
	`^you lose ([0-9.]+)% of (.*?) per second`:                           "DEGENPERCENT",
	`^([0-9.]+) ([a-zA-Z]+) damage taken per second`:                     "DEGEN",
	`^([0-9.]+) ([a-zA-Z]+) damage per second`:                           "DEGEN",
	`([0-9]+) to ([0-9]+) added ([a-zA-Z]+) damage`:                      "DMG",
	`([0-9]+)-([0-9]+) added ([a-zA-Z]+) damage`:                         "DMG",
	`([0-9]+) to ([0-9]+) additional ([a-zA-Z]+) damage`:                 "DMG",
	`([0-9]+)-([0-9]+) additional ([a-zA-Z]+) damage`:                    "DMG",
	`^([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage`:                           "DMG",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage`:                       "DMG",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) damage`:                          "DMG",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage to attacks`:            "DMGATTACKS",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) damage to attacks`:               "DMGATTACKS",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) attack damage`:                "DMGATTACKS",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) attack damage`:                   "DMGATTACKS",
	`([0-9]+) to ([0-9]+) added attack ([a-zA-Z]+) damage`:               "DMGATTACKS",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage to spells`:             "DMGSPELLS",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) damage to spells`:                "DMGSPELLS",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) spell damage`:                 "DMGSPELLS",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) spell damage`:                    "DMGSPELLS",
	`([0-9]+) to ([0-9]+) added spell ([a-zA-Z]+) damage`:                "DMGSPELLS",
	`([0-9]+) to ([0-9]+) spell ([a-zA-Z]+) damage`:                      "DMGSPELLS",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage to attacks and spells`: "DMGBOTH",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) damage to attacks and spells`:    "DMGBOTH",
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage to spells and attacks`: "DMGBOTH", // o_O
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) damage to spells and attacks`:    "DMGBOTH", // o_O
	`adds ([0-9]+) to ([0-9]+) ([a-zA-Z]+) damage to hits`:               "DMGBOTH",
	`adds ([0-9]+)-([0-9]+) ([a-zA-Z]+) damage to hits`:                  "DMGBOTH",
	`^you have `:       "FLAG",
	`^have `:           "FLAG",
	`^you are `:        "FLAG",
	`^are `:            "FLAG",
	`^gain `:           "FLAG",
	`^you gain `:       "FLAG",
	`is (-?[0-9]+)%? `: "OVERRIDE",
	`is doubled`:       "DOUBLED",
	`doubles?`:         "DOUBLED",
	`causes? double`:   "DOUBLED",
}
