package modparser

// List of modifier flags — ModParser.lua:912.
var modFlagList = map[string]any{
	// Weapon types
	"with axes":                      Tag{"flags": ModFlag.Axe | ModFlag.Hit},
	"to axe attacks":                 Tag{"flags": ModFlag.Axe | ModFlag.Hit},
	"with axe attacks":               Tag{"flags": ModFlag.Axe | ModFlag.Hit},
	"with axes or swords":            d(p("flags", ModFlag.Hit), p("tag", Tag{"type": "ModFlagOr", "modFlags": ModFlag.Axe | ModFlag.Sword})),
	"with bows":                      Tag{"flags": ModFlag.Bow | ModFlag.Hit},
	"to bow attacks":                 Tag{"flags": ModFlag.Bow | ModFlag.Hit},
	"with bow attacks":               Tag{"flags": ModFlag.Bow | ModFlag.Hit},
	"with claws":                     Tag{"flags": ModFlag.Claw | ModFlag.Hit},
	"with claws or daggers":          d(p("flags", ModFlag.Hit), p("tag", Tag{"type": "ModFlagOr", "modFlags": ModFlag.Claw | ModFlag.Dagger})),
	"to claw attacks":                Tag{"flags": ModFlag.Claw | ModFlag.Hit},
	"with claw attacks":              Tag{"flags": ModFlag.Claw | ModFlag.Hit},
	"claw attacks":                   Tag{"flags": ModFlag.Claw | ModFlag.Hit},
	"dealt with claws":               Tag{"flags": ModFlag.Claw | ModFlag.Hit},
	"with daggers":                   Tag{"flags": ModFlag.Dagger | ModFlag.Hit},
	"to dagger attacks":              Tag{"flags": ModFlag.Dagger | ModFlag.Hit},
	"with dagger attacks":            Tag{"flags": ModFlag.Dagger | ModFlag.Hit},
	"with maces":                     Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"to mace attacks":                Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"with mace attacks":              Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"with maces and sceptres":        Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"with maces or sceptres":         Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"with maces, sceptres or staves": d(p("flags", ModFlag.Hit), p("tag", Tag{"type": "ModFlagOr", "modFlags": ModFlag.Mace | ModFlag.Staff})),
	"to mace and sceptre attacks":    Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"to mace or sceptre attacks":     Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"with mace or sceptre attacks":   Tag{"flags": ModFlag.Mace | ModFlag.Hit},
	"with staves":                    Tag{"flags": ModFlag.Staff | ModFlag.Hit},
	"to staff attacks":               Tag{"flags": ModFlag.Staff | ModFlag.Hit},
	"with staff attacks":             Tag{"flags": ModFlag.Staff | ModFlag.Hit},
	"with swords":                    Tag{"flags": ModFlag.Sword | ModFlag.Hit},
	"to sword attacks":               Tag{"flags": ModFlag.Sword | ModFlag.Hit},
	"with sword attacks":             Tag{"flags": ModFlag.Sword | ModFlag.Hit},
	"with wands":                     Tag{"flags": ModFlag.Wand | ModFlag.Hit},
	"to wand attacks":                Tag{"flags": ModFlag.Wand | ModFlag.Hit},
	"with wand attacks":              Tag{"flags": ModFlag.Wand | ModFlag.Hit},
	"unarmed":                        Tag{"flags": ModFlag.Unarmed | ModFlag.Hit},
	"unarmed melee":                  Tag{"flags": ModFlag.Unarmed | ModFlag.Melee | ModFlag.Hit},
	"with unarmed attacks":           Tag{"flags": ModFlag.Unarmed | ModFlag.Hit},
	"with unarmed melee attacks":     Tag{"flags": ModFlag.Unarmed | ModFlag.Melee},
	"with unarmed melee attack":      Tag{"flags": ModFlag.Unarmed | ModFlag.Melee},
	"to unarmed attacks":             Tag{"flags": ModFlag.Unarmed | ModFlag.Hit},
	"to unarmed melee hits":          Tag{"flags": ModFlag.Unarmed | ModFlag.Melee | ModFlag.Hit},
	"with melee weapons":             Tag{"flags": ModFlag.WeaponMelee},
	"with melee weapon attacks":      Tag{"flags": ModFlag.WeaponMelee}, // Tincture mod doesn't care about it being a Hit
	"from melee weapons":             Tag{"flags": ModFlag.WeaponMelee},
	"from melee weapon attacks":      Tag{"flags": ModFlag.WeaponMelee | ModFlag.Hit},
	"melee weapon":                   Tag{"flags": ModFlag.WeaponMelee},
	"with one handed weapons":        Tag{"flags": ModFlag.Weapon1H | ModFlag.Hit},
	"with one handed melee weapons":  Tag{"flags": ModFlag.Weapon1H | ModFlag.WeaponMelee | ModFlag.Hit},
	"with two handed weapons":        Tag{"flags": ModFlag.Weapon2H | ModFlag.Hit},
	"with two handed melee weapons":  Tag{"flags": ModFlag.Weapon2H | ModFlag.WeaponMelee | ModFlag.Hit},
	"with ranged weapons":            Tag{"flags": ModFlag.WeaponRanged | ModFlag.Hit},
	// Skill types
	"spell":                            Tag{"flags": ModFlag.Spell},
	"for spells":                       Tag{"flags": ModFlag.Spell},
	"for spell damage":                 Tag{"flags": ModFlag.Spell},
	"with spell damage":                Tag{"flags": ModFlag.Spell},
	"with spells":                      Tag{"keywordFlags": KeywordFlag.Spell},
	"with spell skills":                Tag{"keywordFlags": KeywordFlag.Spell},
	"with triggered spells":            d(p("keywordFlags", KeywordFlag.Spell), p("tag", Tag{"type": "SkillType", "skillType": SkillType.Triggered})),
	"by spells":                        Tag{"keywordFlags": KeywordFlag.Spell},
	"by your spells":                   Tag{"keywordFlags": KeywordFlag.Spell},
	"with attacks":                     Tag{"keywordFlags": KeywordFlag.Attack},
	"by attacks":                       Tag{"keywordFlags": KeywordFlag.Attack},
	"by your attacks":                  Tag{"keywordFlags": KeywordFlag.Attack},
	"with attack skills":               Tag{"keywordFlags": KeywordFlag.Attack},
	"for attacks":                      Tag{"flags": ModFlag.Attack},
	"for attack damage":                Tag{"flags": ModFlag.Attack},
	"weapon":                           Tag{"flags": ModFlag.Weapon},
	"with weapons":                     Tag{"flags": ModFlag.Weapon},
	"melee":                            Tag{"flags": ModFlag.Melee},
	"with melee attacks":               Tag{"flags": ModFlag.Melee},
	"with melee critical strikes":      d(p("flags", ModFlag.Melee), p("tag", Tag{"type": "Condition", "var": "CriticalStrike"})),
	"with melee skills":                d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Melee})),
	"with bow skills":                  Tag{"keywordFlags": KeywordFlag.Bow},
	"on melee hit":                     Tag{"flags": ModFlag.Melee | ModFlag.Hit},
	"on hit":                           Tag{"flags": ModFlag.Hit},
	"with hits":                        Tag{"keywordFlags": KeywordFlag.Hit},
	"with hits against nearby enemies": Tag{"keywordFlags": KeywordFlag.Hit},
	"with hits and ailments":           Tag{"keywordFlags": KeywordFlag.Hit | KeywordFlag.Ailment},
	"with ailments":                    Tag{"flags": ModFlag.Ailment},
	"with ailments from attack skills": Tag{"flags": ModFlag.Ailment, "keywordFlags": KeywordFlag.Attack},
	"with poison":                      Tag{"keywordFlags": KeywordFlag.Poison},
	"with bleeding":                    Tag{"keywordFlags": KeywordFlag.Bleed},
	"for ailments":                     Tag{"flags": ModFlag.Ailment},
	"for poison":                       Tag{"keywordFlags": KeywordFlag.Poison | KeywordFlag.MatchAll},
	"for bleeding":                     Tag{"keywordFlags": KeywordFlag.Bleed},
	"for ignite":                       Tag{"keywordFlags": KeywordFlag.Ignite},
	"against damage over time":         Tag{"flags": ModFlag.Dot},
	"area":                             Tag{"flags": ModFlag.Area},
	"mine":                             Tag{"keywordFlags": KeywordFlag.Mine},
	"with mines":                       Tag{"keywordFlags": KeywordFlag.Mine},
	"trap":                             Tag{"keywordFlags": KeywordFlag.Trap},
	"with traps":                       Tag{"keywordFlags": KeywordFlag.Trap},
	"for traps":                        Tag{"keywordFlags": KeywordFlag.Trap},
	"skills which throw traps have":    Tag{"keywordFlags": KeywordFlag.Trap},
	"that place mines or throw traps":  Tag{"keywordFlags": KeywordFlag.Mine | KeywordFlag.Trap},
	"that throw mines":                 Tag{"keywordFlags": KeywordFlag.Mine},
	"that throw traps":                 Tag{"keywordFlags": KeywordFlag.Trap},
	"brand":                            Tag{"keywordFlags": KeywordFlag.Brand},
	"totem":                            Tag{"keywordFlags": KeywordFlag.Totem},
	"with totem skills":                Tag{"keywordFlags": KeywordFlag.Totem},
	"for skills used by totems":        Tag{"keywordFlags": KeywordFlag.Totem},
	"totem skills that cast an aura":   d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura}), p("keywordFlags", KeywordFlag.Totem)),
	"aura skills that summon totems":   d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura}), p("keywordFlags", KeywordFlag.Totem)),
	"of aura skills":                   d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura})),
	"curse skills":                     Tag{"keywordFlags": KeywordFlag.Curse},
	"of curse skills":                  Tag{"keywordFlags": KeywordFlag.Curse},
	"with curse skills":                Tag{"keywordFlags": KeywordFlag.Curse},
	"of curse aura skills":             d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura}), p("keywordFlags", KeywordFlag.Curse)),
	"of curse auras":                   Tag{"keywordFlags": KeywordFlag.Curse | KeywordFlag.Aura | KeywordFlag.MatchAll},
	"of hex skills":                    d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Hex})),
	"with hex skills":                  d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Hex})),
	"by retaliation skills":            d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Retaliation})),
	"of herald skills":                 d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Herald})),
	"with herald skills":               d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Herald})),
	"with hits from herald skills":     d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Herald}), p("keywordFlags", KeywordFlag.Hit)),
	"minion skills":                    d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Minion})),
	"with minion skills":               d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Minion})),
	"of minion skills":                 d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Minion})),
	"link skills":                      d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Link})),
	"of link skills":                   d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Link})),
	"for curses":                       Tag{"keywordFlags": KeywordFlag.Curse},
	"for hexes":                        d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Hex})),
	"warcry":                           Tag{"keywordFlags": KeywordFlag.Warcry},
	"vaal":                             Tag{"keywordFlags": KeywordFlag.Vaal},
	"vaal skill":                       Tag{"keywordFlags": KeywordFlag.Vaal},
	"with vaal skills":                 Tag{"keywordFlags": KeywordFlag.Vaal},
	"with non-vaal skills":             d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Vaal, "neg": true})),
	"with movement skills":             Tag{"keywordFlags": KeywordFlag.Movement},
	"of movement skills":               Tag{"keywordFlags": KeywordFlag.Movement},
	"of movement skills used":          Tag{"keywordFlags": KeywordFlag.Movement},
	"of travel skills":                 d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Travel})),
	"of banner skills":                 d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Banner})),
	"lightning skills":                 Tag{"keywordFlags": KeywordFlag.Lightning},
	"with lightning skills":            Tag{"keywordFlags": KeywordFlag.Lightning},
	"with cold skills":                 Tag{"keywordFlags": KeywordFlag.Cold},
	"with fire skills":                 Tag{"keywordFlags": KeywordFlag.Fire},
	"with elemental skills":            Tag{"keywordFlags": KeywordFlag.Lightning | KeywordFlag.Cold | KeywordFlag.Fire},
	"with chaos skills":                Tag{"keywordFlags": KeywordFlag.Chaos},
	"with physical skills":             Tag{"keywordFlags": KeywordFlag.Physical},
	"with channelling skills":          d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel})),
	"channelling":                      d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel})),
	"channelling skills":               d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel})),
	"non-channelling":                  d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel, "neg": true})),
	"non-channelling skills":           d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel, "neg": true})),
	"with brand skills":                d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Brand})),
	"for stance skills":                d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Stance})),
	"of stance skills":                 d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Stance})),
	"mark skills":                      d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Mark})),
	"of mark skills":                   d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Mark})),
	"with skills that cost life":       d(p("tag", Tag{"type": "StatThreshold", "stat": "LifeCost", "threshold": 1})),
	"minion":                           Tag{"addToMinion": true},
	"zombie":                           d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Zombie", "includeTransfigured": true})),
	"raised zombie":                    d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Zombie", "includeTransfigured": true})),
	"skeleton":                         d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Skeletons", "includeTransfigured": true})),
	"spectre":                          d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Spectre", "includeTransfigured": true})),
	"raised spectre":                   d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Spectre", "includeTransfigured": true})),
	"golem":                            d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillType", "skillType": SkillType.Golem})),
	"chaos golem":                      d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Chaos Golem", "includeTransfigured": true})),
	"flame golem":                      d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Flame Golem", "includeTransfigured": true})),
	"increased flame golem":            d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Flame Golem", "includeTransfigured": true})),
	"ice golem":                        d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Ice Golem", "includeTransfigured": true})),
	"lightning golem":                  d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Lightning Golem", "includeTransfigured": true})),
	"stone golem":                      d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Stone Golem", "includeTransfigured": true})),
	"animated guardian":                d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Animate Guardian", "includeTransfigured": true})),
	// Damage types
	"with physical damage":  d(p("tag", Tag{"type": "Condition", "var": "PhysicalHasDamage"})),
	"with lightning damage": d(p("tag", Tag{"type": "Condition", "var": "LightningHasDamage"})),
	"with cold damage":      d(p("tag", Tag{"type": "Condition", "var": "ColdHasDamage"})),
	"with fire damage":      d(p("tag", Tag{"type": "Condition", "var": "FireHasDamage"})),
	"with chaos damage":     d(p("tag", Tag{"type": "Condition", "var": "ChaosHasDamage"})),
	// Other
	"global":                          d(p("tag", Tag{"type": "Global"})),
	"from equipped shield":            d(p("tag", Tag{"type": "SlotName", "slotName": "Weapon 2"})),
	"from equipped armour items":      d(p("tag", d(p("type", "SlotName"), p("slotNameList", d("Helmet", "Body Armour", "Gloves", "Boots", "Weapon 2"))))),
	"from equipped helmet":            d(p("tag", Tag{"type": "SlotName", "slotName": "Helmet"})),
	"from equipped gloves and boots":  d(p("tag", d(p("type", "SlotName"), p("slotNameList", d("Gloves", "Boots"))))),
	"from equipped boots and gloves":  d(p("tag", d(p("type", "SlotName"), p("slotNameList", d("Gloves", "Boots"))))),
	"from equipped helmet and gloves": d(p("tag", d(p("type", "SlotName"), p("slotNameList", d("Helmet", "Gloves"))))),
	"from equipped helmet and boots":  d(p("tag", d(p("type", "SlotName"), p("slotNameList", d("Helmet", "Boots"))))),
	"from your equipped body armour":  d(p("tag", Tag{"type": "SlotName", "slotName": "Body Armour"})),
	"from equipped body armour":       d(p("tag", Tag{"type": "SlotName", "slotName": "Body Armour"})),
	"from body armour":                d(p("tag", Tag{"type": "SlotName", "slotName": "Body Armour"})),
	"from your body armour":           d(p("tag", Tag{"type": "SlotName", "slotName": "Body Armour"})),
}
