package modparser

// List of modifier flags — ModParser.lua:912.
var modFlagList = map[string]*PatternEntry{
	// Weapon types
	"with axes":                      &PatternEntry{Flags: FlagAxe | FlagHit},
	"to axe attacks":                 &PatternEntry{Flags: FlagAxe | FlagHit},
	"with axe attacks":               &PatternEntry{Flags: FlagAxe | FlagHit},
	"with axes or swords":            &PatternEntry{Flags: FlagHit, Tag: &ModFlagOrTag{ModFlags: FlagAxe | FlagSword}},
	"with bows":                      &PatternEntry{Flags: FlagBow | FlagHit},
	"to bow attacks":                 &PatternEntry{Flags: FlagBow | FlagHit},
	"with bow attacks":               &PatternEntry{Flags: FlagBow | FlagHit},
	"with claws":                     &PatternEntry{Flags: FlagClaw | FlagHit},
	"with claws or daggers":          &PatternEntry{Flags: FlagHit, Tag: &ModFlagOrTag{ModFlags: FlagClaw | FlagDagger}},
	"to claw attacks":                &PatternEntry{Flags: FlagClaw | FlagHit},
	"with claw attacks":              &PatternEntry{Flags: FlagClaw | FlagHit},
	"claw attacks":                   &PatternEntry{Flags: FlagClaw | FlagHit},
	"dealt with claws":               &PatternEntry{Flags: FlagClaw | FlagHit},
	"with daggers":                   &PatternEntry{Flags: FlagDagger | FlagHit},
	"to dagger attacks":              &PatternEntry{Flags: FlagDagger | FlagHit},
	"with dagger attacks":            &PatternEntry{Flags: FlagDagger | FlagHit},
	"with maces":                     &PatternEntry{Flags: FlagMace | FlagHit},
	"to mace attacks":                &PatternEntry{Flags: FlagMace | FlagHit},
	"with mace attacks":              &PatternEntry{Flags: FlagMace | FlagHit},
	"with maces and sceptres":        &PatternEntry{Flags: FlagMace | FlagHit},
	"with maces or sceptres":         &PatternEntry{Flags: FlagMace | FlagHit},
	"with maces, sceptres or staves": &PatternEntry{Flags: FlagHit, Tag: &ModFlagOrTag{ModFlags: FlagMace | FlagStaff}},
	"to mace and sceptre attacks":    &PatternEntry{Flags: FlagMace | FlagHit},
	"to mace or sceptre attacks":     &PatternEntry{Flags: FlagMace | FlagHit},
	"with mace or sceptre attacks":   &PatternEntry{Flags: FlagMace | FlagHit},
	"with staves":                    &PatternEntry{Flags: FlagStaff | FlagHit},
	"to staff attacks":               &PatternEntry{Flags: FlagStaff | FlagHit},
	"with staff attacks":             &PatternEntry{Flags: FlagStaff | FlagHit},
	"with swords":                    &PatternEntry{Flags: FlagSword | FlagHit},
	"to sword attacks":               &PatternEntry{Flags: FlagSword | FlagHit},
	"with sword attacks":             &PatternEntry{Flags: FlagSword | FlagHit},
	"with wands":                     &PatternEntry{Flags: FlagWand | FlagHit},
	"to wand attacks":                &PatternEntry{Flags: FlagWand | FlagHit},
	"with wand attacks":              &PatternEntry{Flags: FlagWand | FlagHit},
	"unarmed":                        &PatternEntry{Flags: FlagUnarmed | FlagHit},
	"unarmed melee":                  &PatternEntry{Flags: FlagUnarmed | FlagMelee | FlagHit},
	"with unarmed attacks":           &PatternEntry{Flags: FlagUnarmed | FlagHit},
	"with unarmed melee attacks":     &PatternEntry{Flags: FlagUnarmed | FlagMelee},
	"with unarmed melee attack":      &PatternEntry{Flags: FlagUnarmed | FlagMelee},
	"to unarmed attacks":             &PatternEntry{Flags: FlagUnarmed | FlagHit},
	"to unarmed melee hits":          &PatternEntry{Flags: FlagUnarmed | FlagMelee | FlagHit},
	"with melee weapons":             &PatternEntry{Flags: FlagWeaponMelee},
	"with melee weapon attacks":      &PatternEntry{Flags: FlagWeaponMelee}, // Tincture mod doesn't care about it being a Hit
	"from melee weapons":             &PatternEntry{Flags: FlagWeaponMelee},
	"from melee weapon attacks":      &PatternEntry{Flags: FlagWeaponMelee | FlagHit},
	"melee weapon":                   &PatternEntry{Flags: FlagWeaponMelee},
	"with one handed weapons":        &PatternEntry{Flags: FlagWeapon1H | FlagHit},
	"with one handed melee weapons":  &PatternEntry{Flags: FlagWeapon1H | FlagWeaponMelee | FlagHit},
	"with two handed weapons":        &PatternEntry{Flags: FlagWeapon2H | FlagHit},
	"with two handed melee weapons":  &PatternEntry{Flags: FlagWeapon2H | FlagWeaponMelee | FlagHit},
	"with ranged weapons":            &PatternEntry{Flags: FlagWeaponRanged | FlagHit},
	// Skill types
	"spell":                            &PatternEntry{Flags: FlagSpell},
	"for spells":                       &PatternEntry{Flags: FlagSpell},
	"for spell damage":                 &PatternEntry{Flags: FlagSpell},
	"with spell damage":                &PatternEntry{Flags: FlagSpell},
	"with spells":                      &PatternEntry{KeywordFlags: KeywordSpell},
	"with spell skills":                &PatternEntry{KeywordFlags: KeywordSpell},
	"with triggered spells":            &PatternEntry{KeywordFlags: KeywordSpell, Tag: &SkillTypeTag{SkillType: SkillTypeTriggered}},
	"by spells":                        &PatternEntry{KeywordFlags: KeywordSpell},
	"by your spells":                   &PatternEntry{KeywordFlags: KeywordSpell},
	"with attacks":                     &PatternEntry{KeywordFlags: KeywordAttack},
	"by attacks":                       &PatternEntry{KeywordFlags: KeywordAttack},
	"by your attacks":                  &PatternEntry{KeywordFlags: KeywordAttack},
	"with attack skills":               &PatternEntry{KeywordFlags: KeywordAttack},
	"for attacks":                      &PatternEntry{Flags: FlagAttack},
	"for attack damage":                &PatternEntry{Flags: FlagAttack},
	"weapon":                           &PatternEntry{Flags: FlagWeapon},
	"with weapons":                     &PatternEntry{Flags: FlagWeapon},
	"melee":                            &PatternEntry{Flags: FlagMelee},
	"with melee attacks":               &PatternEntry{Flags: FlagMelee},
	"with melee critical strikes":      &PatternEntry{Flags: FlagMelee, Tag: &CondTag{Var: "CriticalStrike"}},
	"with melee skills":                &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMelee}},
	"with bow skills":                  &PatternEntry{KeywordFlags: KeywordBow},
	"on melee hit":                     &PatternEntry{Flags: FlagMelee | FlagHit},
	"on hit":                           &PatternEntry{Flags: FlagHit},
	"with hits":                        &PatternEntry{KeywordFlags: KeywordHit},
	"with hits against nearby enemies": &PatternEntry{KeywordFlags: KeywordHit},
	"with hits and ailments":           &PatternEntry{KeywordFlags: KeywordHit | KeywordAilment},
	"with ailments":                    &PatternEntry{Flags: FlagAilment},
	"with ailments from attack skills": &PatternEntry{Flags: FlagAilment, KeywordFlags: KeywordAttack},
	"with poison":                      &PatternEntry{KeywordFlags: KeywordPoison},
	"with bleeding":                    &PatternEntry{KeywordFlags: KeywordBleed},
	"for ailments":                     &PatternEntry{Flags: FlagAilment},
	"for poison":                       &PatternEntry{KeywordFlags: KeywordPoison | KeywordMatchAll},
	"for bleeding":                     &PatternEntry{KeywordFlags: KeywordBleed},
	"for ignite":                       &PatternEntry{KeywordFlags: KeywordIgnite},
	"against damage over time":         &PatternEntry{Flags: FlagDot},
	"area":                             &PatternEntry{Flags: FlagArea},
	"mine":                             &PatternEntry{KeywordFlags: KeywordMine},
	"with mines":                       &PatternEntry{KeywordFlags: KeywordMine},
	"trap":                             &PatternEntry{KeywordFlags: KeywordTrap},
	"with traps":                       &PatternEntry{KeywordFlags: KeywordTrap},
	"for traps":                        &PatternEntry{KeywordFlags: KeywordTrap},
	"skills which throw traps have":    &PatternEntry{KeywordFlags: KeywordTrap},
	"that place mines or throw traps":  &PatternEntry{KeywordFlags: KeywordMine | KeywordTrap},
	"that throw mines":                 &PatternEntry{KeywordFlags: KeywordMine},
	"that throw traps":                 &PatternEntry{KeywordFlags: KeywordTrap},
	"brand":                            &PatternEntry{KeywordFlags: KeywordBrand},
	"totem":                            &PatternEntry{KeywordFlags: KeywordTotem},
	"with totem skills":                &PatternEntry{KeywordFlags: KeywordTotem},
	"for skills used by totems":        &PatternEntry{KeywordFlags: KeywordTotem},
	"totem skills that cast an aura":   &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeAura}, KeywordFlags: KeywordTotem},
	"aura skills that summon totems":   &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeAura}, KeywordFlags: KeywordTotem},
	"of aura skills":                   &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeAura}},
	"curse skills":                     &PatternEntry{KeywordFlags: KeywordCurse},
	"of curse skills":                  &PatternEntry{KeywordFlags: KeywordCurse},
	"with curse skills":                &PatternEntry{KeywordFlags: KeywordCurse},
	"of curse aura skills":             &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeAura}, KeywordFlags: KeywordCurse},
	"of curse auras":                   &PatternEntry{KeywordFlags: KeywordCurse | KeywordAura | KeywordMatchAll},
	"of hex skills":                    &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHex}},
	"with hex skills":                  &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHex}},
	"by retaliation skills":            &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeRetaliation}},
	"of herald skills":                 &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHerald}},
	"with herald skills":               &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHerald}},
	"with hits from herald skills":     &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHerald}, KeywordFlags: KeywordHit},
	"minion skills":                    &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMinion}},
	"with minion skills":               &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMinion}},
	"of minion skills":                 &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMinion}},
	"link skills":                      &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeLink}},
	"of link skills":                   &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeLink}},
	"for curses":                       &PatternEntry{KeywordFlags: KeywordCurse},
	"for hexes":                        &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHex}},
	"warcry":                           &PatternEntry{KeywordFlags: KeywordWarcry},
	"vaal":                             &PatternEntry{KeywordFlags: KeywordVaal},
	"vaal skill":                       &PatternEntry{KeywordFlags: KeywordVaal},
	"with vaal skills":                 &PatternEntry{KeywordFlags: KeywordVaal},
	"with non-vaal skills":             &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeVaal, Neg: true}},
	"with movement skills":             &PatternEntry{KeywordFlags: KeywordMovement},
	"of movement skills":               &PatternEntry{KeywordFlags: KeywordMovement},
	"of movement skills used":          &PatternEntry{KeywordFlags: KeywordMovement},
	"of travel skills":                 &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeTravel}},
	"of banner skills":                 &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeBanner}},
	"lightning skills":                 &PatternEntry{KeywordFlags: KeywordLightning},
	"with lightning skills":            &PatternEntry{KeywordFlags: KeywordLightning},
	"with cold skills":                 &PatternEntry{KeywordFlags: KeywordCold},
	"with fire skills":                 &PatternEntry{KeywordFlags: KeywordFire},
	"with elemental skills":            &PatternEntry{KeywordFlags: KeywordLightning | KeywordCold | KeywordFire},
	"with chaos skills":                &PatternEntry{KeywordFlags: KeywordChaos},
	"with physical skills":             &PatternEntry{KeywordFlags: KeywordPhysical},
	"with channelling skills":          &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel}},
	"channelling":                      &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel}},
	"channelling skills":               &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel}},
	"non-channelling":                  &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel, Neg: true}},
	"non-channelling skills":           &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel, Neg: true}},
	"with brand skills":                &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeBrand}},
	"for stance skills":                &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeStance}},
	"of stance skills":                 &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeStance}},
	"mark skills":                      &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMark}},
	"of mark skills":                   &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMark}},
	"with skills that cost life":       &PatternEntry{Tag: &StatTag{StatKind: TagStatThreshold, Stat: "LifeCost", Threshold: opt(1)}},
	"minion":                           &PatternEntry{AddToMinion: true},
	"zombie":                           &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Zombie", IncludeTransfigured: true}},
	"raised zombie":                    &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Zombie", IncludeTransfigured: true}},
	"skeleton":                         &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Skeletons", IncludeTransfigured: true}},
	"spectre":                          &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Spectre", IncludeTransfigured: true}},
	"raised spectre":                   &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Spectre", IncludeTransfigured: true}},
	"golem":                            &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillTypeTag{SkillType: SkillTypeGolem}},
	"chaos golem":                      &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Chaos Golem", IncludeTransfigured: true}},
	"flame golem":                      &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Flame Golem", IncludeTransfigured: true}},
	"increased flame golem":            &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Flame Golem", IncludeTransfigured: true}},
	"ice golem":                        &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Ice Golem", IncludeTransfigured: true}},
	"lightning golem":                  &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Lightning Golem", IncludeTransfigured: true}},
	"stone golem":                      &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Stone Golem", IncludeTransfigured: true}},
	"animated guardian":                &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Animate Guardian", IncludeTransfigured: true}},
	// Damage types
	"with physical damage":  &PatternEntry{Tag: &CondTag{Var: "PhysicalHasDamage"}},
	"with lightning damage": &PatternEntry{Tag: &CondTag{Var: "LightningHasDamage"}},
	"with cold damage":      &PatternEntry{Tag: &CondTag{Var: "ColdHasDamage"}},
	"with fire damage":      &PatternEntry{Tag: &CondTag{Var: "FireHasDamage"}},
	"with chaos damage":     &PatternEntry{Tag: &CondTag{Var: "ChaosHasDamage"}},
	// Other
	"global":                          &PatternEntry{Tag: &MarkerTag{Marker: TagGlobal}},
	"from equipped shield":            &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotName: "Weapon 2"}},
	"from equipped armour items":      &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotNameList: []string{"Helmet", "Body Armour", "Gloves", "Boots", "Weapon 2"}}},
	"from equipped helmet":            &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotName: "Helmet"}},
	"from equipped gloves and boots":  &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotNameList: []string{"Gloves", "Boots"}}},
	"from equipped boots and gloves":  &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotNameList: []string{"Gloves", "Boots"}}},
	"from equipped helmet and gloves": &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotNameList: []string{"Helmet", "Gloves"}}},
	"from equipped helmet and boots":  &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotNameList: []string{"Helmet", "Boots"}}},
	"from your equipped body armour":  &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotName: "Body Armour"}},
	"from equipped body armour":       &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotName: "Body Armour"}},
	"from body armour":                &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotName: "Body Armour"}},
	"from your body armour":           &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotName, SlotName: "Body Armour"}},
}
