package modparser

// Map of modifier names — ModParser.lua:161.
var modNameList = map[string]any{
	// Attributes
	"strength":                   "Str",
	"dexterity":                  "Dex",
	"intelligence":               "Int",
	"omniscience":                "Omni",
	"strength and dexterity":     d("Str", "Dex", "StrDex"),
	"strength and intelligence":  d("Str", "Int", "StrInt"),
	"dexterity and intelligence": d("Dex", "Int", "DexInt"),
	"attributes":                 d("Str", "Dex", "Int", "All"),
	"all attributes":             d("Str", "Dex", "Int", "All"),
	"devotion":                   "Devotion",
	// Life/mana
	"life":                   "Life",
	"maximum life":           "Life",
	"life regeneration rate": "LifeRegen",
	"life regeneration also applies to energy shield": "LifeRegenAppliesToEnergyShield",
	"life and mana":              d("Life", "Mana"),
	"maximum life and mana":      d("Life", "Mana"),
	"mana":                       "Mana",
	"maximum mana":               "Mana",
	"mana regeneration":          "ManaRegen",
	"mana regeneration rate":     "ManaRegen",
	"mana cost":                  "ManaCost",
	"mana cost of":               "ManaCost",
	"mana cost of skills":        "ManaCost",
	"mana cost of attacks":       d("ManaCost", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"total cost":                 "Cost",
	"total mana cost":            "ManaCost",
	"total mana cost of skills":  "ManaCost",
	"life cost of skills":        "LifeCost",
	"rage cost of skills":        "RageCost",
	"souls per use":              "SoulCost",
	"cost of":                    "Cost",
	"cost of skills":             "Cost",
	"cost of attacks":            d("Cost", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"cost of retaliation skills": d("Cost", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Retaliation})),
	// Cost efficiency
	"cost efficiency":                         "CostEfficiency",
	"cost efficiency of skills":               "CostEfficiency",
	"cost efficiency of attacks":              d("CostEfficiency", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"cost efficiency of spells":               d("CostEfficiency", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Spell})),
	"mana cost efficiency":                    "ManaCostEfficiency",
	"mana cost efficiency of skills":          "ManaCostEfficiency",
	"mana cost efficiency of attacks":         d("ManaCostEfficiency", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"mana cost efficiency of spells":          d("ManaCostEfficiency", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Spell})),
	"life cost efficiency":                    "LifeCostEfficiency",
	"life cost efficiency of skills":          "LifeCostEfficiency",
	"life cost efficiency of attacks":         d("LifeCostEfficiency", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"life cost efficiency of spells":          d("LifeCostEfficiency", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Spell})),
	"energy shield cost efficiency":           "ESCostEfficiency",
	"energy shield cost efficiency of skills": "ESCostEfficiency",
	"es cost efficiency":                      "ESCostEfficiency",
	"es cost efficiency of skills":            "ESCostEfficiency",
	"soul cost efficiency":                    "SoulCostEfficiency",
	"soul cost efficiency of skills":          "SoulCostEfficiency",
	"rage cost efficiency":                    "RageCostEfficiency",
	"rage cost efficiency of skills":          "RageCostEfficiency",
	"mana reserved":                           "ManaReserved",
	"mana reservation":                        "ManaReserved",
	"mana reservation of skills":              d("ManaReserved", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura})),
	"mana reservation efficiency of skills":   "ManaReservationEfficiency",
	"life reserved":                           "LifeReserved",
	"life reservation":                        "LifeReserved",
	"life reservation of skills":              d("LifeReserved", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura})),
	"life reservation efficiency of skills":   "LifeReservationEfficiency",
	"reservation of skills":                   "Reserved",
	"mana reservation if cast as an aura":     d("ManaReserved", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura})),
	"reservation if cast as an aura":          d("Reserved", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura})),
	"reservation":                             d("Reserved"),
	"reservation efficiency":                  "ReservationEfficiency",
	"reservation efficiency of skills":        "ReservationEfficiency",
	"mana reservation efficiency":             "ManaReservationEfficiency",
	"life reservation efficiency":             "LifeReservationEfficiency",
	// Primary defences
	"maximum energy shield":                     "EnergyShield",
	"energy shield recharge rate":               "EnergyShieldRecharge",
	"start of energy shield recharge":           "EnergyShieldRechargeFaster",
	"restoration of ward":                       "WardRechargeFaster",
	"armour":                                    "Armour",
	"evasion":                                   "Evasion",
	"evasion rating":                            "Evasion",
	"energy shield":                             "EnergyShield",
	"ward":                                      "Ward",
	"armour and evasion":                        "ArmourAndEvasion",
	"armour and evasion rating":                 "ArmourAndEvasion",
	"evasion rating and armour":                 "ArmourAndEvasion",
	"armour and energy shield":                  "ArmourAndEnergyShield",
	"evasion rating and energy shield":          "EvasionAndEnergyShield",
	"evasion and energy shield":                 "EvasionAndEnergyShield",
	"armour, evasion and energy shield":         "Defences",
	"defences":                                  "Defences",
	"to evade":                                  "EvadeChance",
	"chance to evade":                           "EvadeChance",
	"to evade attacks":                          "EvadeChance",
	"to evade attack hits":                      "EvadeChance",
	"chance to evade attacks":                   "EvadeChance",
	"chance to evade attack hits":               "EvadeChance",
	"chance to evade projectile attacks":        "ProjectileEvadeChance",
	"chance to evade melee attacks":             "MeleeEvadeChance",
	"evasion rating against melee attacks":      "MeleeEvasion",
	"evasion rating against projectile attacks": "ProjectileEvasion",
	// Resistances
	"physical damage reduction":                                   "PhysicalDamageReduction",
	"physical damage reduction from hits":                         "PhysicalDamageReductionWhenHit",
	"elemental damage reduction":                                  "ElementalDamageReduction",
	"fire resistance":                                             "FireResist",
	"maximum fire resistance":                                     "FireResistMax",
	"cold resistance":                                             "ColdResist",
	"maximum cold resistance":                                     "ColdResistMax",
	"lightning resistance":                                        "LightningResist",
	"maximum lightning resistance":                                "LightningResistMax",
	"chaos resistance":                                            "ChaosResist",
	"maximum chaos resistance":                                    "ChaosResistMax",
	"fire and cold resistances":                                   d("FireResist", "ColdResist"),
	"fire and lightning resistances":                              d("FireResist", "LightningResist"),
	"cold and lightning resistances":                              d("ColdResist", "LightningResist"),
	"elemental resistance":                                        "ElementalResist",
	"elemental resistances":                                       "ElementalResist",
	"all elemental resistances":                                   "ElementalResist",
	"elemental and chaos resistances":                             d("ElementalResist", "ChaosResist"),
	"all resistances":                                             d("ElementalResist", "ChaosResist"),
	"all maximum elemental resistances":                           "ElementalResistMax",
	"all maximum resistances":                                     d("ElementalResistMax", "ChaosResistMax"),
	"all elemental resistances and maximum elemental resistances": d("ElementalResist", "ElementalResistMax"),
	"fire and chaos resistances":                                  d("FireResist", "ChaosResist"),
	"cold and chaos resistances":                                  d("ColdResist", "ChaosResist"),
	"lightning and chaos resistances":                             d("LightningResist", "ChaosResist"),
	// Damage taken
	"damage taken":                                          "DamageTaken",
	"damage taken when hit":                                 "DamageTakenWhenHit",
	"damage taken from hits":                                "DamageTakenWhenHit",
	"damage over time taken":                                "DamageTakenOverTime",
	"damage taken from damage over time":                    "DamageTakenOverTime",
	"attack damage taken":                                   "AttackDamageTaken",
	"spell damage taken":                                    "SpellDamageTaken",
	"physical damage taken":                                 "PhysicalDamageTaken",
	"physical damage from hits taken":                       "PhysicalDamageFromHitsTaken",
	"physical damage taken when hit":                        "PhysicalDamageTakenWhenHit",
	"physical damage taken from hits":                       "PhysicalDamageTakenWhenHit",
	"physical damage taken from attacks":                    "PhysicalDamageTakenFromAttacks",
	"physical damage taken from attack hits":                "PhysicalDamageTakenFromAttacks",
	"physical damage taken from projectile attacks":         "PhysicalDamageTakenFromProjectileAttacks",
	"physical damage taken from projectile attack hits":     "PhysicalDamageTakenFromProjectileAttacks",
	"fire, cold and lightning damage taken from spell hits": d("FireDamageTakenFromSpells", "ColdDamageTakenFromSpells", "LightningDamageTakenFromSpells"),
	"damage taken of each damage type from spell hits":      "DamageTakenFromSpells",
	"physical damage taken over time":                       "PhysicalDamageTakenOverTime",
	"physical damage over time taken":                       "PhysicalDamageTakenOverTime",
	"physical damage over time damage taken":                "PhysicalDamageTakenOverTime",
	"reflected physical damage taken":                       "PhysicalReflectedDamageTaken",
	"lightning damage taken":                                "LightningDamageTaken",
	"lightning damage from hits taken":                      "LightningDamageFromHitsTaken",
	"lightning damage taken when hit":                       "LightningDamageTakenWhenHit",
	"lightning damage taken from attacks":                   "LightningDamageTakenFromAttacks",
	"lightning damage taken from attack hits":               "LightningDamageTakenFromAttacks",
	"lightning damage taken over time":                      "LightningDamageTakenOverTime",
	"cold damage taken":                                     "ColdDamageTaken",
	"cold damage from hits taken":                           "ColdDamageFromHitsTaken",
	"cold damage taken when hit":                            "ColdDamageTakenWhenHit",
	"cold damage taken from hits":                           "ColdDamageTakenWhenHit",
	"cold damage taken from attacks":                        "ColdDamageTakenFromAttacks",
	"cold damage taken from attack hits":                    "ColdDamageTakenFromAttacks",
	"cold damage taken over time":                           "ColdDamageTakenOverTime",
	"fire damage taken":                                     "FireDamageTaken",
	"fire damage from hits taken":                           "FireDamageFromHitsTaken",
	"fire damage taken when hit":                            "FireDamageTakenWhenHit",
	"fire damage taken from hits":                           "FireDamageTakenWhenHit",
	"fire damage taken from attacks":                        "FireDamageTakenFromAttacks",
	"fire damage taken from attack hits":                    "FireDamageTakenFromAttacks",
	"fire damage taken over time":                           "FireDamageTakenOverTime",
	"chaos damage taken":                                    "ChaosDamageTaken",
	"chaos damage from hits taken":                          "ChaosDamageFromHitsTaken",
	"chaos damage taken when hit":                           "ChaosDamageTakenWhenHit",
	"chaos damage taken from hits":                          "ChaosDamageTakenWhenHit",
	"chaos damage taken from attacks":                       "ChaosDamageTakenFromAttacks",
	"chaos damage taken from attack hits":                   "ChaosDamageTakenFromAttacks",
	"chaos damage taken over time":                          "ChaosDamageTakenOverTime",
	"chaos damage over time taken":                          "ChaosDamageTakenOverTime",
	"elemental taken":                                       "ElementalDamageTaken",
	"elemental damage taken":                                "ElementalDamageTaken",
	"elemental damage from hits taken":                      "ElementalDamageFromHitsTaken",
	"elemental damage taken when hit":                       "ElementalDamageTakenWhenHit",
	"elemental damage taken from hits":                      "ElementalDamageTakenWhenHit",
	"elemental damage taken over time":                      "ElementalDamageTakenOverTime",
	"cold and lightning damage taken":                       d("ColdDamageTaken", "LightningDamageTaken"),
	"fire and lightning damage taken":                       d("FireDamageTaken", "LightningDamageTaken"),
	"fire and cold damage taken":                            d("FireDamageTaken", "ColdDamageTaken"),
	"physical and chaos damage taken":                       d("PhysicalDamageTaken", "ChaosDamageTaken"),
	"reflected elemental damage taken":                      "ElementalReflectedDamageTaken",
	// Other defences
	"to dodge attacks":                               "AttackDodgeChance",
	"to dodge attack hits":                           "AttackDodgeChance",
	"to dodge spells":                                "SpellDodgeChance",
	"to dodge spell hits":                            "SpellDodgeChance",
	"to dodge spell damage":                          "SpellDodgeChance",
	"to dodge attacks and spells":                    d("AttackDodgeChance", "SpellDodgeChance"),
	"to dodge attacks and spell damage":              d("AttackDodgeChance", "SpellDodgeChance"),
	"to dodge attack and spell hits":                 d("AttackDodgeChance", "SpellDodgeChance"),
	"to dodge attack or spell hits":                  d("AttackDodgeChance", "SpellDodgeChance"),
	"to suppress spell damage":                       d("SpellSuppressionChance"),
	"amount of suppressed spell damage prevented":    d("SpellSuppressionEffect"),
	"to amount of suppressed spell damage prevented": d("SpellSuppressionEffect"),
	"to block":                                                          "BlockChance",
	"to block attacks":                                                  "BlockChance",
	"to block attack damage":                                            "BlockChance",
	"block chance":                                                      "BlockChance",
	"chance to block":                                                   "BlockChance",
	"block chance with staves":                                          d("BlockChance", p("tag", Tag{"type": "Condition", "var": "UsingStaff"})),
	"to block with staves":                                              d("BlockChance", p("tag", Tag{"type": "Condition", "var": "UsingStaff"})),
	"block chance against projectiles":                                  "ProjectileBlockChance",
	"to block projectile attack damage":                                 "ProjectileBlockChance",
	"to block projectile spell damage":                                  "ProjectileSpellBlockChance",
	"spell block chance":                                                "SpellBlockChance",
	"to block spells":                                                   "SpellBlockChance",
	"to block spell damage":                                             "SpellBlockChance",
	"chance to block attacks and spells":                                d("BlockChance", "SpellBlockChance"),
	"chance to block attack and spell damage":                           d("BlockChance", "SpellBlockChance"),
	"to block attack and spell damage":                                  d("BlockChance", "SpellBlockChance"),
	"maximum block chance":                                              "BlockChanceMax",
	"maximum chance to block attack damage":                             "BlockChanceMax",
	"maximum chance to block spell damage":                              "SpellBlockChanceMax",
	"life gained when you block":                                        "LifeOnBlock",
	"mana gained when you block":                                        "ManaOnBlock",
	"energy shield when you block":                                      "EnergyShieldOnBlock",
	"maximum chance to dodge spell hits":                                "SpellDodgeChanceMax",
	"to avoid all damage from hits":                                     "AvoidAllDamageFromHitsChance",
	"to avoid physical damage from hits":                                "AvoidPhysicalDamageChance",
	"to avoid fire damage when hit":                                     "AvoidFireDamageChance",
	"to avoid fire damage from hits":                                    "AvoidFireDamageChance",
	"to avoid cold damage when hit":                                     "AvoidColdDamageChance",
	"to avoid cold damage from hits":                                    "AvoidColdDamageChance",
	"to avoid lightning damage when hit":                                "AvoidLightningDamageChance",
	"to avoid lightning damage from hits":                               "AvoidLightningDamageChance",
	"to avoid elemental damage when hit":                                d("AvoidFireDamageChance", "AvoidColdDamageChance", "AvoidLightningDamageChance"),
	"to avoid elemental damage from hits":                               d("AvoidFireDamageChance", "AvoidColdDamageChance", "AvoidLightningDamageChance"),
	"to avoid damage of each element from hits":                         d("AvoidFireDamageChance", "AvoidColdDamageChance", "AvoidLightningDamageChance"),
	"to avoid projectiles":                                              "AvoidProjectilesChance",
	"to avoid being stunned":                                            "AvoidStun",
	"to avoid interruption from stuns while casting":                    "AvoidInterruptStun",
	"to ignore stuns while casting":                                     "AvoidInterruptStun",
	"to avoid being shocked":                                            "AvoidShock",
	"to avoid being frozen":                                             "AvoidFreeze",
	"to avoid being chilled":                                            "AvoidChill",
	"to avoid being ignited":                                            "AvoidIgnite",
	"to avoid non-damaging ailments on you":                             d("AvoidShock", "AvoidFreeze", "AvoidChill", "AvoidSap", "AvoidBrittle", "AvoidScorch"),
	"to avoid blind":                                                    "AvoidBlind",
	"to avoid elemental ailments":                                       "AvoidElementalAilments",
	"to avoid elemental status ailments":                                "AvoidElementalAilments",
	"to avoid ailments":                                                 "AvoidAilments",
	"to avoid status ailments":                                          "AvoidAilments",
	"to avoid bleeding":                                                 "AvoidBleed",
	"to avoid being poisoned":                                           "AvoidPoison",
	"to avoid being impaled":                                            "AvoidImpale",
	"damage is taken from mana before life":                             "DamageTakenFromManaBeforeLife",
	"lightning damage is taken from mana before life":                   "LightningDamageTakenFromManaBeforeLife",
	"damage taken from mana before life":                                "DamageTakenFromManaBeforeLife",
	"effect of curses on you":                                           "CurseEffectOnSelf",
	"effect of curses on them":                                          "CurseEffectOnSelf",
	"effect of exposure on you":                                         "ExposureEffectOnSelf",
	"effect of withered on you":                                         "WitherEffectOnSelf",
	"life recovery rate":                                                "LifeRecoveryRate",
	"mana recovery rate":                                                "ManaRecoveryRate",
	"energy shield recovery rate":                                       "EnergyShieldRecoveryRate",
	"energy shield regeneration rate":                                   "EnergyShieldRegen",
	"recovery rate of life, mana and energy shield":                     d("LifeRecoveryRate", "ManaRecoveryRate", "EnergyShieldRecoveryRate"),
	"recovery rate of life and energy shield":                           d("LifeRecoveryRate", "EnergyShieldRecoveryRate"),
	"maximum life, mana and global energy shield":                       d("Life", "Mana", "EnergyShield", p("tag", Tag{"type": "Global"})),
	"non-chaos damage taken bypasses energy shield":                     d("PhysicalEnergyShieldBypass", "LightningEnergyShieldBypass", "ColdEnergyShieldBypass", "FireEnergyShieldBypass"),
	"armour applies to fire, cold and lightning damage taken from hits": d("ArmourAppliesToFireDamageTaken", "ArmourAppliesToColdDamageTaken", "ArmourAppliesToLightningDamageTaken"),
	"damage taken recouped as life":                                     "LifeRecoup",
	"physical damage taken recouped as life":                            "PhysicalLifeRecoup",
	"lightning damage taken recouped as life":                           "LightningLifeRecoup",
	"cold damage taken recouped as life":                                "ColdLifeRecoup",
	"fire damage taken recouped as life":                                "FireLifeRecoup",
	"chaos damage taken recouped as life":                               "ChaosLifeRecoup",
	"damage taken recouped as energy shield":                            "EnergyShieldRecoup",
	"damage taken recouped as mana":                                     "ManaRecoup",
	"damage taken recouped as life, mana and energy shield":             d("LifeRecoup", "EnergyShieldRecoup", "ManaRecoup"),
	"missing unreserved life before being hit by an enemy":              "MissingLifeBeforeEnemyHit",
	"missing unreserved mana before being hit by an enemy":              "MissingManaBeforeEnemyHit",
	// Stun/knockback modifiers
	"stun recovery":                "StunRecovery",
	"stun and block recovery":      "StunRecovery",
	"block and stun recovery":      "StunRecovery",
	"stun duration on you":         "StunDuration",
	"stun threshold":               "StunThreshold",
	"block recovery":               "BlockRecovery",
	"enemy stun threshold":         "EnemyStunThreshold",
	"stun duration on enemies":     "EnemyStunDuration",
	"stun duration":                "EnemyStunDuration",
	"to double stun duration":      "DoubleEnemyStunDurationChance",
	"to knock enemies back on hit": "EnemyKnockbackChance",
	"knockback distance":           "EnemyKnockbackDistance",
	// Auras/curses/buffs
	"aura effect":                                                "AuraEffect",
	"effect of non-curse auras you cast":                         d("AuraEffect", p("tagList", d(Tag{"type": "SkillType", "skillType": SkillType.Aura}, Tag{"type": "SkillType", "skillType": SkillType.AppliesCurse, "neg": true}))),
	"effect of non-curse auras from your skills":                 d("AuraEffect", p("tagList", d(Tag{"type": "SkillType", "skillType": SkillType.Aura}, Tag{"type": "SkillType", "skillType": SkillType.AppliesCurse, "neg": true}))),
	"effect of non-curse auras from your skills on your minions": d("AuraEffectOnSelf", p("tagList", d(Tag{"type": "SkillType", "skillType": SkillType.Aura}, Tag{"type": "SkillType", "skillType": SkillType.AppliesCurse, "neg": true})), p("addToMinion", true)),
	"effect of non-curse auras":                                  d("AuraEffect", p("tag", Tag{"type": "SkillType", "skillType": SkillType.AppliesCurse, "neg": true})),
	"effect of your curses":                                      "CurseEffect",
	"effect of auras on you":                                     "AuraEffectOnSelf",
	"effect of auras on your minions":                            d("AuraEffectOnSelf", p("addToMinion", true)),
	"effect of auras from mines":                                 d("AuraEffect", p("keywordFlags", KeywordFlag.Mine)),
	"effect of auras from your vaal skills":                      d("AuraEffect", p("keywordFlags", KeywordFlag.Vaal)),
	"effect of consecrated ground you create":                    "ConsecratedGroundEffect",
	"curse effect":                                               "CurseEffect",
	"effect of curses applied by bane":                           d("CurseEffect", p("tag", Tag{"type": "Condition", "var": "AppliedByBane"})),
	"effect of your marks":                                       d("CurseEffect", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Mark})),
	"effect of marks":                                            d("CurseEffect", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Mark})),
	"effect of arcane surge on you":                              "ArcaneSurgeEffect",
	"curse duration":                                             d("Duration", p("keywordFlags", KeywordFlag.Curse)),
	"hex duration":                                               d("Duration", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Hex})),
	"radius of auras":                                            d("AreaOfEffect", p("keywordFlags", KeywordFlag.Aura)),
	"radius of curses":                                           d("AreaOfEffect", p("keywordFlags", KeywordFlag.Curse)),
	"buff effect":                                                "BuffEffect",
	"effect of buffs on you":                                     "BuffEffectOnSelf",
	"effect of buffs granted by your golems":                     d("BuffEffect", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Golem})),
	"effect of buffs granted by socketed golem skills":           d("BuffEffect", p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "golem")))),
	"effect of the buff granted by your stone golems":            d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Summon Stone Golem", "includeTransfigured": true})),
	"effect of the buff granted by your lightning golems":        d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Summon Lightning Golem", "includeTransfigured": true})),
	"effect of the buff granted by your ice golems":              d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Summon Ice Golem", "includeTransfigured": true})),
	"effect of the buff granted by your flame golems":            d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Summon Flame Golem", "includeTransfigured": true})),
	"effect of the buff granted by your chaos golems":            d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Summon Chaos Golem", "includeTransfigured": true})),
	"effect of the buff granted by your carrion golems":          d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Summon Carrion Golem", "includeTransfigured": true})),
	"effect of offering spells":                                  d("BuffEffect", p("tag", d(p("type", "SkillName"), p("skillNameList", d("Bone Offering", "Flesh Offering", "Spirit Offering", "Blood Offering"))))),
	"effect of offerings":                                        d("BuffEffect", p("tag", d(p("type", "SkillName"), p("skillNameList", d("Bone Offering", "Flesh Offering", "Spirit Offering", "Blood Offering"))))),
	"effect of heralds on you":                                   d("BuffEffect", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Herald})),
	"effect of herald buffs on you":                              d("BuffEffect", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Herald})),
	"effect of buffs granted by your active ancestor totems":     d("BuffEffect", p("tag", d(p("type", "SkillName"), p("skillNameList", d("Ancestral Warchief", "Ancestral Protector", "Earthbreaker"))))),
	"effect of buffs your ancestor totems grant ":                d("BuffEffect", p("tag", d(p("type", "SkillName"), p("skillNameList", d("Ancestral Warchief", "Ancestral Protector", "Earthbreaker"))))),
	"effect of shrine buffs on you":                              "ShrineBuffEffect",
	"effect of withered":                                         "WitherEffect",
	"warcry effect":                                              d("BuffEffect", p("keywordFlags", KeywordFlag.Warcry)),
	"aspect of the avian buff effect":                            d("BuffEffect", p("tag", Tag{"type": "SkillName", "skillName": "Aspect of the Avian"})),
	"maximum rage":                                               "MaximumRage",
	"minimum rage":                                               "MinimumRage",
	"rage effect":                                                "RageEffect",
	"maximum fortification":                                      "MaximumFortification",
	"fortification":                                              "MinimumFortification",
	"fortification duration":                                     "FortifyDuration",
	"maximum valour":                                             "MaximumValour",
	// Charges
	"maximum power charge":                                "PowerChargesMax",
	"maximum power charges":                               "PowerChargesMax",
	"minimum power charge":                                "PowerChargesMin",
	"minimum power charges":                               "PowerChargesMin",
	"power charge duration":                               "PowerChargesDuration",
	"maximum frenzy charge":                               "FrenzyChargesMax",
	"maximum frenzy charges":                              "FrenzyChargesMax",
	"minimum frenzy charge":                               "FrenzyChargesMin",
	"minimum frenzy charges":                              "FrenzyChargesMin",
	"frenzy charge duration":                              "FrenzyChargesDuration",
	"maximum endurance charge":                            "EnduranceChargesMax",
	"maximum endurance charges":                           "EnduranceChargesMax",
	"minimum endurance charge":                            "EnduranceChargesMin",
	"minimum endurance charges":                           "EnduranceChargesMin",
	"minimum endurance, frenzy and power charges":         d("PowerChargesMin", "FrenzyChargesMin", "EnduranceChargesMin"),
	"endurance charge duration":                           "EnduranceChargesDuration",
	"maximum frenzy charges and maximum power charges":    d("FrenzyChargesMax", "PowerChargesMax"),
	"maximum power charges and maximum endurance charges": d("PowerChargesMax", "EnduranceChargesMax"),
	"maximum endurance, frenzy and power charges":         d("EnduranceChargesMax", "PowerChargesMax", "FrenzyChargesMax"),
	"endurance, frenzy and power charge duration":         d("PowerChargesDuration", "FrenzyChargesDuration", "EnduranceChargesDuration"),
	"maximum siphoning charge":                            "SiphoningChargesMax",
	"maximum siphoning charges":                           "SiphoningChargesMax",
	"maximum challenger charges":                          "ChallengerChargesMax",
	"maximum blitz charges":                               "BlitzChargesMax",
	"maximum number of crab barriers":                     "CrabBarriersMax",
	"maximum blood charges":                               "BloodChargesMax",
	"maximum spirit charges":                              "SpiritChargesMax",
	"charge duration":                                     "ChargeDuration",
	// On hit/kill/leech effects
	"life gained on kill":                                                       "LifeOnKill",
	"life per enemy killed":                                                     "LifeOnKill",
	"life on kill":                                                              "LifeOnKill",
	"life per enemy hit":                                                        d("LifeOnHit", p("flags", ModFlag.Hit)),
	"life gained for each enemy hit":                                            d("LifeOnHit", p("flags", ModFlag.Hit)),
	"life for each enemy hit":                                                   d("LifeOnHit", p("flags", ModFlag.Hit)),
	"mana gained on kill":                                                       "ManaOnKill",
	"mana per enemy killed":                                                     "ManaOnKill",
	"mana on kill":                                                              "ManaOnKill",
	"mana per enemy hit":                                                        d("ManaOnHit", p("flags", ModFlag.Hit)),
	"mana gained for each enemy hit":                                            d("ManaOnHit", p("flags", ModFlag.Hit)),
	"mana for each enemy hit":                                                   d("ManaOnHit", p("flags", ModFlag.Hit)),
	"energy shield gained on kill":                                              "EnergyShieldOnKill",
	"energy shield per enemy killed":                                            "EnergyShieldOnKill",
	"energy shield on kill":                                                     "EnergyShieldOnKill",
	"energy shield per enemy hit":                                               d("EnergyShieldOnHit", p("flags", ModFlag.Hit)),
	"energy shield gained for each enemy hit":                                   d("EnergyShieldOnHit", p("flags", ModFlag.Hit)),
	"energy shield for each enemy hit":                                          d("EnergyShieldOnHit", p("flags", ModFlag.Hit)),
	"life and mana gained for each enemy hit":                                   d("LifeOnHit", "ManaOnHit", p("flags", ModFlag.Hit)),
	"life and mana for each enemy hit":                                          d("LifeOnHit", "ManaOnHit", p("flags", ModFlag.Hit)),
	"damage as life":                                                            "DamageLifeLeech",
	"elemental damage as energy shield":                                         "ElementalDamageEnergyShieldLeech",
	"life leeched per second":                                                   "LifeLeechRate",
	"mana leeched per second":                                                   "ManaLeechRate",
	"total recovery per second from life leech":                                 "LifeLeechRate",
	"recovery per second from life leech":                                       "LifeLeechRate",
	"total recovery per second from energy shield leech":                        "EnergyShieldLeechRate",
	"recovery per second from energy shield leech":                              "EnergyShieldLeechRate",
	"total recovery per second from mana leech":                                 "ManaLeechRate",
	"recovery per second from mana leech":                                       "ManaLeechRate",
	"total recovery per second from life, mana, or energy shield leech":         d("LifeLeechRate", "ManaLeechRate", "EnergyShieldLeechRate"),
	"maximum recovery per life leech":                                           "MaxLifeLeechInstance",
	"maximum recovery per energy shield leech":                                  "MaxEnergyShieldLeechInstance",
	"maximum recovery per mana leech":                                           "MaxManaLeechInstance",
	"maximum total recovery per second from life leech":                         "MaxLifeLeechRate",
	"maximum total life recovery per second from leech":                         "MaxLifeLeechRate",
	"maximum total recovery per second from energy shield leech":                "MaxEnergyShieldLeechRate",
	"maximum total energy shield recovery per second from leech":                "MaxEnergyShieldLeechRate",
	"maximum total recovery per second from mana leech":                         "MaxManaLeechRate",
	"maximum total mana recovery per second from leech":                         "MaxManaLeechRate",
	"maximum total life, mana and energy shield recovery per second from leech": d("MaxLifeLeechRate", "MaxManaLeechRate", "MaxEnergyShieldLeechRate"),
	"life and mana leech is instant":                                            d("InstantManaLeech", "InstantLifeLeech"),
	"life leech is instant":                                                     d("InstantLifeLeech"),
	"mana leech is instant":                                                     d("InstantManaLeech"),
	"energy shield leech is instant":                                            d("InstantEnergyShieldLeech"),
	"leech is instant":                                                          d("InstantEnergyShieldLeech", "InstantManaLeech", "InstantLifeLeech"),
	"to impale enemies on hit":                                                  "ImpaleChance",
	"to impale on attack hit":                                                   d("ImpaleChance", p("flags", ModFlag.Attack)),
	"to impale on spell hit":                                                    d("ImpaleChance", p("flags", ModFlag.Spell)),
	"impale effect":                                                             "ImpaleEffect",
	"effect of impales you inflict":                                             "ImpaleEffect",
	"effects of impale inflicted":                                               "ImpaleEffect", // typo / old wording change
	"effect of impales inflicted":                                               "ImpaleEffect",
	"impale duration":                                                           "ImpaleDuration",
	// Projectile modifiers
	"projectile":       "ProjectileCount",
	"projectiles":      "ProjectileCount",
	"arrow":            d("ProjectileCount", p("keywordFlags", KeywordFlag.Arrow)),
	"arrows":           d("ProjectileCount", p("keywordFlags", KeywordFlag.Arrow)),
	"projectile speed": "ProjectileSpeed",
	"arrow speed":      d("ProjectileSpeed", p("keywordFlags", KeywordFlag.Arrow)),
	"chain ":           "ChainCountMax",
	// Totem/trap/mine/brand modifiers
	"totem placement speed":                          "TotemPlacementSpeed",
	"totem life":                                     "TotemLife",
	"totem duration":                                 "TotemDuration",
	"maximum number of summoned totems":              "ActiveTotemLimit",
	"maximum number of summoned totems.":             "ActiveTotemLimit", // Mark plz
	"maximum number of summoned ballista totems":     d("ActiveBallistaLimit", p("tag", Tag{"type": "SkillType", "skillType": SkillType.TotemsAreBallistae})),
	"maximum number of summoned searing bond totems": d("ActiveTotemLimit", p("tag", Tag{"type": "SkillName", "skillName": "Searing Bond", "includeTransfigured": true})),
	"trap throwing speed":                            "TrapThrowingSpeed",
	"trap and mine throwing speed":                   d("TrapThrowingSpeed", "MineLayingSpeed"),
	"trap trigger area of effect":                    "TrapTriggerAreaOfEffect",
	"trap duration":                                  "TrapDuration",
	"cooldown recovery speed for throwing traps":     d("CooldownRecovery", p("keywordFlags", KeywordFlag.Trap)),
	"cooldown recovery rate for throwing traps":      d("CooldownRecovery", p("keywordFlags", KeywordFlag.Trap)),
	"additional trap":                                "TrapThrowCount",
	"additional traps":                               "TrapThrowCount",
	"mine laying speed":                              "MineLayingSpeed",
	"mine throwing speed":                            "MineLayingSpeed",
	"mine detonation area of effect":                 "MineDetonationAreaOfEffect",
	"mine duration":                                  "MineDuration",
	"additional mine":                                "MineThrowCount",
	"additional mines":                               "MineThrowCount",
	"activation frequency":                           "BrandActivationFrequency",
	"brand activation frequency":                     "BrandActivationFrequency",
	"brand attachment range":                         "BrandAttachmentRange",
	// Minion modifiers
	"maximum number of skeletons":                "ActiveSkeletonLimit",
	"maximum number of summoned skeletons":       "ActiveSkeletonLimit",
	"maximum number of zombies":                  "ActiveZombieLimit",
	"maximum number of raised zombies":           "ActiveZombieLimit",
	"number of zombies allowed":                  "ActiveZombieLimit",
	"maximum number of spectres":                 "ActiveSpectreLimit",
	"maximum number of raised spectres":          "ActiveSpectreLimit",
	"maximum number of golems":                   "ActiveGolemLimit",
	"maximum number of summoned golems":          "ActiveGolemLimit",
	"maximum number of animated weapons":         "ActiveAnimatedWeaponLimit",
	"maximum number of summoned raging spirits":  "ActiveRagingSpiritLimit",
	"maximum number of raging spirits":           "ActiveRagingSpiritLimit",
	"maximum number of raised spiders":           "ActiveSpiderLimit",
	"maximum number of summoned reapers":         "ActiveReaperLimit",
	"maximum number of summoned phantasms":       "ActivePhantasmLimit",
	"maximum number of summoned holy relics":     "ActiveHolyRelicLimit",
	"maximum number of sentinels of absolution":  "ActiveSentinelOfAbsolutionLimit",
	"maximum number of sentinels of dominance":   "ActiveSentinelOfDominanceLimit",
	"maximum number of sentinels of purity":      "ActiveSentinelOfPurityLimit",
	"maximum number of summoned spectral wolves": "ActiveWolfLimit",
	"maximum number of living lightning":         "ActiveLivingLightningLimit",
	"maximum number of holy armaments":           "ActiveHolyStrikeMinionLimit",
	"number of summoned arbalists":               "ActiveArbalistLimit",
	"minion duration":                            d("Duration", p("tagList", d(Tag{"type": "SkillType", "skillType": SkillType.CreatesMinion}, Tag{"type": "SkillType", "skillType": SkillType.Minion}))),
	"skeleton duration":                          d("Duration", p("tag", Tag{"type": "SkillName", "skillName": "Summon Skeletons", "includeTransfigured": true})),
	"sentinel of dominance duration":             d("Duration", p("tag", Tag{"type": "SkillName", "skillName": "Dominating Blow", "includeTransfigured": true})),
	// Other skill modifiers
	"radius":                                "AreaOfEffect",
	"radius of area skills":                 "AreaOfEffect",
	"area of effect radius":                 "AreaOfEffect",
	"area of effect":                        "AreaOfEffect",
	"area of effect of skills":              "AreaOfEffect",
	"area of effect of area skills":         "AreaOfEffect",
	"aspect of the spider area of effect":   d("AreaOfEffect", p("tag", Tag{"type": "SkillName", "skillName": "Aspect of the Spider"})),
	"firestorm explosion area of effect":    d("AreaOfEffectSecondary", p("tag", Tag{"type": "SkillName", "skillName": "Firestorm", "includeTransfigured": true})),
	"duration":                              "Duration",
	"skill effect duration":                 "Duration",
	"chaos skill effect duration":           d("Duration", p("keywordFlags", KeywordFlag.Chaos)),
	"soul gain prevention duration":         "SoulGainPreventionDuration",
	"aspect of the spider debuff duration":  d("Duration", p("tag", Tag{"type": "SkillName", "skillName": "Aspect of the Spider"})),
	"fire trap burning ground duration":     d("Duration", p("tag", Tag{"type": "SkillName", "skillName": "Fire Trap"})),
	"sentinel of absolution duration":       d("SecondaryDuration", p("tag", Tag{"type": "SkillName", "skillName": "Absolution", "includeTransfigured": true})),
	"cooldown recovery":                     "CooldownRecovery",
	"cooldown recovery speed":               "CooldownRecovery",
	"cooldown recovery rate":                "CooldownRecovery",
	"cooldown use":                          "AdditionalCooldownUses",
	"cooldown uses":                         "AdditionalCooldownUses",
	"weapon range":                          "WeaponRange",
	"metres to weapon range":                "WeaponRangeMetre",
	"metre to weapon range":                 "WeaponRangeMetre",
	"melee range":                           "MeleeWeaponRange",
	"melee weapon range":                    "MeleeWeaponRange",
	"melee weapon and unarmed range":        d("MeleeWeaponRange", "UnarmedRange"),
	"melee weapon and unarmed attack range": d("MeleeWeaponRange", "UnarmedRange"),
	"melee strike range":                    d("MeleeWeaponRange", "UnarmedRange"),
	"metres to melee strike range":          d("MeleeWeaponRangeMetre", "UnarmedRangeMetre"),
	"metre to melee strike range":           d("MeleeWeaponRangeMetre", "UnarmedRangeMetre"),
	"to deal double damage":                 "DoubleDamageChance",
	"to deal triple damage":                 "TripleDamageChance",
	// Buffs
	"onslaught effect":           "OnslaughtEffect",
	"effect of onslaught on you": "OnslaughtEffect",
	"adrenaline duration":        "AdrenalineDuration",
	"effect of tailwind on you":  "TailwindEffectOnSelf",
	"elusive effect":             "ElusiveEffect",
	"effect of elusive on you":   "ElusiveEffect",
	"effect of infusion":         "InfusionEffect",
	// Basic damage types
	"damage":                   "Damage",
	"physical damage":          "PhysicalDamage",
	"minimum physical damage":  "MinPhysicalDamage",
	"maximum physical damage":  "MaxPhysicalDamage",
	"lightning damage":         "LightningDamage",
	"minimum lightning damage": "MinLightningDamage",
	"maximum lightning damage": "MaxLightningDamage",
	"cold damage":              "ColdDamage",
	"minimum cold damage":      "MinColdDamage",
	"maximum cold damage":      "MaxColdDamage",
	"fire damage":              "FireDamage",
	"minimum fire damage":      "MinFireDamage",
	"maximum fire damage":      "MaxFireDamage",
	"chaos damage":             "ChaosDamage",
	"minimum chaos damage":     "MinChaosDamage",
	"maximum chaos damage":     "MaxChaosDamage",
	"non-chaos damage":         "NonChaosDamage",
	"elemental damage":         "ElementalDamage",
	// Other damage forms
	"attack damage":                        d("Damage", p("flags", ModFlag.Attack)),
	"attack physical damage":               d("PhysicalDamage", p("flags", ModFlag.Attack)),
	"physical attack damage":               d("PhysicalDamage", p("flags", ModFlag.Attack)),
	"minimum physical attack damage":       d("MinPhysicalDamage", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"maximum physical attack damage":       d("MaxPhysicalDamage", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"minimum attack damage":                d("MinDamage", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"maximum attack damage":                d("MaxDamage", p("tag", Tag{"type": "SkillType", "skillType": SkillType.Attack})),
	"physical weapon damage":               d("PhysicalDamage", p("flags", ModFlag.Weapon)),
	"physical damage with weapons":         d("PhysicalDamage", p("flags", ModFlag.Weapon)),
	"melee damage":                         d("Damage", p("flags", ModFlag.Melee)),
	"physical melee damage":                d("PhysicalDamage", p("flags", ModFlag.Melee)),
	"melee physical damage":                d("PhysicalDamage", p("flags", ModFlag.Melee)),
	"projectile damage":                    d("Damage", p("flags", ModFlag.Projectile)),
	"projectile attack damage":             d("Damage", p("flags", ModFlag.Projectile|ModFlag.Attack)),
	"bow damage":                           d("Damage", p("flags", ModFlag.Bow|ModFlag.Hit)),
	"damage with arrow hits":               d("Damage", p("flags", ModFlag.Hit), p("keywordFlags", KeywordFlag.Arrow)),
	"wand damage":                          d("Damage", p("flags", ModFlag.Wand|ModFlag.Hit)),
	"wand physical damage":                 d("PhysicalDamage", p("flags", ModFlag.Wand|ModFlag.Hit)),
	"claw physical damage":                 d("PhysicalDamage", p("flags", ModFlag.Claw|ModFlag.Hit)),
	"sword physical damage":                d("PhysicalDamage", p("flags", ModFlag.Sword|ModFlag.Hit)),
	"damage over time":                     d("Damage", p("flags", ModFlag.Dot)),
	"physical damage over time":            d("PhysicalDamage", p("keywordFlags", KeywordFlag.PhysicalDot)),
	"cold damage over time":                d("ColdDamage", p("keywordFlags", KeywordFlag.ColdDot)),
	"chaos damage over time":               d("ChaosDamage", p("keywordFlags", KeywordFlag.ChaosDot)),
	"burning damage":                       d("FireDamage", p("keywordFlags", KeywordFlag.FireDot)),
	"damage with ignite":                   d("Damage", p("keywordFlags", KeywordFlag.Ignite)),
	"damage with ignites":                  d("Damage", p("keywordFlags", KeywordFlag.Ignite)),
	"damage with ignites inflicted":        d("Damage", p("keywordFlags", KeywordFlag.Ignite)),
	"damage with bleed":                    d("Damage", p("keywordFlags", KeywordFlag.Bleed)),
	"damage with bleeding":                 d("Damage", p("keywordFlags", KeywordFlag.Bleed)),
	"damage with poison":                   d("Damage", p("keywordFlags", KeywordFlag.Poison)),
	"incinerate damage for each stage":     d("Damage", p("tagList", d(Tag{"type": "Multiplier", "var": "IncinerateStage"}, Tag{"type": "SkillName", "skillName": "Incinerate"}))),
	"physical damage over time multiplier": "PhysicalDotMultiplier",
	"fire damage over time multiplier":     "FireDotMultiplier",
	"cold damage over time multiplier":     "ColdDotMultiplier",
	"chaos damage over time multiplier":    "ChaosDotMultiplier",
	"damage over time multiplier":          "DotMultiplier",
	// Crit/accuracy/speed modifiers
	"critical strike chance":            "CritChance",
	"critical hit chance":               "CritChance",
	"attack critical strike chance":     d("CritChance", p("flags", ModFlag.Attack)),
	"critical strike multiplier":        "CritMultiplier",
	"attack critical strike multiplier": d("CritMultiplier", p("flags", ModFlag.Attack)),
	"accuracy":                          "Accuracy",
	"accuracy rating":                   "Accuracy",
	"minion accuracy rating":            d("Accuracy", p("addToMinion", true)),
	"attack speed":                      d("Speed", p("flags", ModFlag.Attack)),
	"cast speed":                        d("Speed", p("flags", ModFlag.Cast)),
	"warcry speed":                      d("WarcrySpeed", p("keywordFlags", KeywordFlag.Warcry)),
	"attack and cast speed":             "Speed",
	"dps":                               "DPS",
	// Elemental ailments
	"to shock":                                    "EnemyShockChance",
	"shock chance":                                "EnemyShockChance",
	"to freeze":                                   "EnemyFreezeChance",
	"freeze chance":                               "EnemyFreezeChance",
	"to ignite":                                   "EnemyIgniteChance",
	"ignite chance":                               "EnemyIgniteChance",
	"to freeze, shock and ignite":                 d("EnemyFreezeChance", "EnemyShockChance", "EnemyIgniteChance"),
	"to scorch enemies":                           "EnemyScorchChance",
	"to inflict brittle":                          "EnemyBrittleChance",
	"to sap enemies":                              "EnemySapChance",
	"effect of scorch":                            "EnemyScorchEffect",
	"effect of sap":                               "EnemySapEffect",
	"effect of brittle":                           "EnemyBrittleEffect",
	"effect of shock":                             "EnemyShockEffect",
	"effect of shock on you":                      "SelfShockEffect",
	"effect of shock you inflict":                 "EnemyShockEffect",
	"effect of shocks you inflict":                "EnemyShockEffect",
	"effect of lightning ailments":                d("EnemyShockEffect", "EnemySapEffect"),
	"effect of chill":                             "EnemyChillEffect",
	"effect of chill and shock on you":            d("SelfChillEffect", "SelfShockEffect"),
	"chill effect":                                "EnemyChillEffect",
	"effect of chill you inflict":                 "EnemyChillEffect",
	"effect of chills you inflict":                "EnemyChillEffect",
	"effect of cold ailments":                     d("EnemyChillEffect", "EnemyBrittleEffect"),
	"effect of chill on you":                      "SelfChillEffect",
	"effect of freeze on you":                     "SelfFreezeEffect",
	"effect of non-damaging ailments":             d("EnemyShockEffect", "EnemyChillEffect", "EnemyFreezeEffect", "EnemyScorchEffect", "EnemyBrittleEffect", "EnemySapEffect"),
	"effect of non-damaging ailments you inflict": d("EnemyShockEffect", "EnemyChillEffect", "EnemyFreezeEffect", "EnemyScorchEffect", "EnemyBrittleEffect", "EnemySapEffect"),
	"effect of non-damaging ailments on you":      d("SelfShockEffect", "SelfChillEffect", "SelfFreezeEffect", "SelfScorchEffect", "SelfBrittleEffect", "SelfSapEffect"),
	"shock duration":                              "EnemyShockDuration",
	"duration of shocks you inflict":              "EnemyShockDuration",
	"shock duration on you":                       "SelfShockDuration",
	"duration of lightning ailments":              d("EnemyShockDuration", "EnemySapDuration"),
	"freeze duration":                             "EnemyFreezeDuration",
	"duration of freezes you inflict":             "EnemyFreezeDuration",
	"freeze duration on you":                      "SelfFreezeDuration",
	"chill duration":                              "EnemyChillDuration",
	"duration of chills you inflict":              "EnemyChillDuration",
	"chill duration on you":                       "SelfChillDuration",
	"duration of cold ailments":                   d("EnemyFreezeDuration", "EnemyChillDuration", "EnemyBrittleDuration"),
	"ignite duration":                             "EnemyIgniteDuration",
	"duration of ignites you inflict":             "EnemyIgniteDuration",
	"ignite duration on you":                      "SelfIgniteDuration",
	"duration of ignite on you":                   "SelfIgniteDuration",
	"duration of elemental ailments":              "EnemyElementalAilmentDuration",
	"duration of elemental ailments on you":       "SelfElementalAilmentDuration",
	"duration of elemental status ailments":       "EnemyElementalAilmentDuration",
	"duration of ailments":                        "EnemyAilmentDuration",
	"duration of ailments on you":                 "SelfAilmentDuration",
	"elemental ailment duration on you":           "SelfElementalAilmentDuration",
	"duration of ailments you inflict":            "EnemyAilmentDuration",
	"duration of ailments inflicted":              "EnemyAilmentDuration",
	"duration of ailments inflicted on you":       "SelfAilmentDuration",
	"duration of damaging ailments on you":        d("SelfIgniteDuration", "SelfBleedDuration", "SelfPoisonDuration"),
	// Other ailments
	"to poison":                       "PoisonChance",
	"to cause poison":                 "PoisonChance",
	"to poison on hit":                "PoisonChance",
	"poison duration":                 d("EnemyPoisonDuration"),
	"poison duration on you":          "SelfPoisonDuration",
	"duration of poisons on you":      "SelfPoisonDuration",
	"duration of poisons you inflict": d("EnemyPoisonDuration"),
	"to cause bleeding":               "BleedChance",
	"to cause bleeding on hit":        "BleedChance",
	"to inflict bleeding":             "BleedChance",
	"to inflict bleeding on hit":      "BleedChance",
	"to bleed":                        "BleedChance",
	"bleed duration":                  d("EnemyBleedDuration"),
	"bleeding duration":               d("EnemyBleedDuration"),
	"bleed duration on you":           "SelfBleedDuration",
	// Misc modifiers
	"movement speed":                            "MovementSpeed",
	"attack, cast and movement speed":           d("Speed", "MovementSpeed"),
	"action speed":                              "ActionSpeed",
	"light radius":                              "LightRadius",
	"rarity of items found":                     "LootRarity",
	"rarity of items dropped":                   "LootRarity",
	"quantity of items found":                   "LootQuantity",
	"quantity of items dropped":                 "LootQuantity",
	"item quantity":                             "LootQuantity",
	"strength requirement":                      "StrRequirement",
	"dexterity requirement":                     "DexRequirement",
	"intelligence requirement":                  "IntRequirement",
	"omni requirement":                          "OmniRequirement",
	"strength and intelligence requirement":     d("StrRequirement", "IntRequirement"),
	"attribute requirements":                    d("StrRequirement", "DexRequirement", "IntRequirement"),
	"effect of socketed jewels":                 "SocketedJewelEffect",
	"effect of socketed abyss jewels":           "SocketedJewelEffect",
	"to inflict fire exposure on hit":           "FireExposureChance",
	"to apply fire exposure on hit":             "FireExposureChance",
	"to inflict cold exposure on hit":           "ColdExposureChance",
	"to apply cold exposure on hit":             "ColdExposureChance",
	"to inflict lightning exposure on hit":      "LightningExposureChance",
	"to apply lightning exposure on hit":        "LightningExposureChance",
	"to ignore enemy physical damage reduction": "ChanceToIgnoreEnemyPhysicalDamageReduction",
	// Flask and Tincture modifiers
	"effect":                                    "LocalEffect",
	"effect of flasks":                          "FlaskEffect",
	"effect of tinctures":                       "TinctureEffect",
	"amount recovered":                          "FlaskRecovery",
	"life recovered":                            "FlaskRecovery",
	"life recovery from flasks used":            "FlaskLifeRecovery",
	"recovery":                                  "FlaskLifeRecoveryLowLife",
	"mana recovered":                            "FlaskRecovery",
	"life recovery from flasks":                 "FlaskLifeRecovery",
	"mana recovery from flasks":                 "FlaskManaRecovery",
	"life and mana recovery from flasks":        d("FlaskLifeRecovery", "FlaskManaRecovery"),
	"flask effect duration":                     "FlaskDuration",
	"recovery speed":                            "FlaskRecoveryRate",
	"recovery rate":                             "FlaskRecoveryRate",
	"flask recovery rate":                       "FlaskRecoveryRate",
	"flask recovery speed":                      "FlaskRecoveryRate",
	"flask life recovery rate":                  "FlaskLifeRecoveryRate",
	"flask mana recovery rate":                  "FlaskManaRecoveryRate",
	"extra charges":                             "FlaskCharges",
	"maximum charges":                           "FlaskCharges",
	"charges used":                              "FlaskChargesUsed",
	"charges per use":                           "FlaskChargesUsed",
	"flask charges used":                        "FlaskChargesUsed",
	"flask charges gained":                      "FlaskChargesGained",
	"charge recovery":                           "FlaskChargeRecovery",
	"for flasks you use to not consume charges": "FlaskChanceNotConsumeCharges",
	"for tinctures to not inflict mana burn":    "TincturesNotInflictManaBurn",
	"mana burn rate":                            "TinctureManaBurnRate",
	"impales you inflict last":                  "ImpaleStacksMax",
	// Buffs
	"adrenaline":                   "Condition:Adrenaline",
	"elusive":                      "Condition:CanBeElusive",
	"onslaught":                    "Condition:Onslaught",
	"rampage":                      "Condition:Rampage",
	"soul eater":                   "Condition:CanHaveSoulEater",
	"phasing":                      "Condition:Phasing",
	"arcane surge":                 "Condition:ArcaneSurge",
	"unholy might":                 d("Condition:UnholyMight", "Condition:CanWither"),
	"chaotic might":                "Condition:ChaoticMight",
	"lesser brutal shrine buff":    "Condition:LesserBrutalShrine",
	"lesser massive shrine buff":   "Condition:LesserMassiveShrine",
	"acceleration shrine buff":     "Condition:AccelerationShrine",
	"brutal shrine buff":           "Condition:BrutalShrine",
	"diamond shrine buff":          "Condition:DiamondShrine",
	"echoing shrine buff":          "Condition:EchoingShrine",
	"gloom shrine buff":            "Condition:GloomShrine",
	"greater freezing shrine buff": "Condition:GreaterFreezingShrine",
	"greater shocking shrine buff": "Condition:GreaterShockingShrine",
	"greater skeletal shrine buff": "Condition:GreaterSkeletalShrine",
	"impenetrable shrine buff":     "Condition:ImpenetrableShrine",
	"massive shrine buff":          "Condition:MassiveShrine",
	"replenishing shrine buff":     "Condition:ReplenishingShrine",
	"resistance shrine buff":       "Condition:ResistanceShrine",
	"resonating shrine buff":       "Condition:ResonatingShrine",
}
