package modparser

// Map of modifier names — ModParser.lua:161.
var modNameList = map[string]nameValue{
	// Attributes
	"strength":                   name("Str"),
	"dexterity":                  name("Dex"),
	"intelligence":               name("Int"),
	"omniscience":                name("Omni"),
	"strength and dexterity":     &PatternEntry{Names: []string{"Str", "Dex", "StrDex"}},
	"strength and intelligence":  &PatternEntry{Names: []string{"Str", "Int", "StrInt"}},
	"dexterity and intelligence": &PatternEntry{Names: []string{"Dex", "Int", "DexInt"}},
	"attributes":                 &PatternEntry{Names: []string{"Str", "Dex", "Int", "All"}},
	"all attributes":             &PatternEntry{Names: []string{"Str", "Dex", "Int", "All"}},
	"devotion":                   name("Devotion"),
	// Life/mana
	"life":                   name("Life"),
	"maximum life":           name("Life"),
	"life regeneration rate": name("LifeRegen"),
	"life regeneration also applies to energy shield": name("LifeRegenAppliesToEnergyShield"),
	"life and mana":              &PatternEntry{Names: []string{"Life", "Mana"}},
	"maximum life and mana":      &PatternEntry{Names: []string{"Life", "Mana"}},
	"mana":                       name("Mana"),
	"maximum mana":               name("Mana"),
	"mana regeneration":          name("ManaRegen"),
	"mana regeneration rate":     name("ManaRegen"),
	"mana cost":                  name("ManaCost"),
	"mana cost of":               name("ManaCost"),
	"mana cost of skills":        name("ManaCost"),
	"mana cost of attacks":       &PatternEntry{Names: []string{"ManaCost"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"total cost":                 name("Cost"),
	"total mana cost":            name("ManaCost"),
	"total mana cost of skills":  name("ManaCost"),
	"life cost of skills":        name("LifeCost"),
	"rage cost of skills":        name("RageCost"),
	"souls per use":              name("SoulCost"),
	"cost of":                    name("Cost"),
	"cost of skills":             name("Cost"),
	"cost of attacks":            &PatternEntry{Names: []string{"Cost"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"cost of retaliation skills": &PatternEntry{Names: []string{"Cost"}, Tag: &SkillTypeTag{SkillType: SkillTypeRetaliation}},
	// Cost efficiency
	"cost efficiency":                         name("CostEfficiency"),
	"cost efficiency of skills":               name("CostEfficiency"),
	"cost efficiency of attacks":              &PatternEntry{Names: []string{"CostEfficiency"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"cost efficiency of spells":               &PatternEntry{Names: []string{"CostEfficiency"}, Tag: &SkillTypeTag{SkillType: SkillTypeSpell}},
	"mana cost efficiency":                    name("ManaCostEfficiency"),
	"mana cost efficiency of skills":          name("ManaCostEfficiency"),
	"mana cost efficiency of attacks":         &PatternEntry{Names: []string{"ManaCostEfficiency"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"mana cost efficiency of spells":          &PatternEntry{Names: []string{"ManaCostEfficiency"}, Tag: &SkillTypeTag{SkillType: SkillTypeSpell}},
	"life cost efficiency":                    name("LifeCostEfficiency"),
	"life cost efficiency of skills":          name("LifeCostEfficiency"),
	"life cost efficiency of attacks":         &PatternEntry{Names: []string{"LifeCostEfficiency"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"life cost efficiency of spells":          &PatternEntry{Names: []string{"LifeCostEfficiency"}, Tag: &SkillTypeTag{SkillType: SkillTypeSpell}},
	"energy shield cost efficiency":           name("ESCostEfficiency"),
	"energy shield cost efficiency of skills": name("ESCostEfficiency"),
	"es cost efficiency":                      name("ESCostEfficiency"),
	"es cost efficiency of skills":            name("ESCostEfficiency"),
	"soul cost efficiency":                    name("SoulCostEfficiency"),
	"soul cost efficiency of skills":          name("SoulCostEfficiency"),
	"rage cost efficiency":                    name("RageCostEfficiency"),
	"rage cost efficiency of skills":          name("RageCostEfficiency"),
	"mana reserved":                           name("ManaReserved"),
	"mana reservation":                        name("ManaReserved"),
	"mana reservation of skills":              &PatternEntry{Names: []string{"ManaReserved"}, Tag: &SkillTypeTag{SkillType: SkillTypeAura}},
	"mana reservation efficiency of skills":   name("ManaReservationEfficiency"),
	"life reserved":                           name("LifeReserved"),
	"life reservation":                        name("LifeReserved"),
	"life reservation of skills":              &PatternEntry{Names: []string{"LifeReserved"}, Tag: &SkillTypeTag{SkillType: SkillTypeAura}},
	"life reservation efficiency of skills":   name("LifeReservationEfficiency"),
	"reservation of skills":                   name("Reserved"),
	"mana reservation if cast as an aura":     &PatternEntry{Names: []string{"ManaReserved"}, Tag: &SkillTypeTag{SkillType: SkillTypeAura}},
	"reservation if cast as an aura":          &PatternEntry{Names: []string{"Reserved"}, Tag: &SkillTypeTag{SkillType: SkillTypeAura}},
	"reservation":                             &PatternEntry{Names: []string{"Reserved"}},
	"reservation efficiency":                  name("ReservationEfficiency"),
	"reservation efficiency of skills":        name("ReservationEfficiency"),
	"mana reservation efficiency":             name("ManaReservationEfficiency"),
	"life reservation efficiency":             name("LifeReservationEfficiency"),
	// Primary defences
	"maximum energy shield":                     name("EnergyShield"),
	"energy shield recharge rate":               name("EnergyShieldRecharge"),
	"start of energy shield recharge":           name("EnergyShieldRechargeFaster"),
	"restoration of ward":                       name("WardRechargeFaster"),
	"armour":                                    name("Armour"),
	"evasion":                                   name("Evasion"),
	"evasion rating":                            name("Evasion"),
	"energy shield":                             name("EnergyShield"),
	"ward":                                      name("Ward"),
	"armour and evasion":                        name("ArmourAndEvasion"),
	"armour and evasion rating":                 name("ArmourAndEvasion"),
	"evasion rating and armour":                 name("ArmourAndEvasion"),
	"armour and energy shield":                  name("ArmourAndEnergyShield"),
	"evasion rating and energy shield":          name("EvasionAndEnergyShield"),
	"evasion and energy shield":                 name("EvasionAndEnergyShield"),
	"armour, evasion and energy shield":         name("Defences"),
	"defences":                                  name("Defences"),
	"to evade":                                  name("EvadeChance"),
	"chance to evade":                           name("EvadeChance"),
	"to evade attacks":                          name("EvadeChance"),
	"to evade attack hits":                      name("EvadeChance"),
	"chance to evade attacks":                   name("EvadeChance"),
	"chance to evade attack hits":               name("EvadeChance"),
	"chance to evade projectile attacks":        name("ProjectileEvadeChance"),
	"chance to evade melee attacks":             name("MeleeEvadeChance"),
	"evasion rating against melee attacks":      name("MeleeEvasion"),
	"evasion rating against projectile attacks": name("ProjectileEvasion"),
	// Resistances
	"physical damage reduction":                                   name("PhysicalDamageReduction"),
	"physical damage reduction from hits":                         name("PhysicalDamageReductionWhenHit"),
	"elemental damage reduction":                                  name("ElementalDamageReduction"),
	"fire resistance":                                             name("FireResist"),
	"maximum fire resistance":                                     name("FireResistMax"),
	"cold resistance":                                             name("ColdResist"),
	"maximum cold resistance":                                     name("ColdResistMax"),
	"lightning resistance":                                        name("LightningResist"),
	"maximum lightning resistance":                                name("LightningResistMax"),
	"chaos resistance":                                            name("ChaosResist"),
	"maximum chaos resistance":                                    name("ChaosResistMax"),
	"fire and cold resistances":                                   &PatternEntry{Names: []string{"FireResist", "ColdResist"}},
	"fire and lightning resistances":                              &PatternEntry{Names: []string{"FireResist", "LightningResist"}},
	"cold and lightning resistances":                              &PatternEntry{Names: []string{"ColdResist", "LightningResist"}},
	"elemental resistance":                                        name("ElementalResist"),
	"elemental resistances":                                       name("ElementalResist"),
	"all elemental resistances":                                   name("ElementalResist"),
	"elemental and chaos resistances":                             &PatternEntry{Names: []string{"ElementalResist", "ChaosResist"}},
	"all resistances":                                             &PatternEntry{Names: []string{"ElementalResist", "ChaosResist"}},
	"all maximum elemental resistances":                           name("ElementalResistMax"),
	"all maximum resistances":                                     &PatternEntry{Names: []string{"ElementalResistMax", "ChaosResistMax"}},
	"all elemental resistances and maximum elemental resistances": &PatternEntry{Names: []string{"ElementalResist", "ElementalResistMax"}},
	"fire and chaos resistances":                                  &PatternEntry{Names: []string{"FireResist", "ChaosResist"}},
	"cold and chaos resistances":                                  &PatternEntry{Names: []string{"ColdResist", "ChaosResist"}},
	"lightning and chaos resistances":                             &PatternEntry{Names: []string{"LightningResist", "ChaosResist"}},
	// Damage taken
	"damage taken":                                          name("DamageTaken"),
	"damage taken when hit":                                 name("DamageTakenWhenHit"),
	"damage taken from hits":                                name("DamageTakenWhenHit"),
	"damage over time taken":                                name("DamageTakenOverTime"),
	"damage taken from damage over time":                    name("DamageTakenOverTime"),
	"attack damage taken":                                   name("AttackDamageTaken"),
	"spell damage taken":                                    name("SpellDamageTaken"),
	"physical damage taken":                                 name("PhysicalDamageTaken"),
	"physical damage from hits taken":                       name("PhysicalDamageFromHitsTaken"),
	"physical damage taken when hit":                        name("PhysicalDamageTakenWhenHit"),
	"physical damage taken from hits":                       name("PhysicalDamageTakenWhenHit"),
	"physical damage taken from attacks":                    name("PhysicalDamageTakenFromAttacks"),
	"physical damage taken from attack hits":                name("PhysicalDamageTakenFromAttacks"),
	"physical damage taken from projectile attacks":         name("PhysicalDamageTakenFromProjectileAttacks"),
	"physical damage taken from projectile attack hits":     name("PhysicalDamageTakenFromProjectileAttacks"),
	"fire, cold and lightning damage taken from spell hits": &PatternEntry{Names: []string{"FireDamageTakenFromSpells", "ColdDamageTakenFromSpells", "LightningDamageTakenFromSpells"}},
	"damage taken of each damage type from spell hits":      name("DamageTakenFromSpells"),
	"physical damage taken over time":                       name("PhysicalDamageTakenOverTime"),
	"physical damage over time taken":                       name("PhysicalDamageTakenOverTime"),
	"physical damage over time damage taken":                name("PhysicalDamageTakenOverTime"),
	"reflected physical damage taken":                       name("PhysicalReflectedDamageTaken"),
	"lightning damage taken":                                name("LightningDamageTaken"),
	"lightning damage from hits taken":                      name("LightningDamageFromHitsTaken"),
	"lightning damage taken when hit":                       name("LightningDamageTakenWhenHit"),
	"lightning damage taken from attacks":                   name("LightningDamageTakenFromAttacks"),
	"lightning damage taken from attack hits":               name("LightningDamageTakenFromAttacks"),
	"lightning damage taken over time":                      name("LightningDamageTakenOverTime"),
	"cold damage taken":                                     name("ColdDamageTaken"),
	"cold damage from hits taken":                           name("ColdDamageFromHitsTaken"),
	"cold damage taken when hit":                            name("ColdDamageTakenWhenHit"),
	"cold damage taken from hits":                           name("ColdDamageTakenWhenHit"),
	"cold damage taken from attacks":                        name("ColdDamageTakenFromAttacks"),
	"cold damage taken from attack hits":                    name("ColdDamageTakenFromAttacks"),
	"cold damage taken over time":                           name("ColdDamageTakenOverTime"),
	"fire damage taken":                                     name("FireDamageTaken"),
	"fire damage from hits taken":                           name("FireDamageFromHitsTaken"),
	"fire damage taken when hit":                            name("FireDamageTakenWhenHit"),
	"fire damage taken from hits":                           name("FireDamageTakenWhenHit"),
	"fire damage taken from attacks":                        name("FireDamageTakenFromAttacks"),
	"fire damage taken from attack hits":                    name("FireDamageTakenFromAttacks"),
	"fire damage taken over time":                           name("FireDamageTakenOverTime"),
	"chaos damage taken":                                    name("ChaosDamageTaken"),
	"chaos damage from hits taken":                          name("ChaosDamageFromHitsTaken"),
	"chaos damage taken when hit":                           name("ChaosDamageTakenWhenHit"),
	"chaos damage taken from hits":                          name("ChaosDamageTakenWhenHit"),
	"chaos damage taken from attacks":                       name("ChaosDamageTakenFromAttacks"),
	"chaos damage taken from attack hits":                   name("ChaosDamageTakenFromAttacks"),
	"chaos damage taken over time":                          name("ChaosDamageTakenOverTime"),
	"chaos damage over time taken":                          name("ChaosDamageTakenOverTime"),
	"elemental taken":                                       name("ElementalDamageTaken"),
	"elemental damage taken":                                name("ElementalDamageTaken"),
	"elemental damage from hits taken":                      name("ElementalDamageFromHitsTaken"),
	"elemental damage taken when hit":                       name("ElementalDamageTakenWhenHit"),
	"elemental damage taken from hits":                      name("ElementalDamageTakenWhenHit"),
	"elemental damage taken over time":                      name("ElementalDamageTakenOverTime"),
	"cold and lightning damage taken":                       &PatternEntry{Names: []string{"ColdDamageTaken", "LightningDamageTaken"}},
	"fire and lightning damage taken":                       &PatternEntry{Names: []string{"FireDamageTaken", "LightningDamageTaken"}},
	"fire and cold damage taken":                            &PatternEntry{Names: []string{"FireDamageTaken", "ColdDamageTaken"}},
	"physical and chaos damage taken":                       &PatternEntry{Names: []string{"PhysicalDamageTaken", "ChaosDamageTaken"}},
	"reflected elemental damage taken":                      name("ElementalReflectedDamageTaken"),
	// Other defences
	"to dodge attacks":                               name("AttackDodgeChance"),
	"to dodge attack hits":                           name("AttackDodgeChance"),
	"to dodge spells":                                name("SpellDodgeChance"),
	"to dodge spell hits":                            name("SpellDodgeChance"),
	"to dodge spell damage":                          name("SpellDodgeChance"),
	"to dodge attacks and spells":                    &PatternEntry{Names: []string{"AttackDodgeChance", "SpellDodgeChance"}},
	"to dodge attacks and spell damage":              &PatternEntry{Names: []string{"AttackDodgeChance", "SpellDodgeChance"}},
	"to dodge attack and spell hits":                 &PatternEntry{Names: []string{"AttackDodgeChance", "SpellDodgeChance"}},
	"to dodge attack or spell hits":                  &PatternEntry{Names: []string{"AttackDodgeChance", "SpellDodgeChance"}},
	"to suppress spell damage":                       &PatternEntry{Names: []string{"SpellSuppressionChance"}},
	"amount of suppressed spell damage prevented":    &PatternEntry{Names: []string{"SpellSuppressionEffect"}},
	"to amount of suppressed spell damage prevented": &PatternEntry{Names: []string{"SpellSuppressionEffect"}},
	"to block":                                                          name("BlockChance"),
	"to block attacks":                                                  name("BlockChance"),
	"to block attack damage":                                            name("BlockChance"),
	"block chance":                                                      name("BlockChance"),
	"chance to block":                                                   name("BlockChance"),
	"block chance with staves":                                          &PatternEntry{Names: []string{"BlockChance"}, Tag: &CondTag{Var: "UsingStaff"}},
	"to block with staves":                                              &PatternEntry{Names: []string{"BlockChance"}, Tag: &CondTag{Var: "UsingStaff"}},
	"block chance against projectiles":                                  name("ProjectileBlockChance"),
	"to block projectile attack damage":                                 name("ProjectileBlockChance"),
	"to block projectile spell damage":                                  name("ProjectileSpellBlockChance"),
	"spell block chance":                                                name("SpellBlockChance"),
	"to block spells":                                                   name("SpellBlockChance"),
	"to block spell damage":                                             name("SpellBlockChance"),
	"chance to block attacks and spells":                                &PatternEntry{Names: []string{"BlockChance", "SpellBlockChance"}},
	"chance to block attack and spell damage":                           &PatternEntry{Names: []string{"BlockChance", "SpellBlockChance"}},
	"to block attack and spell damage":                                  &PatternEntry{Names: []string{"BlockChance", "SpellBlockChance"}},
	"maximum block chance":                                              name("BlockChanceMax"),
	"maximum chance to block attack damage":                             name("BlockChanceMax"),
	"maximum chance to block spell damage":                              name("SpellBlockChanceMax"),
	"life gained when you block":                                        name("LifeOnBlock"),
	"mana gained when you block":                                        name("ManaOnBlock"),
	"energy shield when you block":                                      name("EnergyShieldOnBlock"),
	"maximum chance to dodge spell hits":                                name("SpellDodgeChanceMax"),
	"to avoid all damage from hits":                                     name("AvoidAllDamageFromHitsChance"),
	"to avoid physical damage from hits":                                name("AvoidPhysicalDamageChance"),
	"to avoid fire damage when hit":                                     name("AvoidFireDamageChance"),
	"to avoid fire damage from hits":                                    name("AvoidFireDamageChance"),
	"to avoid cold damage when hit":                                     name("AvoidColdDamageChance"),
	"to avoid cold damage from hits":                                    name("AvoidColdDamageChance"),
	"to avoid lightning damage when hit":                                name("AvoidLightningDamageChance"),
	"to avoid lightning damage from hits":                               name("AvoidLightningDamageChance"),
	"to avoid elemental damage when hit":                                &PatternEntry{Names: []string{"AvoidFireDamageChance", "AvoidColdDamageChance", "AvoidLightningDamageChance"}},
	"to avoid elemental damage from hits":                               &PatternEntry{Names: []string{"AvoidFireDamageChance", "AvoidColdDamageChance", "AvoidLightningDamageChance"}},
	"to avoid damage of each element from hits":                         &PatternEntry{Names: []string{"AvoidFireDamageChance", "AvoidColdDamageChance", "AvoidLightningDamageChance"}},
	"to avoid projectiles":                                              name("AvoidProjectilesChance"),
	"to avoid being stunned":                                            name("AvoidStun"),
	"to avoid interruption from stuns while casting":                    name("AvoidInterruptStun"),
	"to ignore stuns while casting":                                     name("AvoidInterruptStun"),
	"to avoid being shocked":                                            name("AvoidShock"),
	"to avoid being frozen":                                             name("AvoidFreeze"),
	"to avoid being chilled":                                            name("AvoidChill"),
	"to avoid being ignited":                                            name("AvoidIgnite"),
	"to avoid non-damaging ailments on you":                             &PatternEntry{Names: []string{"AvoidShock", "AvoidFreeze", "AvoidChill", "AvoidSap", "AvoidBrittle", "AvoidScorch"}},
	"to avoid blind":                                                    name("AvoidBlind"),
	"to avoid elemental ailments":                                       name("AvoidElementalAilments"),
	"to avoid elemental status ailments":                                name("AvoidElementalAilments"),
	"to avoid ailments":                                                 name("AvoidAilments"),
	"to avoid status ailments":                                          name("AvoidAilments"),
	"to avoid bleeding":                                                 name("AvoidBleed"),
	"to avoid being poisoned":                                           name("AvoidPoison"),
	"to avoid being impaled":                                            name("AvoidImpale"),
	"damage is taken from mana before life":                             name("DamageTakenFromManaBeforeLife"),
	"lightning damage is taken from mana before life":                   name("LightningDamageTakenFromManaBeforeLife"),
	"damage taken from mana before life":                                name("DamageTakenFromManaBeforeLife"),
	"effect of curses on you":                                           name("CurseEffectOnSelf"),
	"effect of curses on them":                                          name("CurseEffectOnSelf"),
	"effect of exposure on you":                                         name("ExposureEffectOnSelf"),
	"effect of withered on you":                                         name("WitherEffectOnSelf"),
	"life recovery rate":                                                name("LifeRecoveryRate"),
	"mana recovery rate":                                                name("ManaRecoveryRate"),
	"energy shield recovery rate":                                       name("EnergyShieldRecoveryRate"),
	"energy shield regeneration rate":                                   name("EnergyShieldRegen"),
	"recovery rate of life, mana and energy shield":                     &PatternEntry{Names: []string{"LifeRecoveryRate", "ManaRecoveryRate", "EnergyShieldRecoveryRate"}},
	"recovery rate of life and energy shield":                           &PatternEntry{Names: []string{"LifeRecoveryRate", "EnergyShieldRecoveryRate"}},
	"maximum life, mana and global energy shield":                       &PatternEntry{Names: []string{"Life", "Mana", "EnergyShield"}, Tag: &MarkerTag{Marker: TagGlobal}},
	"non-chaos damage taken bypasses energy shield":                     &PatternEntry{Names: []string{"PhysicalEnergyShieldBypass", "LightningEnergyShieldBypass", "ColdEnergyShieldBypass", "FireEnergyShieldBypass"}},
	"armour applies to fire, cold and lightning damage taken from hits": &PatternEntry{Names: []string{"ArmourAppliesToFireDamageTaken", "ArmourAppliesToColdDamageTaken", "ArmourAppliesToLightningDamageTaken"}},
	"damage taken recouped as life":                                     name("LifeRecoup"),
	"physical damage taken recouped as life":                            name("PhysicalLifeRecoup"),
	"lightning damage taken recouped as life":                           name("LightningLifeRecoup"),
	"cold damage taken recouped as life":                                name("ColdLifeRecoup"),
	"fire damage taken recouped as life":                                name("FireLifeRecoup"),
	"chaos damage taken recouped as life":                               name("ChaosLifeRecoup"),
	"damage taken recouped as energy shield":                            name("EnergyShieldRecoup"),
	"damage taken recouped as mana":                                     name("ManaRecoup"),
	"damage taken recouped as life, mana and energy shield":             &PatternEntry{Names: []string{"LifeRecoup", "EnergyShieldRecoup", "ManaRecoup"}},
	"missing unreserved life before being hit by an enemy":              name("MissingLifeBeforeEnemyHit"),
	"missing unreserved mana before being hit by an enemy":              name("MissingManaBeforeEnemyHit"),
	// Stun/knockback modifiers
	"stun recovery":                name("StunRecovery"),
	"stun and block recovery":      name("StunRecovery"),
	"block and stun recovery":      name("StunRecovery"),
	"stun duration on you":         name("StunDuration"),
	"stun threshold":               name("StunThreshold"),
	"block recovery":               name("BlockRecovery"),
	"enemy stun threshold":         name("EnemyStunThreshold"),
	"stun duration on enemies":     name("EnemyStunDuration"),
	"stun duration":                name("EnemyStunDuration"),
	"to double stun duration":      name("DoubleEnemyStunDurationChance"),
	"to knock enemies back on hit": name("EnemyKnockbackChance"),
	"knockback distance":           name("EnemyKnockbackDistance"),
	// Auras/curses/buffs
	"aura effect":                                                name("AuraEffect"),
	"effect of non-curse auras you cast":                         &PatternEntry{Names: []string{"AuraEffect"}, TagList: []Tag{&SkillTypeTag{SkillType: SkillTypeAura}, &SkillTypeTag{SkillType: SkillTypeAppliesCurse, Neg: true}}},
	"effect of non-curse auras from your skills":                 &PatternEntry{Names: []string{"AuraEffect"}, TagList: []Tag{&SkillTypeTag{SkillType: SkillTypeAura}, &SkillTypeTag{SkillType: SkillTypeAppliesCurse, Neg: true}}},
	"effect of non-curse auras from your skills on your minions": &PatternEntry{Names: []string{"AuraEffectOnSelf"}, TagList: []Tag{&SkillTypeTag{SkillType: SkillTypeAura}, &SkillTypeTag{SkillType: SkillTypeAppliesCurse, Neg: true}}, AddToMinion: true},
	"effect of non-curse auras":                                  &PatternEntry{Names: []string{"AuraEffect"}, Tag: &SkillTypeTag{SkillType: SkillTypeAppliesCurse, Neg: true}},
	"effect of your curses":                                      name("CurseEffect"),
	"effect of auras on you":                                     name("AuraEffectOnSelf"),
	"effect of auras on your minions":                            &PatternEntry{Names: []string{"AuraEffectOnSelf"}, AddToMinion: true},
	"effect of auras from mines":                                 &PatternEntry{Names: []string{"AuraEffect"}, KeywordFlags: KeywordMine},
	"effect of auras from your vaal skills":                      &PatternEntry{Names: []string{"AuraEffect"}, KeywordFlags: KeywordVaal},
	"effect of consecrated ground you create":                    name("ConsecratedGroundEffect"),
	"curse effect":                                               name("CurseEffect"),
	"effect of curses applied by bane":                           &PatternEntry{Names: []string{"CurseEffect"}, Tag: &CondTag{Var: "AppliedByBane"}},
	"effect of your marks":                                       &PatternEntry{Names: []string{"CurseEffect"}, Tag: &SkillTypeTag{SkillType: SkillTypeMark}},
	"effect of marks":                                            &PatternEntry{Names: []string{"CurseEffect"}, Tag: &SkillTypeTag{SkillType: SkillTypeMark}},
	"effect of arcane surge on you":                              name("ArcaneSurgeEffect"),
	"curse duration":                                             &PatternEntry{Names: []string{"Duration"}, KeywordFlags: KeywordCurse},
	"hex duration":                                               &PatternEntry{Names: []string{"Duration"}, Tag: &SkillTypeTag{SkillType: SkillTypeHex}},
	"radius of auras":                                            &PatternEntry{Names: []string{"AreaOfEffect"}, KeywordFlags: KeywordAura},
	"radius of curses":                                           &PatternEntry{Names: []string{"AreaOfEffect"}, KeywordFlags: KeywordCurse},
	"buff effect":                                                name("BuffEffect"),
	"effect of buffs on you":                                     name("BuffEffectOnSelf"),
	"effect of buffs granted by your golems":                     &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillTypeTag{SkillType: SkillTypeGolem}},
	"effect of buffs granted by socketed golem skills":           &PatternEntry{Names: []string{"BuffEffect"}, AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "golem"}},
	"effect of the buff granted by your stone golems":            &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Summon Stone Golem", IncludeTransfigured: true}},
	"effect of the buff granted by your lightning golems":        &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Summon Lightning Golem", IncludeTransfigured: true}},
	"effect of the buff granted by your ice golems":              &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Summon Ice Golem", IncludeTransfigured: true}},
	"effect of the buff granted by your flame golems":            &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Summon Flame Golem", IncludeTransfigured: true}},
	"effect of the buff granted by your chaos golems":            &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Summon Chaos Golem", IncludeTransfigured: true}},
	"effect of the buff granted by your carrion golems":          &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Summon Carrion Golem", IncludeTransfigured: true}},
	"effect of offering spells":                                  &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillNameList: []string{"Bone Offering", "Flesh Offering", "Spirit Offering", "Blood Offering"}}},
	"effect of offerings":                                        &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillNameList: []string{"Bone Offering", "Flesh Offering", "Spirit Offering", "Blood Offering"}}},
	"effect of heralds on you":                                   &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillTypeTag{SkillType: SkillTypeHerald}},
	"effect of herald buffs on you":                              &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillTypeTag{SkillType: SkillTypeHerald}},
	"effect of buffs granted by your active ancestor totems":     &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillNameList: []string{"Ancestral Warchief", "Ancestral Protector", "Earthbreaker"}}},
	"effect of buffs your ancestor totems grant ":                &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillNameList: []string{"Ancestral Warchief", "Ancestral Protector", "Earthbreaker"}}},
	"effect of shrine buffs on you":                              name("ShrineBuffEffect"),
	"effect of withered":                                         name("WitherEffect"),
	"warcry effect":                                              &PatternEntry{Names: []string{"BuffEffect"}, KeywordFlags: KeywordWarcry},
	"aspect of the avian buff effect":                            &PatternEntry{Names: []string{"BuffEffect"}, Tag: &SkillNameTag{SkillName: "Aspect of the Avian"}},
	"maximum rage":                                               name("MaximumRage"),
	"minimum rage":                                               name("MinimumRage"),
	"rage effect":                                                name("RageEffect"),
	"maximum fortification":                                      name("MaximumFortification"),
	"fortification":                                              name("MinimumFortification"),
	"fortification duration":                                     name("FortifyDuration"),
	"maximum valour":                                             name("MaximumValour"),
	// Charges
	"maximum power charge":                                name("PowerChargesMax"),
	"maximum power charges":                               name("PowerChargesMax"),
	"minimum power charge":                                name("PowerChargesMin"),
	"minimum power charges":                               name("PowerChargesMin"),
	"power charge duration":                               name("PowerChargesDuration"),
	"maximum frenzy charge":                               name("FrenzyChargesMax"),
	"maximum frenzy charges":                              name("FrenzyChargesMax"),
	"minimum frenzy charge":                               name("FrenzyChargesMin"),
	"minimum frenzy charges":                              name("FrenzyChargesMin"),
	"frenzy charge duration":                              name("FrenzyChargesDuration"),
	"maximum endurance charge":                            name("EnduranceChargesMax"),
	"maximum endurance charges":                           name("EnduranceChargesMax"),
	"minimum endurance charge":                            name("EnduranceChargesMin"),
	"minimum endurance charges":                           name("EnduranceChargesMin"),
	"minimum endurance, frenzy and power charges":         &PatternEntry{Names: []string{"PowerChargesMin", "FrenzyChargesMin", "EnduranceChargesMin"}},
	"endurance charge duration":                           name("EnduranceChargesDuration"),
	"maximum frenzy charges and maximum power charges":    &PatternEntry{Names: []string{"FrenzyChargesMax", "PowerChargesMax"}},
	"maximum power charges and maximum endurance charges": &PatternEntry{Names: []string{"PowerChargesMax", "EnduranceChargesMax"}},
	"maximum endurance, frenzy and power charges":         &PatternEntry{Names: []string{"EnduranceChargesMax", "PowerChargesMax", "FrenzyChargesMax"}},
	"endurance, frenzy and power charge duration":         &PatternEntry{Names: []string{"PowerChargesDuration", "FrenzyChargesDuration", "EnduranceChargesDuration"}},
	"maximum siphoning charge":                            name("SiphoningChargesMax"),
	"maximum siphoning charges":                           name("SiphoningChargesMax"),
	"maximum challenger charges":                          name("ChallengerChargesMax"),
	"maximum blitz charges":                               name("BlitzChargesMax"),
	"maximum number of crab barriers":                     name("CrabBarriersMax"),
	"maximum blood charges":                               name("BloodChargesMax"),
	"maximum spirit charges":                              name("SpiritChargesMax"),
	"charge duration":                                     name("ChargeDuration"),
	// On hit/kill/leech effects
	"life gained on kill":                                                       name("LifeOnKill"),
	"life per enemy killed":                                                     name("LifeOnKill"),
	"life on kill":                                                              name("LifeOnKill"),
	"life per enemy hit":                                                        &PatternEntry{Names: []string{"LifeOnHit"}, Flags: FlagHit},
	"life gained for each enemy hit":                                            &PatternEntry{Names: []string{"LifeOnHit"}, Flags: FlagHit},
	"life for each enemy hit":                                                   &PatternEntry{Names: []string{"LifeOnHit"}, Flags: FlagHit},
	"mana gained on kill":                                                       name("ManaOnKill"),
	"mana per enemy killed":                                                     name("ManaOnKill"),
	"mana on kill":                                                              name("ManaOnKill"),
	"mana per enemy hit":                                                        &PatternEntry{Names: []string{"ManaOnHit"}, Flags: FlagHit},
	"mana gained for each enemy hit":                                            &PatternEntry{Names: []string{"ManaOnHit"}, Flags: FlagHit},
	"mana for each enemy hit":                                                   &PatternEntry{Names: []string{"ManaOnHit"}, Flags: FlagHit},
	"energy shield gained on kill":                                              name("EnergyShieldOnKill"),
	"energy shield per enemy killed":                                            name("EnergyShieldOnKill"),
	"energy shield on kill":                                                     name("EnergyShieldOnKill"),
	"energy shield per enemy hit":                                               &PatternEntry{Names: []string{"EnergyShieldOnHit"}, Flags: FlagHit},
	"energy shield gained for each enemy hit":                                   &PatternEntry{Names: []string{"EnergyShieldOnHit"}, Flags: FlagHit},
	"energy shield for each enemy hit":                                          &PatternEntry{Names: []string{"EnergyShieldOnHit"}, Flags: FlagHit},
	"life and mana gained for each enemy hit":                                   &PatternEntry{Names: []string{"LifeOnHit", "ManaOnHit"}, Flags: FlagHit},
	"life and mana for each enemy hit":                                          &PatternEntry{Names: []string{"LifeOnHit", "ManaOnHit"}, Flags: FlagHit},
	"damage as life":                                                            name("DamageLifeLeech"),
	"elemental damage as energy shield":                                         name("ElementalDamageEnergyShieldLeech"),
	"life leeched per second":                                                   name("LifeLeechRate"),
	"mana leeched per second":                                                   name("ManaLeechRate"),
	"total recovery per second from life leech":                                 name("LifeLeechRate"),
	"recovery per second from life leech":                                       name("LifeLeechRate"),
	"total recovery per second from energy shield leech":                        name("EnergyShieldLeechRate"),
	"recovery per second from energy shield leech":                              name("EnergyShieldLeechRate"),
	"total recovery per second from mana leech":                                 name("ManaLeechRate"),
	"recovery per second from mana leech":                                       name("ManaLeechRate"),
	"total recovery per second from life, mana, or energy shield leech":         &PatternEntry{Names: []string{"LifeLeechRate", "ManaLeechRate", "EnergyShieldLeechRate"}},
	"maximum recovery per life leech":                                           name("MaxLifeLeechInstance"),
	"maximum recovery per energy shield leech":                                  name("MaxEnergyShieldLeechInstance"),
	"maximum recovery per mana leech":                                           name("MaxManaLeechInstance"),
	"maximum total recovery per second from life leech":                         name("MaxLifeLeechRate"),
	"maximum total life recovery per second from leech":                         name("MaxLifeLeechRate"),
	"maximum total recovery per second from energy shield leech":                name("MaxEnergyShieldLeechRate"),
	"maximum total energy shield recovery per second from leech":                name("MaxEnergyShieldLeechRate"),
	"maximum total recovery per second from mana leech":                         name("MaxManaLeechRate"),
	"maximum total mana recovery per second from leech":                         name("MaxManaLeechRate"),
	"maximum total life, mana and energy shield recovery per second from leech": &PatternEntry{Names: []string{"MaxLifeLeechRate", "MaxManaLeechRate", "MaxEnergyShieldLeechRate"}},
	"life and mana leech is instant":                                            &PatternEntry{Names: []string{"InstantManaLeech", "InstantLifeLeech"}},
	"life leech is instant":                                                     &PatternEntry{Names: []string{"InstantLifeLeech"}},
	"mana leech is instant":                                                     &PatternEntry{Names: []string{"InstantManaLeech"}},
	"energy shield leech is instant":                                            &PatternEntry{Names: []string{"InstantEnergyShieldLeech"}},
	"leech is instant":                                                          &PatternEntry{Names: []string{"InstantEnergyShieldLeech", "InstantManaLeech", "InstantLifeLeech"}},
	"to impale enemies on hit":                                                  name("ImpaleChance"),
	"to impale on attack hit":                                                   &PatternEntry{Names: []string{"ImpaleChance"}, Flags: FlagAttack},
	"to impale on spell hit":                                                    &PatternEntry{Names: []string{"ImpaleChance"}, Flags: FlagSpell},
	"impale effect":                                                             name("ImpaleEffect"),
	"effect of impales you inflict":                                             name("ImpaleEffect"),
	"effects of impale inflicted":                                               name("ImpaleEffect"), // typo / old wording change
	"effect of impales inflicted":                                               name("ImpaleEffect"),
	"impale duration":                                                           name("ImpaleDuration"),
	// Projectile modifiers
	"projectile":       name("ProjectileCount"),
	"projectiles":      name("ProjectileCount"),
	"arrow":            &PatternEntry{Names: []string{"ProjectileCount"}, KeywordFlags: KeywordArrow},
	"arrows":           &PatternEntry{Names: []string{"ProjectileCount"}, KeywordFlags: KeywordArrow},
	"projectile speed": name("ProjectileSpeed"),
	"arrow speed":      &PatternEntry{Names: []string{"ProjectileSpeed"}, KeywordFlags: KeywordArrow},
	"chain ":           name("ChainCountMax"),
	// Totem/trap/mine/brand modifiers
	"totem placement speed":                          name("TotemPlacementSpeed"),
	"totem life":                                     name("TotemLife"),
	"totem duration":                                 name("TotemDuration"),
	"maximum number of summoned totems":              name("ActiveTotemLimit"),
	"maximum number of summoned totems.":             name("ActiveTotemLimit"), // Mark plz
	"maximum number of summoned ballista totems":     &PatternEntry{Names: []string{"ActiveBallistaLimit"}, Tag: &SkillTypeTag{SkillType: SkillTypeTotemsAreBallistae}},
	"maximum number of summoned searing bond totems": &PatternEntry{Names: []string{"ActiveTotemLimit"}, Tag: &SkillNameTag{SkillName: "Searing Bond", IncludeTransfigured: true}},
	"trap throwing speed":                            name("TrapThrowingSpeed"),
	"trap and mine throwing speed":                   &PatternEntry{Names: []string{"TrapThrowingSpeed", "MineLayingSpeed"}},
	"trap trigger area of effect":                    name("TrapTriggerAreaOfEffect"),
	"trap duration":                                  name("TrapDuration"),
	"cooldown recovery speed for throwing traps":     &PatternEntry{Names: []string{"CooldownRecovery"}, KeywordFlags: KeywordTrap},
	"cooldown recovery rate for throwing traps":      &PatternEntry{Names: []string{"CooldownRecovery"}, KeywordFlags: KeywordTrap},
	"additional trap":                                name("TrapThrowCount"),
	"additional traps":                               name("TrapThrowCount"),
	"mine laying speed":                              name("MineLayingSpeed"),
	"mine throwing speed":                            name("MineLayingSpeed"),
	"mine detonation area of effect":                 name("MineDetonationAreaOfEffect"),
	"mine duration":                                  name("MineDuration"),
	"additional mine":                                name("MineThrowCount"),
	"additional mines":                               name("MineThrowCount"),
	"activation frequency":                           name("BrandActivationFrequency"),
	"brand activation frequency":                     name("BrandActivationFrequency"),
	"brand attachment range":                         name("BrandAttachmentRange"),
	// Minion modifiers
	"maximum number of skeletons":                name("ActiveSkeletonLimit"),
	"maximum number of summoned skeletons":       name("ActiveSkeletonLimit"),
	"maximum number of zombies":                  name("ActiveZombieLimit"),
	"maximum number of raised zombies":           name("ActiveZombieLimit"),
	"number of zombies allowed":                  name("ActiveZombieLimit"),
	"maximum number of spectres":                 name("ActiveSpectreLimit"),
	"maximum number of raised spectres":          name("ActiveSpectreLimit"),
	"maximum number of golems":                   name("ActiveGolemLimit"),
	"maximum number of summoned golems":          name("ActiveGolemLimit"),
	"maximum number of animated weapons":         name("ActiveAnimatedWeaponLimit"),
	"maximum number of summoned raging spirits":  name("ActiveRagingSpiritLimit"),
	"maximum number of raging spirits":           name("ActiveRagingSpiritLimit"),
	"maximum number of raised spiders":           name("ActiveSpiderLimit"),
	"maximum number of summoned reapers":         name("ActiveReaperLimit"),
	"maximum number of summoned phantasms":       name("ActivePhantasmLimit"),
	"maximum number of summoned holy relics":     name("ActiveHolyRelicLimit"),
	"maximum number of sentinels of absolution":  name("ActiveSentinelOfAbsolutionLimit"),
	"maximum number of sentinels of dominance":   name("ActiveSentinelOfDominanceLimit"),
	"maximum number of sentinels of purity":      name("ActiveSentinelOfPurityLimit"),
	"maximum number of summoned spectral wolves": name("ActiveWolfLimit"),
	"maximum number of living lightning":         name("ActiveLivingLightningLimit"),
	"maximum number of holy armaments":           name("ActiveHolyStrikeMinionLimit"),
	"number of summoned arbalists":               name("ActiveArbalistLimit"),
	"minion duration":                            &PatternEntry{Names: []string{"Duration"}, TagList: []Tag{&SkillTypeTag{SkillType: SkillTypeCreatesMinion}, &SkillTypeTag{SkillType: SkillTypeMinion}}},
	"skeleton duration":                          &PatternEntry{Names: []string{"Duration"}, Tag: &SkillNameTag{SkillName: "Summon Skeletons", IncludeTransfigured: true}},
	"sentinel of dominance duration":             &PatternEntry{Names: []string{"Duration"}, Tag: &SkillNameTag{SkillName: "Dominating Blow", IncludeTransfigured: true}},
	// Other skill modifiers
	"radius":                                name("AreaOfEffect"),
	"radius of area skills":                 name("AreaOfEffect"),
	"area of effect radius":                 name("AreaOfEffect"),
	"area of effect":                        name("AreaOfEffect"),
	"area of effect of skills":              name("AreaOfEffect"),
	"area of effect of area skills":         name("AreaOfEffect"),
	"aspect of the spider area of effect":   &PatternEntry{Names: []string{"AreaOfEffect"}, Tag: &SkillNameTag{SkillName: "Aspect of the Spider"}},
	"firestorm explosion area of effect":    &PatternEntry{Names: []string{"AreaOfEffectSecondary"}, Tag: &SkillNameTag{SkillName: "Firestorm", IncludeTransfigured: true}},
	"duration":                              name("Duration"),
	"skill effect duration":                 name("Duration"),
	"chaos skill effect duration":           &PatternEntry{Names: []string{"Duration"}, KeywordFlags: KeywordChaos},
	"soul gain prevention duration":         name("SoulGainPreventionDuration"),
	"aspect of the spider debuff duration":  &PatternEntry{Names: []string{"Duration"}, Tag: &SkillNameTag{SkillName: "Aspect of the Spider"}},
	"fire trap burning ground duration":     &PatternEntry{Names: []string{"Duration"}, Tag: &SkillNameTag{SkillName: "Fire Trap"}},
	"sentinel of absolution duration":       &PatternEntry{Names: []string{"SecondaryDuration"}, Tag: &SkillNameTag{SkillName: "Absolution", IncludeTransfigured: true}},
	"cooldown recovery":                     name("CooldownRecovery"),
	"cooldown recovery speed":               name("CooldownRecovery"),
	"cooldown recovery rate":                name("CooldownRecovery"),
	"cooldown use":                          name("AdditionalCooldownUses"),
	"cooldown uses":                         name("AdditionalCooldownUses"),
	"weapon range":                          name("WeaponRange"),
	"metres to weapon range":                name("WeaponRangeMetre"),
	"metre to weapon range":                 name("WeaponRangeMetre"),
	"melee range":                           name("MeleeWeaponRange"),
	"melee weapon range":                    name("MeleeWeaponRange"),
	"melee weapon and unarmed range":        &PatternEntry{Names: []string{"MeleeWeaponRange", "UnarmedRange"}},
	"melee weapon and unarmed attack range": &PatternEntry{Names: []string{"MeleeWeaponRange", "UnarmedRange"}},
	"melee strike range":                    &PatternEntry{Names: []string{"MeleeWeaponRange", "UnarmedRange"}},
	"metres to melee strike range":          &PatternEntry{Names: []string{"MeleeWeaponRangeMetre", "UnarmedRangeMetre"}},
	"metre to melee strike range":           &PatternEntry{Names: []string{"MeleeWeaponRangeMetre", "UnarmedRangeMetre"}},
	"to deal double damage":                 name("DoubleDamageChance"),
	"to deal triple damage":                 name("TripleDamageChance"),
	// Buffs
	"onslaught effect":           name("OnslaughtEffect"),
	"effect of onslaught on you": name("OnslaughtEffect"),
	"adrenaline duration":        name("AdrenalineDuration"),
	"effect of tailwind on you":  name("TailwindEffectOnSelf"),
	"elusive effect":             name("ElusiveEffect"),
	"effect of elusive on you":   name("ElusiveEffect"),
	"effect of infusion":         name("InfusionEffect"),
	// Basic damage types
	"damage":                   name("Damage"),
	"physical damage":          name("PhysicalDamage"),
	"minimum physical damage":  name("MinPhysicalDamage"),
	"maximum physical damage":  name("MaxPhysicalDamage"),
	"lightning damage":         name("LightningDamage"),
	"minimum lightning damage": name("MinLightningDamage"),
	"maximum lightning damage": name("MaxLightningDamage"),
	"cold damage":              name("ColdDamage"),
	"minimum cold damage":      name("MinColdDamage"),
	"maximum cold damage":      name("MaxColdDamage"),
	"fire damage":              name("FireDamage"),
	"minimum fire damage":      name("MinFireDamage"),
	"maximum fire damage":      name("MaxFireDamage"),
	"chaos damage":             name("ChaosDamage"),
	"minimum chaos damage":     name("MinChaosDamage"),
	"maximum chaos damage":     name("MaxChaosDamage"),
	"non-chaos damage":         name("NonChaosDamage"),
	"elemental damage":         name("ElementalDamage"),
	// Other damage forms
	"attack damage":                        &PatternEntry{Names: []string{"Damage"}, Flags: FlagAttack},
	"attack physical damage":               &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagAttack},
	"physical attack damage":               &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagAttack},
	"minimum physical attack damage":       &PatternEntry{Names: []string{"MinPhysicalDamage"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"maximum physical attack damage":       &PatternEntry{Names: []string{"MaxPhysicalDamage"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"minimum attack damage":                &PatternEntry{Names: []string{"MinDamage"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"maximum attack damage":                &PatternEntry{Names: []string{"MaxDamage"}, Tag: &SkillTypeTag{SkillType: SkillTypeAttack}},
	"physical weapon damage":               &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagWeapon},
	"physical damage with weapons":         &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagWeapon},
	"melee damage":                         &PatternEntry{Names: []string{"Damage"}, Flags: FlagMelee},
	"physical melee damage":                &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagMelee},
	"melee physical damage":                &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagMelee},
	"projectile damage":                    &PatternEntry{Names: []string{"Damage"}, Flags: FlagProjectile},
	"projectile attack damage":             &PatternEntry{Names: []string{"Damage"}, Flags: FlagProjectile | FlagAttack},
	"bow damage":                           &PatternEntry{Names: []string{"Damage"}, Flags: FlagBow | FlagHit},
	"damage with arrow hits":               &PatternEntry{Names: []string{"Damage"}, Flags: FlagHit, KeywordFlags: KeywordArrow},
	"wand damage":                          &PatternEntry{Names: []string{"Damage"}, Flags: FlagWand | FlagHit},
	"wand physical damage":                 &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagWand | FlagHit},
	"claw physical damage":                 &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagClaw | FlagHit},
	"sword physical damage":                &PatternEntry{Names: []string{"PhysicalDamage"}, Flags: FlagSword | FlagHit},
	"damage over time":                     &PatternEntry{Names: []string{"Damage"}, Flags: FlagDot},
	"physical damage over time":            &PatternEntry{Names: []string{"PhysicalDamage"}, KeywordFlags: KeywordPhysicalDot},
	"cold damage over time":                &PatternEntry{Names: []string{"ColdDamage"}, KeywordFlags: KeywordColdDot},
	"chaos damage over time":               &PatternEntry{Names: []string{"ChaosDamage"}, KeywordFlags: KeywordChaosDot},
	"burning damage":                       &PatternEntry{Names: []string{"FireDamage"}, KeywordFlags: KeywordFireDot},
	"damage with ignite":                   &PatternEntry{Names: []string{"Damage"}, KeywordFlags: KeywordIgnite},
	"damage with ignites":                  &PatternEntry{Names: []string{"Damage"}, KeywordFlags: KeywordIgnite},
	"damage with ignites inflicted":        &PatternEntry{Names: []string{"Damage"}, KeywordFlags: KeywordIgnite},
	"damage with bleed":                    &PatternEntry{Names: []string{"Damage"}, KeywordFlags: KeywordBleed},
	"damage with bleeding":                 &PatternEntry{Names: []string{"Damage"}, KeywordFlags: KeywordBleed},
	"damage with poison":                   &PatternEntry{Names: []string{"Damage"}, KeywordFlags: KeywordPoison},
	"incinerate damage for each stage":     &PatternEntry{Names: []string{"Damage"}, TagList: []Tag{&MultiplierTag{Var: "IncinerateStage"}, &SkillNameTag{SkillName: "Incinerate"}}},
	"physical damage over time multiplier": name("PhysicalDotMultiplier"),
	"fire damage over time multiplier":     name("FireDotMultiplier"),
	"cold damage over time multiplier":     name("ColdDotMultiplier"),
	"chaos damage over time multiplier":    name("ChaosDotMultiplier"),
	"damage over time multiplier":          name("DotMultiplier"),
	// Crit/accuracy/speed modifiers
	"critical strike chance":            name("CritChance"),
	"critical hit chance":               name("CritChance"),
	"attack critical strike chance":     &PatternEntry{Names: []string{"CritChance"}, Flags: FlagAttack},
	"critical strike multiplier":        name("CritMultiplier"),
	"attack critical strike multiplier": &PatternEntry{Names: []string{"CritMultiplier"}, Flags: FlagAttack},
	"accuracy":                          name("Accuracy"),
	"accuracy rating":                   name("Accuracy"),
	"minion accuracy rating":            &PatternEntry{Names: []string{"Accuracy"}, AddToMinion: true},
	"attack speed":                      &PatternEntry{Names: []string{"Speed"}, Flags: FlagAttack},
	"cast speed":                        &PatternEntry{Names: []string{"Speed"}, Flags: FlagCast},
	"warcry speed":                      &PatternEntry{Names: []string{"WarcrySpeed"}, KeywordFlags: KeywordWarcry},
	"attack and cast speed":             name("Speed"),
	"dps":                               name("DPS"),
	// Elemental ailments
	"to shock":                                    name("EnemyShockChance"),
	"shock chance":                                name("EnemyShockChance"),
	"to freeze":                                   name("EnemyFreezeChance"),
	"freeze chance":                               name("EnemyFreezeChance"),
	"to ignite":                                   name("EnemyIgniteChance"),
	"ignite chance":                               name("EnemyIgniteChance"),
	"to freeze, shock and ignite":                 &PatternEntry{Names: []string{"EnemyFreezeChance", "EnemyShockChance", "EnemyIgniteChance"}},
	"to scorch enemies":                           name("EnemyScorchChance"),
	"to inflict brittle":                          name("EnemyBrittleChance"),
	"to sap enemies":                              name("EnemySapChance"),
	"effect of scorch":                            name("EnemyScorchEffect"),
	"effect of sap":                               name("EnemySapEffect"),
	"effect of brittle":                           name("EnemyBrittleEffect"),
	"effect of shock":                             name("EnemyShockEffect"),
	"effect of shock on you":                      name("SelfShockEffect"),
	"effect of shock you inflict":                 name("EnemyShockEffect"),
	"effect of shocks you inflict":                name("EnemyShockEffect"),
	"effect of lightning ailments":                &PatternEntry{Names: []string{"EnemyShockEffect", "EnemySapEffect"}},
	"effect of chill":                             name("EnemyChillEffect"),
	"effect of chill and shock on you":            &PatternEntry{Names: []string{"SelfChillEffect", "SelfShockEffect"}},
	"chill effect":                                name("EnemyChillEffect"),
	"effect of chill you inflict":                 name("EnemyChillEffect"),
	"effect of chills you inflict":                name("EnemyChillEffect"),
	"effect of cold ailments":                     &PatternEntry{Names: []string{"EnemyChillEffect", "EnemyBrittleEffect"}},
	"effect of chill on you":                      name("SelfChillEffect"),
	"effect of freeze on you":                     name("SelfFreezeEffect"),
	"effect of non-damaging ailments":             &PatternEntry{Names: []string{"EnemyShockEffect", "EnemyChillEffect", "EnemyFreezeEffect", "EnemyScorchEffect", "EnemyBrittleEffect", "EnemySapEffect"}},
	"effect of non-damaging ailments you inflict": &PatternEntry{Names: []string{"EnemyShockEffect", "EnemyChillEffect", "EnemyFreezeEffect", "EnemyScorchEffect", "EnemyBrittleEffect", "EnemySapEffect"}},
	"effect of non-damaging ailments on you":      &PatternEntry{Names: []string{"SelfShockEffect", "SelfChillEffect", "SelfFreezeEffect", "SelfScorchEffect", "SelfBrittleEffect", "SelfSapEffect"}},
	"shock duration":                              name("EnemyShockDuration"),
	"duration of shocks you inflict":              name("EnemyShockDuration"),
	"shock duration on you":                       name("SelfShockDuration"),
	"duration of lightning ailments":              &PatternEntry{Names: []string{"EnemyShockDuration", "EnemySapDuration"}},
	"freeze duration":                             name("EnemyFreezeDuration"),
	"duration of freezes you inflict":             name("EnemyFreezeDuration"),
	"freeze duration on you":                      name("SelfFreezeDuration"),
	"chill duration":                              name("EnemyChillDuration"),
	"duration of chills you inflict":              name("EnemyChillDuration"),
	"chill duration on you":                       name("SelfChillDuration"),
	"duration of cold ailments":                   &PatternEntry{Names: []string{"EnemyFreezeDuration", "EnemyChillDuration", "EnemyBrittleDuration"}},
	"ignite duration":                             name("EnemyIgniteDuration"),
	"duration of ignites you inflict":             name("EnemyIgniteDuration"),
	"ignite duration on you":                      name("SelfIgniteDuration"),
	"duration of ignite on you":                   name("SelfIgniteDuration"),
	"duration of elemental ailments":              name("EnemyElementalAilmentDuration"),
	"duration of elemental ailments on you":       name("SelfElementalAilmentDuration"),
	"duration of elemental status ailments":       name("EnemyElementalAilmentDuration"),
	"duration of ailments":                        name("EnemyAilmentDuration"),
	"duration of ailments on you":                 name("SelfAilmentDuration"),
	"elemental ailment duration on you":           name("SelfElementalAilmentDuration"),
	"duration of ailments you inflict":            name("EnemyAilmentDuration"),
	"duration of ailments inflicted":              name("EnemyAilmentDuration"),
	"duration of ailments inflicted on you":       name("SelfAilmentDuration"),
	"duration of damaging ailments on you":        &PatternEntry{Names: []string{"SelfIgniteDuration", "SelfBleedDuration", "SelfPoisonDuration"}},
	// Other ailments
	"to poison":                       name("PoisonChance"),
	"to cause poison":                 name("PoisonChance"),
	"to poison on hit":                name("PoisonChance"),
	"poison duration":                 &PatternEntry{Names: []string{"EnemyPoisonDuration"}},
	"poison duration on you":          name("SelfPoisonDuration"),
	"duration of poisons on you":      name("SelfPoisonDuration"),
	"duration of poisons you inflict": &PatternEntry{Names: []string{"EnemyPoisonDuration"}},
	"to cause bleeding":               name("BleedChance"),
	"to cause bleeding on hit":        name("BleedChance"),
	"to inflict bleeding":             name("BleedChance"),
	"to inflict bleeding on hit":      name("BleedChance"),
	"to bleed":                        name("BleedChance"),
	"bleed duration":                  &PatternEntry{Names: []string{"EnemyBleedDuration"}},
	"bleeding duration":               &PatternEntry{Names: []string{"EnemyBleedDuration"}},
	"bleed duration on you":           name("SelfBleedDuration"),
	// Misc modifiers
	"movement speed":                            name("MovementSpeed"),
	"attack, cast and movement speed":           &PatternEntry{Names: []string{"Speed", "MovementSpeed"}},
	"action speed":                              name("ActionSpeed"),
	"light radius":                              name("LightRadius"),
	"rarity of items found":                     name("LootRarity"),
	"rarity of items dropped":                   name("LootRarity"),
	"quantity of items found":                   name("LootQuantity"),
	"quantity of items dropped":                 name("LootQuantity"),
	"item quantity":                             name("LootQuantity"),
	"strength requirement":                      name("StrRequirement"),
	"dexterity requirement":                     name("DexRequirement"),
	"intelligence requirement":                  name("IntRequirement"),
	"omni requirement":                          name("OmniRequirement"),
	"strength and intelligence requirement":     &PatternEntry{Names: []string{"StrRequirement", "IntRequirement"}},
	"attribute requirements":                    &PatternEntry{Names: []string{"StrRequirement", "DexRequirement", "IntRequirement"}},
	"effect of socketed jewels":                 name("SocketedJewelEffect"),
	"effect of socketed abyss jewels":           name("SocketedJewelEffect"),
	"to inflict fire exposure on hit":           name("FireExposureChance"),
	"to apply fire exposure on hit":             name("FireExposureChance"),
	"to inflict cold exposure on hit":           name("ColdExposureChance"),
	"to apply cold exposure on hit":             name("ColdExposureChance"),
	"to inflict lightning exposure on hit":      name("LightningExposureChance"),
	"to apply lightning exposure on hit":        name("LightningExposureChance"),
	"to ignore enemy physical damage reduction": name("ChanceToIgnoreEnemyPhysicalDamageReduction"),
	// Flask and Tincture modifiers
	"effect":                                    name("LocalEffect"),
	"effect of flasks":                          name("FlaskEffect"),
	"effect of tinctures":                       name("TinctureEffect"),
	"amount recovered":                          name("FlaskRecovery"),
	"life recovered":                            name("FlaskRecovery"),
	"life recovery from flasks used":            name("FlaskLifeRecovery"),
	"recovery":                                  name("FlaskLifeRecoveryLowLife"),
	"mana recovered":                            name("FlaskRecovery"),
	"life recovery from flasks":                 name("FlaskLifeRecovery"),
	"mana recovery from flasks":                 name("FlaskManaRecovery"),
	"life and mana recovery from flasks":        &PatternEntry{Names: []string{"FlaskLifeRecovery", "FlaskManaRecovery"}},
	"flask effect duration":                     name("FlaskDuration"),
	"recovery speed":                            name("FlaskRecoveryRate"),
	"recovery rate":                             name("FlaskRecoveryRate"),
	"flask recovery rate":                       name("FlaskRecoveryRate"),
	"flask recovery speed":                      name("FlaskRecoveryRate"),
	"flask life recovery rate":                  name("FlaskLifeRecoveryRate"),
	"flask mana recovery rate":                  name("FlaskManaRecoveryRate"),
	"extra charges":                             name("FlaskCharges"),
	"maximum charges":                           name("FlaskCharges"),
	"charges used":                              name("FlaskChargesUsed"),
	"charges per use":                           name("FlaskChargesUsed"),
	"flask charges used":                        name("FlaskChargesUsed"),
	"flask charges gained":                      name("FlaskChargesGained"),
	"charge recovery":                           name("FlaskChargeRecovery"),
	"for flasks you use to not consume charges": name("FlaskChanceNotConsumeCharges"),
	"for tinctures to not inflict mana burn":    name("TincturesNotInflictManaBurn"),
	"mana burn rate":                            name("TinctureManaBurnRate"),
	"impales you inflict last":                  name("ImpaleStacksMax"),
	// Buffs
	"adrenaline":                   name("Condition:Adrenaline"),
	"elusive":                      name("Condition:CanBeElusive"),
	"onslaught":                    name("Condition:Onslaught"),
	"rampage":                      name("Condition:Rampage"),
	"soul eater":                   name("Condition:CanHaveSoulEater"),
	"phasing":                      name("Condition:Phasing"),
	"arcane surge":                 name("Condition:ArcaneSurge"),
	"unholy might":                 &PatternEntry{Names: []string{"Condition:UnholyMight", "Condition:CanWither"}},
	"chaotic might":                name("Condition:ChaoticMight"),
	"lesser brutal shrine buff":    name("Condition:LesserBrutalShrine"),
	"lesser massive shrine buff":   name("Condition:LesserMassiveShrine"),
	"acceleration shrine buff":     name("Condition:AccelerationShrine"),
	"brutal shrine buff":           name("Condition:BrutalShrine"),
	"diamond shrine buff":          name("Condition:DiamondShrine"),
	"echoing shrine buff":          name("Condition:EchoingShrine"),
	"gloom shrine buff":            name("Condition:GloomShrine"),
	"greater freezing shrine buff": name("Condition:GreaterFreezingShrine"),
	"greater shocking shrine buff": name("Condition:GreaterShockingShrine"),
	"greater skeletal shrine buff": name("Condition:GreaterSkeletalShrine"),
	"impenetrable shrine buff":     name("Condition:ImpenetrableShrine"),
	"massive shrine buff":          name("Condition:MassiveShrine"),
	"replenishing shrine buff":     name("Condition:ReplenishingShrine"),
	"resistance shrine buff":       name("Condition:ResistanceShrine"),
	"resonating shrine buff":       name("Condition:ResonatingShrine"),
}
