package modparser

// List of modifier flags found before the modifier name — ModParser.lua:1101.
var preFlagList = map[string]any{
	// Weapon types
	`^axe attacks [hd][ae][va][el] `:                           Tag{"flags": ModFlag.Axe},
	`^axe or sword attacks [hd][ae][va][el] `:                  d(p("tag", Tag{"type": "ModFlagOr", "modFlags": ModFlag.Axe | ModFlag.Sword})),
	`^bow attacks [hd][ae][va][el] `:                           Tag{"flags": ModFlag.Bow},
	`^claw attacks [hd][ae][va][el] `:                          Tag{"flags": ModFlag.Claw},
	`^claw or dagger attacks [hd][ae][va][el] `:                d(p("tag", Tag{"type": "ModFlagOr", "modFlags": ModFlag.Claw | ModFlag.Dagger})),
	`^dagger attacks [hd][ae][va][el] `:                        Tag{"flags": ModFlag.Dagger},
	`^mace or sceptre attacks [hd][ae][va][el] `:               Tag{"flags": ModFlag.Mace},
	`^mace, sceptre or staff attacks [hd][ae][va][el] `:        d(p("tag", Tag{"type": "ModFlagOr", "modFlags": ModFlag.Mace | ModFlag.Staff})),
	`^staff attacks [hd][ae][va][el] `:                         Tag{"flags": ModFlag.Staff},
	`^sword attacks [hd][ae][va][el] `:                         Tag{"flags": ModFlag.Sword},
	`^wand attacks [hd][ae][va][el] `:                          Tag{"flags": ModFlag.Wand},
	`^unarmed attacks [hd][ae][va][el] `:                       Tag{"flags": ModFlag.Unarmed},
	`^attacks with one handed weapons [hd][ae][va][el] `:       Tag{"flags": ModFlag.Weapon1H},
	`^attacks with two handed weapons [hd][ae][va][el] `:       Tag{"flags": ModFlag.Weapon2H},
	`^attacks with melee weapons [hd][ae][va][el] `:            Tag{"flags": ModFlag.WeaponMelee},
	`^melee weapon hits [hd][ae][va][el] `:                     Tag{"flags": ModFlag.WeaponMelee | ModFlag.Hit},
	`^attacks with one handed melee weapons [hd][ae][va][el] `: Tag{"flags": ModFlag.Weapon1H | ModFlag.WeaponMelee},
	`^attacks with two handed melee weapons [hd][ae][va][el] `: Tag{"flags": ModFlag.Weapon2H | ModFlag.WeaponMelee},
	`^attacks with ranged weapons [hd][ae][va][el] `:           Tag{"flags": ModFlag.WeaponRanged},
	// Damage types
	`^attack damage `:         Tag{"flags": ModFlag.Attack},
	`^hits deal `:             Tag{"keywordFlags": KeywordFlag.Hit},
	`^melee weapon damage`:    Tag{"flags": ModFlag.WeaponMelee},
	`^deal `:                  d(),
	`^critical strikes deal `: d(p("tag", Tag{"type": "Condition", "var": "CriticalStrike"})),
	`^poisons you inflict with critical strikes have `: d(p("keywordFlags", KeywordFlag.Poison|KeywordFlag.MatchAll), p("tag", Tag{"type": "Condition", "var": "CriticalStrike"})),
	// Add to minion
	`^minions `:                  Tag{"addToMinion": true},
	`^minions [hd][ae][va][el] `: Tag{"addToMinion": true},
	`^while a unique enemy is in your presence, minions [hd][ae][va][el] `:        d(p("addToMinion", true), p("playerTag", Tag{"type": "ActorCondition", "actor": "enemy", "var": "RareOrUnique"})),
	`^while a pinnacle atlas boss is in your presence, minions [hd][ae][va][el] `: d(p("addToMinion", true), p("playerTag", Tag{"type": "ActorCondition", "actor": "enemy", "var": "PinnacleBoss"})),
	`^minions leech `:                                                Tag{"addToMinion": true},
	`^minions' attacks deal `:                                        Tag{"addToMinion": true, "flags": ModFlag.Attack},
	`^minions created recently have `:                                d(p("addToMinion", true), p("playerTag", Tag{"type": "Condition", "var": "MinionsCreatedRecently"})),
	`^golems [hd][ae][va][el] `:                                      d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillType", "skillType": SkillType.Golem})),
	`^summoned golems [hd][ae][va][el] `:                             d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillType", "skillType": SkillType.Golem})),
	`^golem skills have `:                                            d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Golem})),
	`^non-minion skills have `:                                       d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Minion, "neg": true})),
	`^zombies [hd][ae][va][el] `:                                     d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Zombie", "includeTransfigured": true})),
	`^raised zombies [hd][ae][va][el] `:                              d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Zombie", "includeTransfigured": true})),
	`^skeletons [hd][ae][va][el] `:                                   d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Skeletons", "includeTransfigured": true})),
	`^raging spirits [hd][ae][va][el] `:                              d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Raging Spirit", "includeTransfigured": true})),
	`^summoned raging spirits [hd][ae][va][el] `:                     d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Raging Spirit", "includeTransfigured": true})),
	`^r?a?i?s?e?d? ?spectres [hd][ae][va][el] `:                      d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Raise Spectre", "includeTransfigured": true})),
	`^chaos golems [hd][ae][va][el] `:                                d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Chaos Golem", "includeTransfigured": true})),
	`^summoned chaos golems [hd][ae][va][el] `:                       d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Chaos Golem", "includeTransfigured": true})),
	`^flame golems [hd][ae][va][el] `:                                d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Flame Golem", "includeTransfigured": true})),
	`^summoned flame golems [hd][ae][va][el] `:                       d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Flame Golem", "includeTransfigured": true})),
	`^ice golems [hd][ae][va][el] `:                                  d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Ice Golem", "includeTransfigured": true})),
	`^summoned ice golems [hd][ae][va][el] `:                         d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Ice Golem", "includeTransfigured": true})),
	`^lightning golems [hd][ae][va][el] `:                            d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Lightning Golem", "includeTransfigured": true})),
	`^summoned lightning golems [hd][ae][va][el] `:                   d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Lightning Golem", "includeTransfigured": true})),
	`^stone golems [hd][ae][va][el] `:                                d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Stone Golem", "includeTransfigured": true})),
	`^summoned stone golems [hd][ae][va][el] `:                       d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Stone Golem", "includeTransfigured": true})),
	`^summoned carrion golems [hd][ae][va][el] `:                     d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Carrion Golem", "includeTransfigured": true})),
	`^summoned skitterbots [hd][ae][va][el] `:                        d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Carrion Golem", "includeTransfigured": true})),
	`^blink arrow and blink arrow clones [hd][ae][va][el] `:          d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Blink Arrow", "includeTransfigured": true})),
	`^mirror arrow and mirror arrow clones [hd][ae][va][el] `:        d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Mirror Arrow", "includeTransfigured": true})),
	`^animated weapons [hd][ae][va][el] `:                            d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Animate Weapon", "includeTransfigured": true})),
	`^animated guardians? deals? `:                                   d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Animate Guardian", "includeTransfigured": true})),
	`^summoned holy relics [hd][ae][va][el] `:                        d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Holy Relic", "includeTransfigured": true})),
	`^summoned reaper [dh][ea][as]l?s? `:                             d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Reaper", "includeTransfigured": true})),
	`^summoned arbalists [hgdf][aei][vair][eln] `:                    d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Arbalists"})),
	`^summoned arbalists' attacks have `:                             d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Summon Arbalists"})),
	`^herald skills [hd][ae][va][el] `:                               d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Herald})),
	`^agony crawler deals `:                                          d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Herald of Agony"})),
	`^summoned agony crawler fires `:                                 d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Herald of Agony"})),
	`^sentinels of purity deal `:                                     d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Herald of Purity"})),
	`^summoned sentinels of absolution have `:                        d(p("addToMinion", true), p("addToMinionTag", Tag{"type": "SkillName", "skillName": "Absolution", "includeTransfigured": true})),
	`^summoned sentinels have `:                                      d(p("addToMinion", true), p("addToMinionTag", d(p("type", "SkillName"), p("skillNameList", d("Herald of Purity", "Dominating Blow", "Absolution")), p("includeTransfigured", true)))),
	`^raised zombies' slam attack has `:                              d(p("addToMinion", true), p("tag", Tag{"type": "SkillId", "skillId": "ZombieSlam"})),
	`^raised spectres, raised zombies, and summoned skeletons have `: d(p("addToMinion", true), p("addToMinionTag", d(p("type", "SkillName"), p("skillNameList", d("Raise Spectre", "Raise Zombie", "Summon Skeletons")), p("includeTransfigured", true)))),
	// Totem/trap/mine
	`^attacks used by totems have `:                                      Tag{"flags": ModFlag.Attack, "keywordFlags": KeywordFlag.Totem},
	`^totems have `:                                                      Tag{"keywordFlags": KeywordFlag.Totem},
	`^skills used by totems [hd][ae][va][el] `:                           Tag{"keywordFlags": KeywordFlag.Totem},
	`^spells cast by totems [hd][ae][va][el] `:                           Tag{"flags": ModFlag.Spell, "keywordFlags": KeywordFlag.Totem},
	`^trap and mine damage `:                                             Tag{"keywordFlags": KeywordFlag.Trap | KeywordFlag.Mine},
	`^skills used by traps [hgd][ae][via][enl] `:                         Tag{"keywordFlags": KeywordFlag.Trap},
	`^skills which throw traps [hgd][ae][via][enl] `:                     Tag{"keywordFlags": KeywordFlag.Trap},
	`^skills used by mines [hgd][ae][via][enl] `:                         Tag{"keywordFlags": KeywordFlag.Mine},
	`^skills which throw mines ([hgd]?[ae]?[via]?[enl]?[ ]?)`:            Tag{"keywordFlags": KeywordFlag.Mine},
	`^skills used by your traps and mines ([hgd]?[ae]?[via]?[enl]?[ ]?)`: Tag{"keywordFlags": KeywordFlag.Trap | KeywordFlag.Mine},
	// Local damage
	`^attacks with this weapon `:                  d(p("tagList", d(d(p("type", "Condition"), p("var", "{Hand}Attack")), Tag{"type": "SkillType", "skillType": SkillType.Attack}))),
	`^attacks with this weapon [hd][ae][va][el] `: d(p("tagList", d(d(p("type", "Condition"), p("var", "{Hand}Attack")), Tag{"type": "SkillType", "skillType": SkillType.Attack}))),
	`^hits with this weapon [hd][ae][va][el] `:    d(p("flags", ModFlag.Hit), p("tagList", d(d(p("type", "Condition"), p("var", "{Hand}Attack")), Tag{"type": "SkillType", "skillType": SkillType.Attack}))),
	// Skill types
	`^attacks [hd][ae][va][el] `:                  Tag{"flags": ModFlag.Attack},
	`^attack skills [hd][ae][va][el] `:            Tag{"keywordFlags": KeywordFlag.Attack},
	`^spells [hd][ae][va][el] a? ?`:               Tag{"flags": ModFlag.Spell},
	`^spell skills [hd][ae][va][el] `:             d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Spell})),
	`^projectile attack skills [hd][ae][va][el] `: d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.RangedAttack})),
	`^projectiles from attacks [hd][ae][va][el] `: d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.RangedAttack})),
	`^arrows [hd][ae][va][el] `:                   d(p("tag", Tag{"type": "KeywordFlagAnd", "keywordFlags": KeywordFlag.Arrow})),
	`^bow skills [hdf][aei][var][el] `:            Tag{"keywordFlags": KeywordFlag.Bow},
	`^projectiles [hdf][aei][var][el] `:           Tag{"flags": ModFlag.Projectile},
	`^projectiles `:                               Tag{"flags": ModFlag.Projectile},
	`^melee attacks have `:                        Tag{"flags": ModFlag.Melee},
	`^movement attack skills have `:               Tag{"flags": ModFlag.Attack, "keywordFlags": KeywordFlag.Movement},
	`^travel skills have `:                        d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Travel})),
	`^link skills have `:                          d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Link})),
	`^lightning skills [hd][ae][va][el] a? ?`:     Tag{"keywordFlags": KeywordFlag.Lightning},
	`^lightning spells [hd][ae][va][el] a? ?`:     Tag{"keywordFlags": KeywordFlag.Lightning, "flags": ModFlag.Spell},
	`^cold skills [hd][ae][va][el] a? ?`:          Tag{"keywordFlags": KeywordFlag.Cold},
	`^cold spells [hd][ae][va][el] a? ?`:          Tag{"keywordFlags": KeywordFlag.Cold, "flags": ModFlag.Spell},
	`^fire skills [hd][ae][va][el] a? ?`:          Tag{"keywordFlags": KeywordFlag.Fire},
	`^fire spells [hd][ae][va][el] a? ?`:          Tag{"keywordFlags": KeywordFlag.Fire, "flags": ModFlag.Spell},
	`^chaos skills [hd][ae][va][el] a? ?`:         Tag{"keywordFlags": KeywordFlag.Chaos},
	`^vaal skills [hd][ae][va][el] `:              Tag{"keywordFlags": KeywordFlag.Vaal},
	`^vaal skills require `:                       Tag{"keywordFlags": KeywordFlag.Vaal},
	`^non-aura vaal skills require `:              d(p("keywordFlags", KeywordFlag.Vaal), p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura, "neg": true})),
	`^brand skills [hd][ae][va][el] `:             d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Brand})),
	`^channelling skills [hd][ae][va][el] `:       d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel})),
	`^curse skills [hd][ae][va][el] `:             Tag{"keywordFlags": KeywordFlag.Curse},
	`^hex skills [hd][ae][va][el] `:               d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Hex})),
	`^mark skills [hd][ae][va][el] `:              d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Mark})),
	`^melee skills [hd][ae][va][el] `:             d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Melee})),
	`^guard skills [hd][ae][va][el] `:             d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Guard})),
	`^banner skills [hd][ae][va][el] `:            d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Banner})),
	`^nova spells [hd][ae][va][el] `:              d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Nova})),
	`^area skills [hd][ae][va][el] `:              d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Area})),
	`^aura skills [hd][ae][va][el] `:              d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Aura})),
	`^prismatic skills [hd][ae][va][el] `:         d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.RandomElement})),
	`^retaliation skills [hd][ae][va][el] `:       d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Retaliation})),
	`^pact skills [hd][ae][va][el] `:              d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Pact})),
	`^warcry skills have `:                        d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Warcry})),
	`^non-curse aura skills have `:                d(p("tagList", d(Tag{"type": "SkillType", "skillType": SkillType.Aura}, Tag{"type": "SkillType", "skillType": SkillType.AppliesCurse, "neg": true}))),
	`^non-channelling skills have `:               d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Channel, "neg": true})),
	`^non-vaal skills deal `:                      d(p("tag", Tag{"type": "SkillType", "skillType": SkillType.Vaal, "neg": true})),
	`^skills [hgdf][aei][vari][eln] `:             d(),
	// Slot specific
	`^left ring slot: `:  d(p("tag", Tag{"type": "SlotNumber", "num": 1})),
	`^right ring slot: `: d(p("tag", Tag{"type": "SlotNumber", "num": 2})),
	`^socketed gems ([hgd]?[ae]?[via]?[enl]?[ \t\n\v\f\r]?)`: d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}")))),
	`^socketed skills [hgd][ae][via][enl] `:                  d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}")))),
	`^socketed travel skills [hgd][ae][via][enl] `:           d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "travel")))),
	`^socketed warcry skills [hgd][ae][via][enl] `:           d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "warcry")))),
	`^socketed attacks [hgd][ae][via][enl] `:                 d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "attack")))),
	`^socketed spells [hgd][ae][via][enl] `:                  d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "spell")))),
	`^socketed curse gems [hgd][ae][via][enl] `:              d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "curse")))),
	`^socketed melee gems [hgd][ae][via][enl] `:              d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "melee")))),
	`^socketed golem gems [hgd][ae][via][enl] `:              d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "golem")))),
	`^socketed golem skills [hgd][ae][via][enl] `:            d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "golem")))),
	`^socketed golem skills have minions `:                   d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "golem")))),
	`^socketed vaal skills [hgd][ae][via][enl] `:             d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"), p("keyword", "vaal")))),
	`^socketed projectile spells [hgdf][aei][viar][enl] `:    d(p("addToSkill", d(p("type", "SocketedIn"), p("slotName", "{SlotName}"))), p("tagList", d(Tag{"type": "SkillType", "skillType": SkillType.Projectile}, Tag{"type": "SkillType", "skillType": SkillType.Spell}))),
	// Enemy modifiers
	`^enemies withered by you [th]a[vk]e `:                        d(p("tag", Tag{"type": "MultiplierThreshold", "var": "WitheredStack", "threshold": 1}), p("applyToEnemy", true)),
	`^enemies shocked or frozen by you take `:                     d(p("tag", d(p("type", "Condition"), p("varList", d("Shocked", "Frozen")))), p("applyToEnemy", true), p("modSuffix", "Taken")),
	`^enemies affected by your spider's webs [thd][ae][avk][el] `: d(p("tag", Tag{"type": "MultiplierThreshold", "var": "Spider's WebStack", "threshold": 1}), p("applyToEnemy", true)),
	`^enemies you curse take `:                                    d(p("tag", Tag{"type": "Condition", "var": "Cursed"}), p("applyToEnemy", true), p("modSuffix", "Taken")),
	`^enemies you curse `:                                         d(p("tag", Tag{"type": "Condition", "var": "Cursed"}), p("applyToEnemy", true)),
	`^nearby enemies take `:                                       Tag{"modSuffix": "Taken", "applyToEnemy": true},
	`^nearby enemies have `:                                       Tag{"applyToEnemy": true},
	`^nearby enemies deal `:                                       Tag{"applyToEnemy": true},
	`^nearby enemies'? `:                                          Tag{"applyToEnemy": true},
	`^nearby enemy monsters' `:                                    Tag{"applyToEnemy": true},
	`against you`:                                                 Tag{"applyToEnemy": true, "actorEnemy": true},
	`^hits against you `:                                          Tag{"applyToEnemy": true, "flags": ModFlag.Hit},
	`^enemies near your totems deal `:                             Tag{"applyToEnemy": true},
	// Other
	`^your flasks grant `:                         d(),
	`^when hit, `:                                 d(),
	`^you and allies [hgd][ae][via][enl] `:        d(),
	`^auras from your skills grant `:              Tag{"addToAura": true},
	`^auras grant `:                               Tag{"addToAura": true},
	`^banners also grant `:                        Tag{"addToAura": true, "onlyAddToBanners": true},
	`^you and nearby allies `:                     Tag{"newAura": true},
	`^you and nearby allies [hgd][ae][via][enl] `: Tag{"newAura": true},
	`^nearby allies [hgd][ae][via][enl] `:         Tag{"newAura": true, "newAuraOnlyAllies": true},
	`^every rage also grants `:                    d(p("tag", Tag{"type": "Multiplier", "var": "RageEffect"})),
	`^each rage also grants `:                     d(p("tag", Tag{"type": "Multiplier", "var": "RageEffect"})),
	`^you and allies affected by auras from your skills [hgd][ae][via][enl] `: d(p("tag", Tag{"type": "Condition", "var": "AffectedByAura"})),
	`^take `:      Tag{"modSuffix": "Taken"},
	`^marauder: `: d(p("tag", Tag{"type": "Condition", "var": "ConnectedToMarauderStart"})),
	`^duelist: `:  d(p("tag", Tag{"type": "Condition", "var": "ConnectedToDuelistStart"})),
	`^ranger: `:   d(p("tag", Tag{"type": "Condition", "var": "ConnectedToRangerStart"})),
	`^shadow: `:   d(p("tag", Tag{"type": "Condition", "var": "ConnectedToShadowStart"})),
	`^witch: `:    d(p("tag", Tag{"type": "Condition", "var": "ConnectedToWitchStart"})),
	`^templar: `:  d(p("tag", Tag{"type": "Condition", "var": "ConnectedToTemplarStart"})),
	`^scion: `:    d(p("tag", Tag{"type": "Condition", "var": "ConnectedToScionStart"})),
	`^skills supported by spellslinger have `:                               d(p("tag", Tag{"type": "Condition", "var": "SupportedBySpellslinger"})),
	`^skills that have dealt a critical strike in the past 8 seconds deal `: d(p("tag", Tag{"type": "Condition", "var": "CritInPast8Sec"})),
	`^blink arrow and mirror arrow have `:                                   d(p("tag", d(p("type", "SkillName"), p("skillNameList", d("Blink Arrow", "Mirror Arrow")), p("includeTransfigured", true)))),
	`attacks with energy blades `:                                           d(p("flags", ModFlag.Attack), p("tag", Tag{"type": "Condition", "var": "AffectedByEnergyBlade"})),
	`^for each nearby corpse, `:                                             d(p("tag", Tag{"type": "Multiplier", "var": "NearbyCorpse"})),
	`^enemies in your link beams have `:                                     d(p("tag", Tag{"type": "Condition", "var": "BetweenYouAndLinkedTarget"}), p("applyToEnemy", true)),
	`^consecrated ground you create a?l?s?o? ?grants `:                      d(p("tag", Tag{"type": "Condition", "var": "OnConsecratedGround"})),
	// While in the presence of...
	`^while a unique enemy is in your presence, `:        d(p("tag", Tag{"type": "ActorCondition", "actor": "enemy", "var": "RareOrUnique"})),
	`^while a pinnacle atlas boss is in your presence, `: d(p("tag", Tag{"type": "ActorCondition", "actor": "enemy", "var": "PinnacleBoss"})),

	// enemies X by you take/have — ModParser.lua:1284-1305 (closures)
	`^enemies ([a-zA-Z]+) by you take `: fn(func(c caps) any {
		return d(p("tag", Tag{"type": "Condition", "var": firstToUpper(c.s(1))}), p("applyToEnemy", true), p("modSuffix", "Taken"))
	}),
	`^enemies ([a-zA-Z]+) by `: fn(func(c caps) any {
		return d(p("tag", Tag{"type": "Condition", "var": firstToUpper(c.s(1))}), p("applyToEnemy", true))
	}),
	`^enemies ([a-zA-Z]+) by you have `: fn(func(c caps) any {
		return d(p("tag", Tag{"type": "Condition", "var": firstToUpper(c.s(1))}), p("applyToEnemy", true))
	}),
	`^while a pinnacle atlas boss is in your presence, enemies you've hit recently have `: fn(func(c caps) any {
		return d(p("playerTagList", []any{Tag{"type": "Condition", "var": "HitRecently"}, Tag{"type": "ActorCondition", "actor": "enemy", "var": "PinnacleBoss"}}), p("applyToEnemy", true))
	}),
	`^while a unique enemy is in your presence, enemies you've hit recently have `: fn(func(c caps) any {
		return d(p("playerTagList", []any{Tag{"type": "Condition", "var": "HitRecently"}, Tag{"type": "ActorCondition", "actor": "enemy", "var": "RareOrUnique"}}), p("applyToEnemy", true))
	}),
	`^enemies you've hit recently have `: fn(func(c caps) any {
		return d(p("playerTag", Tag{"type": "Condition", "var": "HitRecently"}), p("applyToEnemy", true))
	}),
	`^hits against enemies ([a-zA-Z]+) by you have `: fn(func(c caps) any {
		return d(p("tag", Tag{"type": "ActorCondition", "actor": "enemy", "var": firstToUpper(c.s(1))}))
	}),
}
