package modparser

// List of modifier flags found before the modifier name — ModParser.lua:1101.
var preFlagList = map[string]entryValue{
	// Weapon types
	`^axe attacks [hd][ae][va][el] `:                           &PatternEntry{Flags: FlagAxe},
	`^axe or sword attacks [hd][ae][va][el] `:                  &PatternEntry{Tag: &ModFlagOrTag{ModFlags: FlagAxe | FlagSword}},
	`^bow attacks [hd][ae][va][el] `:                           &PatternEntry{Flags: FlagBow},
	`^claw attacks [hd][ae][va][el] `:                          &PatternEntry{Flags: FlagClaw},
	`^claw or dagger attacks [hd][ae][va][el] `:                &PatternEntry{Tag: &ModFlagOrTag{ModFlags: FlagClaw | FlagDagger}},
	`^dagger attacks [hd][ae][va][el] `:                        &PatternEntry{Flags: FlagDagger},
	`^mace or sceptre attacks [hd][ae][va][el] `:               &PatternEntry{Flags: FlagMace},
	`^mace, sceptre or staff attacks [hd][ae][va][el] `:        &PatternEntry{Tag: &ModFlagOrTag{ModFlags: FlagMace | FlagStaff}},
	`^staff attacks [hd][ae][va][el] `:                         &PatternEntry{Flags: FlagStaff},
	`^sword attacks [hd][ae][va][el] `:                         &PatternEntry{Flags: FlagSword},
	`^wand attacks [hd][ae][va][el] `:                          &PatternEntry{Flags: FlagWand},
	`^unarmed attacks [hd][ae][va][el] `:                       &PatternEntry{Flags: FlagUnarmed},
	`^attacks with one handed weapons [hd][ae][va][el] `:       &PatternEntry{Flags: FlagWeapon1H},
	`^attacks with two handed weapons [hd][ae][va][el] `:       &PatternEntry{Flags: FlagWeapon2H},
	`^attacks with melee weapons [hd][ae][va][el] `:            &PatternEntry{Flags: FlagWeaponMelee},
	`^melee weapon hits [hd][ae][va][el] `:                     &PatternEntry{Flags: FlagWeaponMelee | FlagHit},
	`^attacks with one handed melee weapons [hd][ae][va][el] `: &PatternEntry{Flags: FlagWeapon1H | FlagWeaponMelee},
	`^attacks with two handed melee weapons [hd][ae][va][el] `: &PatternEntry{Flags: FlagWeapon2H | FlagWeaponMelee},
	`^attacks with ranged weapons [hd][ae][va][el] `:           &PatternEntry{Flags: FlagWeaponRanged},
	// Damage types
	`^attack damage `:         &PatternEntry{Flags: FlagAttack},
	`^hits deal `:             &PatternEntry{KeywordFlags: KeywordHit},
	`^melee weapon damage`:    &PatternEntry{Flags: FlagWeaponMelee},
	`^deal `:                  &PatternEntry{},
	`^critical strikes deal `: &PatternEntry{Tag: &CondTag{Var: "CriticalStrike"}},
	`^poisons you inflict with critical strikes have `: &PatternEntry{KeywordFlags: KeywordPoison | KeywordMatchAll, Tag: &CondTag{Var: "CriticalStrike"}},
	// Add to minion
	`^minions `:                  &PatternEntry{AddToMinion: true},
	`^minions [hd][ae][va][el] `: &PatternEntry{AddToMinion: true},
	`^while a unique enemy is in your presence, minions [hd][ae][va][el] `:        &PatternEntry{AddToMinion: true, PlayerTag: &CondTag{IsActor: true, Actor: "enemy", Var: "RareOrUnique"}},
	`^while a pinnacle atlas boss is in your presence, minions [hd][ae][va][el] `: &PatternEntry{AddToMinion: true, PlayerTag: &CondTag{IsActor: true, Actor: "enemy", Var: "PinnacleBoss"}},
	`^minions leech `:                                                &PatternEntry{AddToMinion: true},
	`^minions' attacks deal `:                                        &PatternEntry{AddToMinion: true, Flags: FlagAttack},
	`^minions created recently have `:                                &PatternEntry{AddToMinion: true, PlayerTag: &CondTag{Var: "MinionsCreatedRecently"}},
	`^golems [hd][ae][va][el] `:                                      &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillTypeTag{SkillType: SkillTypeGolem}},
	`^summoned golems [hd][ae][va][el] `:                             &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillTypeTag{SkillType: SkillTypeGolem}},
	`^golem skills have `:                                            &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeGolem}},
	`^non-minion skills have `:                                       &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMinion, Neg: true}},
	`^zombies [hd][ae][va][el] `:                                     &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Zombie", IncludeTransfigured: true}},
	`^raised zombies [hd][ae][va][el] `:                              &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Zombie", IncludeTransfigured: true}},
	`^skeletons [hd][ae][va][el] `:                                   &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Skeletons", IncludeTransfigured: true}},
	`^raging spirits [hd][ae][va][el] `:                              &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Raging Spirit", IncludeTransfigured: true}},
	`^summoned raging spirits [hd][ae][va][el] `:                     &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Raging Spirit", IncludeTransfigured: true}},
	`^r?a?i?s?e?d? ?spectres [hd][ae][va][el] `:                      &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Raise Spectre", IncludeTransfigured: true}},
	`^chaos golems [hd][ae][va][el] `:                                &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Chaos Golem", IncludeTransfigured: true}},
	`^summoned chaos golems [hd][ae][va][el] `:                       &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Chaos Golem", IncludeTransfigured: true}},
	`^flame golems [hd][ae][va][el] `:                                &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Flame Golem", IncludeTransfigured: true}},
	`^summoned flame golems [hd][ae][va][el] `:                       &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Flame Golem", IncludeTransfigured: true}},
	`^ice golems [hd][ae][va][el] `:                                  &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Ice Golem", IncludeTransfigured: true}},
	`^summoned ice golems [hd][ae][va][el] `:                         &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Ice Golem", IncludeTransfigured: true}},
	`^lightning golems [hd][ae][va][el] `:                            &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Lightning Golem", IncludeTransfigured: true}},
	`^summoned lightning golems [hd][ae][va][el] `:                   &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Lightning Golem", IncludeTransfigured: true}},
	`^stone golems [hd][ae][va][el] `:                                &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Stone Golem", IncludeTransfigured: true}},
	`^summoned stone golems [hd][ae][va][el] `:                       &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Stone Golem", IncludeTransfigured: true}},
	`^summoned carrion golems [hd][ae][va][el] `:                     &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Carrion Golem", IncludeTransfigured: true}},
	`^summoned skitterbots [hd][ae][va][el] `:                        &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Carrion Golem", IncludeTransfigured: true}},
	`^blink arrow and blink arrow clones [hd][ae][va][el] `:          &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Blink Arrow", IncludeTransfigured: true}},
	`^mirror arrow and mirror arrow clones [hd][ae][va][el] `:        &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Mirror Arrow", IncludeTransfigured: true}},
	`^animated weapons [hd][ae][va][el] `:                            &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Animate Weapon", IncludeTransfigured: true}},
	`^animated guardians? deals? `:                                   &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Animate Guardian", IncludeTransfigured: true}},
	`^summoned holy relics [hd][ae][va][el] `:                        &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Holy Relic", IncludeTransfigured: true}},
	`^summoned reaper [dh][ea][as]l?s? `:                             &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Reaper", IncludeTransfigured: true}},
	`^summoned arbalists [hgdf][aei][vair][eln] `:                    &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Arbalists"}},
	`^summoned arbalists' attacks have `:                             &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Summon Arbalists"}},
	`^herald skills [hd][ae][va][el] `:                               &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHerald}},
	`^agony crawler deals `:                                          &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Herald of Agony"}},
	`^summoned agony crawler fires `:                                 &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Herald of Agony"}},
	`^sentinels of purity deal `:                                     &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Herald of Purity"}},
	`^summoned sentinels of absolution have `:                        &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillName: "Absolution", IncludeTransfigured: true}},
	`^summoned sentinels have `:                                      &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillNameList: []string{"Herald of Purity", "Dominating Blow", "Absolution"}, IncludeTransfigured: true}},
	`^raised zombies' slam attack has `:                              &PatternEntry{AddToMinion: true, Tag: &SkillIDTag{SkillID: "ZombieSlam"}},
	`^raised spectres, raised zombies, and summoned skeletons have `: &PatternEntry{AddToMinion: true, AddToMinionTag: &SkillNameTag{SkillNameList: []string{"Raise Spectre", "Raise Zombie", "Summon Skeletons"}, IncludeTransfigured: true}},
	// Totem/trap/mine
	`^attacks used by totems have `:                                      &PatternEntry{Flags: FlagAttack, KeywordFlags: KeywordTotem},
	`^totems have `:                                                      &PatternEntry{KeywordFlags: KeywordTotem},
	`^skills used by totems [hd][ae][va][el] `:                           &PatternEntry{KeywordFlags: KeywordTotem},
	`^spells cast by totems [hd][ae][va][el] `:                           &PatternEntry{Flags: FlagSpell, KeywordFlags: KeywordTotem},
	`^trap and mine damage `:                                             &PatternEntry{KeywordFlags: KeywordTrap | KeywordMine},
	`^skills used by traps [hgd][ae][via][enl] `:                         &PatternEntry{KeywordFlags: KeywordTrap},
	`^skills which throw traps [hgd][ae][via][enl] `:                     &PatternEntry{KeywordFlags: KeywordTrap},
	`^skills used by mines [hgd][ae][via][enl] `:                         &PatternEntry{KeywordFlags: KeywordMine},
	`^skills which throw mines ([hgd]?[ae]?[via]?[enl]?[ ]?)`:            &PatternEntry{KeywordFlags: KeywordMine},
	`^skills used by your traps and mines ([hgd]?[ae]?[via]?[enl]?[ ]?)`: &PatternEntry{KeywordFlags: KeywordTrap | KeywordMine},
	// Local damage
	`^attacks with this weapon `:                  &PatternEntry{TagList: []Tag{&CondTag{Var: "{Hand}Attack"}, &SkillTypeTag{SkillType: SkillTypeAttack}}},
	`^attacks with this weapon [hd][ae][va][el] `: &PatternEntry{TagList: []Tag{&CondTag{Var: "{Hand}Attack"}, &SkillTypeTag{SkillType: SkillTypeAttack}}},
	`^hits with this weapon [hd][ae][va][el] `:    &PatternEntry{Flags: FlagHit, TagList: []Tag{&CondTag{Var: "{Hand}Attack"}, &SkillTypeTag{SkillType: SkillTypeAttack}}},
	// Skill types
	`^attacks [hd][ae][va][el] `:                  &PatternEntry{Flags: FlagAttack},
	`^attack skills [hd][ae][va][el] `:            &PatternEntry{KeywordFlags: KeywordAttack},
	`^spells [hd][ae][va][el] a? ?`:               &PatternEntry{Flags: FlagSpell},
	`^spell skills [hd][ae][va][el] `:             &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeSpell}},
	`^projectile attack skills [hd][ae][va][el] `: &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeRangedAttack}},
	`^projectiles from attacks [hd][ae][va][el] `: &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeRangedAttack}},
	`^arrows [hd][ae][va][el] `:                   &PatternEntry{Tag: &KeywordAndTag{KeywordFlags: KeywordArrow}},
	`^bow skills [hdf][aei][var][el] `:            &PatternEntry{KeywordFlags: KeywordBow},
	`^projectiles [hdf][aei][var][el] `:           &PatternEntry{Flags: FlagProjectile},
	`^projectiles `:                               &PatternEntry{Flags: FlagProjectile},
	`^melee attacks have `:                        &PatternEntry{Flags: FlagMelee},
	`^movement attack skills have `:               &PatternEntry{Flags: FlagAttack, KeywordFlags: KeywordMovement},
	`^travel skills have `:                        &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeTravel}},
	`^link skills have `:                          &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeLink}},
	`^lightning skills [hd][ae][va][el] a? ?`:     &PatternEntry{KeywordFlags: KeywordLightning},
	`^lightning spells [hd][ae][va][el] a? ?`:     &PatternEntry{KeywordFlags: KeywordLightning, Flags: FlagSpell},
	`^cold skills [hd][ae][va][el] a? ?`:          &PatternEntry{KeywordFlags: KeywordCold},
	`^cold spells [hd][ae][va][el] a? ?`:          &PatternEntry{KeywordFlags: KeywordCold, Flags: FlagSpell},
	`^fire skills [hd][ae][va][el] a? ?`:          &PatternEntry{KeywordFlags: KeywordFire},
	`^fire spells [hd][ae][va][el] a? ?`:          &PatternEntry{KeywordFlags: KeywordFire, Flags: FlagSpell},
	`^chaos skills [hd][ae][va][el] a? ?`:         &PatternEntry{KeywordFlags: KeywordChaos},
	`^vaal skills [hd][ae][va][el] `:              &PatternEntry{KeywordFlags: KeywordVaal},
	`^vaal skills require `:                       &PatternEntry{KeywordFlags: KeywordVaal},
	`^non-aura vaal skills require `:              &PatternEntry{KeywordFlags: KeywordVaal, Tag: &SkillTypeTag{SkillType: SkillTypeAura, Neg: true}},
	`^brand skills [hd][ae][va][el] `:             &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeBrand}},
	`^channelling skills [hd][ae][va][el] `:       &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel}},
	`^curse skills [hd][ae][va][el] `:             &PatternEntry{KeywordFlags: KeywordCurse},
	`^hex skills [hd][ae][va][el] `:               &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeHex}},
	`^mark skills [hd][ae][va][el] `:              &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMark}},
	`^melee skills [hd][ae][va][el] `:             &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeMelee}},
	`^guard skills [hd][ae][va][el] `:             &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeGuard}},
	`^banner skills [hd][ae][va][el] `:            &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeBanner}},
	`^nova spells [hd][ae][va][el] `:              &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeNova}},
	`^area skills [hd][ae][va][el] `:              &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeArea}},
	`^aura skills [hd][ae][va][el] `:              &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeAura}},
	`^prismatic skills [hd][ae][va][el] `:         &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeRandomElement}},
	`^retaliation skills [hd][ae][va][el] `:       &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeRetaliation}},
	`^pact skills [hd][ae][va][el] `:              &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypePact}},
	`^warcry skills have `:                        &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeWarcry}},
	`^non-curse aura skills have `:                &PatternEntry{TagList: []Tag{&SkillTypeTag{SkillType: SkillTypeAura}, &SkillTypeTag{SkillType: SkillTypeAppliesCurse, Neg: true}}},
	`^non-channelling skills have `:               &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeChannel, Neg: true}},
	`^non-vaal skills deal `:                      &PatternEntry{Tag: &SkillTypeTag{SkillType: SkillTypeVaal, Neg: true}},
	`^skills [hgdf][aei][vari][eln] `:             &PatternEntry{},
	// Slot specific
	`^left ring slot: `:  &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotNumber, Num: 1}},
	`^right ring slot: `: &PatternEntry{Tag: &SlotTag{SlotKind: TagSlotNumber, Num: 2}},
	`^socketed gems ([hgd]?[ae]?[via]?[enl]?[ \t\n\v\f\r]?)`: &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}"}},
	`^socketed skills [hgd][ae][via][enl] `:                  &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}"}},
	`^socketed travel skills [hgd][ae][via][enl] `:           &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "travel"}},
	`^socketed warcry skills [hgd][ae][via][enl] `:           &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "warcry"}},
	`^socketed attacks [hgd][ae][via][enl] `:                 &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "attack"}},
	`^socketed spells [hgd][ae][via][enl] `:                  &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "spell"}},
	`^socketed curse gems [hgd][ae][via][enl] `:              &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "curse"}},
	`^socketed melee gems [hgd][ae][via][enl] `:              &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "melee"}},
	`^socketed golem gems [hgd][ae][via][enl] `:              &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "golem"}},
	`^socketed golem skills [hgd][ae][via][enl] `:            &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "golem"}},
	`^socketed golem skills have minions `:                   &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "golem"}},
	`^socketed vaal skills [hgd][ae][via][enl] `:             &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}", Keyword: "vaal"}},
	`^socketed projectile spells [hgdf][aei][viar][enl] `:    &PatternEntry{AddToSkill: &SlotTag{SlotKind: TagSocketedIn, SlotName: "{SlotName}"}, TagList: []Tag{&SkillTypeTag{SkillType: SkillTypeProjectile}, &SkillTypeTag{SkillType: SkillTypeSpell}}},
	// Enemy modifiers
	`^enemies withered by you [th]a[vk]e `:                        &PatternEntry{Tag: &MultiplierTag{IsThreshold: true, Var: "WitheredStack", Threshold: opt(1)}, ApplyToEnemy: true},
	`^enemies shocked or frozen by you take `:                     &PatternEntry{Tag: &CondTag{VarList: []string{"Shocked", "Frozen"}}, ApplyToEnemy: true, ModSuffix: "Taken"},
	`^enemies affected by your spider's webs [thd][ae][avk][el] `: &PatternEntry{Tag: &MultiplierTag{IsThreshold: true, Var: "Spider's WebStack", Threshold: opt(1)}, ApplyToEnemy: true},
	`^enemies you curse take `:                                    &PatternEntry{Tag: &CondTag{Var: "Cursed"}, ApplyToEnemy: true, ModSuffix: "Taken"},
	`^enemies you curse `:                                         &PatternEntry{Tag: &CondTag{Var: "Cursed"}, ApplyToEnemy: true},
	`^nearby enemies take `:                                       &PatternEntry{ModSuffix: "Taken", ApplyToEnemy: true},
	`^nearby enemies have `:                                       &PatternEntry{ApplyToEnemy: true},
	`^nearby enemies deal `:                                       &PatternEntry{ApplyToEnemy: true},
	`^nearby enemies'? `:                                          &PatternEntry{ApplyToEnemy: true},
	`^nearby enemy monsters' `:                                    &PatternEntry{ApplyToEnemy: true},
	`against you`:                                                 &PatternEntry{ApplyToEnemy: true, ActorEnemy: true},
	`^hits against you `:                                          &PatternEntry{ApplyToEnemy: true, Flags: FlagHit},
	`^enemies near your totems deal `:                             &PatternEntry{ApplyToEnemy: true},
	// Other
	`^your flasks grant `:                         &PatternEntry{},
	`^when hit, `:                                 &PatternEntry{},
	`^you and allies [hgd][ae][via][enl] `:        &PatternEntry{},
	`^auras from your skills grant `:              &PatternEntry{AddToAura: true},
	`^auras grant `:                               &PatternEntry{AddToAura: true},
	`^banners also grant `:                        &PatternEntry{AddToAura: true, OnlyAddToBanners: true},
	`^you and nearby allies `:                     &PatternEntry{NewAura: true},
	`^you and nearby allies [hgd][ae][via][enl] `: &PatternEntry{NewAura: true},
	`^nearby allies [hgd][ae][via][enl] `:         &PatternEntry{NewAura: true, NewAuraOnlyAllies: true},
	`^every rage also grants `:                    &PatternEntry{Tag: &MultiplierTag{Var: "RageEffect"}},
	`^each rage also grants `:                     &PatternEntry{Tag: &MultiplierTag{Var: "RageEffect"}},
	`^you and allies affected by auras from your skills [hgd][ae][via][enl] `: &PatternEntry{Tag: &CondTag{Var: "AffectedByAura"}},
	`^take `:      &PatternEntry{ModSuffix: "Taken"},
	`^marauder: `: &PatternEntry{Tag: &CondTag{Var: "ConnectedToMarauderStart"}},
	`^duelist: `:  &PatternEntry{Tag: &CondTag{Var: "ConnectedToDuelistStart"}},
	`^ranger: `:   &PatternEntry{Tag: &CondTag{Var: "ConnectedToRangerStart"}},
	`^shadow: `:   &PatternEntry{Tag: &CondTag{Var: "ConnectedToShadowStart"}},
	`^witch: `:    &PatternEntry{Tag: &CondTag{Var: "ConnectedToWitchStart"}},
	`^templar: `:  &PatternEntry{Tag: &CondTag{Var: "ConnectedToTemplarStart"}},
	`^scion: `:    &PatternEntry{Tag: &CondTag{Var: "ConnectedToScionStart"}},
	`^skills supported by spellslinger have `:                               &PatternEntry{Tag: &CondTag{Var: "SupportedBySpellslinger"}},
	`^skills that have dealt a critical strike in the past 8 seconds deal `: &PatternEntry{Tag: &CondTag{Var: "CritInPast8Sec"}},
	`^blink arrow and mirror arrow have `:                                   &PatternEntry{Tag: &SkillNameTag{SkillNameList: []string{"Blink Arrow", "Mirror Arrow"}, IncludeTransfigured: true}},
	`attacks with energy blades `:                                           &PatternEntry{Flags: FlagAttack, Tag: &CondTag{Var: "AffectedByEnergyBlade"}},
	`^for each nearby corpse, `:                                             &PatternEntry{Tag: &MultiplierTag{Var: "NearbyCorpse"}},
	`^enemies in your link beams have `:                                     &PatternEntry{Tag: &CondTag{Var: "BetweenYouAndLinkedTarget"}, ApplyToEnemy: true},
	`^consecrated ground you create a?l?s?o? ?grants `:                      &PatternEntry{Tag: &CondTag{Var: "OnConsecratedGround"}},
	// While in the presence of...
	`^while a unique enemy is in your presence, `:        &PatternEntry{Tag: &CondTag{IsActor: true, Actor: "enemy", Var: "RareOrUnique"}},
	`^while a pinnacle atlas boss is in your presence, `: &PatternEntry{Tag: &CondTag{IsActor: true, Actor: "enemy", Var: "PinnacleBoss"}},

	// enemies X by you take/have — ModParser.lua:1284-1305 (closures)
	`^enemies ([a-zA-Z]+) by you take `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{Tag: &CondTag{Var: firstToUpper(c.s(1))}, ApplyToEnemy: true, ModSuffix: "Taken"}
	}),
	`^enemies ([a-zA-Z]+) by `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{Tag: &CondTag{Var: firstToUpper(c.s(1))}, ApplyToEnemy: true}
	}),
	`^enemies ([a-zA-Z]+) by you have `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{Tag: &CondTag{Var: firstToUpper(c.s(1))}, ApplyToEnemy: true}
	}),
	`^while a pinnacle atlas boss is in your presence, enemies you've hit recently have `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{PlayerTagList: []Tag{&CondTag{Var: "HitRecently"}, &CondTag{IsActor: true, Actor: "enemy", Var: "PinnacleBoss"}}, ApplyToEnemy: true}
	}),
	`^while a unique enemy is in your presence, enemies you've hit recently have `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{PlayerTagList: []Tag{&CondTag{Var: "HitRecently"}, &CondTag{IsActor: true, Actor: "enemy", Var: "RareOrUnique"}}, ApplyToEnemy: true}
	}),
	`^enemies you've hit recently have `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{PlayerTag: &CondTag{Var: "HitRecently"}, ApplyToEnemy: true}
	}),
	`^hits against enemies ([a-zA-Z]+) by you have `: entryFn(func(c caps) *PatternEntry {
		return &PatternEntry{Tag: &CondTag{IsActor: true, Actor: "enemy", Var: firstToUpper(c.s(1))}}
	}),
}
